### ISSUE TITLE
Mumble does not detect changes in default audio devices while running

### ISSUE THREAD

**Issue by mumble-voip** [mumble-voip/mumble#1013]
I use Mac OS X 10.8.4 and in Mumble I have set the audio input and audio output to "Default Device". Yet switching an audio input or output device in the system has no effect on Mumble. Mumble always sticks to the audio device that was set in the system when Mumble started running. Mumble never changes audio devices automatically when they are changed in the system settings. In order to change an audio device in Mumble I either have to set it manually or quit Mumble and start it again after selecting the audio device in the system.

_This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/1013/ ._

**Comment by jlsalmon** [comment]
This is still an issue with macOS 11.6 / mumble 1.3.3, and it's rather a troublesome one for me at least. 

I'd be happy to have a go at patching this myself, if someone could give me a very brief clue on the right part of the codebase to look at?

**Comment by Krzmbrzl** [comment]
I'm not too familiar with the exact details but you should be able to work your way through by looking in `src/mumble/AudioConfigDialog.cpp` (this is the functional backend for the audio input/output settings pages) where `qcbDevice` should be the combo box in which you can set the device to use (the variable has the same name for the input and output dialog).
The actual audio stuff happens in `src/mumble/AudioInput.cpp` and `src/mumble/AudioOutput.cpp` and/or in the backend-specific code that can also be found under `src/mumble`. I think on macOS what you are looking for there is `CoreAudio.mm`.

Is that enough to get you started on this?

**Comment by jlsalmon** [comment]
Thanks @Krzmbrzl, that's really helpful. It looks like the `CoreAudioOutput::propertyChange` is the key piece here - it's not being invoked when switching devices, presumably because `kAudioUnitProperty_StreamFormat` is not changing on the AUHAL unit (which is the only property that Mumble is listening on). Suggesting that maybe we need to listen to additional `kAudioUnitProperty_*` changes, but I'm not familiar with CoreAudio so I don't really know how it's supposed to work at the moment.

Interestingly, when I switch _off_ my bluetooth headphones while Mumble is using them, `kAudioUnitProperty_StreamFormat ` _is_ changing, the property change callback _is_ invoked, and the audio switches correctly to my computer speakers. I'm not sure why the property is changing in that scenario only. I'll keep reading through the CoreAudio docs and see if I can figure it out.
