### ISSUE TITLE
push-to-talk transmission colour change in ui isn't noticeable enough

### ISSUE THREAD

**Issue by mumble-voip** [mumble-voip/mumble#1038]
i'm colourblind and i can't notice the change in colours between the transmitting/not-transmitting icon in the ui. i think it should be more obvious like in ts3. there are skins that fix this, but i don't think it should be a problem in the default install.

*This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/1038/ .*

**Comment by mkrautz** [comment]
Do we believe this is fixed by the new skins?

**Comment by Kissaki** [comment]
Personally, I find the new icons less distinguishable than the old ones.
Grey to red was much more visible to me than the now down-toned red to green.
Actually, I’m not sure if my impression of less distinguishability was from the overlay, which is white/grey to green.
Maybe its just that it’s different, which is why I can’t spot it as easily any more, as I’m not used to it.

As this issue is for color-blindness specifically, we do have a symbol-distinguished icon now.
For Red–green color blindness, having red and green icons is obviously bad for distinguishability.
For Blue–yellow color blindness, our current skin colors should be fine.

**As we do have different symbols, I’d close this as fixed.**
Unless we have someone with color blindness who can give direct feedback, we can’t do more right now. And such a person can always create a new feature request.

**Comment by danielhoherd** [comment]
I'm a new mumble user who is colorblind and was looking for a solution to the problem described by the OP about not being able to see when people are talking. I see this ticket is closed because apparently there are some symbols that indicate state, but I am unable to find these symbols or the preference to turn them on, so although this ticket may technically be considered complete, color blind users are still suffering.

**Comment by Kissaki** [comment]
Which version of Mumble are you using?
Are you using the 1.3.0 snapshots? If not, please try them and see if that shows the different state icons.

**Comment by danielhoherd** [comment]
@Kissaki I was using Mumble version 1.2.15, installed via `brew cask install mumble`, which was quite convenient so thanks to whoever maintains that.

I just checked out version 1.3.0 and it looks much better! Previously I could never tell when anybody was speaking, but now it is perfectly clear with the change from a grey to a blue icon and the addition of the sound waves around the head of the speaker. Very cool, many thanks for accommodating us unfortunate colorblind folks.
