### ISSUE TITLE
Mumble hanging immediately after loading

### ISSUE THREAD

**Issue by mumble-voip** [mumble-voip/mumble#1043]
My mumble is crashing immediately after it's loaded.
Not sure of a list of steps to reproduce it other than simply opening it. It didn't have any issues a couple of days ago and I've completely deinstalled and remove the folder from the roaming area before reinstalling and tried deinstalling the only program that's been installed on my PC since I last used mumble which didn't help.

I've tried disabling the bonjour service.

I started on version 1.2.4 and tried updating to the latest snapshot, occurs regardless of version.

Pastebin link of the debug copy-paste; http://pastebin.com/fZZPDk81
I've attached my dxdiag.txt as well, the sound I use for mumble is "Speakers (Realtek High Definition Audio)"

I'm using Windows 7

_This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/1043/ ._

*The following attachments were added on the original item:
- https://sourceforge.net/p/mumble/bugs/1043/attachment/DxDiag.txt*

**Comment by Krzmbrzl** [comment]
Does this issue still happen with 1.3?

**Comment by StephanGocht** [comment]
I have the exact issue described here except that the culprit is not a razer device but the VRS DirectForce Pro Wheel Base. As soon as I turn on the control unit which is connected via USB, the mumble UI freezes. When I turn it of again it becomes responsive. While froozen the audio works but it seems that user joining the channel are not registered.

I am on Windows 11 with Mumble version 1.4.287.

**Comment by Krzmbrzl** [comment]
See #5631 - I believe it's the same problem
