### ISSUE TITLE
Overlay flickers in Castle Story

### ISSUE THREAD

**Issue by Kissaki** [mumble-voip/mumble#1047]
The overlay flickers and is not visible most of the time in Castle Story, which is in Alpha, on my Win7x64 system.

In the main menu it still displays fine.
Once loaded into the game, it disappears, but regularly flashes in for a minimal time.

_This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/1047/ ._

**Comment by Krzmbrzl** [comment]
@Kissaki were you able to reproduce this with 1.3?

**Comment by Kissaki** [comment]
not tested

**Comment by Kissaki** [comment]
Nothing changed in the Overlay, so why would it have changed?

**Comment by Krzmbrzl** [comment]
> Nothing changed in the Overlay, so why would it have changed?

Given that the issue is from 2013, I assumed that some work has been performed on the Overlay since. Looking at `Overlay.cpp` there are indeed a handful of commits, though most concern refactoring. There are some fixes (according to the commit message at least) as well though, so maybe some of those "accidentally" fixed the problem?
