### ISSUE TITLE
Overlay issues for Final Fantasy XIV

### ISSUE THREAD

**Issue by mumble-voip** [mumble-voip/mumble#1056]
~~Running Final Fantasy XIV in Fullscreen, mumble overlay is displayed, but game will crash after couple of minutes.~~

Running Final Fantasy XIV in Borderless Windowed, mumble overlay is not displayed, game will not crash.

Overlay debug logs attached for both display mode.

Is there any way to get Final Fantasy XIV to display overlay in Borderless Windowed?

OS: Windows 7 64bit

*This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/1056/ .*

*The following attachments were added on the original item:
* https://sourceforge.net/p/mumble/bugs/1056/attachment/borderless%20windowed.LOG
* https://sourceforge.net/p/mumble/bugs/1056/attachment/fullscreen.LOG*

**Comment by spacekh** [comment]
I think this issue got solved for the DX9 FFXIV client, because I have been using mumble with no problems for about a year, but I got a new graphics card, and now I'm using the DX11 client, and I don't get an overlay anymore, regardless of whether I'm in Borderless Windowed or Fullscreen mode.

I was wondering if someone could give me some tips on how to track this down.  I don't know how to get the info on what DLLs are loaded, or how to run mumble in debug mode to get the logs.

**Comment by mkrautz** [comment]
I just re-tested this.

The current status, on NVIDIA:

- D3D11 works fine, in all modes.
- D3D9 works in fullscreen. Windowed (borderless, and plain windowed) thinks the viewport is 1x1, so no overlay.

**Comment by mkrautz** [comment]
FWIW, the rendertarget code in discussion in this thread originates from this commit:
https://github.com/mumble-voip/mumble/commit/cf86cdc976e773ce0e2da0db8e89d2ab30524c96

**Comment by mkrautz** [comment]
OK, I got it drawing in D3D9 windowed mode.

PR at https://github.com/mumble-voip/mumble/pull/2367
