### ISSUE TITLE
Different behavior on usernames like Test/test/tESt for registered/unregistered users...

### ISSUE THREAD

**Issue by Natenom** [mumble-voip/mumble#1078]
When a user "test" is connected to a server and is not registered then another user with a different ip/certificate named "Test" can connect.

If the user "test" is registered, "Test" can't connect anymore.

Shouldn't the behavior be the same in both cases?

**Comment by mkrautz** [comment]
This is because the SQL query in the "default" authenticator built-in to Murmur queries with a lowercased username:

https://github.com/mumble-voip/mumble/blob/c0879e57bf9baefedede3e548e7b85cca69c9839/src/murmur/ServerDB.cpp#L910

If you have a custom authenticator connected, it may not.
But we could potentially document that it's best that it does.

There's also the check for unregistered users with the same name, which isn't case sensitive by default:
https://github.com/mumble-voip/mumble/blob/master/src/murmur/Messages.cpp#L152

**Comment by hacst** [comment]
Imho a case insensitive check makes a lot of sense. We should document the behavior and recommend authenticators replicate it if possible (might not be possible depending on the backend I guess).

**Comment by mkrautz** [comment]
SGTM.

I believe the change that needs to be made is to make the check at https://github.com/mumble-voip/mumble/blob/master/src/murmur/Messages.cpp#L152 convert the strings to lowercase before comparing.

**Comment by Kissaki** [comment]
I agree, case-insensitive is probably the expected behaviour for most ppl.

**Comment by hacst** [comment]
Have to be careful though. This probably has backwards compatibility implications we have to trade off against.
