### ISSUE TITLE
Mumble crashes when RDP in use

### ISSUE THREAD

**Issue by ykram** [mumble-voip/mumble#1085]
I frequently will leave mumble (1.2.4) running in the background while I go to work. When I RDP remotely from my MBA to my desktop machine using the OSX RDP client, everything is fine. However, when I physically return to the workstation running mumble, once mumble gains focus the entire system will run sluggishly, followed by mumble crashing before performance stabilizes.

**Comment by wchristian** [comment]
Small update on this, like atarlen, i find that when i access my system via RDP, then return later in the day and access it directly, mumble stops processing microphone input. However restarting it entirely isn't necessary, just opening the settings and clicking OK.

Here's a day's worth of usage from the log. I used mumble between 05:55 and 08:58, then didn't touch it for the rest of the day, accessed the system via RDP at 17:09, disconnected RDP at 22:24 and logged in physically again at 22:40.

Note that mic input processing freezes at 17:09 already and the bug is more that upon reconnecting physically, mumble doesn't pick the hardware up again.

https://gist.github.com/wchristian/18f9671aaeefcffead20b0fe4e6907f8

**Comment by live4ever** [comment]
> Small update on this, like atarlen, i find that when i access my system via RDP, then return later in the day and access it directly, mumble stops processing microphone input. However restarting it entirely isn't necessary, just opening the settings and clicking OK.
> 
> Here's a day's worth of usage from the log. I used mumble between 05:55 and 08:58, then didn't touch it for the rest of the day, accessed the system via RDP at 17:09, disconnected RDP at 22:24 and logged in physically again at 22:40.
> 
> Note that mic input processing freezes at 17:09 already and the bug is more that upon reconnecting physically, mumble doesn't pick the hardware up again.
> 
> https://gist.github.com/wchristian/18f9671aaeefcffead20b0fe4e6907f8

Any updates on this issue - using Mumble for the first time (setup as a low latency remote intercom) - I manage the remote PC via Windows 10 RDP and the sound coming into Mumble will stop working until I open the config audio settings.

**Comment by Krzmbrzl** [comment]
As far as I can tell no progress has been made here. Apparently nobody has found the time to try and pinpoint the bug in code :eyes:

**Comment by ZeroAbility** [comment]
This could be related to Audio over RDP. Here are two methods to enable/disable that feature:

https://www.wikihow.com/Hear-Audio-from-the-Remote-PC-when-Using-Remote-Desktop

Does this still occur if the Audio over RDP is disabled?

**Comment by wchristian** [comment]
Fwiw, i am not a user anymore, but @ZeroAbility you should be aware that putting a label on an issue does not generate a notification, so to make the bot make sense, adding that label should be accompanied by a comment
