### ISSUE TITLE
Volume adjust per user.

### ISSUE THREAD

**Issue by Mhrok** [mumble-voip/mumble#1156]
Hello!
I will be happy if option of adjusting volume for each user appears in mumble.

**Comment by sxealex** [comment]
Mumble auto-leveling works great imo... only issue is I want to hear 2 or 3 users LESS than 100%.  This really is why people use vent over mumble, this feature alone. Its a shame because mumble is better by far in all other aspects.  Have been running a server since early beta :].

**Comment by Nemesis-Xero** [comment]
>but it's up to the devs if that's worth compromising the "people should take care of their own settings" principle.

It's ridiculous that the devs' position on this is that every user should sit there and try to not only force other users to change their audio settings but also attempt to convey a "perfect configuration" via spoken opinion. Not only for the logistical impossibility of doing so but also because each person hears differently, so what is perfect for one user will either be too loud or too soft for another. Not to mention how different audio hardware records and transmits audio at ever varying levels.

Auto-leveling is also insufficient for the same reason, not everyone hears exactly the same as the person(s) developing the auto-leveling functionality.

The only solution is to allow a user to adjust the output volume of each other user individually.

**Comment by slowstuff** [comment]
This is my one complaint, and why I hate using Mumble ... The devs belief that they are right is short sighted, arrogant, and annoying as hell... Yes it it there application, but come on, at least try and make your users happy.

**Comment by Tarun80** [comment]
@slowstuff Why should they add in a redundant feature because some users don't want to do things which have already been laid out for them? Have people rerun the audio wizard and check their settings. Problem solved.

**Comment by HotRod72** [comment]
@Tarun80 It won't be redundant. Not all people are techwise, no matter how many times you tell them what to do, they don't get it.
If the user who's on the receiving end should have the option to lower the volume on a specific user to stop their ears from bleeding...
This is the ONLY big issue we have with Mumble. And it's a BIG issue every bleeping day!

We will go back to TeamSpeak3 if this issue is not being fixed pretty soon.
For us you can throw away the AGC shit, it does not work for anyone of us in our community.

I really hope this is being taken seriously. We are close to 60 users on our servers and this is the number one issue.

**Comment by Tarun80** [comment]
@HotRod72 Your problem is with the users not knowing what they're doing. Server admins/moderators can take steps to  correct this. A bit of moderation goes a long way. Pull them aside and work with them to help them fix it. If they refuse, mute them until they message you that it's fixed. If they try to get around the mute, you escalate with a temp-ban. Moderation is not a difficult thing, even if the user is too loud/quiet.

Your "issue" is a PEBKAC error. This is not a fault of the program but of the user. Get after the problematic users, not the program. You also have an option to lower their volume. It's called Local Mute. If that's your "number one issue" I think you need to work on communicating to your users how to properly run the Audio Wizard and configure their Mumble since you have this problem "every bleeping day". Communicating with them is the issue, not Mumble itself.

Close to 60 users? Okay...? Is there a point to that? I've pulled 30-40 on mine and every so often (Maybe once every three months if even that) I may need to tell people that they need to rerun the Audio Wizard. They do, and it fixes the issue. Takes minutes to do.

The Audio Wizard is designed to make it easier for the end-user to properly configure their audio input and output settings.

I run a community with 500 people in it. I've written a Mumble Setup Guide for those who want to join us on Mumble.

It shows how to do the following, complete with screenshots:

* Download and Install Mumble
* Add a new server
* Username options (clearly stating what it not allowed)
* Step-by-step directions for running through the Audio Wizard, including how to use set-up and use a Push-To-Talk key.
* Ways to optimize your Mumble configuration

The only people who have ever had an issue are those who did not follow/make use of the guide.

**Comment by Nemesis-Xero** [comment]
@Tarun80 You seem to be under the misconception that everyone using Mumble is only using it in a community which strictly adheres to a hierarchy of authority.

People do exist who will not spend more than 1 second attempting to configure anything on their computer. Regardless of how much hand-holding you are willing to provide to them. I'm guessing your solution would be to simply not allow these people to connect to your Mumble server?

You're also completely ignoring the use case of temporarily changing the volume at which you hear specific people for a special occasion. Are you going to ask everyone to manually change their settings to suit your individual needs? Do you believe anyone would actually do that for you? The priority speaker functionality is great but, to my knowledge, it does not allow for multiple tiers of "priority."

Finally, the best reason of all: Providing the choice is always better than not providing the choice.

**Comment by erittainvarma** [comment]
@Tarun80 90's called, they want you back.

Users aren't robots that do things optimal way and perceive things the same way. Usually optimal situation for users isn't "everybody at the same level". It's "most of the dudes at same level and those two retards little lower so that they don't annoy me" mixed with situations where you may want to have also couple guys with higher voice than others. Then, some other dude is totally fine with what ever voice levels are, as long as he can hear them. And then the third guy gets annoyed by totally different people than the first guy.

Also, even minute is too long time for configuring your voice if you are playing a game and other users say to you that you need to fix your voice. You end up having this dude with too low or loud voice through entire gaming session until he has time to fix it. And then, next time you happen to play again with him, the wizard haven't really fixed his problem and you are stuck with too loud or low voice again. If you had option to control user voice, you would have just fixed this problem in couple seconds. You have time for that in pretty much all games, sometimes it may take couple minutes to situation cool down a bit, but usually not too long.

**Comment by Loque-** [comment]
Pah, this is why we use teamspeak, just as good and you and control other users volumes - great for so many reasons.

I love the dev sidestepping the work, would be more interesting to hear technically why he doesn't want to implement the feature, instead of anecdotal reasons why he personally doesn't need the feature himself and then displays a lack of empathy to people who really want to the feature. 

There is no denying it, a lot of users want this feature, some of them are even on github and voice that. If you can't build the feature fine, but stop presuming your users are noobs and do not have the capacity to explain to other users of mumble that they need to modify their operating systems microphone settings... ontop of which, their mic settings might be fine, we just don't want to hear them so loudly...

**Comment by Pluckerpluck** [comment]
I thought I'd add to this:

The issue is that they want someone to set up mumble properly. When set up properly they'll be able to move between mumble servers without issue. From this point on, wherever they go they will work correctly!

When set up correctly, slight changes in mic setup that may change the outgoing volume are actually corrected. So you never need to adjust volume again.

If you give users the chance to mess with the volume of other users this INSTANTLY no longer needs to happen. Instead of people trying to get their setup correct, others have to mess with volumes to get settle each individual. This doesn't solve the underlying problem, it masks it.

If you can barely hear someone that is because their mic is too quite. You would have to amplify them, causing distortion. In theory it's better that they fix the issue themselves.

I do not know how you could add volume controls without compromising the ideal that people setup their systems correctly.

It is for this reason I prefer mumble for small, integrated groups of people. Where everyone knows everyone by name (ingame or real life, whatever you're doing). Yet for large scale, quick join, things Teamspeak is much better because of the volume control.

It does mean you can't run musicboxes in mumble though :/

--------------------------------

The problem is that not everyone has the same frequency response. So some people may find some voices too grating.

So in the end, it's a personal choice. Adding volume controls will cause people to be lazy. That's why they don't want to add it. Mumble is about you setting up your system properly. Don't expect others do mess with their volume because you're stupidly quiet. The CAN'T add this as a feature, without ruining why I prefer mumble in smaller group situations.

**Comment by chevex** [comment]
I think this all sounds great on paper, having the offender adjust their own setup and whatnot. In reality though, it's annoying as hell and makes me go back to TeamSpeak or Ventrillo every time I decide to try out Mumble again. If the maintainers' position on this ever changes then I'll start using Mumble again, but for now I just can't stand it with more than a few people on the server.

**Comment by Tatsujinichi** [comment]
Obviously people want this feature, me being one of them.

**Comment by shodanx2** [comment]
This is so annoying, my volume is too loud and I can't find where to adjust !! Damnit why do you make it so damn hard to use your software which is otherwise really great !

**Comment by ThePoet444** [comment]
on my server I have people whose equipment is garbage but they still love to talk. I have others that can't be bothered to run the setup and adjust the mic. Right now the one who loves it, but has garbage equipment is soft while the others who can't be bothered are super loud. Explain to me why I can't adjust the volume on my end to compensate for this? They aren't going to other mumble servers, most don't care enough to adjust their settings, and not everyone speaks at the same volume, tone, and decibel so the AGC isn't going to help me. I want to lower the volume of some and raise the volume of others. If it distorts that's on me to live with. I would hate to go back to TS because of this, so please can we get this looked at again and maybe implemented? Thanks!

**Comment by Malow** [comment]
Ok this is absolutely crazy.

I love mumble, I've been using mumble for a really long time. It has everything I want except this. And when I try to promote mumble to my friends over vent/TS this alone is the only reason they're able to give why they don't want to use mumble.

It is a legit concern. Even if the mumble-auto-balancer fixes 90% of the issues (and btw I love this feature) there's still 10% that could be better. Scenarios where it's well needed and where mumble's current option isn't suffice:

1. Me and my friends are playing a game, using Mumble as our VOIP. A random player we meet online is cool and we tell him to join us on mumble. We're in the middle of a game and he's new to mumble so he doesn't configure it properly and therefor is really loud. We're in the middle of a game and only had a couple of minutes to spare for him to join. We don't have time at this point to sit and try to troubleshoot it with him to see if we can get it to work on his end, if we could all just quickly lower his volume on our ends for now, we could finish our game and then later deal with the root issue.

2. We're 3 persons on mumble, Person A, Person B and Person C. When C is talking he's really loud for person A and really quiet for Person B despite setting everything up correctly. This scenario is semi-rare but has occurred several times over the years I've used mumble. To date the only solution to this is to "live with it".

3. I'm doing a specific activity that requires some users to be louder than others. For example I'm playing CS:GO and I want the in-game leader's voice to be much louder than the other peoples. 

4. I'm on mumble with a bunch of people and one guy has a really shitty mic so his sound quality is bad, I want to hear him lower than everyone else.

5. I wanna do something cool like have a bot on mumble playing background music for everyone. Can't be done because user can't individually choose the volume of the music then which is pretty much a required feature if you wanna listen to music, especially if you want to be able to hear other people talking over it.

6. One guy on mumble is really low and he needs to configure his shit, but he sucks so much at computers that even the wizard is too advanced for him, the only solution in this case is getting him to install team-viewer and me doing it for him.

Even if most situations can be solved by proper configuring it correctly there's the whole social aspect to consider. When a new guy just joined mumble that I've never talked to before the last thing I want to do is telling him he sounds bad and he needs to configure his stuff. That's pretty awkward and he might get a bad first impression of me. But the main point here is that there are situations that CANNOT be solved with the current implementation! Stop trying to tell us it can, IT CAN'T! I've used Mumble for years and I love it, and this is literally the only thing that mumble can improve on, but the developers refusing to acknowledge it is crazy.

Just to repeat what someone else said earlier: We're humans, not robots. Humans will not act perfectly and we're able to give feedback on how to make something better for us, so the question is, are you making a product for humans or robots?

PS. Like I said I love mumble and it's the best VOIP out there, it's just sad that it's missing this one feature .

**Comment by Kissaki** [comment]
There’s code for this already in the queue, but did not land yet. We’re short on time of course, sadly, which is why it has not landed yet. Keep your fingers crossed for a timely snapshot release with it. :)

**Comment by Zuko** [comment]
impossibru!!! mumble isn't dead yet!

**Comment by AeSix** [comment]
I might be able to convince my group to use mumble again if this is true.

**Comment by chevex** [comment]
Can it be? Mumble will finally have individual volume control? I'm so happy. I can FINALLY get my group to ditch our teamspeak server and support a great open-source project if this actually happens.

**Comment by Malow** [comment]
This is GREAT news. :) Finally Mumble will be better at everything compared to any other product!

**Comment by Xaekai** [comment]
Per user volume control is coming?

Maybe there is a god.

**Comment by peterparkerccc** [comment]
please add this function.

A friend of mine is totally too quiet. the system doesnt work or I cant explaibn him how to do it.

basically 1. Rule of development:

make the software idiot proof.


....

**Comment by chevex** [comment]
They said it was coming. Though "when" is an entirely different question. I sure hope it really happens.

**Comment by jammet** [comment]
Man, the people I talk to, I can sometimes just barely hear them. I need to crawl into the headphones ... there needs to be something to amp some people, or the opposite.

**Comment by Loque-** [comment]
We transitioned over to teamspeak a long time ago specifically for this feature, but will move back if if ever ever gets implemented in mumble.

**Comment by Eltiech** [comment]
Though it appears to be a milestone above, I just want to second this. Not all use cases for Mumble work well with relying on every individual user to calibrate their mic properly. A community I am a part of regularly has 15-20+ drunk friends getting together all on one channel in TeamSpeak. We have attempted to use Mumble in the past, but there are always people who inevitably either A) fail to to adjust their mic in the first place, or B) get significantly louder as the night goes on. Per user volume control is a must in scenarios where the users are welcome, but less than reliable.

**Comment by HotRod72** [comment]
I have given up Mumble. Nothing has happened in this long time. We have swapped to Teamspeak 3 and love that. Individual volume control, file transfer and great sound and low latency.
Won't even look back at Mumble - Out!

**Comment by Xylemon** [comment]
I've noticed on the wiki that for the 1.3.0 page, it mentions this feature:

Mumble can be configured to locally lower volume of other users while you talk if you have the "Priority Speaker" status.

This isn't the solution to this issue right?

**Comment by rce** [comment]
No, it's a different feature.

2015-07-20 11:28 GMT+03:00 Gethyn ThomasQuail <notifications@github.com>:

> I've noticed on the wiki that for the 1.3.0 page, it mentions this feature:
>
> Mumble can be configured to locally lower volume of other users while you
> talk if you have the "Priority Speaker" status.
>
> This isn't the solution to this issue right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mumble-voip/mumble/issues/1156#issuecomment-122812241>
> .
>



-- 
Henry Heikkinen
+358 400 467708
Kokkokalliontie 3 E 13
00370 Helsinki

**Comment by jammet** [comment]
The feature we're looking for is essentially a volume slider vor each person, with automatic default being somewhere near the center, so you can either amp the volume by another 100% or decrease it by 100% if you turn it all the way down.

**Comment by zenzr** [comment]
Has there been any update on this? Literally the only think keeping me and my group of friends moving to mumble.

**Comment by madkat** [comment]
This continues to be the primary hold-up that prevents my guild from switching to Mumble.

**Comment by Tarun80** [comment]
A lot of pressure and false claims like above. No reason to make such comments, people. A minor feature doesn't stop people from changing software...

**Comment by Xylemon** [comment]
@Tarun80 I don't think a lot of these comments are "false claims, nor would I exactly call this a minor feature for a program like Mumble.

**Comment by Tarun80** [comment]
@Xylemon - a "primary hold-up" that stops a guild from switching? No... That's just a false claim used to try and put pressure on developers. I've seen it before and had it happen to myself, as a developer too. @zenzr did well in asking for a status update, @HotRod72 however did nothing to help and his type of comment isn't a positive contribution to helping this feature land faster.

As I've stated before, there is already volume normalization, and rerunning the Audio Wizard. Yes, this would be a welcome feature but the fact that it is not present is not breaking or stopping anything. It's not a showstopper bug. The program still works (quite well) as intended. That is what makes this a minor feature. That's no major need for it.

Volume problems that are causing people to ask for this feature is because some people are inherently lazy and don't want to take even the two minutes or less to run the Audio Wizard. This feature can help to counter those who are lazy and don't want to put forth the little effort to configure their systems and setup properly. If people don't want to be a positive contribution and want to blast eardrums because they don't care, that is where proper administrator actions come in, or users can use the Local Mute feature. Just because someone wants to cause a problem and not care about how they sound, is not an excuse to hurt other people's hearing.

I'm not against this feature, though I see it as being a bit redundant because there are already two things already present. Volume Normalization and the Audio Wizard. Both can take care of this very problem. That's why I say Per-User Volume is a minor feature request.

Further responses in here don't really seem necessary. The developers have already said it's coming and even code exists for it. 
> There’s code for this already in the queue, but did not land yet. We’re short on time of course, sadly, which is why it has not landed yet. Keep your fingers crossed for a timely snapshot release with it. :)

It will land when it's ready. Posting here about it is not helping the developers in any way. If people want it sooner, contribute to the code and help make a pull-request land faster with the code for it.

**Comment by jammet** [comment]
You know, you don't have to take it personally. I'm using mumble. Been using it for a long time. I can easily see how this is "holding someone up" from using it. That's not really pressure, it's just one more person who'll benefit from such a feature. Posting here may not help the situation but people feel better. It's all fine. Relax.

**Comment by madkat** [comment]
@Tarun80 As someone that has been stuck on Vent for the last nine years, I am very ready to switch off the product. While evaluating other options, Mumble looks like the best choice on paper. I rented a server and found the audio quality fantastic. However, I didn't realize that the product lacked the feature at the time. I have had so much pushback from the lack of client-side audio adjustment that we had to switch back to Vent. Years of utilizing the feature is hard to break.

The automatic normalization does not handle every scenario for every person. Specifically, when you are in a channel with twenty other people, there are inevitably cases where you want someone just a little quieter. You don't want to mute them, but you don't want the voice to stand out on your client.

I find it particularly relevant to revive github issues every month or so. If there's is no evidence that people care, it is easy to sideline the request for other tasks.

**Comment by Eltiech** [comment]
I can't speak for anyone else, but this exact feature is why a community I'm a part of moved off of mumble and onto teamspeak.

**Comment by AeSix** [comment]
So, my three cents:
Yes, the feature is wanted and needed by the community at large. 
Yes, the developers see an alternative to using this feature.
Yes, there are arguments for using and for avoiding this feature.

I don't see why this is such a huge deal when someone could easily create an add-on or a custom Mumble build that would include this feature. I understand that this is not how Mumble builds are normally created, but this is open source software, and that prevents no one from creating a fork or add-ons.

With that said, there are many programs which lack what some would call a minor feature, but others see as a very big deal. If that isn't clear to the devs, then perhaps they need to really learn their user base, or start targeting specific users. Microsoft recently learned this lesson when they removed the Start menu from Windows 8. It was seen as an outmoded methodology to Microsoft, but a rather major change to many users who use computers for more than just facebook. 

The only alternative that I can see that would appease the community of potential new users and to bring back other users, like myself, while not implementing per-user volume would be more difficult. To create a better audio leveling and equalizing algorithm that would adjust the volumes of each talker on the listener's side to that listener's predetermined decibel level, making quiet talkers louder and capping loud talkers (which will inevitably cause audio clipping where they are not understood). I understand this is similar to what Mumble currently has implemented, however this is more in depth audio leveling. 

Now, can this thread be locked? The next piece of email I want to receive regarding this issue is that it has been tested and is being implemented.

**Comment by chevex** [comment]
@Tarun80 If anything is a false claim, it's your idea that anyone who says this feature is the only thing keeping them or their clan/guild/group from switching to mumble is just lying.

**Comment by Kissaki** [comment]
> I don't see why this is such a huge deal when someone could easily create an add-on or a custom Mumble build that would include this feature.

Because it’s not *easy*, or quickly done.

We already stated we want it in the official client, and that work has been started. There’s various tasks and issues, and only limited time in the free time we (can) designate to the project though, so I don’t think it had much progress recently. We did not abandon this feature though.

Saying that people who state they do not make a switch because of this feature are lying is pretty rude. We don’t know what others base their decisions on - even if they are not based on facts; which is not the case here. If there were no use case for this, we would not target a release in the official client. If the automatic algorithms were perfect, we’d try to (only) educate users instead.
We also know that political decisions are not always based on facts. Even a single GUI display issue may block an otherwise very important and useful migration or switch.

Although constant bugging can be annoying and especially frustrating (because you can’t devote the time and motivation to a project or feature you would like to, and then even more so feel like it’s a pressing issue and/or you should be doing it for others/leave them in a pitch), obviously when people want the feature they have to communicate that somehow. Additional people posting does show the interest in it. Unfortunately, github does not provide a simple issue voting functionality, which could reduce the amount of additional "me too" posts.

I do not think locking the conversation would be the right approach.
Again, because of a limitation of githubs issue system, we can not get notifications for one or both of general, pre-done talk, and (only) a done-notification. I guess if subscribers want to get a notification of when its done, they will just have to live with other notifications like we developers have to. :)
It’s just how it is (for now).

We know this is a wanted feature, we want it as well, but it’ll still take time. It’s in queue.
There’s not much more I can say, even if this does not “help you”.

**Comment by chevex** [comment]
Very well said. Also, thank you for the update @Kissaki. Very much appreciated.

**Comment by jagodragon** [comment]
My group would much appreciate this feature. for a long time it WAS the only reason they didn't switch and there was a big push because of it to go with team speak... as the server host i explained to them that if they wanted ts they would have to find some one to pay for the server...

We stayed on raid call (crappy software if you ask me) for a while until too many of our members found it to be nearly unusable then i was finally able to get them to use mumble. we love it! this is great software. But, in a fight there are sertain members who can not keep from crying out or yelling in the heat of war... once they start yelling they don't stop.. it would be great for instances like that.

but, as it stands this feature not being here makes it so the only reason we use this is because of the ability to host our own server and not be forced to pay for a third party host to do it. but i will not complain too much as this is a free service and free program. i just appreciate that it is here to use.

**Comment by sxealex** [comment]
:dancers:  \o/   :dancers:  :heart:

**Comment by Xylemon** [comment]
Awesome, can't wait to compile and test out!

**Comment by chevex** [comment]
https://www.youtube.com/watch?v=nGE0P_jWWSg

**Comment by avollmerhaus** [comment]
Mumble has been rejected in my community because of this, maybe I can finally convince them to stop using teamspeak!

**Comment by KaLam1tyAC** [comment]
Been testing it for a couple days now and it's worked very well thus far. Great to see this finally implemented and I can't wait for 1.3 to go official.

**Comment by ForbodingAngel** [comment]
I was just wondering wtf I was going to do for a tourney coming up where I will be co casting with 2 or 3 other guys, one of which has a mic that is very "clippy". Awesome! Development snapshot here I come!

@Tarun80 dude, frankly, if you can't see how people would move to other products because of this feature, you have never truly been involved in a large online community. This feature was such a godsend in TS3 and one of the main reasons I moved from TS2 to vent way back in the day, even though I could not stand vent.

This feature is of dire importance.

**Comment by Tarun80** [comment]
@ForbodingAngel - since you missed the memo. This is closed. The feature was added to Mumble in the snapshots a while back. Not sure why you feel the need to try and call me out over having a discussion about this being added as a feature long after this has been **added** and **closed**. Oh, for what it's worth, I run a community with over 300+ people in it. But hey, since you want to be petty and if this helps you sleep better at night. More power to you, feel free to be rude.

**Comment by chevex** [comment]
Does mumble come with anti-burn gel or does he have to install that as a separate plugin?

**Comment by ForbodingAngel** [comment]
@Tarun80 lol bruh, umad? Dial back the asshurt a little bit. I wasn't calling you out, simply responding to an important discussion.

http://www.funnyjunk.com/Ring+bitch/funny-pictures/4901204/177

**Comment by chevex** [comment]
Quit projecting. You started up an argument that was resolved a long time ago. He was big enough to move on after arguing against it and seeing it implemented anyway. You're not impressing anyone.

**Comment by ForbodingAngel** [comment]
@chevex I'm not projecting. I replied to a discussion with my viewpoint and was immediately attacked for it. What are you, his momma?

Back in 2014, no one said shit for 6 months then someone replied, yet neither of you butthurt all over him for stating his viewpoint.

You might notice that this feature is STILL not in production versions, therefore, the discussion is still a valid one.

**Comment by chevex** [comment]
You replied to a discussion that is over and **closed**. I don't know how to put that more plainly. No, the discussion is not valid. It will make it's way to production builds in due time, but the debate about whether the feature should exist or not is over. It exists. You have what you want. And yes, clearly you are projecting, claiming others are "asshurt". Have you read your own comments? lol

This is what happens when your project is used by gamers. Trolls on Github. Le sigh.

**Comment by hacst** [comment]
This feature has been implemented and is available in snapshots and the upcoming 1.3.0 stable release. I'll lock this issue to prevent further confusion.
