### ISSUE TITLE
Colaborative Web Translation of .ts files

### ISSUE THREAD

**Issue by capiscuas** [mumble-voip/mumble#1180]
Hi, congratulations for Mumble, I find it very useful as free software alternative.
I would like to help you making easier the way people translate the strings of the software(currently it seems a bit difficult having to offline download the .ts file and edit them individually in our machines after installing more software)

Even though having 18 translations or more is a big success already. Congrats for that, it means the community loves you.
Now, I have used /www.transifex.com service(it's free for opensource softwares) for many years and it seems very practical for Mumble's case I think.

Plus new updated .ts will be pulled automatically from github so you won't have to .7z zip them anymore or mantain anything, it will be an automatically process.
Github support: http://support.transifex.com/customer/portal/articles/1166968-updating-your-source-files-automatically

They support the TS format:
http://support.transifex.com/customer/portal/articles/991987-qt-files

Should I help you out creating or configuring the transifex project for mumble and connect it to the github .ts files?
As soon as it's finished you'll have a new Esperanto ready for you since I'll send the link to our community.

Here you have many examples of open source projects using it already:
https://www.transifex.com/connect/projects/

Best Regards and thanks.

**Comment by comradekingu** [comment]
@Kissaki 
Weblate is libre software, and gratis for libre software, it [supports .ts files]([(comradekingu)](epost@anotheragency.no)).
I keep getting updates about new strings, but can't log in without re-licensing everything I have ever done on Transifex.

**Comment by Krzmbrzl** [comment]
Well we have been using Transifex for a while now and all our infrastructure (e.g. the bot for automatic pull requests) is working with it.

I don't quite understand the problem you have with Transifex? Why would anything be relicensed? :thinking:

**Comment by comradekingu** [comment]
I am just seeing the quality eroding and finding myself unable to do anything about it.

Because it enters their closed translation memory, along with every conceivable detail about my activity shared with all their spying scripts, and in turn aggregates thereof. The "why" is the original premise, indeed. Transifex is also a closed source service-only that isn't gratis for libre software projects. The usability is horrendous.

https://hosted.weblate.org/legal/ is even better than what it says about itself, brass tacks. There is a [helper-user/bot](https://github.com/weblate) and [webhooks](https://docs.weblate.org/en/latest/admin/continuous.html?highlight=webhooks#automatically-receiving-changes-from-github).

https://hosted.weblate.org/projects/mumla/#languages has only been on there for a month, and has good coverage already.
Self-hosted Weblate is also fine. (there are no good alternatives atm)
