### ISSUE TITLE
can't disable overlay

### ISSUE THREAD

**Issue by khmnc** [mumble-voip/mumble#1181]
I have been trying to turn off the overlay for planetside 2 but nothing seems to make it go away. i have disabled it globally and added the game to the black list but the overlay still shows up.

**Comment by The-Duchess** [comment]
firefox and derivatives use the GPU for rendering and now the mumble overlay will not disable despite disabling it and restarting all relevant applications and it appears in firefox!

**Comment by Kissaki** [comment]
Not for me. I don’t see this issue.
Are you using a non-stable Firefox?

**Comment by joltcan** [comment]
I'm using Firefox Quantum, 61.0.1 (64-bit), on macOS and just stumbled upon this issue as well.

**Comment by Kissaki** [comment]
Are you using a Mumble 1.3.0 development snapshot? Honestly I don't know what the 1.2 state is; maybe the blacklist is missing some stuff. So I’d suggest using 1.3.0 snapshots.

**Comment by joltcan** [comment]
Very good question, probably not. Ill look into it at work tomorrow and report back!

**Comment by Kissaki** [comment]
Are you using Mumble at work? That's pretty cool

**Comment by joltcan** [comment]
Trying the latest snapshot for macOS now, same problem. In the mumble overlay settings I see the whole desktop (albeit messed up due to my 3 screens), but in reality, the overlay just corresponds to my firefox window! The overlay is only drawn inside my Firefox window, not anywhere else on the desktop 😆 

Moving the overlay just moves it inside FF. Removing the overlay plugin changes nothing. Blacklisting FF changes nothing.

![screen shot 2018-07-12 at 09 44 20](https://user-images.githubusercontent.com/537157/42619377-2b173aec-85b8-11e8-8b04-a7a215699173.png)
![screen shot 2018-07-12 at 09 40 36](https://user-images.githubusercontent.com/537157/42619379-2b4ebada-85b8-11e8-84f1-79c1b0dbd68f.png)
