### ISSUE TITLE
Please add token in Mumble URL and make mumble client add token automatically instead of user

### ISSUE THREAD

**Issue by a1668753** [mumble-voip/mumble#1228]
Relevant docs: http://mumble.sourceforge.net/Mumble_URL (need to be updated too).

**Comment by ZeroAbility** [comment]
Updating URL's for posterity since the sourceforge page is gone:

https://wiki.mumble.info/wiki/Mumble_URL
https://wiki.mumble.info/wiki/Murmurguide#Access_Tokens

Is there a valid security reason where we would not want to have this behavior? Have we already implemented similar behavior since this issue is old?

**Comment by Krzmbrzl** [comment]
For reference, this is the associated code:
https://github.com/mumble-voip/mumble/blob/b133de94c08c1b148d4ee52296b6d14417d2ce57/src/mumble/MainWindow.cpp#L1147-L1225

However, we can't implement this feature as the client doesn't know which of its access tokens unlocks which channel (or whether they might only have access to that channel because they are in a specific group rather than having access tokens configured). Only the server has this information and it is not a good idea to give that information away to clients.
