### ISSUE TITLE
Fuzzy fonts/icons on Retina display

### ISSUE THREAD

**Issue by Frore** [mumble-voip/mumble#1267]
Running OS X 10.9.3 on a 13" MacBook Pro Retina Display, I have Mumble 1.2.6 installed. The program itself seems to function fine, but the actual interface is very fuzzy looking including the fonts in both the chat window and channel list.

**Comment by janniklorenz** [comment]
Any updates to that? Still planned for 1.3.0?

**Comment by mkrautz** [comment]
Not only planned, it is implemented (except for a few icons) on OS X. A bit unsure of Windows's status -- but it shouldn't be too bad.

Unfortunately, we can't release 1.3.0 just yet.

And we can't do it in 1.2.x, as those releases use Qt 4.

**Comment by brunophilipe** [comment]
This used to work on 1.2.9 (for everything but the icons) by adding `<key>NSHighResolutionCapable</key><true/>` to the `Info.plist` file, but on 1.2.10 it doesn't work anymore? Screenshots below:
![screen shot 1 2 9](https://cloud.githubusercontent.com/assets/2136642/9289271/c20bc4bc-4340-11e5-8ffc-cd547093c438.png)
<img width="938" alt="screen shot 1 2 10" src="https://cloud.githubusercontent.com/assets/2136642/9289272/c239597c-4340-11e5-84ac-ed43fa32d6b8.png">

**Comment by mrmayfield** [comment]
Bump. What's going on with this, the pixelation looks pretty bad.

**Comment by mkrautz** [comment]
Available in 1.3.0 snapshots on OS X and Windows...

**Comment by mrmayfield** [comment]
Yayyy

**Comment by mkrautz** [comment]
Since both OS X and Windows snapshots use Qt 5.6, I'll close this as fixed.

**Comment by mrmayfield** [comment]
Is 1.3.0 publicly available?

**Comment by mkrautz** [comment]
It's available from the front page of http://www.mumble.info. ...But actually, the OS X build has been out of service for some time... I'll re-open this until we get it into a good state.

**Comment by mrmayfield** [comment]
Yeah sorry I was referencing in terms of OS X. Kk that sounds good thanks. 👍

**Comment by brunophilipe** [comment]
@mkrautz The current version (1.2.16) for OS X already supports retina, but I have to add these keys to the plist file manually:

```
<key>NSHighResolutionCapable</key>
<string>True</string>
```

After that I run `touch /Applications/Mumble.app` and it works! 😃

**Comment by mkrautz** [comment]
@brunophilipe OK. I thought it didn't work anymore, since you reported otherwise at https://github.com/mumble-voip/mumble/issues/1267#issuecomment-131387557.

Perhaps we should enable it by default in what will potentially be a 1.2.17 bug fix release?...

**Comment by brunophilipe** [comment]
Yup! I forgot to update from 1.2.9 for a long time, and when I updated to 1.2.16 I tested it again and it worked.

I suppose so, yes. If you wish I can test it on my Mac before the public release to be sure.

**Comment by whitehat101** [comment]
It's really disappointing that this issue has been known for years, and supposedly fixed since around June 2015, but the official releases still have this bug.

Apple's been selling computers with Retina displays since 2012. In 2016, Apple technically sold one type of non-Retina device.

Effectively, all mac users (that do not opt for the "Development Snapshot") first experience with your app is a functional, but otherwise **hideous** application. The only other Really Ugly mac app I can think of would be pgAdmin 3, but pgAdmin 4 has been released and is stable. 

It's also quite disappointing that, as @brunophilipe points out, adding a single key value pair to a particular plist fixes this, on the current stable releases.

It's great that you guys are developing (or have already developed) an even better fix (but can't release it for whatever reason), but why on Earth can't you release the fix for the stable version?! Especially when it is so trivial.

Even the [Qt development blog](https://blog.qt.io/blog/2013/04/25/retina-display-support-for-mac-os-ios-and-x11/) brags bout how backwards compatible this plist option is:
> If NSHighResolutionCapable is set to false, or the keys are missing, then the application will be rendered at the “normal” resolution and scaled up. **This looks horrible and should be avoided,** especially since the high-dpi mode is **very backwards compatible** and the application gets **a lot of high-dpi support for free**.

**Comment by mkrautz** [comment]
Nothing prevents this from going into a 1.2.x point release. It's quite trivial, but it has missed many of our point-releases.

I've created https://github.com/mumble-voip/mumble/issues/2645 to track it.
It'll get into 1.2.18, which will probably release soon because of https://github.com/mumble-voip/mumble/issues/2638.

If you see us letting an issue sit, that you think is important, please speak up, or maybe even send a PR. That would be wonderful. We have quite a bit of backlog at the moment, and we appreciate all the help we can get.

Thanks.

**Comment by mkrautz** [comment]
Status update:

There are some problems with NSHighResolutionCapable=true and stock Qt 4.
For example, the icons in the connection dialog are double the size of what they should be when run with NSHighResolutionCapable=true.

I've tried playing with Qt's gerrit changeset 54636, but that doesn't provide very good results either (toolbar icons are too small... and still grainy).

Perhaps we'd be better off with simply getting 1.3.x done and ship that, I don't know...

Anyway, just a quick brain dump.

**Comment by whitehat101** [comment]
Here's an album comparing NSHighResolutionCapable true/false: http://imgur.com/a/AOC86 (Click for full size, setting is below image)

It's true that some icons are different sizes. But as far as I've noticed, nothing is pushed off screen or inaccessible (broken). The trade off is clear text everywhere.

I think it's worthwhile. For me, the blurry text is borderline unreadable. It takes more effort to read. Especially when you're setting things up and going through the audio wizard, there's a fair amount of text to read. Even if you don't need to read the text to complete the wizard, it's hard to look at a window with text without automatically trying to read some of it.

Thanks for your consideration.

**Comment by mkrautz** [comment]
While I don't personally like the large icons, I can agree that it's the better of two evils -- and maybe not very bad at all.

It's a good band-aid until we can release 1.3.x. We should just go ahead, I think.

**Comment by mkrautz** [comment]
I've snapshotted what will probably become 1.2.18:
https://dl.mumble.info/Mumble-1.2.17~5~gd254f6c~snapshot.dmg

It includes the Info.plist fix.

**Comment by mkrautz** [comment]
@whitehat101 I've now released 1.2.18.

**Comment by mkrautz** [comment]
I will close this bug since we've backported macOS Retina support to 1.2.x, and HiDPI support should work on macOS, Linux and Windows on 1.3.0.
