### ISSUE TITLE
Overlay not work on League of Legends

### ISSUE THREAD

**Issue by duanwujie** [mumble-voip/mumble#1288]
On the  windows xp the overlay not work on League of Legends game.

**Comment by Kissaki** [comment]
The other ticked referenced `TenProtect,so`, which I assume is an anticheat library they use. So if this is still an issue, and the anticheat is allowing fraps but not Mumble, they would have to whitelist Mumble as well for it to show. Nothing we should fix on our side. In that case, this ticket should be closed.

If this is caused by something else, we need more input.
