### ISSUE TITLE
not closing speech-dispatchers

### ISSUE THREAD

**Issue by dedavidd** [mumble-voip/mumble#1324]
After i have used mumble i am left with a lot of "speech-dispatcher" items in my pulseaudio playback tab. They are not properly shut down when quitting mumble. 
My theory is that they are opened when a user joins a channel or the server. in my settings i have set those messages to be done in text in the chatarea.

i run mumble 1.2.6 on debian.

**Comment by WizardGed** [comment]
This is annoying but to other people that just want a quick solution until this is fixed ```pkill -f speech``` does kill all the instances of the speech dispatcher left running on a system after mumble has been run.

**Comment by tYGjQCsvVI** [comment]
Same issue here, I've seen them stuck at 100% CPU before way after Mumble has quit (Which was why I even noticed they were stuck running), although I can't recreate that issue.

Is there any reason why they need to exist? I have all text-to-speech disabled in Mumble:-

![Text-to-speech photo](https://i.imgur.com/60K1dTR.png)

**Comment by HybridDog** [comment]
When l use the spd-say command, some "speech dispatcher: playback"s appear and don't disappear, now l have 4 although l executed the command more than 4 times.

**Comment by ubergard** [comment]
On Debian Jessie amd64 fully updated with Mumble 1.2.8-2 the five devices appear immediately when Mumble is launched along with the Mumble Speakers device in KDE Mixer. This is before connecting to any server/channel.
As I don't use the speech dispatcher for anything including in Mumble, I just removed it from my system along with the 17 packages afterwards using "apt-get autoremove" as those were no longer needed. That solved the problem for me and Mumble still works.

**Comment by mkrautz** [comment]
As @HybridDog notes, this is standard speech-dispatcher behavior. The speechd library spawns those processes.

(@HybridDog, just to confirm -- you have not seen speechd used with Mumble spawn more than those four processes, have you?)

If you look at the spawned processes, they're helpers for speechd's various backends.

You can even reproduce the behavior without Mumble:

    $ killall -9 speech-dispatcher  # make sure we start off with a clean slate
    $ ps aux | grep speech # Note that there are no speech dispatcher processes anymore
    $ spd-say "hello world" # Say hello world
    $ ps aux  # Notice that the dispatchers are now spawned, without any Mumble involvement.

...So, here's what I suggest:

If you *do* use TTS in Mumble, and find them annoying, I suggest you file a bug against speechd or your distro.

If you *do* use TTS in Mumble, and find that some of the speechd processes use 100% CPU, I suggest you file a bug against speechd or your distro.

If you *do not* use TTS in Mumble -- meaning that you have explicitly disabled Text-to-Speech in the Settings menu -- then we should strive to not initiate speechd at all.

But since this is expected speechd behavior, we will not be implementing this in the 1.2 series for now.

If I have misrepresented any of the existing findings, or there are other issues or disagreements, please let me know, and we will take a look again.

**Comment by HybridDog** [comment]
>you have not seen speechd used with Mumble spawn more than those four processes, have you?

no, l haven't

**Comment by Osirus126** [comment]
i have found a solution to the issue. 

in the properties of mumble.desktop the command to open mumble used to look like this
 **`Command: mumble %u`**
i added this to the command **`&& pkill -f speech`** and it seems to halt after mumble opens leaving speech dispatcher open until you close mumble, at which point it continues the command "&& pkill -f speech"

**Comment by ZeroAbility** [comment]
Debian had a bug filed for the 100% CPU:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=573897

Based on their release schedule, it could have still been in experimental per the report. If the rest is standard speech-dispatcher behavior, then can the original issue be reproduced?
