### ISSUE TITLE
Cannot add Mumble (1.2.7) to Assistive Devices list in Yosemite

### ISSUE THREAD

**Issue by jadanzzy** [mumble-voip/mumble#1326]
When you try adding Mumble in the Accessibility section within the Security and Privacy preference pane, nothing happens. Nothing also happens when you try dragging Mumble in from /Applications.

**Comment by theY4Kman** [comment]
This has been frustrating. Is there any news on this?

**Comment by mkrautz** [comment]
I am not able to reproduce.

Everything when works Mumble is added in Security & Privacy -> Accessibility, and I can add it just fine.

One caveat though: the *warning* won't disappear (unless you "skip" it), because 1.2.x used an old method to determine the accessibility API being enabled for the program.

I have made some quality of life changes regarding this in a1a5b10dba0a42368cd3db81d335f1e4cc1b6159

I will close this, as I feel it is fixed.

If the problem persists in 1.2.11, which will be released soon, please re-open or open a new bug.

Thanks!
