### ISSUE TITLE
Intermittent sound pops/crackles/static

### ISSUE THREAD

**Issue by pythion** [mumble-voip/mumble#1373]
+Intermittent sound pops/crackles/static using local mumble server.
My issue seems to happen exclusively on local servers and here's a list of things I've tried.
I'm using Windows 8.1 and Mumble 1.2.8.
- Windows
  *\* Installed newer sound drivers
  *\* Ran with Windows XP, Vista, and 7 compatibility.
  *\* Changed playback default audio format
  *\* Disabled Sound Effects
- Mumble
  *\* Old versions
  *\* Different qualities on server and client
  *\* Higher delay and jitter ms
  *\* QoS and TCP enabled/disabled

**Comment by Kissaki** [comment]
So, did you check the other users?
Did you try *increasing* noice cancellation?
Could you record an audio snippet, so we can hear what kind of category of issue it sound like?

**Comment by xclabit** [comment]
I also have a similar problem that's been on going since I switched from Ventrilo to Mumble last year. I sometimes hear this crackle sound when someone begins talking (and only at the beginning). It most often occurs when that person hasn't spoken after a while (probably few minutes).

An example can be found in this video:
https://www.youtube.com/watch?v=8NXWcJtoFUQ
You can hear the 'crackle' at time 4:26, 9:33, 9:40

**Comment by xclabit** [comment]
Any updated word on this?

Using the latest stable release of Mumble (1.2.10 for Windows), I have tried playing around with the amplification and noise suppression settings (min, max, mid) and users can still hear this intermittent crackling noise at the beginning of the my voice transmission. Likewise, I can hear this from other users. I also played around with the server settings to force OPUS and to use max 128 kbps bandwidth per user. Problem still exists.

Furthermore, I can sometimes force this crackle noise even in the Audio Wizard, particularly when I've been silent for a few minutes. 

I also see on SourceForge there are other users complaining of this issue, particularly in this thread from 2010: https://sourceforge.net/p/mumble/discussion/492607/thread/ccdf8c36#d1f1 

I have used Ventrilo before and never had this issue. Also recording my voice through other software shows no signs of this crackle noise. I'm currently looking for alternatives to Mumble now because of this crackle noise.

**Comment by danger89** [comment]
I also suffer from this 'plop' /'static tick' sound. Its definitely something due to Mumble, properly related to the sound **buffer** and/or the sound **compression algorithm** used in Mumble. 

Please developers, take this issue seriously! Its a very annoying issue, since the rest of the time the sound is crisp expect those moments. Often when you start talking (goes from muted to unmute).

**Comment by danger89** [comment]
OK, maybe I solved it under Linux.. I keep you posted.

I open alsamixer and changed the capture item (after pressing F4) to Gain: 0 dB, meaning no boost and also no lower. While alsamixer is open, in a different window save the settings using: `sudo alsactl store`.
In the volume control (`pavucontrol`), went to the Recording tab. And put the sound on 100% (0dB), again no boost no nothing.

As you can see under Linux you already have multiple places to boost signal.

**Comment by Krzmbrzl** [comment]
So I assume this to be somewhat fixed? If not, please let me know and I'll reopen this issue again

**Comment by rembomy** [comment]
I would say it is not fixed, I am experiencing similar thing on windows and it does not matter if i lower the volume or not. My input does not even have boost option and signal coming in is around 50% on the mumble voice activation bar. In comparison, I do not have a single issue when talking with microphone using other comms software or OBS. Similarly to other my mumble server is running on the same network as I am. 

I have tried playing with the sound bandwidth on server side, on client side, reconfigured my microphone on the mixer and on windows. Even added compression on mixer side to reduce input volume, but it did not change anything. Mic is not clipping and just occasionally messes up sound on Mumble.

**Comment by Krzmbrzl** [comment]
What Mumble-version are you using @rembomy ?

**Comment by rembomy** [comment]
08 Sept stable x64 1.3.0 for Windows. Server is running same, but on Linux and on another machine on the network.

**Comment by Krzmbrzl** [comment]
Okay. Thank you for the report. I'll reopen the issue :+1:

**Comment by Krzmbrzl** [comment]
Were you able to reproduce this behaviour on another computer as well? Does it happen on that specific server only or does it happen on all servers you connect to?

**Comment by rembomy** [comment]
Might be complicated to test it on another computer for me, but I will check on other servers. I'll check if someone can record this for me as well.

**Comment by Krzmbrzl** [comment]
Thanks! :)
If another computer is hit possible, then perhaps a different microphone? Do you happen to have another one? That would also be a valuable test for us.

**Comment by rembomy** [comment]
Managed to test same PC, but 2 different microphones. Main one (2 channels, 24bit 44100Hz) has issues, 2ndary (1 channel, 16bit, 44100 Hz) no issues. Interesting is that on 2ndary volume levels spiked much higher than on the Main. Neither of them had any issues with OBS at the time being when it happened in Mumble so I can confirm its not a hardware fault.  
It doesn't happen all the time, occurs randomly.

**Comment by Krzmbrzl** [comment]
That makes it hard to Debug of course. From reading through your test results my guess would be that it might be related to multi-channel microphones. Maybe the second channel somehow screws the system up.

Nonetheless I belive that this is a different issue than the one described earlier in this thread. Thus I'd ask you to create a new issue for it (sadly I can't just move comments from one issue to another (AFAIK)). If you don't get to do this, I might have the time later on to do it for you :)

**Comment by rembomy** [comment]
I opened a new one for my issue, thanks. https://github.com/mumble-voip/mumble/issues/3950
