### ISSUE TITLE
[Win64/Snapshot] Overlay sometimes randomly causes crashes of Windows processes

### ISSUE THREAD

**Issue by JoelTroch** [mumble-voip/mumble#1527]
With Windows 7 x64 and since a certain Mumble x64 Snapshot (around 3 updates earlier the latest version at the time I am writing this), some of my Windows processes (taskhost.exe being the most affected one) and sometimes other software like "Intel WiFi Dashboard" are crashing, in the Windows crash window (where I can choose between "Search a solution on Internet", "Stop the program" or "Debug the program"), they refer to "mumble_ol.something".

I'll give more details about this issue later since the crashes appears randomly and I am very busy those moments.

**Comment by mkrautz** [comment]
We recently enabled the overlay for 64-bit programs when running the x64 snapshot.

Seems like the x64 overlay doesn't like some of the processes on your system.

Do you know which program taskhost.exe refers to?  Here's a guide that explains how to figure it out:
http://www.ghacks.net/2010/05/12/taskhost-exe-process-explained/

However, since the taskhost.exe process is crashing, the guide is quite useless.  Can you spot if something goes missing on your desktop when it crashes?

**Comment by mkrautz** [comment]
Also, something that could be helpful would be to add those processes to your 'LocalDumps' registry key (HEY_LOCAL_MACHINE\Software\Microsoft\Windows\Windows Error Reporting\LocalDumps).

For example, here's how I've added FarCry4.exe to get minidumps from it:

![image](https://cloud.githubusercontent.com/assets/36527/5767867/fab8635a-9d0b-11e4-882f-d2faa436b510.png)

(The DumpType=1 specifies that you want a minidump as opposed to a full dump)

After the processes crash, their dumps will be available in %LOCALAPPDATA%\CrashDumps

I'd like to have a few so I can look at them.  If you think they might contain personal data, feel free to email them to me at mikkel@krautz.dk.

**Comment by JoelTroch** [comment]
Thanks for those useful informations, I'll provide the necessary informations as soon as possible.

**Comment by JoelTroch** [comment]
I had the crashes when I closed Mumble, it crashed my Intel WiFi Dashboard and my "taskhost.exe", unfortunetaly, I wasn't able to go deeper in "taskhost.exe", you can download the minidumps here : https://1fichier.com/?drn2o61701

**Comment by mkrautz** [comment]
Thanks.

The crashes are in mumble_ol.dll after the DLL itself has been unloaded.

Windbg isn't too helpful in resolving the offsets to symbols, and I can't get dissasembly because the DLL wasn't loaded, so the memory is not included in the dump.

I'll need to addr2line the address or dig manually, but I don't have an MSVC compatible version right now.

Anyway, thanks a lot.  Now we know where to dig.

**Comment by mkrautz** [comment]
Closing this, as mumble-voip/mumble#1637 is closed.

If this is in error, pleas re-open (or re-create).
