### ISSUE TITLE
Broken notifications on Fedora 21 (GNOME 3)

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#1535]
Bendem reports on IRC that notifications are broken in Fedora 21.

HTML messages can be displayed just fine.

But notifications that include our own URL schemes (users and channels), are not displayed correctly:

https://i.imgur.com/HrSL32H.png

Are we assuming that those messages do not include HTML, and force plain text display?  The notification code is older than the clickable usernames and channels, so it's possible I guess.

**Comment by bendem** [comment]
I guess the problem is upstream tho,
`notify-send --icon=gtk-add "Test" "This a <a href='http://test.com'>link</a>"` breaks in the same way as mumble does but `notify-send --icon=gtk-add "Test" 'This is <i>italic</i>'` works just fine.
(a similar report has been made to Cinnamon: https://github.com/linuxmint/Cinnamon/issues/2416)
