### ISSUE TITLE
Nobody can hear me & I can't hear anyone

### ISSUE THREAD

**Issue by Exaltedqt** [mumble-voip/mumble#1541]
I've had this issue with mumble for a few hours now, seemingly out of the blue where I'm unable to hear anyone talk and they also cannot hear me.

1. I tested my mic and headphones in skype, so I know they are working just fine.

2. I did multiple clean uninstalls of mumble.

3. I can hear myself in the audio wizard just fine.

4. When I first enter the mumble server, I can hear talking for a split second before it seems like I'm auto deafened and muted.

5. Nobody has me muted/deafened.

6. Vent works fine.

7. Other mumble servers and channels also do not work for me.

The only thing that changed regarding my computer was that I switched from wifi to ethernet this afternoon, which weirdly required me to switch my Speed & Duplex to 10Mbps Full Duplex for it to even function. I've also tried reverting this change, and switching back to wifi, but the problem persists with mumble.

Completely fucking stumped here.

**Comment by meZee** [comment]
I see that you've closed this, but this is a seemingly intermittent issue, I'm not sure what causes it, but after some time I won't be able to communicate, and I can't hear them communicate, it is usually solved after I restart mumble. I'm not sure if it would be related, but I also run multiple instances. I've noticed it also happens when connecting and disconnecting from a VPN connection, but it happens over time even without establishing a tunnel. I'm connected via ethernet to my LAN, no WiFi adapter.
