### ISSUE TITLE
Mumble interferes with Visual Studio 2013

### ISSUE THREAD

**Issue by Squazz** [mumble-voip/mumble#1549]
I don't know what data to supply you guys with for this bug, so please do tell me what I can give you to help you more.

I have some problems with Visual Studio 2013 when I have Mumble running.
If Mumble is open and running when starting Visual Studio 2013 (From now on VS13), VS13 won't update it's "view". When clicking anything I have to minimize and reopen the program to see the change.
If on the other hand I first open VS13, and then Mumble, there is no problems. Everything works as intended.

I don't what I can be that makes this happen, just wanted you guys to know.

**Comment by Squazz** [comment]
I made a video to shoe it: https://www.youtube.com/watch?v=Z_vetlruy58

**Comment by hacst** [comment]
Strange. devenv.exe should be blacklisted (at least for somewhat recent Snapshots). Which version of Mumble are you using?

**Comment by Squazz** [comment]
Oh, I'm using 1.2.6, is that the problem?

**Comment by hacst** [comment]
1.2.8 is the latest stable. The current snapshot is 1.3.0~511 . Unfortunately we haven't been able to release for quite a while due to some blocking issues we don't want to release in a stable.

If you don't want to run a snapshot you can work around the issue with the old stable by manually adding the devenv.exe to the mumble blacklist using the following steps:

* Configure->Settings
* Make sure "Advanced" in the bottom left is checked
* In the Overlay menu select the overlay exceptions tab
* Press add and browse to the devenv.exe

This should fix the issue. Another alternative is to disable the overlay completely if you don't use it.

**Comment by Squazz** [comment]
That fixed the problem :) Thanks

**Comment by hacst** [comment]
Awesome. I'll close this then.
