### ISSUE TITLE
Bad Opus compatibility when using 1.2.3-349-g315b5f5-2.2+deb7u2?

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#1586]
micah reports on IRC that a user using 1.2.3-349-g315b5f5-2.2+deb7u2 has problems communicating with other users on a server that is also running 1.2.3-349-g315b5f5-2.2+deb7u2.

The server had negotiated Opus, but the user using 1.2.3-349-g315b5f5-2.2+deb7u2 could not hear what  other people were saying, nor use server loopback. (Local loopback worked fine).

**Comment by actown** [comment]
It looks like that snapshot of 1.2.3 is the provided version in debian wheezy https://packages.debian.org/wheezy/mumble (1.2.3-349-g315b5f5-2.2+deb7u2)

**Comment by crknadle** [comment]
Touched base with mkrautz in IRC this evening, he mentioned this bug and the fact that it could theoretically be related to #1968 and #2007 -- if it's like those:

"Try if forcing TCP (With advanced checked go to Network -> Force TCP Mode) helps. If so this is likely caused by a Qt bug which randomly prevents us from receiving UDP."

Unfortunately the fix involves patching Qt4 which is not a simple matter on Debian Wheezy and Jessie.

**Comment by Krzmbrzl** [comment]
I assume this issue is outdated by now. If not, please let me know
