### ISSUE TITLE
Option to specify mumble.sqlite

### ISSUE THREAD

**Issue by bitingsock** [mumble-voip/mumble#1613]
As far as I understand, if a command line option to specify a database was implemented it would solve a lot of people's multiple instance issues (and other issues like permissions).

Another thing I noticed is that -ini is not listed as a valid option when running "mumble --help"
Also, if mumble is run with "-ini" does it switch to portable mode?

Essentially, if you could specify an .ini and a .sqlite you could get the benefits of making a duplicate folder by just have these two files somewhere.

**Comment by JoelTroch** [comment]
If you are running on Windows, you could make a batch script that change temporarily the `%APPDATA%` env variable and start Mumble, something like that (might be wrong, haven't done Batch a long while) :
```batch
set APPDATA="C:\Program Files\Mumble\CustomConfig"
start "C:\Program Files\Mumble\mumble.exe"
```
I think this can also be done on Mac OS and Linux.

**Comment by Eriner** [comment]
@JoelTroch If you used a chroot, yes, this could also work on linux systems. You may be able to pass some envars as well, to simplify things.

**Comment by bitingsock** [comment]
I finally got around to trying your suggestion but unfortunately it does not work for me. I'm running procmon and can see mumble trying to do something with this new path but it never actually generates anything inside. Furthermore, it continues to load the settings out of the normal appdata path.

**Comment by mkrautz** [comment]
So, right now the client has a built-in feature where if you place an .ini file in the same directory as mumble.exe, it'll be "portable", and write all its settings into that ini file, and use that directory as its app storage dir. (You refer to that in your original description, so I'm guessing you're aware!)

What you're suggesting, in addition to the above, is a command line flag for specifying an .ini to use; alternatively, simply a directory to use as the app data for Mumble.

The problem with @JoelTroch's approach is that Mumble will still use the registry as the config store in that solution.

I think that's pretty reasonable.  But we should consider how it should look.

Should you only specify the path to the .ini? That's confusing, because it doesn't signal that Mumble will use the directory that the .ini lives in as its app data dir.

So perhaps it should point to a directory to use for that session, like a profile directory in a browser.

How about something like:

    mumble.exe -profilepath %userprofile%\mumble-normal-identity
    mumble.exe -profilepath %userprofile%\mumble-alt-identity

With a description like:

    -profilepath
        Specifies a profile path to use for this session.
        The profile path is a directory where all settings and data will be stored.
        Profiles can be used to create fully separate instances of Mumble that will not interfere with one another.

**Comment by bitingsock** [comment]
Your solution seems to make more sense, considering the how you mentioned all the other stuff mumble looks for. I'm not opposed to a cleaner OS-based solution, I'm mostly trying to avoid have multiple installations.

**Comment by Krzmbrzl** [comment]
With the latest version (1.4.0 - currently available as development snapshots from our website) you can set the database's location in the `Mumble.conf` file on Linux and in the registry on Windows. The corresponding key is `General -> datavaselocation`.
