### ISSUE TITLE
Set max slots per a channel

### ISSUE THREAD

**Issue by HarpyWar** [mumble-voip/mumble#1619]
For example, create "private" channel without a password where only 2 users can communicate.

**Comment by Tarun80** [comment]
This would be a nice addition, along with the ability to have a true AFK channel (muted/deafened), and setting a channel phonetic.

**Comment by bheart** [comment]
@Tarun80 you can deny all the Speak privilege in your AFK channel, suppressing anyone who enters.

**Comment by Kissaki** [comment]
I don’t see the use case.

For AFK channels, you can already enforce mute.

You can already enforce a user limit per channel by creating an Ice script that handles user state changes (joining channels).

**Comment by Tarun80** [comment]
Why use an ice script when it could be a simple feature that's integrated and handled in the sqlite database? Not everyone uses ice/dbus.

Running a guild, it would be nice to have it where Mumble supports only a certain number of users in a channel. I've had it where people run a dungeon and others not running also join in when the people who moved specifically did so in order to just talk with their group running the dungeon. The channel limit in this case would be beneficial because anyone not in said group couldn't join the channel once the limit has been hit.

For AFK channels, people can still hear TTS and things of that nature, they're not deafened, yet that should be supported so that there's a true AFK channel like what most other VoIP clients support. I know Teamspeak and Ventrilo both have true AFK channel support.

**Comment by HarpyWar** [comment]
@Kissaki Do you mean that Ice script can handle user state changes as events in real-time? If not then it can not be a replacement.
It also can be used on a public servers where server admin wants restrict max users per channel.

**Comment by Kissaki** [comment]
Yes, real-time. See http://mumble.sourceforge.net/slice/1.2.7/Murmur/ServerCallback.html#userStateChanged
That should allow it.

**Comment by Natenom** [comment]
A script for this is for example http://wiki.mumble.info/index.php?title=Mumo#Max_users

We use that on our private server for a while (if you want to test is...). The problem with such a script is that users can still join the limited channel before the servers moves them back.
One can spam with joining messages or even can hear the discussion for a very short time depending of the speed of your server. In this case the server would need an additional script for antispam, see http://wiki.mumble.info/index.php?title=Mumo#AntiFlood

With a user limit via murmur users wouldn't be able to join a "full" channel at all and the setup would be much easier.

**Comment by JoelTroch** [comment]
I think @Tarun80 asked this feature to be in Mumble itself because some Mumble providers don't allow you the usage of DBus/Ice. I might be wrong though, if it's the case, sorry.

**Comment by HarpyWar** [comment]
Sure, a Mumble hosting provider can give you only access to a web control panel, without direct Ice access. 
Anyway feature to set a user limit per channel from GUI will be much easier than use 3d party scripts, even on your own server.

**Comment by Tarun80** [comment]
JoelTroch and HarpyWar are correct. We should not have to rely on third party scripts for functionality that would benefit the program as a whole.

**Comment by thecure** [comment]
I use Mumble every day; I'm a nontechnical user and I don't know what an ice script is. +1 to make it a feature via the GUI.

**Comment by FilipPyrek** [comment]
Exactly @thecure and @Tarun80!  :+1:  to make it a feature via the GUI.

**Comment by Tarun80** [comment]
Oh man I forgot about this being here. There's also some who are unable to use dbus or ice.

**Comment by mkrautz** [comment]
Fixed by mumble-voip/mumble#1889.
