### ISSUE TITLE
opus music profile

### ISSUE THREAD

**Issue by copyliu** [mumble-voip/mumble#1630]
The Opus codec has a music profile for high-fidelity encoding. (form http://www.opus-codec.org/docs/html_api-1.1.0/group__opus__encoder.html#gaa89264fd93c9da70362a0c9b96b9ca88 )

can we add a option to client that can let the user decide to optimize for voice or for music?
a patch i found for that is in https://github.com/Natenom/mumble/commit/63f00d1afd59f645a1849467cc0fdbd3ce32e165

**Comment by mkrautz** [comment]
I think this is fine as a hidden setting, but I don't think it's something most people should worry about.

So I think this can go in, as long as we don't add any UI for it.

**Comment by copyliu** [comment]
+1 for hidden setting.

**Comment by Kissaki** [comment]
I agree.
Probably more of a use-case for Bots, and people looking for this specifically.

**Comment by mumbledenoise** [comment]
+1 Would love to see this!

**Comment by TFMvdBroek** [comment]
+1 Yes please :)

**Comment by hacst** [comment]
Agree with @mkrautz . Hidden setting is fine as it's just a flag for us. Against adding any more obscure UI options.

**Comment by TFMvdBroek** [comment]
Does that mean that we can expect it to be available in the next release?

**Comment by JustArchi** [comment]
Bump.

**Comment by Kissaki** [comment]
Please don’t meanlessly "bump" issue tickets/feature requests with comments. From what I can see this issue has already been discussed and a consensus reached, and you did not add any new arguments or other points.

If you just want to agree or show you support for this feature request, please use the "reaction" functionality on the initial post with a "thumbs up". Scrolling through every feature request and counting "+1" comments would be a waste of time. Just as "bump" comments are, where we have to handle, read and remove notifications instead of (potentially) doing useful stuff. While a single one is not problematic, it being used as a system would be.

Not trying to BM, just arguing how you could better show your support.

**Comment by WhatsCS** [comment]
Has this request been approved or slated for eventually? If not could we get a reason or two for those of us who want to see this added? If a PR is desired then I'm sure someone would be happy to provide it.

**Comment by mkrautz** [comment]
@WhatsCS Yes, we've agreed that it is a desirable feature. We decided a hidden setting would be best.

Someone just needs to submit a PR to add it. :-)

**Comment by Natenom** [comment]
FYI: @SuperNascher is working on it, based on the mentioned patch :)
