### ISSUE TITLE
Inbound audio leaks to outbound audio when microphone is on

### ISSUE THREAD

**Issue by letharion** [mumble-voip/mumble#1657]
Whenever I speak, and my microphone activates, inbound audio leaks into the outbound, often forming a feedback loop.

Using the same headset, I haven't noticed the same problem in either skype, hangouts or teamspeak, so I believe it's a bug in mumble.

I'd be happy to debug this further, but I have not idea where to begin. Are there any debug instructions anywhere that I have missed?

**Comment by nicolasjoly** [comment]
Hi! This is normally caused by your headset speakers being too loud and your microphone capturing too much. Mumble is a little trickier than the other programs but it gives you a lot more latitude. You will have to fumble around with "Noise Suppression" (mine is at max = -60dB), "Echo" (mine is at Multichannel), with the transmission (this is personal because of how loud you speak and your microphone quality) and with the Volume (mine is at 100%). The first 3 are in Audio Input, the last one in Audio Output.

**Comment by letharion** [comment]
@nicolasjoly Thanks! I guess that sounds like a likely culprit. I have fiddled with the guide multiple times though, trying to get it right. I'll try again. :)

**Comment by Djarid** [comment]
This is ocurring on windows 10 with a microphone with a physical PTT switch. The audio passthough is happing in software (OS or App)
