### ISSUE TITLE
Typo in bad certificate message.

### ISSUE THREAD

**Issue by nighthawk702** [mumble-voip/mumble#1658]
The first word in the message box is typed wrong. Sever in place of server.

**Comment by hacst** [comment]
Which version of mumble do you use and what's your system language (us, uk, something different?). Couldn't find the typo in our current code (which is what's in the snapshots).

**Comment by nighthawk702** [comment]
My version is 1.2.4.0ubuntu1.1. System language is US.

**Comment by hacst** [comment]
Yeah. That's a pretty old version. This typo is very likely fixed in recent versions (like the snapshots you can get from our PPA at https://launchpad.net/~mumble/+archive/ubuntu/snapshot). Thanks for reporting though. I'll close this issue. If you find the typo is still in the newer version we'll reopen it.

**Comment by nighthawk702** [comment]
Thanks. I am using the version that is available in the ubuntu repos. I'll
upgrade as soon as I can.


2015-05-10 19:02 GMT+03:00 Stefan Hacker <notifications@github.com>:
