### ISSUE TITLE
portion of code always working when the microphone is mute

### ISSUE THREAD

**Issue by philectro** [mumble-voip/mumble#1681]
When you mute the mic, the echo cancellation is still working and eat around 15% of cpu on my core 2 quad 9550. It should be idling while mute and open when i'm opening the panel of options.

It will eat your battery too.

With PulseAudio and echo cancellation the cpu consummation is around 40% (20 for mumble, 20-25 on PulseAudio) always when the microphone is mute.

There is something to do here, please fix it...it does over 3years than this lot of cpu use exists.

i suppose than this is for all OS(the fact echo cancellation is still applied when  mic muted). If i will be able to propose a patch, i will...but i can't.

Thank your for listening, i have find others topics over 3 years of people complaining (and even trying to give you a patch) for fix it.

EDIT(mkrautz): Changed PA to PulseAudio

**Comment by mkrautz** [comment]
This feature is not only 3 years old. It has existed since Mumble was created.

The fact is, Mumble will continuously process your audio, even when the microphone is muted in the program. A mute in the program simply means it won't be transmitted to others.

The reason it was done this way, I believe, is to keep the automatic gain control working, so that you can immediately return to your conversation after unmuting -- presumably, the other preprocessor steps benefit as well.

However, if our solution to people experiencing this problem is to simply tell them to exit Mumble in these cases -- the end result is the same: when you start up your Mumble client again, the state will be clean, and it will have to adjust.

So, I think we should probably implement the behavior that people expect: to stop processing audio when you are muted. And then, possibly add an option to keep the processing going, for people who want the old behavior.

I'm very curious though -- what OS are you seeing these numbers on? They are inconsistent with anything I've ever seen on Windows.

**Comment by philectro** [comment]
i'm on fedora 21 using PA :)

**Comment by mkrautz** [comment]
Changed the top post to refer to PulseAudio instead of PA (which means Positional Audio in Mumble speak).

**Comment by philectro** [comment]
I add information from my tests.

set the audio delay from 10ms to 20ms divides by two the cpu cost on PulseAudio
9% vs 18-19% 
and the combination of that with echo cancellation disabled shut it down to 5%(but the input seems really less proper without that)

**Comment by mkrautz** [comment]
Note that it's also possible that your PulseAudio daemon is *already* doing echo cancellation for your mic.

Also, I recall there being an issue with our PulseAudio subsystem that set latencies way too optimistic, resulting in higher CPU%. I don't have a bug to reference, but I will check later.

**Comment by philectro** [comment]
i have do the same test today and the result is different.
amusing when a day after another the same thing you do give you a different result :)

today no change while i set it 20 or 10ms (audio delay) always 11-12% of one core used by PulseAudio

**Comment by davidebeatrici** [comment]
Closing in favor of #1089.
