### ISSUE TITLE
provide option to set alsa device string

### ISSUE THREAD

**Issue by lemmi** [mumble-voip/mumble#1690]
Unfortunately I'm forced to have a definition in asound.rc for my capture device. This device isn't listed in the list of available capture devices. Yet it works to set the name of the pcm device in the Mumble.conf. Of course the value gets overwritten as soon as I hit the apply button in the options menu. 
So I suggest to add an option to set the alsa device by hand via a text-input.

**Comment by eNTi** [comment]
i second this request. Mumble shows only the devices listed in arecord -L
`null
    Discard all samples (playback) or generate zero samples (capture)
pulse
    PulseAudio Sound Server
default:CARD=Audigy2
    SB Audigy 5/Rx [SB1550], ADC Capture/Standard PCM Playback
    Default Audio Device
sysdefault:CARD=Audigy2
    SB Audigy 5/Rx [SB1550], ADC Capture/Standard PCM Playback
    Default Audio Device
front:CARD=Audigy2,DEV=0
    SB Audigy 5/Rx [SB1550], ADC Capture/Standard PCM Playback
    Front speakers
rear:CARD=Audigy2,DEV=0
    SB Audigy 5/Rx [SB1550], ADC Capture/Standard PCM Playback
    Rear speakers
center_lfe:CARD=Audigy2,DEV=0
    SB Audigy 5/Rx [SB1550], ADC Capture/Standard PCM Playback
    Center and Subwoofer speakers
side:CARD=Audigy2,DEV=0
    SB Audigy 5/Rx [SB1550], ADC Capture/Standard PCM Playback
    Side speakers
iec958:CARD=Audigy2,DEV=0
    SB Audigy 5/Rx [SB1550], ADC Capture/Standard PCM Playback
    IEC958 (S/PDIF) Digital Audio Output`

Instead of showing the capture devies listed through arecord -l
`**** List of CAPTURE Hardware Devices ****
card 0: Audigy2 [SB Audigy 5/Rx [SB1550]], device 0: emu10k1 [ADC Capture/Standard PCM Playback]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: Audigy2 [SB Audigy 5/Rx [SB1550]], device 1: emu10k1 mic [Mic Capture]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: Audigy2 [SB Audigy 5/Rx [SB1550]], device 2: emu10k1 efx [Multichannel Capture/PT Playback]
  Subdevices: 1/1
  Subdevice #0: subdevice #0`

Please do it like teamspeak 3 and make an input field for the device.
