### ISSUE TITLE
Can't use bluetooth microphone, audio works fine

### ISSUE THREAD

**Issue by mpkarlo** [mumble-voip/mumble#1708]
I have a Turtle Beach PX5 Headset paired to my PC using bluetooth. I was able to test the sound and microphone on Skype and Windows. But when I try to complete the Audio Wizard on Mumble, I can't seem to get it to pick up my voice.

It seems the problem is with the Bluetooth connection, as the audio only worked through the S/PDIF out or the speakers. I've tried setting it as the default device, re-installing, and restarting. No luck.

Don't know what else to try, the volume for the microphone is maxed out, and I can see it picking up sound in the Windows Sound Window.

**Comment by KMelendez** [comment]
So I troubleshooted my way out of it, bit by bit. Regardless, it's a situation I believe deserves attention, so I'll include the details below:

I have a Xbox 360 Controller (Wired) plugged into the same PC. This controller provides a Microphone adapter as well, which I usually have disabled.

Turns out that if I go configure mumble I have to disconnect my Xbox 360 Controller, configure my microphone, then plug it back in. Otherwise it doesn't pick up sound from the Hands Free bluetooth device.

This is pretty inconvenient. I hope that I don't have to do this every single time, but there it is.

If any other information is needed, I'll be happy to provide or test any other ideas.

**Comment by Krzmbrzl** [comment]
I assume this still happens in 1.3?

Have you tried with a microphone that is not connected via Bluetooth? Does the problem occur as well or does the XBox controller onyl seem to cause trouble with bluetotth headsets (were you able to test whether this also happens with another bluetotth mic?)
