### ISSUE TITLE
Whispers bleeding into regular push-to-talk chat

### ISSUE THREAD

**Issue by doggydude73** [mumble-voip/mumble#1754]
So... I am not sure what is causing the issue but when I am whispering a group of people, occassionally the voice will carry out to the entire group.  

Attached is a copy of my key-config.
![keybinds](https://cloud.githubusercontent.com/assets/4459418/8689737/5fbb63f4-2a71-11e5-8bed-8889331cd016.png)
  I can give more information as requested.

This is a really recent issue (today was the first time I noticed but wasnt happening on Sunday). I tried working with  1.2.9 and 1.2.10.  Uninstalled both, cleared local app data and am out of ideas.

**Comment by jagodragon** [comment]
I have the same issue with my server

**Comment by doggydude73** [comment]
I ended up learning a bit more about this issue from a friend.  One of the ways (I believe) that can fix this is to take the hold time and turn it to 0 seconds. That setting is in Audio Input --> Transmission Section --> Hold Time Slider bar.  It seems to fix the issue and havent had any complaints since then but the only problem now is I tend to release my key early and it cuts off my transmission part way through a word or end of sentence.

**Comment by LuaMilkshake** [comment]
I encountered this today and worked out the reproduction steps:

- Set your Audio Input > Hold Time to a value that you'll be able to double-push the PTT button within (ex 1000ms)
- Whisper to a target and release the PTT button
- Within the Hold Time value, press the PTT again
- You are now talking to the channel, not just your whisper targets

**Comment by Krzmbrzl** [comment]
I am unable to reproduce this issue with the current master (1.4. snapshot). If I use a hold-time that long, then whispering will always keep on going for that time before switching to normal voice, even if the normal PTT button has already been pressed. In the latter case audio will switch to normal speech once the whisper timed out.

When holding the PTT button and then also pressing the whisper button, the latter takes precedence immediately (same goes for when pressing the whisper button as long as PTT times out).

Given that this issue is quite old now, I'll assume that it has been fixed. If you still encounter this with Mumble 1.3.0 or newer, please reach out to me :)
