### ISSUE TITLE
Stricter minVersion

### ISSUE THREAD

**Issue by funkydude** [mumble-voip/mumble#1770]
Currently we have "suggestVersion" which prints out a pathetic text line when joining a server that most people won't notice. I propose changing this to be more obvious, adding a new variable, or both.

Maybe the implementation of a "minVersion" var would be best. I'd like to see something that generates a popup and says:

> Your version is too old to connect to this server. It requires at least version 1.2.10, please download it by clicking here.

This enforcement should probably not apply to Linux users. 1) because they may be on an old version or have the latest changes patched into the old version and 2) because it has a sane updating mechanism anyway.

**Comment by Tarun80** [comment]
As a server administrator who had difficulty getting people to upgrade during some of the exploit fixes, I very much like this idea.

**Comment by nicolasjoly** [comment]
I have Mumo with Wrong Version addon. I set it to the latest version with just a warning and after a week or so I make it kick people with an older version.

**Comment by funkydude** [comment]
I'm unaware of said addon, but we may want it copied into mainline.

**Comment by JoelTroch** [comment]
I like this too, some people on my Mumble server are still running 1.2.7 even if I left a warning about the 1.2.10 update.

I suggest "modes of warning" that servers OP could choose about outdated versions:
* Light: Just a console message.
* Medium: A warning popup window and a console message.
* Brutal: Kick + warning popup + console message.

@nicolasjoly I think a lot of people uses dedicated Mumble servers providers and most of them don't allow you the usage of Ice, Python scripts and stuff like that. I think that's why @funkydude asked to have this feature implemented into Mumble itself.

**Comment by funkydude** [comment]
There is no need for "Light". That functionality is already implemented in the form of the variable "suggestVersion" which I am currently using. "Medium" and "Brutal" is what we need.

**Comment by Tarun80** [comment]
My concern is the popups. I don't believe popups are necessary. Some people may dismiss them.

I believe a message in the log where the connection is perhaps refused may be sufficient.

"Your version of Mumble is out-of-date and below the minimum that the server requires. Please download the latest version here." -- here could be a clickable link, or you could simply say "here: <mumble url>"

**Comment by funkydude** [comment]
Yep I agree. You pretty much described my original post :P which I think would be the best solution.

**Comment by jagodragon** [comment]
Does mumo allow you to kick for other reasons like not having ptt enabled?

**Comment by Krzmbrzl** [comment]
Closing in favor of #4128
