### ISSUE TITLE
Echo cancellation disabled in OSX

### ISSUE THREAD

**Issue by Toasty27** [mumble-voip/mumble#1775]
I know this has been a long-running issue, but I didn't see any mention of it in closed or open tickets in Github.

The echo cancellation feature has been missing from OSX for a long time (forever?), since OSX doesn't offer a method for getting all the audio streams in the system through CoreAudio. There are other applications out there that can achieve this, but supposedly they use a lower-level interface than CoreAudio.

If this is impossible for some reason, please leave a detailed explanation so that others don't ask for this feature in the future. If there is no reason, then lets have a meaningful discussion on how to implement it.

**Comment by Ginja** [comment]
+1

**Comment by mkrautz** [comment]
We need to change the AudioUnit used in CoreAudio.cpp to use the VoiceProcessingIO audio unit. However, it is not as simple as just changing the audio unit subtype, which caused various problems -- the CoreAudio code needs to be reworked somehow.

I don't recall the problems encountered when simply switching the audio unit subtype, but I believe it simply "broke" audio output and/or input.

**Comment by mike-sol** [comment]
+1 from me as well, alas, I don't speak the languages needed to help fix this

**Comment by mkrautz** [comment]
Also, the UI for Audio Input in the ConfigDialog needs to be able to show that it is using "System-provided Echo Cancellation".

**Comment by alakra** [comment]
:+1:

**Comment by tiagoefreitas** [comment]
Will this ever be fixed?

**Comment by saschaludwig** [comment]
Maybe this year?

**Comment by crertel-packlane** [comment]
This would be absolutely wonderful!

**Comment by Chris2000SP** [comment]
I'm wondering that under linux there is a switch to turn AEC on but it doesn't seem to be working. I heard that it should not work under Windows either, but unfortunately I can't test it myself.

I have already been asked to write a script to avoid the Echo problem. I started it but I remembered that there are other implementations, e.g. pulseaudio module-echo-cancel which runs stable since version 9.0 and works as well as mumble 1.1.x under Windows with ASIO on single speaker. That's why I didn't finish it. 

I think the whole implementation of the echo cancellation has to be brought up to date.

**Comment by TerryGeng** [comment]
I'd like to provide some follow-up to this old issue.

As indicated in https://developers.google.com/web/updates/2018/03/macos-native-echo-cancellation, since macOS 10.12, Apple included a native echo canceller in the OS.

Some useful code snippets can be found here: https://developer.apple.com/forums/thread/66953.

I'm wondering if there's anyone interested in implementing this.

**Comment by TerryGeng** [comment]
I made an experimental implementation in #4694 of the VoiceProcessingIO AU mentioned by @mkrautz, and studied Chrome's implementation.

I hope people in this thread may help me test it and kindly provide some feedback.

Thanks :)

**Comment by ProjectPatatoe** [comment]
mumble wiki has a dead link in the FAQ regarding this topic (points to sourceforge). The wiki is what appeared in web search. Should probably point it to this Issue. https://wiki.mumble.info/wiki/FAQ/English#No_Echo_Cancellation_on_Mac_OS_X
