### ISSUE TITLE
Mumble changes file needs updating

### ISSUE THREAD

**Issue by shirishag75** [mumble-voip/mumble#1798]
The changes file shows changes till 1.2.8.x versions, anything later than that is not recorded. Please update that changes/changelog file please. 

https://github.com/mumble-voip/mumble/blob/master/CHANGES

**Comment by bendem** [comment]
https://github.com/mumble-voip/mumble/commits/1.2.x/CHANGES

**Comment by shirishag75** [comment]
aha... you have done it on the branch, not on the master,  guessing at some point the branch would be integrated into the master .

**Comment by mkrautz** [comment]
Hi,

The master branch is what will become 1.3.0. Once 1.3.0 is released, master will become what will be 1.4.0, and the commit tagged for 1.3.0 will be branched off into a 1.3.x branch. This branch will only have security and bug fix-patches applied to it. From this branch, we tag new releases in the 1.3.x series.

As mentioned above, the master branch will become 1.3.0 at some point in the future. The CHANGES file hasn't been updated in a while because we typically only do it when we cut a release (but sometimes we need to "bump" the repository's latest commit hash in order to release a new snapshot because of changes to external repos like mumble-releng -- in these cases, we also sometimes update the CHANGES file).

The 1.2.x repository has a more up-to-date CHANGES file because it has seen recent releases with bugfixes and security updates to dependencies.

**Comment by mkrautz** [comment]
Oh, and I'd like to add that when a snapshot from the master branch is made, the build scripts do indeed update the CHANGES file.

So, our builds from the master branch do have an up-to-date CHANGES file once in the hands of users. (Except for the tarballs, I suppose).
