### ISSUE TITLE
Dependency issue on debian Stretch

### ISSUE THREAD

**Issue by zeechs** [mumble-voip/mumble#1809]
Hi,

I'm not sure if this is the right place to talk about this, but on Debian Stretch, *mumble* seems to be the only package depending on *libprotobuf9*.
... As you can see:
```
:~$ apt-rdepends -r libprotobuf9
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libprotobuf9
  Reverse Depends: mumble (1.2.8-2)
  Reverse Depends: mumble-server (1.2.8-2)
mumble
  Reverse Depends: mumble-dbg (= 1.2.8-2)
mumble-dbg
mumble-server
  Reverse Depends: mumble-dbg (= 1.2.8-2)
```
All the other packages who used to depend on  *libprotobuf9* now depend on *libprotobuf9v5*.
For exemple *clementine* which I am trying to install.
https://packages.debian.org/stretch/clementine

It makes it impossible to install *clementine* and *mumble* on the same machine as *libprotobuf9* and *libprotobuf9v5* conflict. Installing one of them makes the other one be removed.

I reproduced this on a fresh install in virtualbox with no additional repositories.
Also, it seems like the problem is not solve in Sid
https://packages.debian.org/sid/mumble
*Mumble* still depends on *libprotobuf9*

**Comment by mkrautz** [comment]
cc @crknadle

**Comment by crknadle** [comment]
Short version:
All is fine: mumble 1.2.8-2+b1 will transition to Stretch in a couple of days.

Long version:
Debian has been going through an extensive transition for gcc-5 and libstdc++6 (simultaneously) during which the build for mumble was broken.  As libraries are transitioned, the libraries are renamed with a 'v5' but the -dev packages are not renamed, so that dependencies for "leaf" packages (such as mumble) don't need to be patched -- the new library is used automatically upon a rebuild, and when the library transitions it causes a binNMU that causes those rebuilds to happen.  libprotobuf9 was patched and it triggered a binNMU on mumble, but the build was still broken because zeroc-ice wasn't transitioned -- the maintainers for zeroc-ice didn't respond.  When the gcc-5/libstdc++6 transition was thought to be nearly complete it was also brought to Stretch.

I got help from a friend, who discussed it with the release team in IRC, and someone from the release team applied the gcc-5 transition patch and 4 others that had been pending, and the resulting zeroc-ice package has now made it into Sid and mumble has finally rebuilt correctly for all release architectures.  So that will transition to Stretch in a couple of days.

There are a few non-release architectures that are still trying to build packages and mumble is 'on hold' for those, so I'm going to wait a bit more before uploading mumble 1.2.10-1 (which I've had waiting for 2 months during this time that the build has been broken).

**Comment by zeechs** [comment]
Thank you for the detailed answer,
I see things are already happening on Sid.
