### ISSUE TITLE
The new 1.3.x skin may be offensive to some people

### ISSUE THREAD

**Issue by promi** [mumble-voip/mumble#1828]
The new skin has talking icons that are supposed to look like little people, but it's not hard to image that they also look like primary male sex organs ...

![Example image](http://files.teneon.de/people.png)

I had someone who was offended by that. We fixed it by overwriting the speaking icons with the old ones from the previous skin.

**Comment by mkotb** [comment]
![](http://i.imgur.com/7Ae8XXn.jpg)

**Comment by gsand** [comment]
Sometimes people see what they want to see. I see a bottle.

**Comment by roastnewt** [comment]
Sometimes a cigar is just a cigar

**Comment by hacst** [comment]
I would recommend people offended by these specific icons to switch to no theme (basically the old look with the old icons) or try one of the other third party ones out there with other icons. From my POV there is nothing we can do to prevent some people from having unusual associations with any icon we might chose due to the simple geometric nature of such icons. Which icon might trigger such associations and offense is highly personal and nothing we can predict or design around. We certainly are not trying to offend any of our users. Sorry for not being able to offer a general solution :(
