### ISSUE TITLE
Feature Request: Option to mute input when typing and clicking

### ISSUE THREAD

**Issue by ghost** [mumble-voip/mumble#1864]
I think this'd be nice for people like me who have loud, clicky keyboards. Just mute the microphone while the user is pressing any keys or clicking any mouse buttons (with buffer period) as to prevent the loud noises from being broadcast to everyone else.

**Comment by mkrautz** [comment]
Not a bad idea.

**Comment by mkrautz** [comment]
But not too sure of its usefulness while gaming. You typically do not want to be cut off if you're mashing buttons.

**Comment by smalltock** [comment]
True. It should be optional, of course. Gamers' headset microphones do a good job isolating the voice anyway.

**Comment by ZeroAbility** [comment]
In most game related situations with mechanical keyboards, people are using PTT. There are some occasions where people are not using PTT but are using Voice Activity with the Silence Before and After tuned to filter these kinds of utterances out. People using Continuous mode after being asked politely to use one of the other modes is an Admin problem. Making an option to mute the mic when "any" key is pressed (because that is what you would have to do) seems like overkill. Even if you were conducting a conference using Mumble and the presenter was typing while speaking, it would be simpler to just configure voice activity.

**Comment by Krzmbrzl** [comment]
I agree that having push-to-mute trigger on any key in existence is not desirable. If you have the problem of a really loud keyboard, then you'll have to use PTT, unless you find a setting that involves noise suppression (in some situations RNNoise was reported to work rather well) that works for you.
