### ISSUE TITLE
[Bug] Ice slice error

### ISSUE THREAD

**Issue by HarpyWar** [mumble-voip/mumble#1874]
I'm not sure is this issue only with .NET implementation or other languages too, and should I report this here or on Zero Ice forums.

IceEncapsulationException throws when .NET program calls a method `server.getUsers()`. BUT only when user `identity` is not empty (user enable a Mumble plugin linked with a game). 
When `identity` is empty then all works fine.

On the screenshot below the exception throws when reading `context` variable instantly after `identity` (this value is displayed):

![2015-11-05 22 46 15](https://cloud.githubusercontent.com/assets/1132835/10980542/89a43bb8-8413-11e5-98fc-6dc2fd057c66.png)

Tested with:
Ice v3.4.2. 
Murmur.ice slice v1.2.10
Murmur v1.2.10
Client Mumble v1.2.10

**Comment by mkrautz** [comment]
Perhaps the context contains a NUL character? Ice doesn't allow that:
https://doc.zeroc.com/display/Ice36/Basic+Types

It's a std::string internally for us: https://github.com/mumble-voip/mumble/blob/master/src/murmur/MurmurIce.cpp#L95

So it's very probable that that's the issue. The field is also a 'bytes' field in protobuf.

Is it a custom game plugin?

**Comment by HarpyWar** [comment]
It was Guild Wars plugin that is distributed witn a Mumble client (user doesn't install anything else). And he played in Guild Wars 2.
I don't know how to check is there NUL character (I can't debug inside `readString()` method), and exception throws without a detailed info.

**Comment by mkrautz** [comment]
OK, the context will always include a NUL: https://github.com/mumble-voip/mumble/blob/master/src/mumble/Plugins.cpp#L429

@hacst @Kissaki
Should we deprecate the context string in Ice?

I'm not sure how we handle versioning of the Slice with regards to modification, addition of fields, and so on.

Either we simply make it a `sequence<byte> context`, and it'll work. This would make the Murmur 1.3.0 slice incompatible with earlier versions.

Or we begin sending an empty context for the string version, and add a `sequence<byte> context_bytes`?

**Comment by HarpyWar** [comment]
There is also exception when call Ice method `getTree` on line `is__.readPendingObjects();`. 
Two different exceptions in one place:

a) `Ice.UnmarshalOutOfBoundsException` if at least one user online on a server. 
or
b) `Ice.UnexpectedObjectException` if nobody online (even on a new server without channels).

![2015-11-06 17 46 12](https://cloud.githubusercontent.com/assets/1132835/10999695/7f7ec61c-84ae-11e5-97e6-ffd5141b85f4.png)

Now I use `getChannels` and `getUsers` methods to compose channel viewer three. They work properly

**Comment by hacst** [comment]
@mkrautz Context and identity are essential to all the Ice plugins we have that move users into channels and adjust groups depending on in-game state. I'm not sure what you mean with "deprecating" it but there is a good reason we want to have it in the user information.

**Comment by mkrautz** [comment]
Sorry. I never meant to suggest we deprecate it. I meant deprecate the *string* version.

**Comment by mkrautz** [comment]
@Kissaki @Svedrin 

Any opinions on how we should or should not change the slice file for this in 1.3.0?

Is it expected that the slice file for each version is incompatible, such that we can change the type of `context` from `string` to `sequence<byte>`?

**Comment by Svedrin** [comment]
I think it's okay. We implemented the getSlice method so that the slice file can be changed without needing API users to track it. Clients that uses this method to get the slice should be fine.

**Comment by Kissaki** [comment]
So we either stay backwards compatible to older/current clients by changing the server slice context type to sequence<byte>
or change the plugins to not include a NULL - then making the context of different client versions not equal-comparable.

I would simply change to sequence of bytes in Murmur slice for 1.3.0 then.
Then its consistent on the server for any number of client versions.

Not sure what the implications of that is in terms of usage?
Can the sequence of bytes be handled like a string without problems, in the various languages?

-----

My thought process, probably of no more interest:

I don’t quite get what this is about.
We combine a string with plugin shortname + NULL + context, which seems to cause problems on unmarshalling.
Checking the Murmur.ice slice context is of type `string`.

So I guess the suggestion is to use a `sequence<byte>` in the slice to allow the NULL, but changing the slice API.

Even with `getSlice`, I’m not sure that’s enough to prevent incompatibilities.
The slice2XY tools translate slice definition to XY language sources; this is done at development time rather than run time.

I guess up to now we have no slice versioning at all, and no handling of API changes.

I wonder if the NULL problem is for all ice language bindings, or just python (as demonstrated here).

The linked Plugins.cpp that combines/creates the string seems to be client-side, so we’re gonna have to make an incompatible change anyway (otherwise the context can be considered a single value and used to equal-compare rather than parse, separating by NULL).

Even if this an issue only for python, we should not leave it for 1.3.0.
We have to make this incompatible change then.

Actually there was a mismatch between client side context construction and server side context slice type definition - so maybe some of the stuff above is not correct.

Anyway, … (now wrote the above)

Sorry for the long text - just writing to get the idea and solution.
