### ISSUE TITLE
Linux Mumble refuses to let ALSA-using software touch it's precious input/output hardware

### ISSUE THREAD

**Issue by SilverSynch** [mumble-voip/mumble#1887]
Any input/output hardware selected to be used by Mumble cannot be accessed by other software on Linux, seemingly only effecting ALSA. Programs that can use PulseAudio (which I have properly configured to work nicely with ALSA) are not effected as far as I know.

This is an issue with me, as Wine has not had a PulseAudio-compatible driver for a long time, and I cannot get sound to work on any of the games with Mumble, because Wine cannot find my headset through ALSA (which is under use by Mumble).

This persists through closing Mumble, and the only way to relieve the hardware is to restart the OS. This effect happens regardless of the audio driver Mumble uses to reach it's hardware (both ALSA in any input/output method and PulseAudio).

**Comment by mkrautz** [comment]
You say that you have configured PulseAudio to work nicely with ALSA. Does that mean you have configured PulseAudio to use dmix/dnsoop -- or does it mean something else?  I believe most configurations would have PulseAudio grab exclusive access to the devices, unless explicitly told not to. And if your audio device doesn't support hardware mixing, only PulseAudio has access. I have to ask, since your post doesn't explain your setup in any detail.

Which devices are listed in Mumble's ALSA device list? What kind of device are you trying to use?  Again, if you're using dmix, I believe you should select the dmix output device, and dsnoop input device for your audio device.

**Comment by Eriner** [comment]
@mkrautz The device exclusivity you mentioned (lack of dmix/dsnoop) is most certainly the answer in this case.
@SilverSynch if you're interested in fixing this problem, here is a copy of my .asoundrc that you can use as a model: https://gist.github.com/ed68d07acab1e5cfae47

**Comment by mkrautz** [comment]
The reporter is unresponsive.

If this is still an issue for you, @SilverSynch, please re-open.

Thanks!
