### ISSUE TITLE
Feature Request: Ability to set channel codec quality

### ISSUE THREAD

**Issue by Xylemon** [mumble-voip/mumble#1948]
In Mumble, I've noticed that there is a voice quality variable you can set server wide but I haven't noticed one for a specific channel. It would be nice if you could give individual channels a lower or higher bitrate with codec choices as well.

**Comment by mkrautz** [comment]
There is no global voice quality variable. There's a bandwidth variable. It's meant to allow the server administrator to limit the bandwidth of Murmur, if it is on a slower home connection or the like.

It is true, however, that Mumble will adjust its bitrate to live up to the bandwidth requirement -- the reason is that if it didn't, the server would simply drop packets.

What's the use case here? In my opinion, giving the user the ability to choose the quality to send with makes a lot of sense, because he/she knows how much upstream bandwidth is available.

Code choice shouldn't be necessary either, why would you prefer Speex/CELT over Opus? (Excepting the embarrasing "Opus bug"...)

**Comment by JoelTroch** [comment]
The requested feature is already implemented in TeamSpeak 3.

First possible use case scenario: you have a "Dance Floor" channel or a "bot" that plays music (like a radio), you can set that channel (or the channel where the bot is) to use a codec specialized in music (Opus Music if I remember correctly).

Second possible use case scenario: unless I'm mistaken, Mumble legacy (pre 1.2.X) used to have CELT as codec, possible backward compatibility.

Third possible use case scenario: use high quality codec and bit rates in "important" channels like "CS:GO War Channel" and use low quality codec and bit rates in "not important" channels like "AFK", "Poker"...

Another thing: how would the server choose the settings in the case of whispering in another channel or multiple channels with different settings?

**Comment by mkrautz** [comment]
@JoelTroch There is no backwards compatibility argument. Mumble is fully backwards compatible. If an old client connects, the whole server switches to CELT.

**Comment by mkrautz** [comment]
Backwards compatibility also makes this very hard to do in any meaningful way.

**Comment by ZeroAbility** [comment]
Was there any support for this added in 1.4, or any further interest?

**Comment by Krzmbrzl** [comment]
It's still not supported and I'm not aware of continued interest in this.

Using a different codec is our of question as we also allow cross-channel communication (whispering, linked channels, channel listeners).

Choosing the quality setting also doesn't seem particularly useful to me. If you want high-quality music, just use a Music bot that uses a high Bitrate. Everything else should be up to the client's settings.
