### ISSUE TITLE
Virtual Audio Cable Mic Input Issues

### ISSUE THREAD

**Issue by ManagerWoW** [mumble-voip/mumble#1963]
Hello,

I'm currently using Adobe Audition to improve my mic quality, as well as Virtual Audio Cable to create a new Mic 1 recording device, which hosts this newly edited mic input. 

VAC + Sound Settings: http://goo.gl/jIJo86

All other programs that I have tried have accepted this new Mic 1 input perfectly (Dxtory, Fraps, Skype, Open Broadcasting System, WoW, Discord) but Mumble seems to be having issues. It acknowledges that Mic 1 is a valid input, but when I try to talk (both PTT & Continuous) the mic is never cued (red lips).

Mumble Input: http://goo.gl/sS2Xfj

**Comment by mkrautz** [comment]
There seem to be issues with VAC and Mumble on Windows 10. Other people have reported that before.

Could you try running a session of Mumble, doing what you usually do, and then post your log here? Maybe there is something useful in it. (%APPDATA%\Mumble\Console.txt)

Also, have you tried without echo cancellation on? Without positional audio on? (Should capture mono instead of stereo)

**Comment by ManagerWoW** [comment]
I have both echo cancellation and positional audio off, so not that.

Log with my normal mic setup (without VAC): http://pastebin.com/mWmdG2ft

Log with VAC Mic 1 setup: http://pastebin.com/GWjWsjNZ

All I did was launch Mumble, join a server, move to a channel, and queue my mic a few times, then disconnect.

**Comment by ManagerWoW** [comment]
Issue appears to have been fixed.

**Comment by mkrautz** [comment]
We made no changes, so it could have been a Windows 10 update. Closing this.

Feel free to ping this thread if this issue continues.
