### ISSUE TITLE
Implement an auto updater

### ISSUE THREAD

**Issue by Gunni** [mumble-voip/mumble#1976]
Hey,

Mumble should implement an auto updater that is very user friendly, like, 2-3 clicks.

See the following flowchart (start on "Client startup") (red = action, green = question)

![mumble_autoupdate_v2 3](https://cloud.githubusercontent.com/assets/358099/11706608/067be660-9ef2-11e5-802b-2cc37108099c.png)

The entire procedure should only take 10-20 seconds max from when the user grants permissions.

**Comment by mkrautz** [comment]
We have the tech in Windows snapshots to do silent autoupdates on Windows. Except for downloading, verifying the signature and extracting...

The client iself would download an archive containing the new version, verify its signature, and extract it in %APPDATA%\Mumble\Versions\1.3.0~bla56.

On next launch, the client should pick the latest "version" to run. It does that by comparing the version for all directories of %APPDATA%\Mumble\Versions and %PROGRAMFILES%\Mumble\Versions.

Note that our installers are already using the Versions directory in Program Files.

We need to figure out a key distribution scheme for the signing keys, including what happens if a key is compromised. (Revocation?)

We also need to figure out if the model itself is safe. Since silent updates are installed on a per-user basis, without requiring administrator privileges, any program on the system could tamer with the files after extraction.

Of course you could say that if the machine has malware on it that is able to change your files, you've lost anyway.

But the new threat picture needs some consideration...

Thanks for listening!

**Comment by Zuko** [comment]
Maybe... drop installer and download updated files only? (dll?) and replace it?

**Comment by mkrautz** [comment]
Yes, that's the plan.

**Comment by bontibon** [comment]
https://github.com/Squirrel/Squirrel.Windows is a dead simple way to get an auto updating installer.

**Comment by mkrautz** [comment]
@bontibon I believe Squirrel's model is that your app lives in %APPDATA%.

Mumble can't do that in its default configuration, because it relies on uiAccess=true in its application manifest. To use that, the program must live in %PROGRMAFILES%.

I haven't looked closely at Squirrel, so maybe it can work for in that mode.

But allow me to elaborate on the current plan for auto-updating:

1. You install mumble-1.3.0.msi. It installs to %PROGRAMFILES%\Mumble.
[time passes, Mumble 1.3.1 is released]
2. Mumble fetches mumble-1.3.1.winx64.zip, and verifies its signature (TBD... maybe sig is a separate file)
3. If the signature is good, Mumble extracts the content to %APPDATA%\Mumble\Versions\1.3.1
4. Mumble knows a new version is available, and can show this to the user somehow. Maybe prompt to restart Mumble.
5. Next time Mumble is restarted, the mumble.exe in %PROGRAMFILES%\Mumble walks the installed Mumble versions, and runs the latest one. It looks in both %APPDATA%\Mumble\Versions and %PROGRAMFILES\Mumble\Versions. Because 1.3.1 was extracted in step 3, that is the version that will run.
6. Mumble upgraded to 1.3.1 without prompting the user.

What's missing from this being a reality is:
1. Fetch update
2. Zip library/class and crypto bits.
3. A small modification to mumble.exe so it walks the Versions folders, looking for the latest version.

**Comment by magicrub** [comment]
+1 

In your example technically it would be step 1 you install 1.3.1, then later 1.3.2 comes out. That's because users with v1.3.0 installed will not auto update (unless they're running betas?)

**Comment by hacst** [comment]
@mkrautz Don't forget about cleanup of old versions ;) On the release track this probably will never be an issue but accumulating all the snaps might actually grow over time.

**Comment by DGMurdockIII** [comment]
I thought this was allready in stable windows versions

**Comment by ZeroAbility** [comment]
Ideally, this is handled on Linux distros by the package managers, and if they have stable or rolling releases. In Windows and macOS the logical options are their respective stores. One day there will be no way getting around that on macOS (at least). Trying to handle that from the application itself can cause unintended side effects that the installers help guard against for the most part.

**Comment by Gunni** [comment]
This ticket is about the client, and I'd like to mention that Discord has this feature, and it works great.

**Comment by ZeroAbility** [comment]
> This ticket is about the client

Yes, I am aware.

>... and I'd like to mention that Discord has this feature, and it works great.

This is also a more sensible use case for Discord because they do not ship an "application". When you run Discord you are running a web page in Electron.

**Comment by Gunni** [comment]
> This is also a more sensible use case for Discord because they do not ship an "application". When you run Discord you are running a web page in Electron.

The user _does not care_, usability should come first imo.

**Comment by ZeroAbility** [comment]
> The user _does not care_, usability should come first imo.

While you think that the user should have the final say in that process, that doesn't always translate to reality.

I realize that you provided a very well explained concept in the flow chart you included. At this time, we do not develop the client and server independently. This means when we consider how to update one, we must consider how to update the other as well as the impact each has. Perhaps a new direction for both can be discovered with libmumble, but that is well into the future.

Auto update in Linux distros is a no-go because as long as Debian and Arch exist, there will be feature support lag and the user will have to take on some portion of the process and become a tester. If we can't provide the feature in one situation then it doesn't make sense to provide it for the others. Given the size of our team and the lack of Discord level funding, we haven't been able to even address this specific issue as promptly as it should be let alone the amount of support effort that would be required to handle the results of auto update happening. This also depends on the users performing the update when notified which historically is a pain point for the operating system alone.

If you have the start to finish concept you would like to submit in the form of a PR that safely allows this functionality to exist on all platforms we develop for, you are more than welcome to do so and we will review it.

**Comment by davidebeatrici** [comment]
Technically on Windows this could be achieved through [`winget`](https://learn.microsoft.com/en-us/windows/package-manager/winget), our project is already handled by it.

**Comment by ZeroAbility** [comment]
Linux would still be an issue. Doing an update that expects a specific feature offered in a newer library we use could cause the application to break on distros like Debian. It doesn't make sense to add the feature for one or two platforms only.

**Comment by davidebeatrici** [comment]
Yeah, what I meant is that ideally a user should rely on the OS' package manager, if it has one.

**Comment by Gunni** [comment]
Another example: Steam, is an application, has always had an auto updater, one click.

**Comment by Krzmbrzl** [comment]
Still, Steam has slightly more manpower to support this happening.

Technically, it would certainly be possible, but it does not seem worth the effort in our case.

As it stands, it seems like the most reasonable thing for us to do is to keep the update notification that includes a link to a download page.
