### ISSUE TITLE
Expose ban issuer in banlist

### ISSUE THREAD

**Issue by spede** [mumble-voip/mumble#1996]
It would be useful to expose the person who issued a particular ban in banlist. I know this information is available in `mumble-server.log` but it seems like a needless extra step to go through.

On a related note, it would also be useful to be more verbose when a ban is removed. Currently, the logfile gives you a very ambiguous `<user> Updated banlist`. The act of "updating" encompasses everything from changing the reason to outright removal of a ban. Here, again, it would be nice to have more information about the act which was done. In case it was a ban removal, the stored username and IP-address should in my opinion be available in the logfile.

**Comment by mkrautz** [comment]
Seems like a good idea.

Regarding the banlist update -- updating the banlist is an atomic operation. It isn't just updating the ban you changed, it is updating everything. That's why it is logged the way it is right now. However, that's not to say that you could not diff the old vs. new list and show something useful.
