### ISSUE TITLE
Layout is not saved on any Mumble version or platform

### ISSUE THREAD

**Issue by falkreon** [mumble-voip/mumble#2003]
Reproduction instructions:
* Select "Settings" from the "Configure" menu
* Select the "User Interface" tab (depending on your platform, that'll be the third item on the left)
* From the top panel called "Layout", make any selection except "Custom" (my preference is "Classic")
* Click any combination of "Apply" and/or "OK"
* Quit and restart Mumble

Expected behavior:
* On OSX, the client behavior is expected to change and be saved the very instant the option is selected.
* On Windows and *nix, Apply is expected to enable the behavior but may or may not save it.
* OK is expected to save the settings so that they'll be usable in both this session and all following sessions.

Observed behavior:
Clicking "OK" enables the behavior, but makes no changes to the underlying settings file(s). In fact, even if you don't restart the client, consecutive visits to the "Settings" window show the setting reverted!

Observing and refreshing the registry from Windows reveals that no change is made to the relevant key under any combination of OK or Apply.

This may be related to  #1185

Implementing #1940 would aid substantially in eliminating bugs like this for good.

**Comment by mkrautz** [comment]
You don't specify your Mumble version. I assume this is for snapshots?

**Comment by mkrautz** [comment]
I apologize. I see you are stating that this happens on all versions.

**Comment by mkrautz** [comment]
Debug branch at https://github.com/mkrautz/mumble/tree/layout-debug

The issue is that our slots at https://github.com/mumble-voip/mumble/blob/master/src/mumble/MainWindow.cpp#L3021-L3035 get called more agressively than previously.

Just before we save on exit, the value is reset by the slots:

<W>2015-12-21 02:43:18.818 after wlWindowLayout = 0
<W>2015-12-21 02:43:18.928 way after wlWindowLayout = 0
<W>2015-12-21 02:43:21.978 log visibility dockLocationChanged!
<W>2015-12-21 02:43:21.979 chat dockLocationChanged!
<W>2015-12-21 02:43:21.988 SAVE wlWindowLayout 3

**Comment by falkreon** [comment]
Confirmed fixed on 1.3.0 build 918 :D
