### ISSUE TITLE
Running 'murmur.x86 -supw' with no password returns successful exit code

### ISSUE THREAD

**Issue by PHLAK** [mumble-voip/mumble#2005]
$ ./murmur.x86 -supw
    <F>2015-12-21 18:55:40.885 -supw expects the password on the command line - maybe you meant -readsupw?
    $ echo $?
    0

This should return a non-zero exit code so we can programmatically determine if the command succeeded or failed.

**Comment by hacst** [comment]
I guess https://github.com/mumble-voip/mumble/blob/8bd3f76a8ea3d8751c0305cfcaaa3592d2ffa9b2/src/murmur/main.cpp#L149 is to blame for that. Also wow is that function messy. 

@mkrautz Is https://github.com/mumble-voip/mumble/blob/8bd3f76a8ea3d8751c0305cfcaaa3592d2ffa9b2/src/murmur/main.cpp#L87 a bug? Just because we log to syslog we still want qFatal to be...well...fatal. No?

**Comment by mkrautz** [comment]
@hacst I'd say it is a bug, yes.

**Comment by mkrautz** [comment]
PR: https://github.com/mumble-voip/mumble/pull/2009

**Comment by mkrautz** [comment]
Fixed by https://github.com/mumble-voip/mumble/commit/703f8c7ffc4d9200b59b39f83ea7f66a5efdd156.
