### ISSUE TITLE
I can set push-to-talk button ONLY through sudo/superuser [debian]

### ISSUE THREAD

**Issue by chrismp** [mumble-voip/mumble#2006]
My OS: Debian 8.2 (Jessie)
My desktop manager: [MATE](https://en.wikipedia.org/wiki/MATE_(software))

I ran `sudo apt-get install mumble`, then went through the audio setup wizard as a non-superuser.

Once setup, I opened MATE terminal. I ran `mumble mumble://MyUserName@someserver.mumbleboxes.com:PORT_NUMBER_HERE` to connect to a friend's server.

Once connected, I went to **Configure >> Settings >> Shortcut**. I clicked "add,", picked "Push-to-talk" under "function", clicked the text field under "Shortcut," and tried pressing my space bar to set it as the push-to-talk button. Nothing happened.

But when I connected by running `sudo mumble mumble://MyUserName@someserver.mumbleboxes.com:PORT_NUMBER_HERE`, I could set the button.

When I launch Mumble by clicking its launch icon, it seems to launch in non-superuser mode.

Why can I change the push-to-talk settings only in superuser mode? 
How do I launch Mumble in superuser mode from clicking its launch icon?

**Comment by mkrautz** [comment]
If you try launching Mumble through a regular terminal, so you can see its output, you should be able to see which GlobalShortcut engine it is using... That should help us troubleshoot further.

If you could copy/paste the output of Mumble here (without any personal information stripped) that would help!

Thanks!

**Comment by chrismp** [comment]
Here's GlobalShortcutX when I connect as a regular user.

`GlobalShortcutX: /dev/input/event12: Microsoft Microsoft® 2.4GHz Transceiver v8.0`


Full output...
```
G15LCDEngineUnix: Unable to connect to G15Daemon.
CELT bitstream 8000000b from /usr/lib/mumble/libcelt0.so.0.7.0
Locale is "en_US" (System: "en_US")
TextToSpeech: Failed to contact speech dispatcher.
Database SQLite: "3.8.7.1" 
Overlay: Listening on "/home/myDebianLoginName/.MumbleOverlayPipe" 
GlobalShortcutX: /dev/input/event12: Microsoft Microsoft® 2.4GHz Transceiver v8.0
AudioInput: 40000 bits/s, 48000 hz, 480 sample
PulseAudio: Starting input alsa_input.usb-Microsoft_Microsoft___LifeCam_VX-2000-02-VX2000.analog-mono
PulseAudio: Starting echo: alsa_output.pci-0000_01_00.1.hdmi-stereo-extra1.monitor
PulseAudio: Starting output: alsa_output.pci-0000_01_00.1.hdmi-stereo-extra1
OpenSSL Support: 1 (OpenSSL 1.0.1k 8 Jan 2015)
AudioInput: Initialized mixer for 0 channel 48000 hz mic and 2 channel 44100 hz echo
AudioOutput: Initialized 2 channel 44100 hz mixer
AudioInput: Initialized mixer for 1 channel 44100 hz mic and 2 channel 44100 hz echo
warning: The VAD has been replaced by a hack pending a complete rewrite
AudioInput: ECHO CANCELLER ACTIVE
```

Full output when I run with `sudo`...
```
G15LCDEngineUnix: Unable to connect to G15Daemon.
CELT bitstream 8000000b from /usr/lib/mumble/libcelt0.so.0.7.0
Locale is "en_US" (System: "en_US")
TextToSpeech: Failed to contact speech dispatcher.
Database SQLite: "3.8.7.1" 
Overlay: Listening on "/root/.MumbleOverlayPipe" 
GlobalShortcutX: /dev/input/event0: Power Button
GlobalShortcutX: /dev/input/event1: Power Button
GlobalShortcutX: /dev/input/event10: Microsoft Microsoft® 2.4GHz Transceiver v8.0
GlobalShortcutX: /dev/input/event11: Microsoft Microsoft® 2.4GHz Transceiver v8.0
GlobalShortcutX: /dev/input/event12: Microsoft Microsoft® 2.4GHz Transceiver v8.0
GlobalShortcutX: /dev/input/event16: Microsoft® LifeCam VX-2000
GlobalShortcutX: /dev/input/event9: Eee PC WMI hotkeys
AudioInput: 40000 bits/s, 48000 hz, 480 sample
PulseAudio: Starting input alsa_input.usb-Microsoft_Microsoft___LifeCam_VX-2000-02-VX2000.analog-mono
PulseAudio: Starting echo: alsa_output.pci-0000_00_1b.0.analog-stereo.monitor
OpenSSL Support: 1 (OpenSSL 1.0.1k 8 Jan 2015)
PulseAudio: Starting output: alsa_output.pci-0000_00_1b.0.analog-stereo
AudioInput: Initialized mixer for 0 channel 48000 hz mic and 1 channel 44100 hz echo
AudioOutput: Initialized 2 channel 44100 hz mixer
AudioInput: Initialized mixer for 1 channel 44100 hz mic and 1 channel 44100 hz echo
warning: The VAD has been replaced by a hack pending a complete rewrite
AudioInput: ECHO CANCELLER ACTIVE
```

**Comment by mkrautz** [comment]
This is a "bug" in Mumble 1.2.8.

Mumble 1.2.8 uses evdev by default for global shortcuts on X11. However, when running as a regular user, Mumble does not have read access to the input devices nodes for things such as your keyboard.

By default, Mumble tries to walk the input device nodes, and once it finds something that resembles a keyboard, it will settle for that. And if it does not, it will fall back to global shortcut engines other than evdev.

Settling for a keyboard in evdev works for many situations, but fails in others, such as yours.

Because Mumble finds something that it thinks is a keyboard, it is using that. And thus not falling back to using XInput, which works better.

As a temporary workaround, here's what you can do:

First, observe what the permissions are for your input devices:

$ ls -l /dev/input*

Generally, OSes try to reduce the attack surface by having the system keyboard owned by root and only readable by root.

In this scenario, at least some of the three devices named "Microsoft Microsoft® 2.4GHz Transceiver v8.0" are seen as keyboards. However, some of them are not restricted to be only read by root.

I would try to:

$ chown root:root /dev/input/event10
$ chmod 0700 /dev/input/event10

After that, try to run Mumble again.

If it finds a valid keyboard, and is still using evdev (/dev/input devices nodes), repeat the above steps for that one.

At some point, you'll have restricted all your keyboard-like devices only to be read by root, and you should be good.

Obviously, this is a temporary workaround, but it should work.
Once you've figured out which ones to disable, you could set up a udev rule to change the permissions for you on bootup.

Please try that, and see if it works for you.

Now, the *real* fix for this would be for the package in Jessie to get the latest fixes from Mumble 1.2.12. (/cc @crknadle, the maintainer).

@crknadle, would it be possible to get some of the bug fixes that have happened since 1.2.12 into jessie? Or perhaps put the current 1.2.12 release into jessie? 1.2.x is in maintenance mode, and thus only receives bug fixes.

Here is the full set of changes:
https://github.com/mumble-voip/mumble/compare/1.2.8...1.2.x

Here are the ones relevant to Debian:

GlobalShortcut_unix: disable evdev by default.
https://github.com/mumble-voip/mumble/commit/6edf2c6008805fce41d20e1fe929a178cca417cd

Avoid "jump to label crosses initialization" error. …
https://github.com/mumble-voip/mumble/commit/b0b43cb9008ce99bff3097c1bffd86a504e93318

Show the IP address of the rejected connection in the mumble-server log.
https://github.com/mumble-voip/mumble/commit/8eea80136cee44195e027b64ddb782b2cf6ca75f

Fix small error in bEnableEvdev config 
https://github.com/mumble-voip/mumble/commit/90f26fb04dc21aa1038672262fa10f4c239ceb40

Backport mumble.desktop file from master
https://github.com/mumble-voip/mumble/commit/ae31d10de7d476306ebc5705f57a8e2b5a6e63a6

GlobalShortcut_unix, Settings: disable XInput2 by default. 
https://github.com/mumble-voip/mumble/commit/e227d6252b695225fb30e731a206870621f5c7a7

Settings: enable XInput 2 by default once again. …
https://github.com/mumble-voip/mumble/commit/83e558ce78ed53fa94fd9c619b9b72cdae06602e

Fix auto-reconnect behavior when kicked or banned. …
https://github.com/mumble-voip/mumble/commit/75282292a9dbf9563a5c78940188e6fd4c0a75c1

Fix incorrect handling of mumble:// links …
https://github.com/mumble-voip/mumble/commit/5ac37bf13fd2079f6f2770fb446bd78751fc0859

Log: trigger scroll-to-bottom for a QAbstractTextDocumentLayout's upd… …
https://github.com/mumble-voip/mumble/commit/192ba96fddda2895a0fb0d143540eb2022bb07be

LogTextBrowser: move all scroll-to-bottom logic to the LogTextBrowser. …
https://github.com/mumble-voip/mumble/commit/1a4ae8deddc9c833ee276cbbb08bd19940e2840c

AudioInput: ensure our encoders are reset correctly when using > 1 fr… …
https://github.com/mumble-voip/mumble/commit/443d0d294ce4aaf8109d897b9b990541cb079901

Thanks!

**Comment by mkrautz** [comment]
For this issue in particular, the following changes should do:

GlobalShortcut_unix: disable evdev by default.
6edf2c6

Fix small error in bEnableEvdev config 
90f26fb

GlobalShortcut_unix, Settings: disable XInput2 by default. 
e227d62

GlobalShortcut_unix: request latest XInput 2 version by default. …
83e558c

Settings: enable XInput 2 by default once again. …
83e558c

**Comment by mkrautz** [comment]
Small update: if you've gotten this thread via email, some of the links to commits have changed. Please use the website instead of the copy received via email. Thanks.

**Comment by crknadle** [comment]
>@crknadle, would it be possible to get some of the bug fixes that have happened since 1.2.12 into jessie? Or perhaps put the current 1.2.12 release into jessie?

Patches for targeted fixes only, and they get carried ongoing as individual quilt patches after scrutiny by the release team.  No new versions can get uploaded to Stable.

[Section 5.5.1] (https://www.debian.org/doc/manuals/developers-reference/ch05.en.html#upload-stable) of the Debian Developer's Reference explains the general situations that are fitting for doing uploads to Stable.  Furthermore the release team has bugs sent to them go to a mailing list, which rejects the email if the attached patch set is too large, then causing a big delay in their response because someone has to find the old bugs that went unnoticed.

The bottom line is that for fixes to get to Stable, the issues need to be serious and the changes need to be minimal, and it's very common for the release team to request removing proposed changes and then asking for both a diff and an *interdiff* comparing the original diff with the new diff for them to re-review the proposed changes.

The biggest issue is that the release team is going to want to know or be able to verify that the patch set actually fixes what it claims to fix.  In this case that would be troublesome because it's a bug that requires additional hardware, making it a more *niche* issue.

I'm all for fixing bugs -- I'm explaining this to try to help set the expectations of what's likely to be realistic.  I'll have a look at the commits that have been linked to above to see if I can make an estimated guess as to which ones would pass release team scrutiny.

**Comment by dstensnes** [comment]
Might I suggest moving talks about getting mumble into Debian into a separate issue? Just for clarity and make it easier to track the issue from emails and such? I would really like an updated version in Debian, but in the meantime, can I download development snapshots for 64-bit linux in binary form from http://mumble.info somewhere? I would love to test them out under linux, but not quite sure how I should go about compiling against newer versions of openssl and qt and such, to get to a level equivalent of the windows builds.

**Comment by mkrautz** [comment]
Mumble is in Debian, we were simply discussing how to get this particular bug fixed in the Debian package in jessie. I am sorry I added some extra patches and noise to the discussion.

Right now, the only Linux packaging of the client we provide are the Ubuntu PPAs available on mumble.info. So for now, you'll have to build yourself. Sorry.

**Comment by crknadle** [comment]
@dstensnes: I maintain backported mumble packages for Debian Unstable, Testing, Stable, and Oldstable in [my public Debian repository] (http://debian-packages.coredump.us) if you want to try that.  Right now I have 1.2.11 available for Jessie, but I'm about to upload 1.2.12 (probably today).

@mkrautz: Your comments and suggestions were all helpful, even if some of the patches pointed to might not fit what the Debian release team might be willing to accept for Jessie.  ;-)  And I'm both glad and sorry that the confines for getting things into Debian Stable are so strict.

**Comment by chrismp** [comment]
@mkrautz The workaround works, thanks. But since I'm paranoid about giving keyboard control to anyone other than root, I'll run `gksudo mumble` for now...

**Comment by mkrautz** [comment]
@chrismp

Note that what I suggested was not to give keyboard access to anyone but root.

What I actually suggested was to make sure all input devices in /dev/input* are owned by, and can only be read by root.

By doing that, Mumble will automatically fall back to XInput2, because it doesn't find any keyboards.

**Comment by mkrautz** [comment]
Correction: not all devices in /dev/input, only keyboard-like devices.

**Comment by chrismp** [comment]
Ah, I understand. My bad. OK, well my problem is solved.

**Comment by chrismp** [comment]
Ah, I see. My bad, thanks. I closed this issue since my problem is solved, but I'll reopen it in case you think this should be closed after a permanent fix.

**Comment by mkrautz** [comment]
The permanent fix is already released. It is just not in Debian jessie yet. Closing.
