### ISSUE TITLE
Users can hear me, but I can't hear them [debian]

### ISSUE THREAD

**Issue by chrismp** [mumble-voip/mumble#2007]
My OS: Debian 8.2 (Jessie)
My desktop manager: [MATE](https://en.wikipedia.org/wiki/MATE_(software))

I can listen to audio/video files, hear sound on YouTube and other sources.

I ran `sudo apt-get install mumble` and went through the audio setup wizard. I could hear myself during the setup.

Once setup, I opened MATE terminal. I ran `mumble mumble://MyUserName@someserver.mumbleboxes.com:PORT_NUMBER_HERE` to connect to a friend's server.

They could hear me, but I couldn't hear them. In the "Configuration" menu, I went thru each audio output device, but nothing worked. In fact, when a friend spoke, the mouth icon next to their username did not turn red to indicate they were speaking.

How do I fix this?

**Comment by MagiX13** [comment]
I have the same issue for a few days now, and am on jessie as well.
It worked fine ~ a week ago and I didn't change anything in my mumble settings. People can still hear me but I can't hear them
I tried 
* different settings regarding the output
* different servers. I found one person that I could talk with on a lot of public servers, but that's about all
* compiling mumble from source
* server loopback

My guess would be that this is related to the recent kernel update to 3.16.7-ckt20-1+deb8u1. This is the only "big" update that I remember and might be related. 
@chrismp which kernel are you using? (uname -a)

**Comment by hacst** [comment]
Try if forcing TCP (With advanced checked go to Network -> Force TCP Mode) helps. If so this is likely caused by a Qt bug which randomly prevents us from receiving UDP.

Once https://github.com/mumble-voip/mumble/issues/1968 is resolved we should at least get automatic fallback to TCP if this issue occurs.

**Comment by chrismp** [comment]
@MagiX13 3.16.7-ckt20-1+deb8u1

@hacst That worked

**Comment by chrismp** [comment]
@hacst Is there a way to start Mumble with the box checked? So I don't have to go to the sub-menu and check it each time I start it up?

**Comment by chrismp** [comment]
@hacst Is there a way to start Mumble with the box checked? So I don't have to go to the sub-menu and check it each time I start it up?

**Comment by hacst** [comment]
Hm. That setting should be stored like any other setting.

**Comment by sharkwouter** [comment]
@hacst I've been having the exact problem and have tried the same troubleshooting steps @MagiX13 used.  I also use Debian Jessie and I stopped being able to hear people at about the time this issue was created.

I've found out that I can only hear people who transfer no more that 72 kb/s. If people put down their quality settings I can hear them. Changing the maximum transfer on the server does not fix this and other users can hear each other (they are on Windows).

If I check transfer from a person which I can't hear, I see transfer happening, but the lips don't light up.

It might have something to do with a kernel update, since https://www.debian.org/security/2015/dsa-3426 but I can't test the older kernel anymore, because I don't have the linux headers for it anymore (which means no xorg for me).

I posted on the forum as well: http://forums.mumble.info/viewtopic.php?f=4&t=2878#p7684

I hope this helps.

**Comment by philip-bl** [comment]
I have this on Debian Stretch. After some time (1 to 15 minutes) I stop hearing people.

mumble 1.2.18-1
Linux 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux

**Comment by zeflap** [comment]
@philip-bl Try 894ade2, available via adding the PPA at  https://launchpad.net/~mumble/+archive/ubuntu/snapshot to your sources.list and using
apt-get source --build
This fixed the issue for me.

**Comment by koudaiNEW** [comment]
Configure -> compression -> quality, adjusting to below 50kb/s.
It worked.
