### ISSUE TITLE
Tablet sensitivity broken when mumble window gains focus. 

### ISSUE THREAD

**Issue by PBnFlash** [mumble-voip/mumble#2056]
Running mumble-1.3.0~930~g143bf86~snapshot.msi 
64 bit windows 7 
Tablet Yinova msp19u driver V5.02f (the most recent one that will run properly on my computer) http://www.yiynova.com/En/qudong.php

Mumble seems to interfere with the pressure sensitivity on my tablet.
When the mumble window gains focus pressure sensitivity fails until the drawing program is restarted. 
Tested programs:
Flash CS6 (fails to largest size like clicking the mouse)
Photoshop CS6 (fails to largest size like clicking the mouse)
Blender 2.76 (fails to smallest size ?) 
The internal tablet pressure test seems to be unaffected.

**Comment by mkrautz** [comment]
Can you try the following, independently of each other:

 - Try to disable the use of win32 hooks in the global shortcut engine.
   You can do this by importing this reg file:
   https://drive.google.com/file/d/0Bw-IBZsflR_1dVlPOTl4U3FwTGM/view?usp=sharing
   If you want to enable them again, you can run this one:
   https://drive.google.com/open?id=0Bw-IBZsflR_1Z0FXbjYtbk5VNFE

 - You can try to disable the use of uiAccess=true in Mumble.
   This is an accessibility feature in Windows that allows Mumble access to
   input from all applications -- also if they run at an elevated integrity level.
   To disable this, copy your Mumble installation from C:\Program Files\Mumble
   or C:\Program Files (x86)\Mumble onto your desktop. (Copy the Mumble folder.)
   Then run mumble.exe from there. Since Mumble is not in a "secure" location,
   it will no longer run with uiAccess=true privileges.

Can you please try the two things above, and report back if one of them works?
Thanks!

**Comment by PBnFlash** [comment]
Running mumble 1.3.0~918~g8eec7cc

Disabling the registry file seemed to have no effect 

Running it from a folder on the desktop seemed to have no effect 

Strangely, when I tried to delete the mumble folder off my desktop the file was locked until I exited adobe flash cs6

Going through and deleting files one by one it seems Mumble\Versions\1.3.0~918~g8eec7cc~snapshot\mumble_ol.dll is the file that's locked 

PS I have attempted to disable to overlay. It didn't seem to fix the problem.

**Comment by mkrautz** [comment]
The file will be locked until all processes which the overlay is injected into are closed.
If nothing else, if you log out of your user account, it should become available for deletion.

**Comment by PBnFlash** [comment]
I deleted the file without issue. The pressure sensitivity works fine while the .dll is locked I just wanted to report it in case it was a relevant symptom.

**Comment by mkrautz** [comment]
Understood.

It does seem odd to me that the two above solutions did not work. They would be the obvious contenders for something like this.

Does it only mess up the pressure sensitivity on the tablet if you *use* the tablet when in Mumble?
For example, if you just use your mouse, make Mumble the frontmost application, click on things, make Photoshop the frontmost application, and use the tablet again -- does it still mess it up?

The other things that could potentially be culprits would be DirectInput (which you can't disable at the moment), and perhaps Qt itself, because I am sure it has support for Microsoft's tablet APIs.

Have you tried if this is also the case with Mumble 1.2.12? It uses Qt 4, not Qt 5, so the situation could be different there.

Thanks!

**Comment by PBnFlash** [comment]
Yes mumble 1.2.12 has the same issue 

Normally mumble is on a separate screen so I alt tab or use the mouse, the tablet only maps onto the screen built into it. Even when the mouse is used to give focus to mumble it disables the pressure feature. 

I can preform the test with the much more standard wacom tablet/drivers but that would require uninstalling my primary tablet drivers. 

I don't think it has anything to do with microsoft's tablet api's I disable as many of those features as I can find, and the tablet drivers are the same ones as I'd use on windows xp. The tablet itself is recognized as a plug and play mouse (I think most of them are anyways) The driver only seems to provide calibration to the screen and pressure sensitivity. 

So if the driver was to fail entirely it would be very similar to what I'm experiencing.

**Comment by Krzmbrzl** [comment]
Does this still happen with the released 1.3 version?

**Comment by PBnFlash** [comment]
I no longer use mumble or that tablet it seemed to be a qt thing causing
the issue.

But that brand of tablet is becoming more popular so it may be worth
passing on to qt if it hasn't been fixed.

**Comment by Krzmbrzl** [comment]
Thanks for the info :)

I did a quick google search for qt and pressure sensitivity on tablets but nothing came up. Given that has happened 4 years ago, I think chances are that Qt has fixed this by now as I have read about other Qt applications explicitly using this pressure sensitivity...

Let's hope the best then and close this issue until it is re-encountered :)
