### ISSUE TITLE
RFC: Overlay injection rule spec

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#2059]
This is a proposal for an internal syntax for overlay exceptions.

My thinking is that we convert the current radio buttons in the client to a dropdown, containing:
- Blacklist   (same as before)
- Whitelist  (same as before)
- Game launchers  (new default, hard-coded, can't be changed)
- Custom  (allows people to write their own rules, uses the 'Game launchers' ruleset by default)

The blacklist and whitelist options will work exactly like they do now. 

Game launchers will show the rules in a list like Blacklist and Whitelist do, but will probably make each rule human readable.

<Steam.exe becomes "Parent is Steam.exe"
!<Steam.exe becomes "Parent is not Steam.exe"
*steamapps* becomes "Path matches *steamapps*"
D:\\MyGames\\\* becomes "Path matches D:\MyGames\*"
hl2.exe becomes "hl2.exe"

Custom is meant for power users, and may contain just a text editor component.
Otherwise, we could do a UI for adding "NOT <rule>", "PARENT IS <rule>", etc.

This supercedes https://github.com/mumble-voip/mumble/issues/1953 and https://github.com/mumble-voip/mumble/issues/1954

Spec at https://gist.github.com/mkrautz/b0fc8d0c80420b9c1618

WDYT?

**Comment by mkrautz** [comment]
Mockup

![overlay-rules-mockup](https://cloud.githubusercontent.com/assets/36527/12079962/e89eaa3e-b24b-11e5-94d6-c04cd243286e.png)

**Comment by hacst** [comment]
Probably a good idea to beef it up that way. Definitely more robust than the auto-whitelisting I proposed a while ago (will be higher maintenance for the defaults though).

How will this handle updates to the defaults provided by us? Is it basically concatenating whatever the user provides to our defaults (which could be auto-updated)? It seems like the scheme requires us to evaluate the full list every time so I guess that would be viable and would solve the problem.

UI wise I think we should go for a simpler approach. As the default is going to be a whitelist and normal users shouldn't switch away from that (so random stuff doesn't crash) I'm fine with making the blacklist an obscure feature of our syntax (e.g. you have to know that you can do ```*``` and then blacklist). Also having the launchers in their own tab you cannot edit doesn't seem very helpful given the way the entries would actually be interpreted. 

Basically all I think we need is mockup 2+3 (maybe using a table or a control element group to make it simpler/faster to edit and reorder the list). Our presets would simply be uneditable/movable entries (with a checkbox to disable them) at the bottom with the user entries going on top (reverse of what the file is I guess...but I think it works better in the UI that way).

We will have to think of a easy and discoverable way to add new entries as otherwise people will simply assume the overlay is no longer working for game XYZ that's not in our defaults. One part of that might be to add an explicit drop fields (e.g. for allow/disallow) where games can be dropped so they appear in the list. No really good idea on how to make the user aware of the feature in general....

Format wise:
* I assume this won't allow compound rules/scopes (e.g. ```<Steam.exe { hl2.exe }``` or ``` <Steam.exe && hl2.exe``` )? Do we need them (if yes that makes lots of things very complicated...)?
* Could think about spelling the single character stuff out if we find good words. Otherwise we should probably prefix the user file with a small header explaining them
* Does ```<``` also match on the parent itself? If we want easy allow/disallow semantics it might make sense to - by default - add entries as "this and all children" as games usually won't have any and that way it's easier to deal with launchers etc. On the other hand we might crash launchers ;)

**Comment by mkrautz** [comment]
We probably also need to add a rule to check for DLL presence in the process.

We don't want to inject the default overlay into VR applications. So checking for the presence of OpenVR/SteamVR/Oculus SDK would be nice.

**Comment by Kissaki** [comment]
I think this was implemented/superseded by the Overlay Exceptions? Or does this look to add something different/additional?

**Comment by Kissaki** [comment]
Our current Launcher Filter:

![image](https://user-images.githubusercontent.com/93181/43037726-36ca0c06-8d11-11e8-930a-09297d406e2f.png)
