### ISSUE TITLE
Remove recording notification feature

### ISSUE THREAD

**Issue by Eviltechie** [mumble-voip/mumble#2079]
Our community has found that users are often called out when they start recording. This pressure makes it hard for them to document cases of verbal abuse for our admins to deal with later.

The recording notifications rely on the client being honest. It's trivial to disable the recording notifications from being sent on either the client or the server. This gives users a false sense of security.

I suggest that the recording notification feature be removed entirely from Mumble. As an alternative, server admins should have some method of defeating this feature.

**Comment by crknadle** [comment]
On the one hand not having the notification might be better for catching abuse, but on the other hand there are varying laws governing [recording someone without their knowledge] (https://en.wikipedia.org/wiki/Telephone_recording_laws).

By blocking the recording notifications server-side this has privacy implications because this is unexpected behavior compared to what Mumble ships upstream.  If nothing else I'd suggest making this behavior clear in the greeting message on your server and as to the intended purpose of it.

On the flip-side it's always possible to have the audio output split to a recording device (whether software or hardware), so there's always going to be a way in which recording **could** happen without other parties knowing it.  I'm not sure that justifies removing the notifications, though.

I think this needs further consideration as to the possible implications.

**Comment by jumpandspintowin** [comment]
Notification of recording is required by law in most democratic countries, but is not the job of the software in order to provide notification. Further, in some countries VoIP is not considered a telco, and therefore not subject to the specific laws restricting the recording of telephone communications. Software should definitely automate as many tasks as reasonable, and notification of recording *when required by law* is definitely reasonable.

However, as Eviltechie has pointed out, there is a safety issue associated with such notifications as well. The lowlifes of the internet tend to take their anonymity as a shield and begin verbally abusing the recorder. Mumble should not force notification of recording, as there are times where it is both not required by law and a safety issue will arise if notification is sent.

Along with the fact there many ways to record sound without using Mumble, or one could recompile Mumble to not send the notification, it seems not only pointless but asinine that a user can not disable sending notification of recording. It provides a false sense of privacy.

My vote is to have notification sending optional, and defaulted to off. If someone wants to undertake the task, the option could default to 'On' at install-time when the client's computer is detected as existing in a country where notification of recording would be required by law, but I'm not a lawyer, especially in the 170+ countries of the world.

As far as server-side filtering of notifications, it doesn't make much sense to me to have the option to disable passing client notifications of recording.

**Comment by Eviltechie** [comment]
We opted to remove the record message forwarding on the server because it was easier than distributing modified clients.

Having an option for the client to simply not send the notification might be a better option. Those than wish to notify others still could, with the caveat that users may still be recorded without their knowledge.

**Comment by JoelTroch** [comment]
@jumpandspintowin Country detection would be pointless because on any "popular" OSes (Windows/Linux/Mac), it's possible to fake the country in many different ways. Even worse if people are using Linux distros specialized in privacy security.

**Comment by hacst** [comment]
It's a damned if you do damned if you don't situation. Imho recording people without their knowledge is a pretty big deal and nothing you should have to be constantly on guard about. Also if starting to record is enough to get the troll to shut up or leave that's pretty much mission accomplished a lot of the time. I see that there might be situations where that is unsatisfactory but overall I still favor "forced" notification. (Obviously mumble cannot guarantee notifications always happen (as @Eviltechie 's patching of the server shows but it is a barrier ).

**Comment by ElPumpo** [comment]
I'm on OPs side. It's up to the end user to tell everyone else they're recording.

Everyone refering to "law" or whatever doesn't see the real point.

Just erase the notification, pls

**Comment by Kissaki** [comment]
What is the use case for not sending a recording notification?

1. Recording abusers to document their misbehaviour
2. Recording something in secret so the other person 

I consider 1. reasonable.

But while 2. is arguably reasonable amongst trustworthy people, who will ask the recorded whether they may share before doing so, it also opens the door to recordings being used unbeknownst and/or damaging to the recorded individual (bullying, making fun of etc).

If someone gets recorded they can still ignore the notification if they are fine with being recorded.

Just because there are other means to record I do not think we should stop being a “good citizen” and not notify users. It is argued users will get a false sense of security, but that is outside of our control. Even then the simple question of “why does Mumble not notify when it could” is a pretty strong argument to me.

Offloading the decision to the server operator seems fine at first, but I do not think it would be clear to users that whether this feature is enabled or not is the decision of the server operator. I am leaning towards having a consistent Mumble application behaviour over that, and to protecting users (as much as we reasonably can and should). It seems only fair to users being recorded to notify them about it.

I would be interested in use cases though and how common each is.

**Comment by Krzmbrzl** [comment]
I tend to agree with @Kissaki. Of course can't guarantee the notification to be in place as Mumble is FOSS, but we can at least provide this functionality in the default setup.
