### ISSUE TITLE
Cant bind Xbox guide button to Push-to-talk.

### ISSUE THREAD

**Issue by bamtan** [mumble-voip/mumble#2082]
Im trying to bind my Xbox button on my 360 controller to a push to talk, but it does not work. 

I've also tried this solution on [Reddit](https://www.reddit.com/r/emulation/comments/1goval/any_way_to_map_the_middle_xbox_360_button/camujj7), assigning the key to "V", yet it did not work for Mumble.

Any solutions?

Regards
bamtan

EDIT: it is a wired controller

**Comment by mkrautz** [comment]
We've recently implemented XInput support in our snapshot builds. You can download them from http://www.mumble.info (Development Snapshot, 1.3.0).

Note that we don't yet filter DirectInput events from the same device -- so Mumble will "double bind" some buttons on the controller -- but that should have no effect. It just visually clutters the global shortcut dialog, since it will show the button as bound by both DirectInput and XInput.

Please report back if trying this with snapshots work for you. Thanks!

**Comment by bamtan** [comment]
Using the latest snapshot, it works! Thank you :grimacing: :purple_heart:

**Comment by mkrautz** [comment]
Excellent, thanks for the confirmation.

**Comment by slikts** [comment]
This is awesome, thanks.
