### ISSUE TITLE
Restore from Dock/System Tray not working on Ubuntu 14.04

### ISSUE THREAD

**Issue by ghost** [mumble-voip/mumble#2126]
A fairly annoying bug that is still present in the version installed from the ubuntu trusty repository and te ppa as well. If you minimize the mumble window after a while there is no way to recover it. The button on the tray icon "Activate" is not working and the dock icon is also unable to restore the window. Strangely if you play with the application settings like hide on tray when minimized and always on top fixes the window manager issue for the current session, but once you quit mumble and restart it it still acts bugged. Can this bug be fixes please? At this point you have to quit and restart the app to access the GUI.

**Comment by mkrautz** [comment]
I briefly tried to reproduce with the stock Mumble in 14.04, and couldn't seem to reproduce it.

Does it happen after a specific event has occurred on the server?

**Comment by szekeres2016** [comment]
Its unrelated to any server activity. Its start up in a way that prevents it to be restored from minimized state. Just going into settings and hiting 'OK' will fix it for the time being but after I start it up again its broken. It must be Unity desktop environment specific because I did not encounter this behavior on other Ubuntu 14.04 based distros like Linux Mint Cinnamon and Ubuntu GNOME etc. The dock indicator is suggesting that something about it not entirely right, the icon is on the Unity launcher but its not highlighted as being active. I hope it helps, let me know if I can provide any more information.

**Comment by szekeres2016** [comment]
I just discovered that keeping Mumble in the Unity launcher makes it start up just fine. Launching it from unity menu if not pinned to the launcher makes it start up bugged that eventually leads the GUI unrecoverable if minimized...

**Comment by mkrautz** [comment]
Maybe related to https://github.com/mumble-voip/mumble/pull/2685

**Comment by Krzmbrzl** [comment]
Is this still the case with Mumble 1.3?
