### ISSUE TITLE
Build a Mumble client optimized for Steam Link

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#2130]
This would be a neat side project.  The Steam Link has an SDK available, and you can write apps for it. It's a Linux/Qt/SDL based environment.

Presumably, such a client would be optimized for a TV scenario. Such a user interface would also be useful in general, on Steam Machines, SteamOS, or living room PCs in general.

**Comment by dstensnes** [comment]
Wouldn't it make sense to make a headless like mumble which is controllable via something like an UNIX socket or something, and a client side library for easy control? That way, making a frontend for that would be quite easy, either directly integrated with games or as a overlay for games, or as a separate program with global hotkeys or something? Just throwing it out there as an idea at least.

**Comment by Kissaki** [comment]
[The Steam Link SDK in question](https://github.com/ValveSoftware/steamlink-sdk)

**Comment by Kissaki** [comment]
@dstensnes decoupling the GUI and Logic would be a huge task.
Qt, as a GUI framework, already provides mechanisms for abstraction, and allows creating multiple GUIs.
However, if we have a Qt client, and Steam Link can run Qt, why not use it?
I don’t see why we would need to tackle a huge decoupling task when we can just take a look at how to make our current client work on Steam Link.

As an "up for grabs" this is definitely intended as a port it over and see where it takes us, rather than a restructuring/new GUI.

**Comment by DGMurdockIII** [comment]
I just got a steam link and would love mumble for it

**Comment by Hartmnt** [comment]
I think the Steam Link is discontinued without any successor... So can this be closed?

**Comment by Kissaki** [comment]
I can confirm the Steam Link hardware has been discontinued.

I would close this. I don't see it happening.
