### ISSUE TITLE
Error compiling mumble - fatal error LNK1106: invalid file or disk full: cannot seek to 0x6D6A13E8

### ISSUE THREAD

**Issue by evangelist88** [mumble-voip/mumble#2136]
Hi,

I cannot compile mumble because I have this error:

```
Microsoft (R) Program Maintenance Utility Version 12.00.21005.1
Copyright (C) Microsoft Corporation.  All rights reserved.

python ../../scripts/gen-mumble_app-qt-def.py release C:/Qt/5.5/msvc2013/lib ../../release/mumble_app.def
link /NOLOGO /DYNAMICBASE /NXCOMPAT -WX /DEF:../../release/mumble_app.def /ignore:4102 /ignore:4197 /INCREMENTAL:NO /DLL /SUBSYSTEM:WINDOWS,5.01 /DEF:..\..\release\mumble_app.def /MANIFEST:embed /OUT:..\..\release\mumble_app.dll @C:\Users\Dena\AppData\Local\Temp\nm3EBA.tmp
   Creating library ..\..\release\mumble_app.lib and object ..\..\release\mumble_app.exp
..\..\release\mumble_app.exp : fatal error LNK1106: invalid file or disk full: cannot seek to 0x6D6A13E8
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\link.EXE"' : return code '0x452'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: 'cd' : return code '0x2'
Stop.
```

How can I compile it? Has anyone else had the same problem ?

**Comment by mkrautz** [comment]
Are you using CONFIG+=static with a non-static Qt?

In general, our Windows builds use the build environments available via the mumble-releng repository:
https://github.com/mumble-voip/mumble-releng/tree/master/buildenv/1.3.x/win32-static

**Comment by evangelist88** [comment]
I followed this instructions [https://wiki.mumble.info/wiki/BuildingWindows](https://wiki.mumble.info/wiki/BuildingWindows) and yes i'm using CONFIG+=static as it write in the that link but I don't know if I have a non-static Qt. How can I know if i'm using a non-static Qt? and How can I setup a non-static Qt?

Thanks

**Comment by mkrautz** [comment]
Hi,

First, have you checked that it isn't because the disk is full? Just checking! Probably isn't that, but still worth a check, if you haven't already. :-)

Now, the reason I assumed you weren't using a static build environment, was that there are references to a non-Mumble version of Qt in your command output:

C:/Qt/5.5/msvc2013/lib

Now, if you followed the instructions from the Wiki, you probably *do* have a static Qt, and the one referenced above is one you've installed yourself for other things.

I am not sure if the fact that it is using a non-static Qt that is causing the errors, but it is at least an error in its own right.
It seems that when you build Mumble, the qmake binary you're using is the one from that Qt installation instead of the one from the Mumble build environment.

When you're in a command prompt, about to type qmake, try instead to type:

    where qmake

to find out which qmake your PATH env var causes cmd.exe to prefer.

To fix that particular issue, you would need to remove the stuff in C:\Qt from your PATH when entering the Mumble build environment.

This is probably a sanity check we should integrate into the mumble-releng repo...

**Comment by evangelist88** [comment]
I resolved one problem but the build stops again in this way:

```
Microsoft (R) Program Maintenance Utility Version 12.00.21005.1
Copyright (C) Microsoft Corporation.  All rights reserved.

        "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\\bin\amd64\link.exe" /DEBUG /OPT:REF /OPT:ICF /NOLOGO /DYNAMICBASE /NXCOMPAT -WX /LIBPATH:"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\\lib\amd64" /LIBPATH:"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\\atlmfc\lib\amd64" /LIBPATH:"C:\Program Files (x86)\Windows Kits\8.1\\lib\winv6.3\um\x64" /LIBPATH:"C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\\lib\x64" /INCREMENTAL:NO /DEBUG /DLL /LTCG /SUBSYSTEM:WINDOWS,5.01 /VERSION:1.3 /OUT:..\release\mumble_ol_x64.dll @C:\Users\Dena\AppData\Local\Temp\nm8364.tmp
   Creating library ..\release\mumble_ol_x64.lib and object ..\release\mumble_ol_x64.exp
LINK : warning LNK4010: invalid subsystem version number 5.01; default subsystem version assumed
LINK : error LNK1218: warning treated as error; no output file generated
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\\bin\amd64\link.exe"' : return code '0xfaa'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: 'cd' : return code '0x2'
Stop.
```

another question, Can I use VisualStudio or QTCreator to build mumble instead of command line?

Thanks

**Comment by mkrautz** [comment]
The problem here is that the overlay uses

    /SUBSYSTEM:WINDOWS,5.01

which doesn't work for the x64 toolchain we're using (it doesn't target XP).

Since we also pass the `-WX` flag to the linker, the warning about the invalid subsystem is treated as an error.

**Comment by mkrautz** [comment]
Not sure why it's using that subsystem, since

https://github.com/mumble-voip/mumble/blob/master/compiler.pri#L130-L132

should reset it to 6.0 (Vista)

**Comment by evangelist88** [comment]
Thank you! I compile in release but I need to compile also in debug and it doesn't work.

I tried to compile the version 1.3.x -> win32-static_debug but during build-all.bash I had an error: 

`LINK: fatal error LNK1181: cannot open input file 'pcre16.lib'` 

and with version 1.3.x -> win32-static I had this error:

```
	C:\Qt\Tools\QtCreator\bin\jom.exe -f Makefile.Debug
Error: dependent 'C:\MumbleBuild\win32-static-1.3.x-2016-01-30-5697a58-611\Qt5\lib\Qt5Svgd.lib' does not exist.
jom: C:\Users\Dena\MumbleBuild\win32-static-1.3.x-2016-01-30-5697a58-611\mumble\src\mumble\Makefile [debug] Error 2
jom: C:\Users\Dena\MumbleBuild\win32-static-1.3.x-2016-01-30-5697a58-611\mumble\Makefile [sub-src-mumble-make_first-ordered] Error 2
```

How can I compile in debug? Is there a guide that learn how to do it?

**Comment by mkrautz** [comment]
You should be able to build debug in the same way -- but it is currently broken. Sorry.

The error is that the build recipe for PCRE doesn't take into account that the debug version of the pcre lib has a different filename. It is probably called "pcre16d.lib" instead of "pcre16.lib".
(You should be able to figure out its name by checking the C:/MumbleBuild/winXX-static-xXXX/pcre/lib/ folder of your build, and navigate to the pcre folder...).

The build script at https://github.com/mumble-voip/mumble-releng/blob/master/buildenv/1.3.x/win32-static/pcre.build would them rename the file from pcre16d.lib to pcre16.lib to make the naming consistent across debug/release builds.

For now, you should be able to rename the file itself in your C:/MumbleBuild/winXX-static-xXXX/pcre/lib/ folder.

The Qt5Svgd error, I am not sure about...

**Comment by evangelist88** [comment]
I have the Qt5Svgd error because I'm compiling the debug version using this command:

`qmake -recursive main.pro CONFIG+="debug static no-elevation no-g15 no-asio" CONFIG-=sse2`
and then 
`nmake`

but during the compilation we need to find the debug QT library "C:\MumbleBuild\win32-static-1.3.x-2016-01-30-5697a58-611\Qt5\lib\Qt5Svgd.lib" but I have only the release version "C:\MumbleBuild\win32-static-1.3.x-2016-01-30-5697a58-611\Qt5\lib\Qt5Svg.lib".

**Comment by mkrautz** [comment]
Right, for that, you would need the win32-static-debug environment that you referenced earlier.

**Comment by evangelist88** [comment]
Ok, using the win32-static-debug environment I have other strange things. The build doesn't create Qt5 folder and during the build of qt library I have this log:
```
Hunk #4 succeeded at 302 (offset -2 lines).
patching file src/network/ssl/qssldiffiehellmanparameters.cpp
patching file src/network/ssl/qssldiffiehellmanparameters.h
patching file src/network/ssl/qssldiffiehellmanparameters_dummy.cpp
The next patch would create the file src/network/ssl/qssldiffiehellmanparameters_openssl.cpp,
which already exists!  Assume -R? [n]
```

finally I don't have a debug build of qt.How can I do? Could you help me?

**Comment by mkrautz** [comment]
It seems like you are building into a folder that already has been used before, since the patch doesn't apply cleanly.

**Comment by evangelist88** [comment]
I'm building in folder C:\MumbleBuild\win32-static-debug-1.3.x-2016-01-30-5697a58-611 and exists also C:\MumbleBuild\win32-static-1.3.x-2016-01-30-5697a58-611. It's strange.

**Comment by evangelist88** [comment]
I've clean and rebuild all using the 1.3.x\win-32-static-debug but I have the same problem before. Using release version (win-32-static) the build complete successfully but I cannot debug.

**Comment by mkrautz** [comment]
Why can't you debug the release build?

It could be because Mumble is built with uiAccess=true, you can disable that by rebuilding Mumble with
CONFIG+="release no-elevation".

**Comment by mkrautz** [comment]
Hi. Please ping this bug if you want me to re-open it! Thanks!
