### ISSUE TITLE
Server Crash when there is a very large concurrency

### ISSUE THREAD

**Issue by pengyz** [mumble-voip/mumble#2186]
When there is more than 600 client connect into one channel,the server may crash with an error "std::badAlloc".
I try to analyze the bug by myself,I'm sorry I can't find the reason.
I think I need some help... SOS!

**Comment by mkrautz** [comment]
Seems like your server is running out of memory.

Can you explain some more about your setup?

What OS are you on?
What kind of hardware are you running Murmur on?
Are you using the 32-bit x86 static server binaries from mumble.info, or are you using other packages?
Etc.

**Comment by pengyz** [comment]
Very Thanks for answer for my question.

I use murmur on windows and linux both.
Just Windows 7 x64 Ultimate and Ubuntu 12.04 LTS x64.

I also use other packages,but I get the same crash error.

I can't find any talk about this crash on internet. Hope anyone can help me
about this.

2016-03-24 20:09 GMT+08:00 Mikkel Krautz <notifications@github.com>:

**Comment by mkrautz** [comment]
We need clear, explicit information in order to be able to diagnose this.

What exact packages are you running?

Do you see the exact same behavior on both Windows 7 x64 and Ubuntu 12.04?

How much memory does the machine have? The std::bad_alloc exception would be thrown if Murmur cannot allocate memory.

On Linux, I believe you would be fighting the OOM killer before you would begin getting std::bad_alloc exceptions... So am I right in assuming the errors you get are on Windows?

Are there any more details to the exception you're getting rather than the text you have provided thus far? I.e, does it include, perhaps, a location of where the exception happened? A stack trace?

Can you try to observe the memory usage of Murmur, and see what kind of resources it is using in the configuration where it crashes with std::bad_alloc?

Thanks,
Mikkel

**Comment by pengyz** [comment]
I'm sorry. This problem is only appear onWindows.

I test it on linux with a release version. Linux give me a message box... I found that it's the limit of the fd counts. I set it to 1030(it's 1024 by default),so murmur is very stable now.

Now I know that this problem is windows only.Thanks for every one. I'm so sorry. I just test murmur with a debug version on linux. It crash without any prompt info.

I think I can close this issue. I really don't know that why it crash on windows. I try debug it for a long time, but now, I try use it on linux and everything goes well.

Thanks for everyone and thanks to god.
