### ISSUE TITLE
Linking channels without showing it to other users

### ISSUE THREAD

**Issue by ReekyMarko** [mumble-voip/mumble#2226]
This is really not an issue, but I thought this would be the best place to get an accurate answer, so here goes:

I host a Mumble server and have a private section for my friends and a public section for everyone else. Sometimes when I see people on the public side, I would like to take a quick listen to them, so they're not violating server rules etc. I am aware of the linking feature, but my I'm conserned that they will be able to see that an admin is listening to them and change their behaviour accordingly :P 

So can anyone confirm whether or not the little link icon is visible to everyone or just the user who created the link?

**Comment by Natenom** [comment]
It is visible to everyone; also all linked channels have a italic font.

**Comment by ReekyMarko** [comment]
OK, thanks! So there is no way to listen to a channel without making it visible?

**Comment by mkrautz** [comment]
No, not currently.

If you would like this feature, and/or have an idea on how it should be implemented in the client (from a user's perspective), you're more than welcome to file a feature request. (Or I can convert this to one...).

**Comment by Kissaki** [comment]
I like that we’re transparent to the user on what his software actually does.
We notify users of being recorded, we show them which channels are linked and thus, who can potentially hear him.

I’m closing this. As @mkrautz said, please feel free to create a feature request, where you can present reasoning and use-case adequately.
(I’d rather have a clean FR rather than a FR with noise, comments to an old discussion. That’ll be confusing.)
