### ISSUE TITLE
DNS name callback

### ISSUE THREAD

**Issue by robingroppe** [mumble-voip/mumble#2252]
Hi,
I have IPv4 and IPv6 set up on my server. There is an A and AAAA record on the external DNS server set up.
This setup worked like a charm for the past.
Since a week or so an error keeps getting into the log.

`<W>2016-05-07 21:47:18.435 1 => <32:(-1)> New connection: 52.201.18.254:60397
<W>2016-05-07 21:47:18.633 1 => <32:(-1)> Connection closed: The TLS/SSL connection has been closed [1]
<W>2016-05-07 21:47:18.635 1 => Registration: DNS name callback m.robingroppe.de=>5.9.6.109, 2a01:4f8:160:71e5:0:0:0:2 failed: Registration updated`

This affects my server in the way that it is listed in the masterserverlist with its IPv4 and not the domain anymore.
And this causes the clients to get a certificate warning because the certificate is issued for m.robingroppe.de and not an IP.
I hope this is a quick fix.

-> Murmur 1.2.16 running

**Comment by mkrautz** [comment]
The reason is that the master server (mumble.hive.no/mumble.info) is currently not able to do IPv6 anymore due to migrating to AWS. When migrating, we didn't consider we would lose IPv6 connectivity. We're considering our options here. (/cc @actown)

However, it obviously shouldn't affect IPv4 usage, like what is happening here.

Until the issue is fixed, the master server should probably just assume that IPv6 connectivity works, as long as it can connect via IPv4, and the DNS records match.

Sorry for breaking your server list entry.

**Comment by mkrautz** [comment]
Hi,

I've changed "host checker" to be more tolerant. If your registration uses a hostname, it will allow it to pass as long as the registration server can connect to more than one of the host's IPs (acquired via A and AAAA).

For a server with just a single A and a single AAAA record, as long as it can connect to IPv4 (or IPv6), your server should still be listed with its hostname.

Can you confirm whether this fixes the issue you were seeing? Thanks.

**Comment by robingroppe** [comment]
Jep its working again.
Thank you :)
