### ISSUE TITLE
Starting mumble will make computer go super slow a couple of seconds

### ISSUE THREAD

**Issue by ElPumpo** [mumble-voip/mumble#2273]
Whenever I start mumble my computer becomes really _slow_ for 3-4sec.
It has been like this for a long while, does it happen to anyone?

Running latest amd64 1.3.0 build, Windows 10 Insider Build 14342.

**Comment by mkrautz** [comment]
What happens is:

Mumble is using Windows hooks for global shortcuts. These are handled on the main thread.

Something during startup, presumably plugin auto-updates, cause the main thread to stall for 3-4 secs. (The main loop is still running, but the Windows hooks aren't processed "fast enough").

Since Mumble is in the chain for Windows hooks, this means that keyboard and mouse input is not processed in due while Mumble is stalling.

Note: It's possible that it's not just plugin updates, but something else as well.

**Comment by ElPumpo** [comment]
So, is fixing the issue going to happen?

**Comment by mkrautz** [comment]
Yep, milestoned 1.3.0.

**Comment by ElPumpo** [comment]
Btw 
[here](https://github.com/mumble-voip/mumble/files/265126/Console.txt) is a 1year old log of Mumble.

**Comment by mkrautz** [comment]
Attached as [Console.txt](https://github.com/mumble-voip/mumble/files/265133/Console.txt)

**Comment by Tarun80** [comment]
I've noticed the same thing happens with Origin - it uses Qt Framework too - especially when updating. Not sure if this is of much help, but it could point to the cause?

**Comment by ibex-are-goats** [comment]
I still get this!

**Comment by ElPumpo** [comment]
Seens only to happen on the amd64 versions. . .

**Comment by ibex-are-goats** [comment]
I'm pretty sure this defect is really old. Is there a bounty we can donate to? I'd like to incentivize this multithreading to be done properly. Mumble is important software for the FOSS world and either this defect needs to be fixed or the x64 builds need to be pulled, IMO.

**Comment by Tarun80** [comment]
It only seems to happen on the first startup though. Any after that are fine. While it is an issue I wouldn't say it's really a "major" issue.

**Comment by ElPumpo** [comment]
It is if it turns users away from using mumble, basic logic.

**Comment by mkrautz** [comment]
@ibex-are-goats I don't think bounties will help.
We don't have a system in place for bounties for the regular contributors.
I can't say if posting to one of the bounty sites for FOSS will work, though!

The project itself takes donations at https://wiki.mumble.info/wiki/Donate.
But they can't be earmarked to a particular feature.

**Comment by ElPumpo** [comment]
Yeah, that solves the issue.

**Comment by ibex-are-goats** [comment]
@Tarun80 To see how important this bug is, use me as your test subject: my last Mumble install date was 2014. I was going to migrate from Ventrilo. I took this bug as a sign of poor quality. Not to mention, my users would laugh at me for suggesting laggy software. I decided to delay migrating because of this bug. I then forgot about Mumble, and it took me 2 years to try it again now.

@mkrautz I'm guessing you are a lead developer? :) You may think of a quick workaround for this bug. But I am even more interested in supporting the long-term health of the Mumble project. Do you see a way that Mumble code can be refactored to be properly threaded, and thus prevent all related performance problems indefinitely? By "properly threaded" I mean "in a modern way", according to modern computer science practices, if you see what I mean.

If you see a solution to this problem that would help the project, I would like to donate directly to the people who you think could fix the problem. Or if you will not accept personal donations, I will donate to the project account.

**Comment by ElPumpo** [comment]
I can also refer to what ibex said, when I started to migrate from Skype to Mumble a lot of my friends went to TS3 after light usage of Mumble due to its hard initial mic setup.
I'm still running Mumble for multiple reasons but I see the potential of this project, I don't see that in the projects' competitors.

The devs just needs BETTER feedback and people who accually report stuff.

**Comment by ibex-are-goats** [comment]
Well done, humans! We have conquered the unconquered and found our path to valhalla!

Because @mkrautz is so bashful, I will donate directly to the Mumble project. But my thanks go directly to you, good sir, for remedying our sore affections!

To infinity, and beyond!!!

**Comment by mkrautz** [comment]
Hold on. Better test the change first! I assume you haven't, since there isn't a snapshot available with the change in it? :)

**Comment by ibex-are-goats** [comment]
You can't change my mind!!! ;)

**Comment by ElPumpo** [comment]
ffs update amd64 snapshot 🎯

**Comment by mkrautz** [comment]
Hi,

Please test https://dl.mumble.info/mumble-1.3.0~1471~gac134d3~snapshot.winx64.msi and see if it's better with that snapshot.

It includes my "fix". Thanks.

**Comment by ElPumpo** [comment]
it does, finally!

**Comment by ibex-are-goats** [comment]
The fixed version works for me too!!! :) :+1:
