### ISSUE TITLE
Typo when joining server with self-signed certificate

### ISSUE THREAD

**Issue by srive** [mumble-voip/mumble#2304]
OS: Windows
Mumble version: 1.2.16
Langauge: English

Might be related to #1658 
The message reads "Sever presented a certificate which failed verification.."
Should read "Server presented a certificate which failed verification."

**Comment by mkrautz** [comment]
The typo is already fixed in 1.3.0.

Unfortunately, we can't really fix strings in 1.2.x -- we'd have to update all translations as well.

The issue with the punctuation at the end is still present.

I suggest we fix it by removing the "." in the string here:
https://github.com/mumble-voip/mumble/blob/a77987097bf1f935a400c1c6f630e3e37e47a23b/src/mumble/MainWindow.cpp#L2812

and keep the "." in the `basereason`s.

**Comment by mkrautz** [comment]
> I suggest we fix it by removing the "." in the string here:
> https://github.com/mumble-voip/mumble/blob/a77987097bf1f935a400c1c6f630e3e37e47a23b/src/mumble/MainWindow.cpp#L2812
>
> and keep the "." in the basereasons.

This was implemented in https://github.com/mumble-voip/mumble/commit/0577ab7303f6a6273260d4982b3048c5c109c711 by accident... :-)

Closing as fixed.
