### ISSUE TITLE
Destination Folder forces itself to C Drive

### ISSUE THREAD

**Issue by JoshBerry022** [mumble-voip/mumble#2317]
I run my OS on a separate hard drive than I have my applications. Installing w/ the latest 1.2.16.msi brings me to the "Change Destination folder" - which allows me to change the folder to my other drives, but upon clicking "OK" i can see in the bottom that it reverts back to C:\  instead of the other drive letter.

**Comment by davidebeatrici** [comment]
This doesn't happen to me, can you provide more info about your system (OS version, hard drives...)?

**Comment by JoshBerry022** [comment]
Running 64-bit Windows 7 Professional SP1
120 GB SSD mounted as drive C
2 TB HDD mounted as drive P

Installer allows me to select a  new drive & location (already exists)
P:\Applications\Utility\Audio and Video\Mumble

As soon as I click through, I see at the bottom that Mumble has replaced the P: with C:

When I continue through, everything works fine, but on my C Drive it had created the entire folder path  C:\Applications\Utility\Audio and Video\Mumble    none of which had existed before.

**Comment by davidebeatrici** [comment]
Have you tried running the installer as administrator?

**Comment by mkrautz** [comment]
I have tried to reproduce this on Windows 10, without luck.

I have also tried to reconstruct the scenario in a Windows 7 VM. I created a new drive P:, and created the directory hierarchy

P:\Applications\Utility\Audio and Video

I ran the installer, and installed succesfully to P:\Applications\Utility\Audio and Video\Mumble without the installer changing the drive to C:

So I'm going to have to close this as it's not something we can do much about at present without more information.

I'd also like to add that installing Mumble to other drives is not a good idea.
It should be installed to your system root's Program Files or Program Files (x86) directory.
Windows forces our hand here, a bit.
We use the UI automation feature of Windows to be able to get global shortcuts from elevated programs -- to avoid breaking people's push-to-talk buttons when they switch to an elevated program. (Common breakages include a 'stuck' button, so a user will continuously transmit.)
We can only get access to this feature if Mumble is installed in %PROGRAMFILES% or %PROGRAMFILES(x86)%. Windows will not enable the feature for programs installed in other locations.

So, our general recommendation is to ALWAYS install Mumble to the default location.
Otherwise, you won't get all features, and it'll break in subtle ways.
