### ISSUE TITLE
RFC: Mumble license across repos

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#2390]
Hi,

Right now, we use different licences per repo.

I.e., grumble is one license, and one set of AUTHORS.
So is mumblekit, mumble-iphoneos, libmumble, mumble-releng, etc.

I would like to unify these, to make integrating or merging some of the code bases easier in the future.

I'm unsure how to proceed, though.

Assuming we agree on this, I propose that we:
1. Create a mumble-license repo. This will be the canonical place for LICENSE, LICENSE.headers, AUTHORS, etc.
2. Copy the generate-AUTHORS.py script from mumble-voip/mumble and put it into the mumble-license repo.
3. Modify generate-AUTHORS.py to work across repos:
   
   repos = [
       "mumble-voip/mumble",
       "mumble-voip/mumble-releng",
       "mumble-voip/mumblekit",
       "mumble-voip/mumble-iphoneos",
       "mumble-voip/libmumble",
       "mumble-voip/mumble-scripts",
       "mumble-voip/grumble",
       // etc.
   ]
4. Modify other repos to use LICENSE.header from mumble-voip/mumble repo. 

The tough part about this is syncing the AUTHORS files across repos.
I'm not sure how to do that in a clean way...

**Comment by hacst** [comment]
Hm. Can we do that? Aren't those separate works with differing authorships? I'm kinda uncomfortable with all this licensing stuff as obviously IANAL...

**Comment by Kissaki** [comment]
Seems unintuitive to me. With separate projects, that are otherwise independent (apart from organization and communication/topic), I think there should be AUTHORS and LICENSE files in those repos.

At the very least, I would not move them to a canonical repo, but create a repo for generation, and then copy/save the artifact.

I am not sure whether we need them to be the same license or copyable without changing authors. Did we copy code from one project to the other in the past? Is copying the authors list too much?

Sounds more like a use case for organization-as-author/copyrightholder to me.

Seems to overcomplicate things for a non-existent or rare use-case to me.

**Comment by Kissaki** [comment]
While I would like to be able to just copy code of course, I don’t think the work and implications are worth it.

So the AUTHORS file would not list authors of one project, but of all mumble-voip projects. That would simplify looking at a list or moving code between the projects, but make it harder to relicense etc, as you would have to ask all users. Now, with a permissive MIT license (pretty much do what you want but name us), I’m not sure that even has a use-case…

So maybe it would be good. Dunno.
