### ISSUE TITLE
Mouse Cursor get slowed down

### ISSUE THREAD

**Issue by xnihilo2k16** [mumble-voip/mumble#2426]
If i put my cherry usb keyboard G230 on my laptop my mouse cursor get slowed down for aprox 10s.  The connected mouse is a Logitech G502. My Windows is a Windows 7 SP1 64bit. If the keyboard was already connected i got the issue shortly after i started mumble. The problem is only be shown if iam opened the server browser indepentendly if iam currently connected or not.

[http://pastebin.com/UzihRUty](http://pastebin.com/UzihRUty)

**Comment by mkrautz** [comment]
Hi @xnihilo2k16,

The stack trace you dumped -- was that taken during the frozen state?
If so, the problem seems to happen during device enumeration.

Also, can you try to run a Mumble snapshot? We have some extra debugging output in there, prints some diagnostics about some of the cases of freezing that can happen in the GlobalShortcut code. (But *not* during device enumeration, which the stack trace you posted makes it seem like...)

You can download a snapshot from the Mumble website: https://www.mumble.info/ under "Developer Snapshot".

Then try to run Mumble without the Cherry keyboard plugged in.

Then, plugin the keyboard in.

Then, post the content of the Mumble log for your latest session. The Mumble log is available at %APPDATA%\Mumble\Console.txt (feel free to remove things from there if there is anything you consider private).

Thanks.

**Comment by xnihilo2k16** [comment]
Hi mkrautz,
In addition the link to the console output after your guide
http://pastebin.com/9fNxCdpJ

**Comment by mkrautz** [comment]
@xnihilo2k16 From the pastebin you posted here, it seems like you closed Mumble 1 second after plugging in the keyboard? Did it not hang there?

**Comment by xnihilo2k16** [comment]
nope it actually not that bad comapred to 1.2.16. it freezes only a second

**Comment by mkrautz** [comment]
The odd thing is, it seems like plugging in the keyboard gives two devices:

> <W>2016-07-16 15:40:05.262 Adding device {b7cc9d40-28c4-11e6-8001-444553540000} HID-konformes Benutzersteuergerät HID-konformes Benutzersteuergerät:1024
> <W>2016-07-16 15:40:05.274 Adding device {b7ccc450-28c4-11e6-8002-444553540000} HID-konformes Gerät HID-konformes Gerät:3

Could you perhaps plug in the keyboard (don't need to have Mumble running) and try do the following:

Start->Run "dxdiag", and save "Save All Information" to a file and upload it?

**Comment by xnihilo2k16** [comment]
http://pastebin.com/1cqSfTN6

**Comment by mkrautz** [comment]
Are you sure it doesn't have anything to do your with USB mic?

For example, does the delay happen at all if you USB mic is not plugged in?

**Comment by xnihilo2k16** [comment]
i disconnected the "Anua" nothing changed.

**Comment by mkrautz** [comment]
Thanks! I'll need add some features to Mumble to help better diagnose this... I'll ask when I have something for you to test...

**Comment by davidebeatrici** [comment]
Closing in favor of #3275.
