### ISSUE TITLE
Feature request: "Hold Time" default value

### ISSUE THREAD

**Issue by ibex-are-goats** [mumble-voip/mumble#2453]
Context: The "hold time" feature is an excellent one. But I don't know what the industry standard "hold time" should be. 

Request: I suggest looking at other audio systems to determine the industry standard for "hold time", then offer that to users as a default value.

**Comment by farcastr** [comment]
Hi, first-time contributor here. I believe I have a fix.

As per [Cisco](https://www.ciscopress.com/articles/article.asp?p=606583&seqNum=7), a hangover of 0.200s is generally appropriate for signal amplitude only, but I haven't been able to find a similar figure for signal to amplitude. I'm not sure if that would matter? If we are happy with the above, I can change the setting default and create a PR.

Let me know your thoughts.

**Comment by Krzmbrzl** [comment]
We currently use
https://github.com/mumble-voip/mumble/blob/c89a9b4158772b3d4e771a41155ff80db89f3110/src/mumble/Settings.cpp#L326
which is counted in "frames" which is defined as
https://github.com/mumble-voip/mumble/blob/c89a9b4158772b3d4e771a41155ff80db89f3110/src/mumble/AudioInput.h#L213-L214
where
https://github.com/mumble-voip/mumble/blob/c89a9b4158772b3d4e771a41155ff80db89f3110/src/mumble/Audio.h#L18
(in Hz)

The voice hold is handled here:
https://github.com/mumble-voip/mumble/blob/c89a9b4158772b3d4e771a41155ff80db89f3110/src/mumble/AudioInput.cpp#L1068-L1071

So it seems like this setting is not quite as simple to grasp as one might expect, but it would be great if you could dig into it a bit, document how it works (aka: how to calculate the hold-time in seconds based on the value in the settings, and then change the default to match 200ms) :eyes:

**Comment by farcastr** [comment]
Sounds good, I'll dive in.

**Comment by farcastr** [comment]
I had a look and commented how the hold time is calculated, and added some minor description for frame size and sample rate.

I'm still not 100% clear on how you guarantee that each iteration of encodeAudioFrame executes in 10ms so that the voice hold setting corresponds with the quoted time in settings. Is it through the lines below from encodeOpusFrame?

https://github.com/mumble-voip/mumble/blob/3b0fa8f8be740058fc60a743c83d96bc829b29c9/src/mumble/AudioInput.cpp#L932-L933

**Comment by Krzmbrzl** [comment]
Not really, no. Looking at it, this property comes from this line right here:
https://github.com/mumble-voip/mumble/blob/3b0fa8f8be740058fc60a743c83d96bc829b29c9/src/mumble/AudioInput.h#L214

Since we have a hard-coded sample rate of 48 kHz, you will find that
```
48 000 samples/s = 48 000 samples/(1000 ms) = 48 samples/ms
```
and thus in 10ms, we get
```
48 samples/ms * 10 ms = 480 samples
```
which has the same numeric value as `48 000 / 100`. Thus, `iFrameSize` is calculated in such a way that it always happens to amount to 10 ms of audio (assuming a constant sample rate of 48 kHz, which we currently have in Mumble)

**Comment by davidebeatrici** [comment]
Please note that the variable's name is wrong: a frame is supposed to be a sample multiplied by the number of channels.
