### ISSUE TITLE
Manual placement plugin: order in the plugins list

### ISSUE THREAD

**Issue by davidebeatrici** [mumble-voip/mumble#2455]
I think that it should be the first plugin in the list.
We could also add a separator and a text "Special plugins".

![plugins_list](https://cloud.githubusercontent.com/assets/5897523/16948931/e6cb7d10-4db7-11e6-846c-c78524613702.PNG)

**Comment by mkrautz** [comment]
It should just be sorted alphabetically, IMO.

So the bug is that it's unsorted because we insert it last.

Is that OK for you? That's the behavior prior to moving into Mumble as a built-in plugin.

**Comment by davidebeatrici** [comment]
Yes, it's OK. However, I think that separating it from the other plugins would be better.

**Comment by mkrautz** [comment]
Why? It's just a plugin...

**Comment by davidebeatrici** [comment]
That's true, but I think that it is more ordered to keep it separate from the others.

**Comment by Krzmbrzl** [comment]
I think it's time to make a decision on this one: In my new plugin framework (#3743) the link and the manual plugin are integrated alphabetically in the list.
From my point of view this makes the most sense as everything else is sorted that way. Thus if a user seat a for them, he/she will probably search for them in the place they'd be according to alphabetical order. 

Putting them at the top might solve that problem because they are directly visible, but I think having the list ordered consistently is better.

**Comment by davidebeatrici** [comment]
I agree.

With the new plugin framework the naming will also be consistent.
