### ISSUE TITLE
WoW + Mumble causing mouse issues

### ISSUE THREAD

**Issue by Malisent** [mumble-voip/mumble#2463]
I am on the current developer version of Mumble. 

My mouse sensitivity in WoW goes nuts if I run Mumble as an administrator and WoW at the same time. This happens with any mouse I use, so I've ruled out the mouse as the issue. However, this does not happen when I run the WoW beta.. only in live.

If I don't run Mumble as admin, WoW mouse sensitivity stays normal.. however if Mumble is not set to admin, my push-to-talk does not work when WoW is in the foreground.

This issue is recent - started happening the last week of June.

**Comment by Malisent** [comment]
After further testing, I have discovered this is only happening with the over-lay activated.

**Comment by mkrautz** [comment]
OK. A few different things here. Let's try to get to the bottom of this... :-)

### Mumble's push-to-talk not working when WoW is in the foreground

It shouldn't be necessary to run Mumble as admin. Mumble uses a Windows feature called UI automation to be able to get global keypresses from other programs, even those running with quite high privileges, such as programs running as admin.

However, this feature only works if Mumble is installed in the default location:
`C:\Program Files (x86)\Mumble` for the x86 build, or `C:\Program Files\Mumble`. Installing Mumble in any other location will not allow this feature to function. There's not much we can do about this: it's a Windows restriction.

### World of Warcraft as admin?

Are you by any chance running World of Warcraft as admin as well? That's not "normal". My WoW installation doesn't run as admin, and push-to-talk works in a Mumble installation that does not use UI automation.

### Different sensitivity with the overlay enabled

How do you run WoW? Fullscreen? Windowed? Borderless windowed? etc.

What's your FPS like when you run WoW with the overlay enabled vs. with the overlay disabled?
You can either use Mumble's built-in FPS counter, or WoW's (which can be toggled via Ctrl-R).

Can you explain in more detail what happens when the overlay is enabled, other than the fact that the sensitivity "goes nuts"?  Does the cursor jump around erratically? All the time? Only when in heavy scenes? etc. Anything that can help me reproduce this problem on my end.

Also, if it is the overlay, more information about your system would be nice. For example, a DXDIAG would be helpful. (http://wizards.custhelp.com/app/answers/detail/a_id/1271)

I've tried to reproduce the sensitivity issue on my end, but I failed to do so. (Using both the 32-bit and 64-bit WoW clients...)
Is it possible the sensitivity issue you're seeing simply is that enabling the overlay causes performance to drop a bit, and therefore the cursor to not be as smooth all of the time? My FPS didn't drop between running Mumble with the overlay vs. without it -- but I was also using the new "1" quality level for this test.

If it's hard to pinpoint, a video showing the behavior you're seeing would be very helpful (and if it included an FPS counter from Mumble/WoW, even better!). You could use a capture program like OBS, or maybe even just shoot a video with a phone, showing the mouse sensitivity behavior you're seeing.

### WoW vs. Winhooks

There is a long-standing known issue where the mouse can act weird sporadically in WoW.
This can be helped by disabling one of Mumble's global shortcut backends, the one that uses global Windows hooks to capture global mouse/keyboard presses/clicks.

You can disable this backend using this .reg file:
https://mumble.info/reg/disable-winhooks.reg

And you can enable it again via:
https://mumble.info/reg/enable-winhooks.reg

**Comment by Malisent** [comment]
Thanks for the response.. I really appreciate it as I'd really like the over lay working!

1) I am not running Mumble at the default location.. I have Windows on one drive, my games and other software on other frives - so I will test this.

2) I do not run WoW as admin (at least nothing I do specially.. I just run it exactly as installed under bnet)

3) I tried this in both windowed and full-screen, so no change there.

4) When I say the mouse goes nuts.. it's like the acceleration is in over-drive.. the mouse-look is just crazy fast.   The cursor seems to be in a normal spot.. but the mouse-look is so super-fast that I can't focus on anything.  I'm not sure how to explain it well.. it's just the mouse movement is so sensitive that I'm looking at the ceiling, the floor.. all super fast.

5) DXDIAG: https://drive.google.com/file/d/0B1RRuc0e2E9kTG4yWlNOWVVwMFE/view?usp=sharing

6) I tried the winhooks regedit fix.. found it on another site.. no-go.

I'm thrilled to provide any more info you need.. thanks again for looking into it!  I have 2 computers with the exact same hardware, and this is only occurring on one of them.

**Comment by Malisent** [comment]
I'm also going to reinstall Mumble in the default location tomorrow to test that.  Again, thanks so much!

**Comment by Malisent** [comment]
Sorry it took me awhile to get back to this.  I uninstalled Mumble and reinstalled it on c:\ 

Same problem.. cannot use the overlay without the mouse-look craziness.

**Comment by mkrautz** [comment]
(This isn't related to the sensitivity issue.)

Sorry for the late answer. It sounds like your WoW is running as admin for some reason (which... isn't a problem -- but it isn't ideal; it doesn't run as that for me, for example.)

Where did you install Mumble on C: BTW? It has to be in "Program Files" or "Program Files (x86)" for Mumble to be able to use the UI automation feature of Windows. If not -- it make sense that it doesn't work for you yet.

**Comment by mkrautz** [comment]
(Sensitivity issue)

For testing, could you try running Mumble (w/ overlay) and WoW without these devices plugged in?

- DSP55 Adapter (Plantronics DSP55 Adapter)
- GWS IDI Device (https://www.gamingmouse.com/, Good Work Systems ... a pedal?)
- SB World of Warcraft Voice Tap

and see if it improves the situation? Just to rule things out.

**Comment by Krzmbrzl** [comment]
Does this still happen with Mumble 1.3?
