### ISSUE TITLE
Make hyperlinks on chat clickable

### ISSUE THREAD

**Issue by ghost** [mumble-voip/mumble#2488]
It is a bit annoying that when you send an URL on the mumble chat, you see it as a hyperlink which you can actually click and will open the website. However, the clients receiving the link do not show is as a hyperlink but as a plain text, and do not allow to click on it.

Could this functionality be added?

**Comment by LuaMilkshake** [comment]
This is caused by the server having `allowhtml` set to `false` in its configuration, which would have been changed from the default setting of `true`. If you're the server admin, setting this option to `true` will allow your users to send working links (in addition to any other HTML formatting).

The fact that you're seeing a working link locally and other users are seeing plain text happens because the filtering of HTML happens on the server, not the client. This also happens if you try to send formatted messages. There is a discussion about improving this UX at #2096.
