### ISSUE TITLE
BF4 Not Listed

### ISSUE THREAD

**Issue by srconner** [mumble-voip/mumble#2519]
BF4 shows supported here:  http://wiki.mumble.info/wiki/Games  But it does not show up on the list of plugins.

**Comment by davidebeatrici** [comment]
Are you using a snapshot release or a stable one?

**Comment by srconner** [comment]
Thanks! 
1.2.16 Stable release link from https://wiki.mumble.info/wiki/Main_Page.  
"https://github.com/mumble-voip/mumble/releases/download/1.2.16/mumble-1.2.16.msi"

**Comment by davidebeatrici** [comment]
The plugin for Battlefield 4 has been created after the 1.2.16 stable release, that's why you don't see it.
Also, the stable releases are x86 only, this means that they will not work with Battlefield 4 x64 or Grand Theft Auto V.
The best solution is to download the latest snapshot release, in order to have the plugins constantly updated :wink:

**Comment by srconner** [comment]
Thanks!

**Comment by davidebeatrici** [comment]
You're welcome, enjoy playing with positional audio :smile:
