### ISSUE TITLE
[Feature Request] Ubuntu Snappy Packaging

### ISSUE THREAD

**Issue by ksthiele** [mumble-voip/mumble#2533]
I just tried to install a Mumble Server on my Raspberry Pi with Ubuntu Core and was disappointed that I couldn't simply 'snap install mumble-server' on it

**Comment by mkrautz** [comment]
Yep, that'd be nice.

**Comment by hacst** [comment]
Snappy would be neat. I think we'll definitely have that for x64 going forward. I'm not sure how easy it would be to provide a armel version though.

**Comment by hbeni** [comment]
Hi, there is a snap available: https://snapcraft.io/mumble

:warning:  However, testing revealed that you cannot load plugins with the snap version.

**Comment by Krzmbrzl** [comment]
@hbeni this should be reported to https://github.com/snapcrafters/mumble/issues as the snap package is maintained externally. My guess would be on issues with snap's sandboxing that might get in the way of loading arbitrary shared libraries (plugins)...

In any case, this issue here can be closed as there is now indeed a snap package available.

**Comment by hbeni** [comment]
https://github.com/snapcrafters/.github/issues/12

**Comment by Krzmbrzl** [comment]
Why did you file the bug against the `.github` repository instead of the mumble one? :thinking:
