### ISSUE TITLE
Add devenv.exe (Visual Studio) to the default blacklist of the overlay

### ISSUE THREAD

**Issue by BrainStone** [mumble-voip/mumble#2571]
Having the overlay in Visual Studio (devenv.exe) is causing weird issues which show in the window not updating until it is resized.

**Comment by mkrautz** [comment]
Hi,

devenv.exe is in the blacklist for both 1.2.x and 1.3.x.

What might be happening here, is that the default blacklist in 1.2.x is used the default value for the blacklist setting in the client. That means that you'll only ever have the blacklist from the version you first installed.

That bug is fixed in 1.3.x though. The default blacklist is hard-coded and will *always* be present.

I believe clearing your existing blacklist should fix this...
We won't port the new behavior to 1.2.x, so I recommend you either get the new defaults by cleaning your own blacklist and letting Mumble populate it with the defaults -- or maybe by manually syncing your local blacklist with the latest one from 1.2.x: https://github.com/mumble-voip/mumble/blob/1.2.x/overlay/overlay_blacklist.h#L68

Thanks!
