### ISSUE TITLE
Mumble sends shout frame as last frame when you stop talking

### ISSUE THREAD

**Issue by TinyMan** [mumble-voip/mumble#2604]
On windows, with latest snap of 1.3 and previous also, when "**Voice Activity**" is selected as input source, and you have a shortcut for "**shout to current channel**".

After shouting to the channel at least one time, every time you **stop talking** (normal talking), the last frame (marked as last according to the proto) is also marked as **shout to the current channel**.

**Comment by mkrautz** [comment]
Probably caused by https://github.com/mumble-voip/mumble/commit/9d16137393bd8a33307cac41c0b55ea1392173a3

I'm not sure I understand the iPrevTarget logic, though...

**Comment by Krzmbrzl** [comment]
The code affected by the mentioned commit has changed now. Thus the question: Is this error still in Mumble 1.3?

**Comment by unterwulf** [comment]
I can confirm that this is still the case on the latest master. The problem is that once anything is shouted to a target, iPrevTarget is set to this target and never reset until next shout is performed. It is a pity because every single last frame of any speech (i.e. last before silence) is targeted to iPrevTarget instead of iTarget.

To be honest I personally couldn't hear that frame when I was trying, I just noticed it in the log of a server I am developing. So it is probably not a big deal from a practical point of view, but just untidy and 9d16137 was probably not worth it because it has (probably) fixed last whisper frame at the cost of broken last normal frame.

**Comment by Krzmbrzl** [comment]
Thanks for the info @unterwulf
