### ISSUE TITLE
No support for multiple OpenSSL versions

### ISSUE THREAD

**Issue by H2L29** [mumble-voip/mumble#2621]
hi :)

i use debian sid openbox

```
$ LANG="en_US.utf8" sudo gdebi Téléchargements/mumble_1.3.0~1650~g30c779c~snapshot-1~ppa1~xenial1_amd64.deb
Requires the installation of the following packages: libssl1.0.0
```

why 1.0.0?

```
$ ls -l /usr/lib/x86_64-linux-gnu/libssl.so
lrwxrwxrwx 1 root root 13 nov.   1 22:02 /usr/lib/x86_64-linux-gnu/libssl.so -> libssl.so.1.1

$ dpkg -l | grep libssl[0-9]
ii  libssl1.0.0:amd64                                                1.0.1t-1+deb8u5                             amd64        Secure Sockets Layer toolkit - shared libraries
ii  libssl1.0.2:amd64                                                1.0.2j-3                                    amd64        Secure Sockets Layer toolkit - shared libraries
ii  libssl1.0.2:i386                                                 1.0.2j-3                                    i386         Secure Sockets Layer toolkit - shared libraries
ii  libssl1.1:amd64                                                  1.1.0b-2                                    amd64        Secure Sockets Layer toolkit - shared libraries

$ dpkg -l | grep mumble
ii  mumble                                                           1.3.0~1650~g30c779c~snapshot-1~ppa1~xenial1 amd64        Low latency encrypted VoIP client

$ mumble
Found multiple libssl.so copies in binary: /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0, /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2
Found multiple libcrypto.so copies in binary: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0, /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.2
Aborting due to previous errors
```

why he no use standard `libssl.so` symlink? or just choice `libssl.so.1.0.0` marked as depend of the package?

hope this help to fix ;)

**Comment by mkrautz** [comment]
Your Qt is linked against one libssl, your Mumble is linked against another. We've decided not to support this configuration (multiple copies of OpenSSL loaded into the same process).

As you say, the mumble package you're using from Xenial seems to require libssl.so with soname 1.0.0.
This package expects that version of libssl that your Qt installation will try to load is also 1.0.0.

That's not the case for your system, and that's why you're getting the error.

**Comment by H2L29** [comment]
understand that but the logic isnt to use libssl.so symlink without depending of any fixed version?

**Comment by mkrautz** [comment]
No, the "libssl.so" without a version after it is from the development package, and is usually not installed on a user's machine.

See for example the libssl-dev package in sid:
https://packages.debian.org/sid/amd64/libssl-dev/filelist
It installs libssl.so.

And for OpenSSL, you can't avoid depending on a fixed version. It's not ABI stable, which is why you see .so.1.0.0, so.1.0.2, so.1.1, etc. on Debian.

**Comment by H2L29** [comment]
good to know, thanks

**Comment by EmperorArthur** [comment]
Ugh, reasons why Debian sid is annoying:

>Found multiple libssl.so copies in binary: /usr/lib/x86_64-linux-gnu/libssl.so.1.1, /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2
>Found multiple libcrypto.so copies in binary: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1, /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.2
>Aborting due to previous errors
>Aborted

This is on a fresh compile no less :/

**Comment by davidebeatrici** [comment]
Mumble builds and runs flawlessly with the check for multiple OpenSSL versions removed.
I'm going to do a PR as soon as possible.

**Comment by davidebeatrici** [comment]
The check code is at: https://github.com/mumble-voip/mumble/blob/master/src/SSL.cpp#L47-L94

**Comment by mkrautz** [comment]
With https://github.com/mumble-voip/mumble/pull/3109 and https://github.com/mumble-voip/mumble/pull/3174 landed, we can close this.
