### ISSUE TITLE
GlobalShortcutWin CreateDevice can fail with qFatal

### ISSUE THREAD

**Issue by Kissaki** [mumble-voip/mumble#2631]
As per [forum post](https://forums.mumble.info/viewtopic.php?f=4&t=3140&p=8163#p8162)
![i5ho4zt](https://cloud.githubusercontent.com/assets/93181/20146830/b591a8fe-a6a5-11e6-8020-b2a93a1f3e14.png)

---

Code: GlobalShortcut_win.cpp L507

As per Screenshot, the return HRESULT is 80004005

The error returns are one of DIERR_DEVICENOTREG
DIERR_INVALIDPARAM
DIERR_NOINTERFACE
, DIERR_NOTINITIALIZED
, DIERR_OUTOFMEMORY.

**Winerror.h defines for "unspecified error" #define E_FAIL _HRESULT_TYPEDEF_(0x80004005L)**

DIERR_NOTINITIALIZED is constructed with MAKE_HRESULT(SEVERITY_ERROR, FACILITY_WIN32, ERROR_NOT_READY)

1 << 31 | 7 << 16 | 21

**Comment by Krzmbrzl** [comment]
As the user didn't even reply to Kissaki's post on the forum there's not much we can do with the info at hand (IMO at least). Also this issue is several years old and it appears to not have been referenced anywhere since. Thus I'd say this error is not really happening a lot (if it even still exists in the current Mumble versions).

Closing until someone encounters it again
