### ISSUE TITLE
Murmurd crashes on FreeBSD 11 - base system/ports tree OpenSSL library clash

### ISSUE THREAD

**Issue by oppa1** [mumble-voip/mumble#2632]
I have attached the backtrace from gdb.
[gdb.txt](https://github.com/mumble-voip/mumble/files/581400/gdb.txt)

I'm not sure what's going wrong, it seems it crashes when verifying the certificate? It's definitely valid though. "openssl verify" is successful too.

**Comment by mkrautz** [comment]
Hm, this seems to be because you're linking against two different sets of OpenSSL libs -- one from ports in /usr/local/lib, and the FreeBSD base system's in /lib or /usr/lib.

From the stackstrace:

`#0  0x0000000800f1911d in OBJ_obj2nid () from /lib/libcrypto.so.8` (Base system's libcrypto)
[...]
`#4  0x00000008052635d8 in ssl_add_cert_chain () from /usr/local/lib/libssl.so` (libssl from ports)

Is this when using murmur from the ports tree, or a self-built murmur?
Is it 1.2.x or 1.3.x? In 1.3.x, we've added rules to ensure we link against the ports tree libssl. (And Qt should, as well).

**Comment by oppa1** [comment]
I'm using FreeBSD's binary package. This sounds an awful lot like:
https://svnweb.freebsd.org/ports?view=revision&revision=402103
I will investigate further when I have more time.

**Comment by mkrautz** [comment]
/cc @feld 

FYI

**Comment by oppa1** [comment]
I just upgraded. Seems like it's fixed in FreeBSD's murmur-1.2.10_3.
