### ISSUE TITLE
BF1 plugin is outdated

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#2660]
As mentioned by @xenadmin in #2643.

The BF1 plugin needs to be updated to the latest version.

**Comment by xenadmin** [comment]
Any news on this? 
FYI: There has been a new major update to version 121316
https://www.battlefield.com/news/article/giants-shadow-and-spectator-mode-in-new-update?setLocale=en-us

**Comment by mkrautz** [comment]
No one is actively working on it. @davidebeatrici doesn't have BF1, as far as I recall.

**Comment by davidebeatrici** [comment]
As @mkrautz said, I don't have the game yet.

I have access to an account that a player borrowed me in order to create the plugin.
The problem is that all of the memory addresses, except avatar position, can be reached only by using pointers, unlike previous Battlefield games, where most of the memory addresses were static.
Sadly it takes quite some time to update Battlefield 1's pointers.

I think that the best thing to do would be to ask DICE to implement native support using the Link plugin, so that we don't have to worry about game updates anymore. :wink:

**Comment by davidebeatrici** [comment]
Plugin updated in 4d3d4d86! :wink:

**Comment by xenadmin** [comment]
What is the estimated time frame for the Mumble team to release a new x64 Snapshot?

I would guess that there will be a January Patch for BF1, like there has been a November and December patch. I'm a little bit worried, that your work will be lost with the next update.

**Comment by mkrautz** [comment]
@xenadmin I've scheduled a new snapshot.

**Comment by davidebeatrici** [comment]
@xenadmin Probably the plugin will need to be updated, but don't worry. I will do it as soon as possible. :wink:

**Comment by xenadmin** [comment]
@davidebeatrici Today I did a test match with my friend. So far it worked for a complete match of conquest.
Yesterday two other firends of mine did a test without me, they reported that it stopped working after 10 minutes. 
I keep you informed about our further tests.

**Comment by davidebeatrici** [comment]
@xenadmin Thank you for the report.
Did the plugin unlink or was it just not working anymore?
