### ISSUE TITLE
Push To Talk sticking on / macOS

### ISSUE THREAD

**Issue by joepagan** [mumble-voip/mumble#2708]
On macOS push to talk seems to stay turned "on" once activated, I then have to push my shortcut again to turn it off.

Sorry if this is a dupe, couldn't see anything anywhere other than this very similar issue on ubuntu: https://github.com/mumble-voip/mumble/issues/1319

**Comment by mkrautz** [comment]
Which key are you using for PTT?

What version of macOS? What version of Mumble?

Thanks.

**Comment by lexbi** [comment]
Using Caps Lock
macOS Sierra 10.12.2
Mumble 1.2.17

Also I did the allowing mumble in accessibility area in security settings thing:

![image](https://cloud.githubusercontent.com/assets/2337910/21163226/bacd3258-c189-11e6-9edf-c8db5787201c.png)

**Comment by mkrautz** [comment]
It's because you're using Caps Lock. :-) When you turn it on, you transmit. When you turn it off, you stop. Other keys like it will behave the same way on macOS.

Can you confirm that other keys don't behave like this?

We should probably try to make Caps Lock behave the same across all systems.

Thanks.

**Comment by lexbi** [comment]
Oh my, yep, that was it! Works fine with CMD. Sorry used mumble for years with caps on windows didn't think that would be it!

Will have to reprogram my brain until then.

Thanks for letting me know!
