### ISSUE TITLE
make attenuation opt-in in default config

### ISSUE THREAD

**Issue by grindhold** [mumble-voip/mumble#2711]
My experiences with trying to convince people to use mumble instead of TS3 urge me to talk about the default config for the attenuation feature.

Every now and then, when I find myself the discussion over wheter we should use mumble or TS3 for a conversation and I win, someone has never used mumble and has to install it to take part in the conversation. Turns out, everytime this happens, people are annoyed by the automatically activated attenuation feature. The probably most annoying thing is, that configuring it is inside the "advanced" configuration menus and it's hard and non-obvious to get there as a first-time user.

Therefore i want the mumble community to rethink whether

a) attenuation should be disabled by default
b) it should be a feature that is to be configured in the advanced section of the config

I know that this is heavily biased, because of the small subset of people I know, but over the last two years it simply happened too often to stay quiet. You're scaring off a valuable potential userbase here.

**Comment by Lartza** [comment]
It's always weird that people hate attentuation since it's absence makes me hate TS3.

On-topic: Attentuation is enabled by default, but is a single checkbox in the **Audio Wizard**. You don't have to delve into advanced settings to configure it.

As a sidenote, I could be completely wrong, but I think there have been talks of removing the advanced settings alltogether and just have all options visible but not sure what those talks amounted to.

**Comment by Tarun80** [comment]
+1 to disabled by default and making it opt-in. I've had to tell people how to fix that because they express how they dislike it.

**Comment by Kissaki** [comment]
There's a typo in OP

> a) attenuation should be activated by default

should be "disabled by default", right? I'll change that.

**Comment by Kissaki** [comment]
Note that we have already enabled advanced config ("expert mode") by default, and are in the process of removing it altogether for 1.3.0.

**Comment by Kissaki** [comment]
Attenuating on own talking is disabled by default, and not in the audio wizard.
Attenuating on others talking is enabled by default in the settings, and available in the audio wizard, initially set as per the setting, and on changing the output system set according to the availability of attenuation functionality.

Lartza said he prefers it enabled, so I wonder how many people actually prefer it enabled, and how many would only learn about it if it is enabled by default.
Nevertheless I feel like disabling it is a saner default - in large part due to my own preference.
If we think about our focus group - gamers - I don't think attenuating a game when you're making shotcalls in a competitive game is what you want. It may be a viable use case there and elsewhere, but typically I would expect voice activation or PTT and echo cancellation to be set up in a way that sound being picked up (too loud) should not be a problem. I have been using voice activation with speakers for a long time, and rarely got people complaining (only after I had turned up the volume to non-my-standard volumes).

So I would agree in that the default should be disabled.
