### ISSUE TITLE
Audio input volume adjustment

### ISSUE THREAD

**Issue by CanadianJeff** [mumble-voip/mumble#2729]
the setting to adjust the volume for input is missing

Windows Client 1.12.18

**Comment by mkrautz** [comment]
That feature is only available in 1.3.0 (Development Snapshots).

**Comment by mkrautz** [comment]
Sorry, I misread and mistook this for user volume adjustment. My apologies.

**Comment by Kissaki** [comment]
I don’t think this is something we want.

You said missing, that implies it would be standard practice, otherwise expected, or already was in Mumble in the past. As far as I know that is not the case though?

Audio input is very different from audio output in that the input is one source used by potentially multiple consumers. Audio output on the other hand is multiple applications, that may need to be adjusted individually.

This difference can be seen in the windows volume mixer. The input has only one volume adjuster on the recording device, not even a volume mixer. Output on the other hand has a volume mixer with overall volume and individual channels per application.

Adding an input volume adjustment into Mumble would add confusion. E.g., if either one of the volumes is 0, the input would not work, but it would not be clear to the user where to look.

If we can use WASAPI to adjust the input volume this could be a good feature. I am not sure that exists though, as there is no input mixer. Doing it per device would be possible, but we'd have to handle boost etc as well, and I'm not sure about that.

Mumbles output adjustment currently does not change the windows mixer application channel volume, which is a missing feature that was never implemented after the original behavior from XP which had no application channels. At that time, application specific volume was the only way to adjust individual application volumes adequately. Now that windows provides such a mixer, the two volume settings should be linked.

Coming back to the input, just like windows has no mixer for the input, I'm not sure we want/need one in Mumble. Of course, it could be helpful for users not to have to search for and use the system volume device settings. We already display the volume with voice activation. And we also provide amplification - whichs effect is not really visible in the settings.

**Comment by Kissaki** [comment]
To compare to other applications:
* Steam has a separate input volume setting
* OBS has a separate input volume setting

After writing the above, and seeing it elsewhere, maybe it would not be so unexpected or confusing after all.

**Comment by CanadianJeff** [comment]
discord has it

http://i.imgur.com/zboyRsK.png

**Comment by CanadianJeff** [comment]
curse voice has it

http://i.imgur.com/yCEF4j4.png

**Comment by CanadianJeff** [comment]
why should mumble be any different and why would it be so difficult to implement

**Comment by Kissaki** [comment]
> why would it be so difficult to implement

I didn’t say it were difficult. Nor do I know how much work it would be. I didn’t manage to code anything for Mumble in recent times, so yeah, even easy may not be done soon.

**Comment by rtm125** [comment]
Maybe I'm just dumb but where can I find the download link for 1.3? I run the server on my home server for me and a group of friends and although long time users of mumble. We really hate the inability of not being able to adjust the user volume on the individuals end. I read on your wiki its in 1.3 but cant find the download anywhere. I need the server and client version. please and TY

**Comment by mkrautz** [comment]
I'll just summarize the (heated) conversation from IRC:

@CanadianJeff's problem was that he is using a third-party piece of software for Android that allows him to use his phone as a microphone. WO Mic: https://play.google.com/store/apps/details?id=com.wo.voice&hl=en. When using that, the virtual device doesn't respect the input volume set in Windows.

(Also, it seems like there's a Pro version of WO Mic which *does* allow the volume to be set... Sigh.)

Personally, I'm not against adding a hidden config option audio input volume.

**Comment by CanadianJeff** [comment]
closing this issue because no longer use mumble feel free to reopen
