### ISSUE TITLE
Mumble locks up after a few hours of being open on Win 10

### ISSUE THREAD

**Issue by raiscan** [mumble-voip/mumble#2842]
In the last few snapshots on Windows 10, I've had issues with Mumble's UI freezing up after a few hours of being connected. I can still receive incoming voice (at least on two occasions) but I cannot speak back, or use the UI as the program has frozen up. This has only started happening in the past week or so.

**Comment by mkrautz** [comment]
Hi raiscan -- if it happens again, could you try to create a dump for us to analyze?

You should be able to do it via the task manager, similar to this:
<img src="http://www.wintellect.com/devcenter/media/Default/Blogs/Images/jrobbins/061710_2204_howtocaptur1.png" />

Since this dump is a full dump, it might contain sensitive information such as your certificate/private key for your client cert, so don't post it online for everyone to see. But feel free to link me to a privately hosted copy, if possible: mikkel@krautz.dk.

You can also create a "mini"dump, for example via Process Explorer. See:
http://www.wintellect.com/devcenter/jrobbins/how-to-capture-a-minidump-let-me-count-the-ways

That might be more managable to send to us (since the file will also be smaller). Thanks!

**Comment by mkrautz** [comment]
I received a dump from @raiscan.

The freeze is in Bonjour:

![image](https://cloud.githubusercontent.com/assets/36527/22953280/ca4ad5c4-f310-11e6-920b-4d0cde0518e3.png)

**Comment by dstensnes** [comment]
is anyone really using this bonjour stuff in mumble?

**Comment by mkrautz** [comment]
@dstensnes you're probably right that it doesn't have wide use.

@raiscan Do you have an idea on how to reproduce this? The hang is inside Apple Bonjour DLL, so we can't really easily figure out what's going on in there.

Is this with the connect dialog open, or not? If not, then it must be a quite pecuilar bug, since I don't think we do any Bonjour things when it isn't open.

**Comment by raiscan** [comment]
@mkrautz I neglected to mention that it was a Windows 10 Insider Preview build. I have since rolled back the build, and no longer have any issues with mumble.

I think it's probably wise I close this,  as I can no longer reproduce the issue and it doesn't seem to be related directly to mumble. Sorry for the trouble!
