### ISSUE TITLE
Can't minimize to tray after restoring from tray

### ISSUE THREAD

**Issue by sztanpet** [mumble-voip/mumble#2892]
Build: `1.3.0~1937~g289d0d4~snapshot`
OS: win10 64bit

I have the setting "Hide in tray when minimized" checked.
The problem:

- minimize mumble, it minimizes to the tray, everything is okay
- now click the tray icon, mumble restores, everything is still okay
- now click the tray icon again, expecting mumble to minimize to the tray again and it does not happen (single or double click does not matter)

This was the behavior of 1.2.19, so I am guessing this must be a bug (or maybe my expectations are flawed).

**Comment by Kissaki** [comment]
I can confirm clicking or double clicking the tray icon does not minimize (doing the other steps before is not a requirement).

The code in question is [MainWindow.cpp#L3044](https://github.com/mumble-voip/mumble/blob/5e7cbcacb0a131b9d279d1e965be61653d445445/src/mumble/MainWindow.cpp#L3044).
For 1.2.x [MainWindow.cpp#L2569](https://github.com/mumble-voip/mumble/blob/1.2.x/src/mumble/MainWindow.cpp#L2569).

Commits making the changes: 694dca851b47e33b7bf09fdcd0b4ee583b934206 06d9f7e6d0ab6081393d4169a10de7ad84010cc3 (a120c8eb28c0dfcdfdb0981c63147bb37d45df2c + revert 7d434bbfa5df0024c021d2647eb603a5947c6ec7).

**Comment by Kissaki** [comment]
Commit 06d9f7e6d0ab6081393d4169a10de7ad84010cc3 deliberately makes this change.

> Always just give focus to mumble when the tray icon is clicked
instead of trying (and failing) to replicate task bar entry
functionality. This is much more in line with how other programs
use the tray icon.

Although I don't really get what "task bar entry functionality" refers to here. I'm also not sure that is more like "other programs use the tray icon". I'd rather refer to guidelines rather than subjective impressions on what the consensus is. From my current tray icons: HexChat toggles between minimizing and showing, Aimp2 singleclick for play/pause and double click for show/hide; notably Windows Defender double click toggles between show/hide. So I don't think the assumptions are correct here.

@hacst what do you think?

**Comment by Krzmbrzl** [comment]
It appears to me as if this has been reverted as this is the current state:
https://github.com/mumble-voip/mumble/blob/1f21debd2e7f614c013adf155c6afe98d2f16551/src/mumble/MainWindow.cpp#L3117-L3129
