### ISSUE TITLE
Add "privacy mode"

### ISSUE THREAD

**Issue by bontibon** [mumble-voip/mumble#2899]
Creating a separate issue for what was mentioned by @mkrautz in https://github.com/mumble-voip/mumble/issues/2893#issuecomment-283485563:

> we should probably consider the fingerprinting possibilities with all the user-specific things we're sending to the server (OS, language, etc.)

**Comment by Kissaki** [comment]
What do you mean by "add privacy mode"? Are you suggesting an option/a setting to not send some information to the server?

**Comment by bontibon** [comment]
@Kissaki Correct. Current identifiable information sent is:

- Client release
- Client OS
- Client OS Version

Language would be included included when #2893 is implemented.

Depending on how such a mode is designed, maybe it should toggle "Disable image download", to prevent someone's IP from being extracted from a non-admin.

**Comment by Piratonym** [comment]
I believe this issue can be closed. #3009 implemented a "privacy mode" for the details sent to Mumble servers, #3015 is supposed to do the same for HTTP requests.

Client version/release information is currently not removed, since the Mumble server seems to use it for some decisions (see e.g. src/murmur/Messages.cpp, search for "uiVersion"). This alone should also not reveal much or make users identifiable. Feel free to check if this information could still be at least partly removed (e.g. remove release but keep version).

The "Disable image download" option is not automatically toggled.

**Comment by Piratonym** [comment]
I think this issue can be closed. #3009 implemented a "privacy mode" for the details sent to Mumble servers, #3015 is supposed to do the same for HTTP requests.

Client version/release information is currently not removed, since the Mumble server seems to use it for some decisions (see e.g. src/murmur/Messages.cpp, search for "uiVersion"). This alone should also not reveal much or make users identifiable. Feel free to check if this information could still be at least partly removed (e.g. remove release but keep version).

The "Disable image download" option is not automatically toggled.

**Comment by bontibon** [comment]
Closing, as external image support has been removed and transmission of OS information can now be toggled.
