### ISSUE TITLE
Add a context menu for channels "links" in log view.

### ISSUE THREAD

**Issue by Natenom** [mumble-voip/mumble#2961]
Currently there is a context menu for users only, but not yet for channels.

A context menu would help for example to follow another user who joined another channel.

Also left click on a user focuses him, this sould be the same for channel links.

**Comment by Krzmbrzl** [comment]
I do have a context menu for channels. Was this added in the meatime or do you need something specific from it that it can't do atm @Natenom?

**Comment by rgarrettrun** [comment]
Hello, I am a student looking to contribute to my first open source project for software engineering class. Would I be able to take this problem, and would you mind helping to walk me through what needs to be done?

**Comment by Krzmbrzl** [comment]
@rgarrettrun you commented the same on #5362 - do you intend to work on both issues?

**Comment by rgarrettrun** [comment]
@Kissaki sorry about commenting on both. I intend on only doing one of them. Which one would you recommend for a first time contributor?

**Comment by Krzmbrzl** [comment]
@rgarrettrun I'm not Kissaki ^^

>  Which one would you recommend for a first time contributor?

It depends on what you want. If you want something that actually involves programming, then this is the one to go. If you just want to make a contribution in general (to see how things work), the other one can probably be done faster.

**Comment by rgarrettrun** [comment]
@Krzmbrzl I see. sorry for all the questions and thanks for the help, what programming language would this be in, C++ right? I only have 2 days to get this done, would that be a reasonable amount of time to do this one?

**Comment by Krzmbrzl** [comment]
Yes C++ is what we use here. How long it takes to implement this issue here largely depends on your background. For me I would estimate that this issue would probably take about 1-2 hours or so (maybe even less) but I know the source code and have been programming with C++ and Qt for several years now.
If you know your way around C++ and Qt and are confident in understanding existing code, I think it should be doable to implement this within 2 days. If on the other hand you don't have experience with C++, this might not be enough.

So my recommendation here would be: Unless you already have the needed skills, #5362 is certainly the safer choice, if it has to be done within 2 days.

**Comment by rgarrettrun** [comment]
I have a good amount of experience with C++ but have not used Qt before. I think I will try this one then. What are the details on what needs to be done?

**Comment by Krzmbrzl** [comment]
You'd have to track down where the existing functionality for users is located and then mirroring that for channels should be relatively easy. I currently don't know where the corresponding code lives, though. Presumably somewhere in `src/mumble/MainWindow.cpp`. That class already has a few context-menu related functions. You's have to check though, whether these are also triggered for this case here.
