### ISSUE TITLE
Allow Mumble to record directly to the MP3 format

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#3079]
cardpuncher mentions on IRC that it would be nice if Mumble could record directly to MP3 format, now that some(?) of the MP3 patents have expired, and the MP3 patent pools have been disbanded.

**Comment by mkrautz** [comment]
> `20:59:41 <cardpuncher> Thanks mkrautz :) AFAIK, *all* the patents have expired and Fedora will soon get full support (encoding, decoding was already included). See https://linux.slashdot.org/story/17/05/06/0055200/fedora-will-get-full-mp3-support-as-iis-fraunhofer-terminates-mp3-licensing-program`

**Comment by TheAssassin** [comment]
@mkrautz *all* the MP3 patents have expired. The patent holders decided to not extend the few remaining ones. Details can be found on the page of Fraunhofer IIS https://www.iis.fraunhofer.de/en/ff/amm/prod/audiocodec/audiocodecs/mp3.html. MP3 is now officially a *free standard*.

Most devices have always included a license for MP3 patents, though, so that wouldn't have been an issue I guess. Especially in private area, where patents are pretty useless in many states anyway, you wouldn't have to worry either. Also, dynamically linking to LAME would've solved the issue as well I guess, if the distro doesn't come with it, you can't encode, otherwise it's up to the user to make the choice.

**Comment by hacst** [comment]
Should be trivial once https://github.com/erikd/libsndfile/issues/258 is completed. We use libsndfile for encoding the recordings.

**Comment by Krzmbrzl** [comment]
Sure, feel free to create a PR. We only have to check the library's version during build and then conditionally enable the code for MP3 encoding based on that. That's what we do with the Opus file format already, so shouldn't be a big deal.

**Comment by cardpuncher** [comment]
On 25.04.2023 21:37, Robert Adam wrote:
> Sure, feel free to create a PR. [...]

Thanks for your reply. The thing is, I'm just a translator, not a 
programmer, I'm not comfortable enough to create a PR for Mumble. 
Hopefully you'll consider this feature request.

**Comment by Chinry** [comment]
Is help still needed on this issue? I can take a look.

**Comment by Hartmnt** [comment]
> Is help still needed on this issue? I can take a look.

Yes, as far as I can tell nobody has started working on that, yet :)

**Comment by Chinry** [comment]
@Hartmnt I'll start working on it.

**Comment by cardpuncher** [comment]
Thanks to everyone involved for adding this feature. IMHO this ticket can now be happily closed. The French translation was just updated with the sentence related to MP3 recording btw :)
