### ISSUE TITLE
How to compile Murmur statically?

### ISSUE THREAD

**Issue by felixsinger** [mumble-voip/mumble#3081]
I'm using Arch and I want to compile Murmur statically. How can I do that?

Sorry for this unnecessary question, I already studied your build scripts but got nothing helpful.

**Comment by mkrautz** [comment]
What would the purpose be?

We don't provide truly static builds, so there is no magic switch to flip.
(Our "static" Linux builds are packaged with Magic Ermine. It's a dynamic build packed into a single executable that is very portable due to being linked against a quite old version of glibc.)

You should be able to achieve what you want if you build static version of all of Murmur's dependencies, and link against those. It's possible you'd need to do a few build system changes as well.

On a related note, @lexesv has a static build of Murmur based on Alpine Linux. See https://github.com/mumble-voip/mumble/issues/2721#issuecomment-283506828
Might serve as inspiration.

**Comment by felixsinger** [comment]
Because of various reasons I decided to try Arch as server system for some VMs. I know it's very controversial (because of the frequent updates), but I want to give it a try.

I would like to have a Murmur build which is so minimalistic as possible. So I don't want to recompile Murmur after each little update of openssl or protobuf or whatever :)

**Comment by mkrautz** [comment]
But that's exatcly what you'll have to do if you build a static Mumur? I'm confused.

**Comment by felixsinger** [comment]
Umm wait... I want to put all libraries needed by Murmur in one file, and also Murmur of course. So if I get an openssl update for my Arch system I don't need to recompile Murmur because all is built in one executeable file. That's what I understand under "static linking".

**Comment by mkrautz** [comment]
I understand. But that means Murmur will not get the OpenSSL update. Is that really what you want?

**Comment by mkrautz** [comment]
Right, I see your note about security -- so ti is what you want.

**Comment by lexesv** [comment]
Hello!

Very difficult build Murmur statically using Arch.
To do this, we need an environment that is built on the musl-libc.

But you can create it. Example:
https://jstrapko.github.io/musl-gcc/

However, best way is Alpine Linux.

Murmur used libc + dynamic linker ld-linux
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fbe90f3f000)
/lib64/ld-linux-x86-64.so.2 (0x0000558e0c3f0000)
And you can not get around this without using musl libc.

My last build with Zeroc ICE, D-BUS, MySQL and PgSQL support.
Also built a static mumble (client)
https://github.com/lexesv/static-murmurd/tree/master/distro
https://github.com/lexesv/static-murmurd/blob/master/files/mumble2017-05-09_12-33-41.png

**Comment by felixsinger** [comment]
I decided against this solution. As far as I know if it's dynamic linked every system update could break Murmur and it would crash until I recompile it against the new headers. So I decided to write some scripts which hooks into pacman and detect dependency updates. If dependencies of Murmur are detected it recompiles the software, repackages it and puts the new version into the repository.

This seems to be the cleanest solution for me :)
