### ISSUE TITLE
Overlay not working for FFXIV.

### ISSUE THREAD

**Issue by Meier23** [mumble-voip/mumble#3103]
Mumble overlay no longer working for FFXIV since the creator update.

**Comment by Kissaki** [comment]
In order to be able to work on this we will need some information:

* Is this still the case? (in Mumble stable release/1.3)
* What Direct3D API does FFXIV use? Did this change with the creator update?
* If not, what changed with the creator update (specifically regarding technology or rendering)
* Does the debug output log print out issues?
* If it does not, maybe it does with a `debugoverlay` file next to the running, rendering game executable
