### ISSUE TITLE
Use Qt Installer Framework instead of WiX Toolset

### ISSUE THREAD

**Issue by davidebeatrici** [mumble-voip/mumble#3104]
My proposal is to use [Qt Installer Framework](http://doc.qt.io/qtinstallerframework/) instead of [WiX Toolset](http://wixtoolset.org/).

- Solves the majority of problems the installer has right now.
- It's cross-platform.
- It can be built with MinGW.
- It's heavily customizable.

**Comment by mkrautz** [comment]
> Solves the majority of problems the installer has right now.
How do you know? Did you build a QIF-based Mumble installer package? PR please :)

> It's cross-platform.
We only need an installer for Windows.

> It can be built with MinGW.
I believe you mean that we can build the final installer on non-Windows systems.
That's obviously nice, but not a strict requirement for us at present.

Right now, we use MSI because it's the standard on Windows. Windows admins like it because it ties into their existing tools, i.e. you can easily remote deploy via group policy.

Also, for this proposal to be sensible, we would also need a plan for how to migrate our installer translations to the new system.

Personally, I'm inclined to stay with MSI/WiX. 1.3.0 will definitely use MSI -- we'll just have to fix as many of the bugs we can.

**Comment by Kissaki** [comment]
> Solves the majority of problems the installer has right now.

Huh. Which ones do we have? Which ones does it solve? What new issues will we introduce?

**Comment by Kissaki** [comment]
This discussion does not currently seem to go anywhere. A suggestion was made, which was put into question, but never discussed/answered. So closing this.

We can always reiterate when we have more substantial reasoning/arguments (and time to actually make a switch).
