### ISSUE TITLE
Update to Opus 1.2: Several relevant improvements

### ISSUE THREAD

**Issue by Cormak** [mumble-voip/mumble#3139]
https://people.xiph.org/%7Ejm/opus/opus-1.2/

Quality improvements, less CPU, fullband audio at 16kbps? 

The sooner this is incorporated, the better.

**Comment by Damianuscz** [comment]
!!!UP

it is fck amazing. Super quality with lower bit and cpu 🐙

**Comment by Kissaki** [comment]
Note: 

> For Windows users, the main change in version 1.2 is that the build process now produces a single library (opus.lib) rather than multiple libraries for SILK, CELT, and so on. This should make it easier to deploy applications based on Opus.

**Comment by Kissaki** [comment]
@Damianuscz Thank you for your input, but please use the "thumbs up" reaction emoji to vote on issues you feel are important (otherwise tickets will get flooded with "me too" comments and the actual discussion is lost/less followable). Of course, if you want to emphasize something specific more elaborately than it has before, you are still more than welcome to.

**Comment by davidebeatrici** [comment]
PR at #3148.

**Comment by davidebeatrici** [comment]
New snapshot with Opus 1.2.1 available!

**1.3.0~2458~g176c041~snapshot**

**Comment by Damianuscz** [comment]
For use opus 1.2.1 with snap 1.3 need i server upgrade?

**Comment by davidebeatrici** [comment]
No, Opus 1.2.1 is available to every user with the latest snapshot.

**Comment by mkrautz** [comment]
Davide updated it, let's close this.
