### ISSUE TITLE
SQLite error on murmur launch

### ISSUE THREAD

**Issue by frollard** [mumble-voip/mumble#3142]
after reboot getting a murmur launch error about the sqlite database attempting to write to a readonly table. 
![image](https://user-images.githubusercontent.com/1535306/27520212-273a237a-59c3-11e7-9e50-3e7025da9c63.png)

I can successfully launch by deleting (backed up) database, but of course lose my everything.  Tried reinstalling, and windows permissions aren't read only.

Edit: works if I launch murmur.exe as administrator. Have never needed to do this.

**Comment by Kissaki** [comment]
How did you restart murmur? Did you kill it? Did you do a hard system reset (power cut off/no shutdown sequence)?

Is the file read-only (windows file properties)?

**Comment by frollard** [comment]
Apologies for slow response. 

Standard restart of windows, launched murmur manually on launch. I have a (separate) issue where if I autorun murmur then it loads before windows has a proper network connection and murmur never latches onto the correct network adapter and cannot be connected to.  -- aside aside, Manually launch murmur after the reboot and it wouldn't have any of it.
Eventually solved with running murmur.exe as administrator where windows complained with UAC window about 'murmur can change your computer'...accept and it works.  Now launching murmur always pops that window regardless of asking for admin access, but it works.

**Comment by Kissaki** [comment]
> as it's running on C:

note that since windows 8 permissions are restrictive, specifically in the c:\program files folders. A standard user does not have write access in these folders. Could that explain your issue?

Generally, while running programs as admin works around permission issues, that’s not a real solution. Programs run under a user account with less permission for a reason.

I’d advise you to check the user file permissions specifically.
Move the file somewhere the user can write, or give adequate permissions.

Strange that a new sqlite file works (in the same place?). Did you change the default permissions?
Or will it save to the virtualstore (a folder under the user folder to emulate the program files folders)?

If this is indeed the issue I guess the error is not very user friendly. Maybe Murmur could check on startup and give an adequate error if it can not modify the sqlite.

I still don’t know whether this is a sqlite file permission issue or sqlite data/locking issue. Given that running it as admin works indicates a windows file permission issue.
