### ISSUE TITLE
mumble.info doesn't have content, it should redirect to wiki imo

### ISSUE THREAD

**Issue by C0rn3j** [mumble-voip/mumble#3155]
https://mumble.info/
https://www.mumble.info/

Both should redirect to the same in my opinion, can it be made such?

**Comment by davidebeatrici** [comment]
Yes.

There's also another problem: http://wiki.mumble.info/wiki/Main_Page doesn't redirect to https://wiki.mumble.info/wiki/Main_Page.

**Comment by hacst** [comment]
Thanks for the reports. https://mumble.info now should behave the same as http://mumble.info w.r.t to redirects. This means it redirects the root / as well as /security/ . Due to legacy support reasons (some API endpoints are still on there) it cannot behave the same as www.mumble.info . I also changed the wiki to always redirect to TLS.

Please let me know if you notice any issues with the new configuration. Thanks again.
