### ISSUE TITLE
You still with mumble?

### ISSUE THREAD

**Issue by hdcd10** [mumble-voip/mumble#3215]
Mumble app will still in development? and why dont have Smite overlay?

**Comment by Kissaki** [comment]
Hey @hdcd10,

yes, Mumble is still actively being developed. If you are talking about the desktop app we are trying to get the 1.3.0 version ready to release with numerous new features.

If you are still on a 1.2.x version you can download a 1.3.0 development snapshot from mumble.info to get new features already and help test (report issues if they arise).

You can also see recent changes to the next feature release at https://github.com/mumble-voip/mumble/commits/master

Historically, our Overlay worked fine in SMITE for a long time, until they added EasyAntiCheat as their anticheat software. Since then it mostly no longer worked, but briefly worked between SMITE updates from time to time (as far as I remember). Unfortunately this is out of our control. I initially contacted Hirez about that when they added EAC, but that has been a long time ago (last year?).
