### ISSUE TITLE
Mumble freezes audio after settings change under FreeBSD

### ISSUE THREAD

**Issue by xanderio** [mumble-voip/mumble#3278]
When i change my setting and apply them.  Mumble do no longer process any audio from to mic. The Audio level indicator freezes and i can no longer speak to other people. This may have to do with OSS, but i don't have that great of a understanding of ether Mumble or OSS.

Mumble Version: 1.2.19_3
FreeBSD Version: 12-Current

If you need any other system information I'm happy to provide them.

**Comment by Chris2000SP** [comment]
I have the same problem and get this output:
OSSInput: Failed to open /dev/dsp2.vr0
@Xanderio can you confirm this by start mumble in terminal?

**Comment by Xanderio** [comment]
I can confirm this on my machine.

**Comment by Chris2000SP** [comment]
I have tested a little bit with Audacity, and if i switch the source to an other device and then switch back i get also a Failure. Maybe it has to do with OSS or something. If that is so mumble is not the problem i think.

**Comment by Chris2000SP** [comment]
I have found a workaround. I use Jack audio to use Mumble with the new 1.3.0 version in ports. Install qjackctl and Compile Mumble with Jack support.

You have to edit the Makefile in ports: Edit in variable "CONFIG" the value "no-jackaudio" and change it to "jackaudio". Done

Jack can be run on OSS with no RT and no latency difference.

I had to change in Jack the Input device by putting "/dev/dspX" in the Advanced tap on my Laptop.

Now i can run "mumble -m" for running multiple mumble windows, and use other Jack audio compatible software to route on Jack. :-)

**Comment by Chris2000SP** [comment]
I have opened a bug report on Freebsd Bugzilla:

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=237168

**Comment by Chris2000SP** [comment]
I make a tutorial to use mumble with audio/jack:

Install audio/qjackctl
With Ports:
`# cd /usr/ports/audio/qjackctl/ && make install clean`
With PKG:
`# pkg install qjackctl`

Install audio/mumble
`# cd /usr/ports/audio/mumble`
`# make config`
with arrow key down to "JACK" mark it with SPACE and press ENTER to continue.
`# make install clean`
let it compile. (`make -j4` didn't work for some reason)

Start Jack:
`$ qjackctl`
Press Play (if the defaults are set. more downwards)

Start Mumble:
`$ mumble`
Go to Preferences and set "System" to "JACK" on Audio Input and Output. Press OK. Now you're using JACK in mumble.

Set different Source in Jack:
Make Sure Jack is Stopped in qjackctl.
Press the button for Preferences.
Go to "Advanced".
On "Input Device" i have put `/dev/dsp2.vr0` for my mic.
Press OK.
Start Jack.
Start Mumble with Jack set.

Finished.

I hope its useful but to compile mumble with Jack please make sure you have this patch:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=240402
otherwise you have to edit the Makefile.

PS: you can use jack to route your audio.

**Comment by Krzmbrzl** [comment]
Does this issue still occur with the latest release?
