### ISSUE TITLE
Feature Request: Possibility to block clients by certain traits like operating system

### ISSUE THREAD

**Issue by commel** [mumble-voip/mumble#3348]
I would love to be able to block clients by certain traits e.g. operating system.

**Comment by bontibon** [comment]
This seems like a limited-used feature that I don't see us adding.

Perhaps a broader request would be to expose the client's Version message to the ICE and gRPC authenticators.

**Comment by mkrautz** [comment]
I mostly agree with @bontibon.

@commel It would help if you could elaborate on your use case.

**Comment by commel** [comment]
Yes of course, a broader approach would fit for more use cases. Just put it here as a reminder. 

My use case: I am running a open mumble server for a linux community. More and more windows clients are connecting and I want to offer the resources I use for this mumble server for linux gamers.

I would love to offer the pull request by myself, given some hints where to look and navigate through the source code and also what would be the desired approach by the mumble developers.

**Comment by Kissaki** [comment]
I would imagine a Linux community be interested in Windows users as well that are interested in switching, or the technical issues and solutions they might or might not have when switching, or have on a different PC that has Linux installed.

Is that not the case? Or are those Windows users mostly not actually interested in Linux - so it's more of an issue of people connecting while being out of focus of the community and server? And you're willing to block those out that are genuinely interested?

**Comment by Kissaki** [comment]
I would also like to point out that 1.3 has a client side setting for not sending OS information to the server at all (for privacy). Those would be blocked out as well.

We should also be aware that such a check can only reliably work for conformant clients. Self compiled and adjusted clients could send fake information.

**Comment by commel** [comment]
We don't want to block anyone, but users that are not interested in Linux but are interested in using our resources to have a free mumble server are considered leechers and not very much welcome. Also I would tolerate them if they wouldn't outnumber the regular linux users on the server now.

I am aware that user's clients can send their own version of client information but as this would require recompilation i think it is neglectable.

What about a broader approach by allowing a regex to be matched on the client information string?

**Comment by hacst** [comment]
Personally I don't think this is a feature I consider useful/healthy in core. How do these users actually find your server? The servers listing themselves in our public list are intended to be...well...public. Which is why murmur won't let you list the server if you set a password.

More generally speaking I see no problem with giving an authenticator access to all information we have on a client at the point of authentication. As the os string is part of the [version exchange](https://mumble-protocol.readthedocs.io/en/latest/establishing_connection.html#version-exchange) it is available then. Our current authenticator interface doesn't offer that information though.

Now with regards to UX I think currently authenticators don't allow returning a reason from an authenticator (while our protocol [allows for one](https://github.com/mumble-voip/mumble/blob/master/src/Mumble.proto#L71) which is unfortunate (though I guess you would offer a "password as a backup" option anyways or something like that).

**Comment by Ytmndissue** [comment]
I'm sure you could easily implement something to look at that client info, but provided that info can be "hidden" on behalf of the client, or just straight up spoofed - I don't really see the point.

**Comment by commel** [comment]
I agree this does not lead to anything useful. Thanks for discussing this!
