### ISSUE TITLE
Debian packaging scripts

### ISSUE THREAD

**Issue by felixsinger** [mumble-voip/mumble#3400]
Hi,

I experimented a lot with Debian packaging in the last days and for myself I adjusted the packaging scripts of Mumble 1.2.18 from the Debian repository to work with Mumble 1.3.

However, if you are interested I would create a pull request to share it with you :)

**Comment by felixsinger** [comment]
Great :) I will do this on the weekend.

**Comment by davidebeatrici** [comment]
Thank you very much! :)

**Comment by felixsinger** [comment]
I'm just thinking about how to manage the packaging scripts for Debian based systems.

I don't know how you handle Ubuntu PPA packaging. I found [mumble-ubuntu-ppa](https://github.com/mumble-voip/mumble-ubuntu-ppa), but it seems not really maintained.

I think it's better to create a dedicated repository for Debian based packaging, with dedicated branches for each <distro-version> and just link with git submodules one of them into the Mumble master branch. So it's possible to switch between them.

In my opinion this is better, because different versions of Debian could have different dependencies (like a package merged with another one), debhelper compatibility level, dependency versions and what not. And it's not given that Ubuntu has the same dependencies as Debian, so we also need dedicated branches for Ubuntu.

This is just to make sure that people can build Mumble master as well on Debian as on Ubuntu.

**Comment by felixsinger** [comment]
What about it now?

**Comment by Kissaki** [comment]
The mumble-ubuntu-ppa repository contains our builds scripts for packaging mumble source packages prepared for uploading to Launchpad/the Ubuntu PPA - which then builds it.

As Ubuntu uses deb packages the tooling should be similar - the preparation actually runs lintian which seems to be configured for debian, and warns about unknown distro versions (when they are Ubuntu versions).

The scripts have a backports folder which adjust the build and package recipes for the corresponding distro versions - e.g. by replacing packages that we depend on to their corresponding names on that version.

I'm not sure what you have for debian, but something similar probably makes sense. Upstream probably has some build scripts already, the maintainer of the debian package. Did you base your scripts on that?

**Comment by Kissaki** [comment]
Ups, didn't mean to close.

**Comment by crknadle** [comment]
Just to mention: I just uploaded mumble 1.3.0~2868~g44b9004+dfsg-1 to Debian experimental yesterday, which should be useful for looking at some of the packaging. There are some particular Qt5 quirks, and I was able to make improvements to the build hardening.

**Comment by Kissaki** [comment]
@crknadle where would we find those?

**Comment by crknadle** [comment]
Jan Klass:
> @crknadle <https://github.com/crknadle> where would we find those?

It took me a while to respond to this email because I had these notifications
from github being filtered into a folder automatically, because most of the time
the notifications are things that I find inactionable.  I'm able to respond
faster if I'm emailed directly so that the mail goes to the Inbox.

I'm not sure which packaging scripts you're referring to.
The normal packaging scripts are the debian/rules file within the Debian package
for Mumble.  The Git repository for the Debian package is on salsa.debian.org here:

   https://salsa.debian.org/pkg-voip-team/mumble

I also wrote a script for building a tarball of Mumble from the Git tree, and
that's also in the Debian package in debian/extras/make-mumble-git-tarball.sh.

This question might mean something else, and if so let me know more specifically
what you're looking for.

   -- Chris

-- 
Chris Knadle
Chris.Knadle@coredump.us
