### ISSUE TITLE
Package repository server

### ISSUE THREAD

**Issue by felixsinger** [mumble-voip/mumble#3401]
Are there any plans to host an own package repository server to provide "ready-to-install" packages? (especially for snapshot releases)

I think this would be interesting for Debian and Centos (maybe Archlinux?). Other distros have their own build service, like PPA for Ubuntu. So there is no need for this. With Open Build Service (from openSUSE) it's possible to build packages system-wide, but the way how to do packaging / building with it feels weird for me.

Opinions?

Related to #3400 

Edit: And Open Build Service is down atm :D

**Comment by Krzmbrzl** [comment]
As a super late answer to this: We/I am currently in the process of working on being able to generate installable Linux packages, starting with DEB packages, that we could then provide as downloads on our website. See also https://github.com/mumble-voip/mumble/pull/5006

**Comment by felixsinger** [comment]
I would try reaching out to the distros and their package maintainers. Maybe you can easily cooperate with them. So you don't need to maintain your own package repository.

**Comment by felixsinger** [comment]
I think I only requested that because at that time the latest stable release was 1.2 and I wanted to use the latest snapshot release.

**Comment by Krzmbrzl** [comment]
I'm currently in active contact with the Debian maintainer in order to get an up-to-date Mumble version into the Debian repositories and to get our PPA up and running again :)

But in addition to that I also want to be able to create downloadable and installable native Linux packages. Deb is just the first case I wanted to try.

And I chose native packages over e.g. Flatpak as the former are directly supported via clack whereas the latter (afaik) is not.
