### ISSUE TITLE
Is it possible to join multiple Channels at once / simulate similar behavior?

### ISSUE THREAD

**Issue by edm7707** [mumble-voip/mumble#3440]
Hey!  wanted to get peoples thoughts on the following...

1) Is it possible to join multiple channels from a single client?  

2) What are pitfalls of multiple mumble clients on the same machine connecting to different channels on the same murmur sever?...   ( I know its possible but not officially supported)
(Use case would be Talking only on single channel but listening to multiple)  

Thanks!!

**Comment by edm7707** [comment]
@davidebeatrici Thanks for the super fast response!

Are there any downsides to using more multiple mumble clients per single box? ( Other then increased latency)?

**Comment by davidebeatrici** [comment]
@edm7707 You're welcome!

The only downside is the increased resources usage, mostly CPU and network.

**Comment by Kissaki** [comment]
It is not currently possible to join multiple channels from the same Mumble client. Davide pointed to the corresponding feature request #3319.

Mumble does support linking channels where users can hear each other from other channels. Mumble allows optionally adding complex rules for controlling which users can talk to and listen to which channels. Depending on your use case that may be more fitting than running multiple clients.

As you hinted you can run multiple clients simultaneously through command line arguments, and you can also make the additional instances not use your (normal) user certificate so you can connect to the same server (which would normally throw out your first instance because you connect to your single account).

You can also specify different keyboard shortcuts for push to talk, or push to mute, or mute, or whatever, to control multiple instances. However, this only works for the runtime. As we do not officially support running multiple clients, there is no logic in place that would handle the settings separately. Only the last saved settings will be loaded when you launch the next client - last saver wins.

You can also use whisper to to only talk to specific channels.

For your use case, only listening to another channel it may be viable to link them and let everyone listen to the other channel (or limit that to your user or a user group). Or it may be viable to link them, and also allow talking to the other channel, and decide how to handle that (talk to both by default, or use shout/whisper to talk to the other channel).
