### ISSUE TITLE
TCP pings are bugged

### ISSUE THREAD

**Issue by radistmorse** [mumble-voip/mumble#3448]
This new functionality was introduced in https://github.com/mumble-voip/mumble/pull/2622/. This functionality causes my client to disconnect 5 seconds after joining. This can repeat several times in a row, but happens only eventually. I have yet to find the pattern when it happens. I use the 1.3.0 snapshot client, and 1.2.19 server. At the very least, the message is misleading, since my server doesn't use TCP (the port is not even forwarded).

There is also a definite bug in how the "maxinflighttcppings" parameter is handled: if it's zero, the feature does not get disabled, but rather the client is disconnected immediately after the connection. This line https://github.com/mumble-voip/mumble/blob/master/src/mumble/ServerHandler.cpp#L471 should have both > instead of >=.

**Comment by Kissaki** [comment]
Mumble definitely uses TCP as its control channel (connecting, user states, object information etc). So I'm not quite sure what you mean by your server does not use TCP. Because without TCP you would not be able to connect.

For your description of being connected to the server but then disconnecting; maybe connection is lenient enough to allow and handle packet loss and late packets, but the ping reconnect mechanism is not. When it happens, can you check the Server -> Information UDP statistics? UDP is not TCP, but maybe late and lost packets could indicate routing/connection problems. I'm also not sure if that survives being reconnected... which sucks. But maybe you can check before the auto-reconnect happens.

**Comment by Profpatsch** [comment]
I’m getting lots of spurious reconnects as well, since the Corona pandemic started our provider is losing packets sometimes.

The above mentioned line:

https://github.com/mumble-voip/mumble/blob/ae026084867335082743266b07c07732658c94f8/src/mumble/ServerHandler.cpp#L507-L508

The `iInFlightTCPPings >= g.s.iMaxInFlightTCPPings` check would mean that if 1 is in flight and another is started, it immediately disconnects, so as OP said we want to have `>` here.
Maybe that already fixes most of the spurious disconnects in practice, or maybe we want to increase the default to 3 (right now it’s effectively `2−1`, so 1).

**Comment by radistmorse** [comment]
I would argue that the first comparison should also be changed to ">" since it contradicts to the documentation here: https://github.com/mumble-voip/mumble/blob/master/src/mumble/Settings.h#L364

Setting iMaxInFlightTCPPings = 0 should disable the check. Or the documentation needs to be updated, by saying that setting this value to zero will break the client, and this is a valuable feature we want to preserve.

**Comment by Krzmbrzl** [comment]
@radistmorse this is exactly what I am thinking. I'm digging through the code as of this moment to verify that :point_up:
