### ISSUE TITLE
wiki.mumble.info open source

### ISSUE THREAD

**Issue by preterive** [mumble-voip/mumble#3458]
Please make wiki.mumble.info open source to allow to translate in other languages.

**Comment by Kissaki** [comment]
What do you mean by that?

It’s a wiki anyone can edit after registration, and the software we use is open source (Mediawiki).

**Comment by preterive** [comment]
Oh, i don't know that. Thanks.

**Comment by preterive** [comment]
Hello, i have made a german homepage here: https://wiki.mumble.info/wiki/Home-De

**Comment by Kissaki** [comment]
We actually put some effort into reworking our homepage/landing pages at https://github.com/mumble-voip/mumble-www

to replace the wiki for that with a website and keep the wiki for the documentation.

We are unsure about how we want to handle translations for that content, because the few wiki pages that have translations always have the problem of keeping them up to date. We are unsure if we want to focus on English to make sure it stays up to date for everyone, or if we want to introduce translations - which would require some commitment from translators, or something.

For mumble-www that is tracked in https://github.com/mumble-voip/mumble-www/issues/4

So thank you for your effort, I'm not quite sure yet what I can or want to do with the translation though. But I guess translating the feature list at the top, on the landing page, does make sense.
