### ISSUE TITLE
Feature Request - Configurable Redundant Username Handling

### ISSUE THREAD

**Issue by BananaHemic** [mumble-voip/mumble#3494]
Currently, to my knowledge, if a user joins using a username that is currently in use, then the previous user is kicked and the new user is allowed to join.

I think it would be a nice feature to allow a configuration setting defining whether:

1. The previous user is booted (the current behaviour), or
2. The new user is rejected with a message from the server asking for them to use a new name

This would help prevent a possible issue where a bad actor could kick unregistered users at will by joining with their username.

**Comment by Kissaki** [comment]
I am not sure when this happens as you describe it/what your use case is specifically.

When a user logs in to an account via their user certificate the user is assigned that accounts username. The user does not specify their own.

If a user logs in to their account via username and password they identify as that account. There is no kicking unregistered users in that case, because that name is registered and belongs to that user.

If an anonymous user is connected, and someone tries to connect with that username, I would expect a username is use message. Is that not the case?

**Comment by BananaHemic** [comment]
Correct, for anonymous users, when someone else joins under the same name they do not get a "username is in use" message. This is at least the case on my Murmur server version 1.2.19-1~ppa4~xenial1

**Comment by Stefan-comkmits** [comment]
I Think he mean the "Disconnecting ghost" feature.
If i see it Correct,it appers only under the same iP.

[16:36:24] You were kicked from the server by the server: You connected to the server from another device.
[16:36:24] Server connection failed: The remote host closed the connection.
