### ISSUE TITLE
Murmur permits client login with any certificate

### ISSUE THREAD

**Issue by StefanBodoarca** [mumble-voip/mumble#3523]
1. I want to make authentication based only on clients certificates. Those certificates must be signed  by the same CA as the murmur certificate.
2. I made my own CA and I made a server certificate signed by this CA.
3. My android/desktop clients can enter into the server with the autogenerated certificates (those made by mumble/plumble clients), with certificates signed by my own CA and with self-signed certificates.
4. My certificate for the server is added in murmur.ini (sslCert), in pem format, and contains all the chain to the Root CA. The key is at sslKey, also in pem format. If I clear the trust database from a plumble client, certificate for murmur (the one made by me) is readed and can be trusted. No error appears. The connection works perfectly.
5. I added the -wipessl option when restarting murmur hoping that those autogenerated/self-signed certificates would not be accepted anymore.
6. I also added my CA in ca-certificates and made "sudo dpkg-reconfigure ca-certificates".
7. All the keys are RSA 4096. Those certificates from my plumble clients are in .p12 format.

How to make the server to verify a client certificate and to block the access to my server?

Any help is appreciated. Thanks a lot.

**Comment by reelsense** [comment]
https://wiki.mumble.info/wiki/Features#Authentication

The users need to _register_ in your server. The admin needs to set the _Access Control Lists_ to restrict _all_ users except those registered. 

You can apply permissions to a group to make things easier when you authorize the _registered_ users by adding them to the group with permissions.

How do you specifically block certs not signed by your CA? I don't think that can be done, or how you should do it. Adding a CA to your OS's trust store just tells the OS that their cert was signed by a trusted key. A key can be "untrusted" but still valid.

**Comment by StefanBodoarca** [comment]
Thank you for your answer.

I have worked with ACLs and groups, registered (with or without a certificate) and unregistered users, permissions.

I know that "A key can be "untrusted" but still valid.", but this "adding your CA in ca-certificates" was what I read somewhere while looking for answers regarding my topic. I read that murmur should have a certificate that has it's CA in my OS's trust store.

Regarding ACLs: How to set an ACL like "@sub, -1 +speak" from a Mumble desktop client? When i type this to Group it's not saved. I am logged in as SuperUser.

**Comment by EPNW** [comment]
Is this feature possible by now?
If not, shouldn't it be as easy as to tell murmurs ssl engine when initalizing to only trust certian CAs?
Like chaning `MumbleSSL::addSystemCA();` in line 134 of `ServerHandler.cpp`?

**Comment by Krzmbrzl** [comment]
> Is this feature possible by now?

Not that I know of.

How difficult it would be to implement this, I don't know. It could be as easy as configuring the CAs but maybe there's also more to it.
If you want to give it a shot though, please do and if you have something working(-ish) go ahead and create a pull request for it. As long as this feature is optional and is disabled by default (aka: it is opt-in), I think we'd be happy to accept the respective changes.

**Comment by EPNW** [comment]
It seems as murmur always trusts only its own certificate and intermediate certificates by default.
From line 1431 of Server.cpp:
```
		// Treat the leaf certificate as a root.
		// This shouldn't strictly be necessary,
		// and is a left-over from early on.
		// Perhaps it is necessary for self-signed
		// certs?
		sock->addCaCertificate(qscCert);

		// Add CA certificates specified via
		// murmur.ini's sslCA option.
		sock->addCaCertificates(Meta::mp.qlCA);

		// Add intermediate CAs found in the PEM
		// bundle used for this server's certificate.
		sock->addCaCertificates(qlIntermediates);

		// Must not get config from socket before setting CA certificates
		config = sock->sslConfiguration();
```
This means that ssl errors already occur, but it seems that murmur just ignores some kinds of ssl errors as in line 1573 of Server.cpp:
```u->proceedAnyway();```
To make the behaviour more configurable I would suggest the following:
Add a new entry in `murmur.ini` named `ignoredClientSslErrors` which is a comma separated list of integers.
Each integer present in this list corresponds to a [QSslError::SslError enum value](https://doc.qt.io/qt-5/qsslerror.html), which should then be ignored as its currently praxis.
To achive the current behaviour with this, the list should default to `5,6,9,10,11,12,21,22`, which correlates to:
```
			case QSslError::NoPeerCertificate: 21
			case QSslError::SelfSignedCertificate: 9
			case QSslError::SelfSignedCertificateInChain: 10
			case QSslError::UnableToGetLocalIssuerCertificate: 11
			case QSslError::UnableToVerifyFirstCertificate: 12
			case QSslError::HostNameMismatch: 22
			case QSslError::CertificateNotYetValid: 5
			case QSslError::CertificateExpired: 6
``` 
(excreed from Server.cpp, starting at line 1556)

If this is fine with you @Krzmbrzl, I will start working on it and create a PR.
Please give me a bit of feedback if you think that there's a better way.

**Comment by Krzmbrzl** [comment]
Ouch these are a lot of ignored SSL errors... I guess it would also be worth it to re-check whether we need that many exceptions. From a first glance it almost seems as if you can connect with basically any certificate, which would bring up the question of why one should bother with a cert in the first place :eyes: 

In general I think your idea is good. For the actual implementation I have 2 comments though:
1. We should not use numbers to represent different options. Instead we should assign names to these cases and write those in the ini file. Otherwise folks will not be able to read the ini anymore (plus we are dependent on the actual values in Qt's enum)
2. I think configuring this as "ignored SSL errors" reads weird as for once this exposes an implementation detail (that these are SSL errors that are actively ignored) that a server admin should not have to worry about.

In general I would propose to add an option called e.g. `clientCertificateRelaxations` which could then contain a comma-separated list of keywords such as `AllowExpired`, `AllowSelfSigned`, ... which then internally get converted to a list of SSL error codes that are then checked inside the `sslError` function.
Imo that makes the semantics and the user-interface of such an option much cleaner.

**Comment by EPNW** [comment]
While implementing this I stumbled upon the following:
If an error that is currently ignored (see above) occurs, `bVerified` will be set to `false`. Other, not ignored errors on the other hand will lead to the client being disconnected from murmur. If we now implement configurable relaxations, what should happen if one of them is then met? My suggestion is to disconnect the client if the error is not allowed, and even if the error is allowed, we should set `bVerified` to `false` as it is currently done.

As of now I actually don't really unterstand what `bVerified` is used for, but in practice it should be `false` for almost every client connecting to current murmur anyway, since most certificates are self signed, and supposingly even more user certificates rise `HostNameMismatch` errors.

**Comment by Krzmbrzl** [comment]
> My suggestion is to disconnect the client if the error is not allowed, and even if the error is allowed, we should set bVerified to false as it is currently done.

Agreed

> As of now I actually don't really unterstand what bVerified is used for, but in practice it should be false for almost every client connecting to current murmur anyway, since most certificates are self-signed, and supposedly even more user certificates rise HostNameMismatch errors.

There is the notion of a "strong" certificate in some context. Admittedly I currently don't know where that is, but essentially in order for a certificate to be considered "strong" `bVerified` must be `true`.

**Comment by EPNW** [comment]
I noticed someting additional: While with this we are now able to configure how murmur reacts to bad client certificates, we can not configure what murmur considers a bad client certificate.

As stated above, the ssl config murmur uses to validate the client (I will referee to this as Murmurs Client Trust Store or MCTS) is initiated with `qscCert`,`Meta::mp.qlCA`, and `qlIntermediates` as CAs (see `Server.cpp` lines 1410 to 1448).
I digged around a bit to find out, where those three came from, but before going into it, let us analyse how certs are loaded by murmur.
To start, certs are parsed from `murmur.ini` using `MetaParams::loadSSLSettings` (`Meta.cpp`, line 606) as follows:
1. Read all certs from `sslCA`; these are `Meta::mp.qlCA`
2. If `sslKey` set and valid, use it as private key
3. If `sslKey` NOT set, try to get a private key from `sslCert`
4. If we have no key by now, fail, else we have found our key `Meta::mp.qskKey`
5. Read ALL certs from `sslCert` and ALL certs from `sslKey` to a list
6. Use the private key to find a matching cert in the list
7. If there is NO match, fail
8. If theres a match, remove it from the list and consider it our cert `Meta::mp.qscCert`
10. Treat all leftover certs in the list as intermediates; these are `Meta::mp.qlIntermediates`

Now `Meta::mp` is pouplated and murmur goes over to wire things up once a `Server` is booted using `Server::initializeCert` which is implemented in `Cert.cpp` (starting at line 71). There, the certificates are more or less simply copied from `Meta::mp` if they are valid, or an own certificate is generated.

Finally we can wrap up what the MCTS actually contains:
* `qscCert`: This is murmurs own certificate as determined above. BTW: The comments say that it is actually unknown, why this is added as CA to MCTS and probably a left over from eralier versions.
* `Meta::mp.qlCA`: All certs from `sslCA`.
* `qlIntermediates`: Certs that were found in `sslCert` and `sslKey`, excluding murmurs own cert (`qscCert`).
* But wait, there is more: System CAs are loaded using `MumbleSSL::addSystemCA()` from `SSL.cpp` on startup (`main.cpp`, line 500) and added to default ssl config, which is thus in turn also part of the MCTS.

Please correct me if any of my previous findings are wrong.

So now we want to make the MCTS configurable but before discussing possible `murmur.ini` options (and suitable default values) I need two things clarified:
1. Why are `qlIntermediates` and `Meta::mp.qlCA` two different things?
2. It appears to me, that the server never actually sets its cert chain to the client socket.
While the server uses `setLocalCertificate` it never uses `setLocalCertificateChain`.
But surprisingly, the mumble client seems to be able to obtain and show the whole chain.
From `ServerHandler.cpp` line 732:
    ```
    qscCert   = connection->peerCertificateChain();
    ```
    My only guess - and I could not find any documentation about it - is that Qt is able to calculate the chain of a cert automatically if all certs belonging to the chain where added to the socket/ssl configs `CA certificate database` (using `addCaCertificates`). If that is really the case, maybe it explains, why `Meta::mp.qlCA` and `qlIntermediates` are added in the first place?

My next step will be more research wheter my theory from point 2 is correct. If it holds, we could maybe use this mechanisms to calculate the appropriate chain of turst for murmur right after parsing the certificates, and don't need to store `qlIntermediates` and `Meta::mp.qlCA` as different and confusing entities, which could also contain much more certificates than we need. We can then use this chain to `setLocalCertificateChain` and finally, use `addCaCertificate` only for certificates we really explicitly want in the MCTS (which was my motivation in the first place).



Now, something different: I also developed a theory why so many ssl errors are currently accepted. Imagine a user with an expired certificate generates a new one. The certificates hash will change and murmur won't recognize the user agian (`ServerDB.cpp`, line 1386).

Btw: I am developing using vs code remote with an docker container and I noticed that the murmur.ini isn't parsed (`qsSettings->allKeys()` is empty) if I use ubuntu focal instead of bionic (took me some hours to find that out but didn't digged deeper). Are there any known problems with focal or might this just be an unlucky coincidence for me?

**Comment by Krzmbrzl** [comment]
In terms of the SSL stuff I have to say that this goes beyond my knowledge of this subject. I also don't know why it was implemented the way it currently is.
Maybe @davidebeatrici knows a bit more?

> Btw: I am developing using vs code remote with an docker container and I noticed that the murmur.ini isn't parsed (qsSettings->allKeys() is empty) if I use ubuntu focal instead of bionic (took me some hours to find that out but didn't digged deeper). Are there any known problems with focal or might this just be an unlucky coincidence for me?

I am not aware of any problems in that regards :thinking:

**Comment by EPNW** [comment]
I think I figured a way out (ofcourse only if my above assumptions are correct), how to clean the whole ssl thing up a bit, and clearly separate the chain the server will present the clients, and the chains the server will accept from the clients.

First, we introduce the MCTS by adding new ini options:
```
allowedClientSslErrors (default: AllowNoPeerCertificate, AllowSelfSignedCertificate, AllowSelfSignedCertificateInChain, AllowUnableToGetLocalIssuerCertificate, AllowUnableToVerifyFirstCertificate, AllowHostNameMismatch, AllowCertificateNotYetValid, AllowCertificateExpired)
If a client presents a certificate to the server, the certificate is validated according to Murmurs Client Truststore (MCTS), which by default contains murmurs own chain-of-trust as well as the hostmachines CAs. Errors might arrise during validation of the clients certificate, but some are not critical and thus ignored. A server admin can configure, what errors should ignored using a comma separated list of the following options: AllowUnableToGetIssuerCertificate, AllowUnableToDecryptCertificateSignature, AllowUnableToDecodeIssuerPublicKey, AllowCertificateSignatureFailed, AllowCertificateNotYetValid, AllowCertificateExpired, AllowInvalidNotBeforeField, AllowInvalidNotAfterField, AllowSelfSignedCertificate, AllowSelfSignedCertificateInChain, AllowUnableToGetLocalIssuerCertificate, AllowUnableToVerifyFirstCertificate, AllowCertificateRevoked, AllowInvalidCaCertificate, AllowPathLengthExceeded, AllowCertificateUntrusted, AllowCertificateRejected, AllowSubjectIssuerMismatch, AllowAuthorityIssuerSerialNumberMismatch, AllowNoPeerCertificate, AllowHostNameMismatch, AllowUnspecifiedError, AllowNoSslSupport, AllowCertificateBlacklisted

mctsAddOwnCertificateAsCA (default: true)
Adds murmurs own certificate (without the chain) as CA to the MCTS.

mctsAddOwnCAs (default: true)
Adds the chain of murmurs own certificate (but not the its own certificate) as CAs to the MCTS. 

mctsHostsCAs (default: true)
If this is set to true, the CAs of the hostmachine are added to the MCTS.

mctsExtraCAs (default: empty)
Path to a pem file containing one to multiple certificates to add to the MCTS.
```

Secondly, we don't change the `sslCA` and `sslCert` options that are currently there, but alter the internal behaviour: Right after parsing in `Meta.cpp`, we calculate the certifiacte chain and store it, but drop every other information we got from here as we don't need them anymore. Then, we always use this chain if a connection to the server is made.

The only other place the certs from  `sslCA` and `sslCert` are used is in `Register.cpp`, but we don't need them there either if we know the chain. In `Register.cpp` it is enought to trust the hostmachines CAs, since mumbles offical server list server (where to connection is made to) should be signed by one of those. There is no use for custom certs here.

I also noticed something that I would consider a critical bug: While validating a clients chain in `Server.cpp` `const QSslCertificate &cert = certs.last();` is used, but from the context I would say it should be `const QSslCertificate &cert = certs.first();`. `last()` actually returns the cert of the CA and not the user, see [QSslConfiguration::peerCertificateChain()](https://doc.qt.io/qt-5/qsslconfiguration.html#peerCertificateChain). Since most current clients don't have a complex chain and in almost every case just one certifiacte, things should be fine for now (and remeber, we are also ignoring a bunch of ssl errors atm), but once clients start having more complex chains (what the intention if this issue is), things will get messy.

**Comment by Krzmbrzl** [comment]
The suggestion sounds good to me :+1: 

> I also noticed something that I would consider a critical bug: While validating a clients chain in Server.cpp const QSslCertificate &cert = certs.last(); is used, but from the context I would say it should be const QSslCertificate &cert = certs.first();

I agree. Do you want to create a pull request that fixes this issue? :)

**Comment by EPNW** [comment]
Yes, I'm currently testing everything we discussed here, will open a PR tomorrow I guess :)
