### ISSUE TITLE
[Linux and Pulseaudio] Spark sound in background when I speak

### ISSUE THREAD

**Issue by MrVBalazs** [mumble-voip/mumble#3528]
Hi.

Today we spoke from linux in a Live what is our experience, problems
etc. It turned out we have a fix problem on linux with a Ryzen cpu. A
bugg of Pulseaudio.

The problem is.. If we speak to microphone then theres have a spark
sound in background. Only on Linux. Because on Windows operation system
works finely. On linux doesnt. Just on Ryzen cpus. Ive tried on an
intel laptop it works finely on it. And it isnt a hardware problem
because in our community doesnt work for nobody. 

Can you fix this problem? Because we cannot make a stream/video on
linux because always have a spark sound in background while we speak.
We tried on Ubuntu, Linux Mint, MX Linux, Manjaro and Arcolinux, Anarchy..
Nowhere.

I am sorry for my bad english because I am hungarian.
I hope Ill get a reply.

Balázs

![image](https://user-images.githubusercontent.com/42870867/45913994-7d0c2d80-be3e-11e8-8c30-a7a48df311e8.png)

**Comment by vbalazs02** [comment]
And pulseaudio version is 12.2

**Comment by sadsfae** [comment]
I had this problem from time to time on Fedora if you're talking about a "scratchy" type sound.  The workaround for me was to go into PulseAudio and set the following:

```
-load-module module-udev-detect
+load-module module-udev-detect tsched=0
```

Also it helps if I open ```pavucontrol``` and set the profile for my audio device to something different and then back again.  e.g. Analog Stereo Output + Analog Mono Input and then **back to the default** of Digital Stereo (IEC958) Output + Analog Mono Input.  Your settings will vary because your hardware will probably be different.  Here's a screenshot.

![screenshot_2018-10-06_17-29-04](https://user-images.githubusercontent.com/3940978/46573473-c0fa4900-c98d-11e8-8d40-f2bcf727017d.png)

Hope this helps, I am not sure it's a Mumble problem but perhaps Mumble + PulseAudio.  I noticed that some other sound applications do it also like Pithos.

**Comment by vbalazs02** [comment]
Yes I tried it but still have spark sound.
