### ISSUE TITLE
THE FOUNDATION in the license

### ISSUE THREAD

**Issue by unterwulf** [mumble-voip/mumble#3593]
Hi,
The license of Mumble has the following sentence
> IN NO EVENT SHALL **THE FOUNDATION** OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT...

I wonder what is referenced to as THE FOUNDATION. The term is never defined in the text of license.
Doesn't it look like a copy-paste issue resulted from using some file from *BSD as a template?

**Comment by Ytmndissue** [comment]
Probably just implied it means the Mumble organization as a singular entity - but most likely you're right. Just copypasta'ed text that was never changed from a general template.

**Comment by Krzmbrzl** [comment]
Is this something we should worry about @davidebeatrici? My gut tells me, that this doesn't matter...

**Comment by davidebeatrici** [comment]
We currently refer to ourselves as "The Mumble developers", but from a legal viewpoint we're not a foundation.

As far as I know it's only a cosmetic issue, but still something we should consider fixing.

**Comment by Krzmbrzl** [comment]
Having thought about this some more, I think that we should not alter the text of the license. I don't know about BSD, but for instance for GPL, you are not even allowed to do that.

Furthermore the text also specifies `OR CONTRIBUTORS` which then covers everything that we need. Thus I don't think that the mentioning of a "FOUNDATION" is problematic.

If we were to change the license's text however, a possibly interested customer may have to parse the license text in all detail in order to ensure that this is still the BSD-3 license and that it has not been altered in other was as well.

Thus overall I think we should stick with the standard formulation.
