### ISSUE TITLE
Conversation recording

### ISSUE THREAD

**Issue by Andres8427** [mumble-voip/mumble#3629]
Hello,

I'm new to the world of Mumble, but I already have my server Mumble (Murmur) version 1.2.19 installed and running perfectly, however I'm interested in saving the conversations of each of the channels in an audio file (the format I do not care about this as long as it is recorded)

According to the documentation, I can do this through PulseAudio but I can not find how, I only find very old references or they say that if it is possible but they do not give more information on how to do it!

Can anybody help me please? My Mumble server (Murmur) is on Ubuntu 16 and I would like it to store all the recordings of the conversations on the server.

Thank you.

**Comment by Kissaki** [comment]
Hello

The Mumble server does not natively support recording audio. It's slim and only relays audio packets without further audio processing.

PulseAudio is for audio handling beyond that. As the Mumble server simply relays the network packets, PulseAudio never knows of them on the server.

You can host and connect a bot that will record audio in a channel. I believe that there are such bots available from third parties.

Arguably, all audio being recorded is unexpected by users, and potentially a privacy issue. That's why the Mumble client will indicate it is recording to other users when it is - at least to the point we have control over..

**Comment by DuckBoss** [comment]
As @Kissaki pointed out, you could have a recording bot instance in each channel to record the individual channels and save them to separate files, or process the individual files further.

**Comment by Kissaki** [comment]
I am closing this as the discussions seems to have come to a close, and I do not see us implementing it at this point in time - because of the concerns I described in my comment.

If you have counter arguments or want to discuss it further feel free to reply still.
