### ISSUE TITLE
Request: Simple Text-to-Speech

### ISSUE THREAD

**Issue by Elusivehawk** [mumble-voip/mumble#3676]
It would be nice if we could get a checkbox that enables a simple, shortened message that's less annoying for people to listen to. So if someone sends a text message, instead of saying "Channel, username, message", text-to-speech just outputs the message itself.

The reason behind this is simple, but a bit of a niche case: A friend's mic died, but they still want to be a part of our conversations. When they send a text message, the extra fluff disrupts the conversation for longer than it should, and is annoyingly repetitive. The alternative is turning off text-to-speech altogether, but then they get ignored unless we're actively monitoring the text chat.

**Comment by marienuac** [comment]
shlorn alredy added this

**Comment by sregister** [comment]
I've sort of hacked this together a long time ago at: 
https://github.com/sregister/mumble/commit/7d4a4b3fba1acb994111022aea61c9aa3b7eec78

If I have time I can try to fix that patch up a little and submit an official PR, I added the gui elements using Qts GUI helper thing (which I've since uninstalled) and it did crazy stuff to the XML files which may or may not really matter.

**Comment by davidebeatrici** [comment]
Don't worry about it, we can clean the changes up before merging the pull request.

**Comment by Kissaki** [comment]
Did #3677 implement this? Or only partially? What is still open?

**Comment by sregister** [comment]
#3677 fully implemented this feature request.

**Comment by marienuac** [comment]
🍆
