### ISSUE TITLE
Can I convert the source file to VC2008 to build a SLN file? I don’t know much about QT.

### ISSUE THREAD

**Issue by chinamore** [mumble-voip/mumble#3751]
Can I convert the source file to VC2008 to build a SLN file? I don’t know much about QT.
THX

**Comment by davidebeatrici** [comment]
You would have to build from the `1.2.x` branch with a Qt 4 kit built with MSVC 2008.

**Comment by chinamore** [comment]
qmake -spec win32-msvc2008 -r -tp vc main.pro  

QT4.7.4 :Aborting configuration
I found 1.2.X from the branch but could not generate the SLN file. The program reported an error. I installed VC2008+QT4.7.4 on the server, and the error message was reported.

**Comment by chinamore** [comment]
Importing PRO from VS2008 intermediate QT is also no reaction, I don't know where the error is.

**Comment by davidebeatrici** [comment]
I'm not familiar with the integration between qmake and Visual Studio, however there are many more dependencies required in order to compile Mumble.

Here you can find our current build environment used to compile Mumble 1.2.x: https://github.com/mumble-voip/mumble-releng

May I ask why you want to compile using MSVC 2008 instead of a recent version?
