### ISSUE TITLE
Make 1.3.0 a simultaneous release with our new website

### ISSUE THREAD

**Issue by Kissaki** [mumble-voip/mumble#3759]
Although it hurts to not just push for the stable release right away, we should and consequently will finish up the new website to make sure both can take advantage of each other.

This is a ticket for the 1.3.0 milestone, to make it clear what is still missing even when it is a separate project. We are waiting for it.

https://github.com/mumble-voip/mumble-www/milestone/1

**Comment by Krzmbrzl** [comment]
Is the new website being developed at https://github.com/mumble-voip/mumble-www/?
I'm asking because I was curious how long this redesign might take so I wanted to get an impression on what's still missing. However I can't seem to find that kind of information in that Repo. Plus the latest changes to that repo seem to have been 7 months ago...

**Comment by xTMxTM** [comment]
> Is the new website being developed at https://github.com/mumble-voip/mumble-www/?

Yes, see here: https://github.com/mumble-voip/mumble/issues/2728#issuecomment-521302996

**Comment by Kissaki** [comment]
Yes, that is the repo.

For now I am mainly looking for an update to the landing page with some Mumble and 1.3.0 information. And probably adding a release notes page for better readable release notes / changelist than on the Wiki or Blog.

**Comment by Kissaki** [comment]
Website is ready.

**Comment by davidebeatrici** [comment]
https://github.com/mumble-voip/mumble/issues/2728#issuecomment-529303754
