### ISSUE TITLE
Failing update checks lead to unnecessarily high CPU usage

### ISSUE THREAD

**Issue by Kissaki** [mumble-voip/mumble#3760]
It looks like (at the very least in our Windows client) the Mumble client update check mechanism has no reasonable handling of failure cases.

When our domain was temporarily unavailable #3749 the (idle) clients CPU usage increased significantly. 1.2 does not have this issue; likely or possibly because it does not use the new domain endpoints(?).

This should be easily testable entering the invalid IP address `0.0.0.0` for our update domain (`update.mumble.info`) into the systems `hosts` file.

**Comment by ZingBlue** [comment]
I am gonna give this a shot over the weekend to see if I can do anything to fix it, I'll update you if I have any luck or not.

**Comment by davidebeatrici** [comment]
Excellent, thank you!

**Comment by ZingBlue** [comment]
Where can I find the hosts file?

**Comment by ZingBlue** [comment]
I am having an issue with building Mumble, after running `./build-all.bash` I get:
```
+ ./nasm.build
/usr/bin/env: ‘mumble-build’: No such file or directory
```
Any idea on how to fix this? Thanks.
(Also, mumble-build is a directory with a mumble-build file in it. So it should be working)

**Comment by ZingBlue** [comment]
Currently I am having trouble building Mumble, once I have gotten building working, I'll let you know if I fix the CPU usage.

**Comment by dingpengyu** [comment]
Is the current problem solved?

**Comment by davidebeatrici** [comment]
Not yet, unfortunately.

**Comment by Krzmbrzl** [comment]
I think the problem lies in `QNetworkAccessManager` that is used to post stuff around. See
- https://stackoverflow.com/questions/30838240/qnetworkaccessmanager-freezes-if-network-is-unreachable
- https://stackoverflow.com/questions/44047292

[This SO question](https://stackoverflow.com/questions/2668519/qnetworkaccessmanager-timeout) suggests that one has to handle timeouts separately as `QNetworkAccessManager` doesn't seem to do it for us.

If this is really the case my suggestion would be to never use the manager directly. Instead we should write a wrapper around it, that automatically handles timeouts by disconnecting from the domain. When doing this, one should take `QNetworkReply::uploadProgress()` and   `QNetworkReply::downloadProgress()` into account in order to not quit an ongoing connection (that might just be slow) or at least use a different timeout for those cases

**Comment by davidebeatrici** [comment]
The StackOverflow questions you linked talk about `QNetworkAccessManager` freezing.

I'm not saying that's not what we're experiencing, but the real cause for the high CPU usage may be unrelated.

**Comment by Krzmbrzl** [comment]
Sure. But I figured it might be related - haven't tested it though :man_shrugging:

**Comment by davidebeatrici** [comment]
In any case, it's still very useful info, thank you for referencing it here.

**Comment by ZingBlue** [comment]
Hello, sorry I haven't responded for awhile (I have been extremely busy for the past four months). I don't think I know how to solve this issue (for now), I only know Python and I said I'd do this because I thought it would be relatively easy, I was wrong. I plan to start learning C++ within the next two months, so in the long run I maybe able to fix it; but not now.

**Comment by Krzmbrzl** [comment]
@Kissaki I edited your initial post to include the domain that has to be adjusted to reproduce this problem.

I can also confirm that this issue exists on Linux as well.
