### ISSUE TITLE
Matrix integration?

### ISSUE THREAD

**Issue by Lurkki14** [mumble-voip/mumble#3791]
I'm not sure if much work has been done on permanent messaging but integrating with Matrix could be a solution.

**Comment by MayeulC** [comment]
> Quoting my earlier comment from [#1813 (comment)](https://github.com/mumble-voip/mumble/issues/1813#issuecomment-525033472):
> > 
> > Matrix.org is currently also bad for privacy, while Mumble currently doesn't store chat logs, the reference homeserver implementation for Matrix, Synapse stores everything forever [matrix-org/matrix-doc#447](https://github.com/matrix-org/matrix-doc/issues/447) including deleted messages. Multiple other privacy issues are listed at [privacytoolsIO/privacytools.io#1049](https://github.com/privacytoolsIO/privacytools.io/issues/1049).
> > I don't know what you would do to Murmur, but I have understood Synapse to be very heavy especially if you have bigger rooms, while Murmur seems to run anywhere and there is µMurmur for even more limited systems.
> 
> I also see additional issue that Mumble doesn't currently support message removals, so in my opinion it would need that feature for Matrix support and then it would be back to Matrix not ever removing messages from the database.

I just want to point out that this has been worked on for some time, and [no longer accurate](https://matrix.org/blog/2019/09/27/privacy-improvements-in-synapse-1-4-and-riot-1-4).

More improvements will come, but redacted messages are now garbage-collected. And of course, I would like to stress again that this is very *synapse-specific*, not an inherent issue with the Matrix protocol.
Of course, since the room history is something the users have access to if the room is configured as such, it remains in the database as long as users are using it. I guess you might want [configurable message retention period](https://github.com/matrix-org/matrix-doc/pull/1763) (disappearing messages)?

But there are some people interested in this, so the best approach could be to showcase a proof-of-concept first :)

**Comment by Mikaela** [comment]
Any media uploads (https://github.com/matrix-org/synapse/issues/1263) are still stored forever and I think the Synapse issue gets Matrix wide issue as soon as you get the first Synapse join the room, but I think Mumble doesn't support file uploads anyway.

I have previously today heard from an Synapse admin that it's painful to self-host and they would consider Modular.im over selfhosting and I can only hope that hosting a private Mumble server is going to stay painless and it can be done on even the cheapest VPSes.

> But there are some people interested in this, so the best approach could be to showcase a proof-of-concept first :)

:+1:

**Comment by rokejulianlockhart** [comment]
When I saw this issue, I expected that it referred to routing VOIP over the Matrix protocol. Would such a suggestion be a separate issue?

**Comment by Krzmbrzl** [comment]
Such a suggestion would be rejected. If you want to use Matrix for voice, use Matrix. What would be the point of using Mumble then?

**Comment by rokejulianlockhart** [comment]
@Krzmbrzl, to use its integration with software that I want to use, per https://github.com/DarkPlacesEngine/darkplaces/issues/61#issue-1463188381, and would allow those who do not know anything about Matrix to seamlessly communicate with practically anyone due to [Matrix's bridge support](https://matrix.org/bridges/).

**Comment by Krzmbrzl** [comment]
It seems to me that what you describe could be achieved by a Mumble-Matrix bridge. That would make more sense than rewriting a Mumble client to ditch the Mumble protocol and instead use the Matrix protocol :thinking:

**Comment by rokejulianlockhart** [comment]
Certainly, @Krzmbrzl, that would be fine if it were to support every feature, but that means even more maintenance. How is that fundamentally better to just using the more interoperable standard?

Now that even NATO and the Bundeswehr have adopted it, I can't imagine that anyone could say it's a fad, for instance. I can quite confidently say that it looks like a decent successor to RFC 6854.

**Comment by Krzmbrzl** [comment]
Yeah sure, it is likely a solid protocol. But it's not the Mumble protocol so if you want to use it, use a Matrix client.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/mumble-voip/mumble/issues/3791#issuecomment-1982730601

@toastal, thanks for the information.
