### ISSUE TITLE
Multisent when Packet Loss.

### ISSUE THREAD

**Issue by Stefan-comkmits** [mumble-voip/mumble#3894]
Let the Client sent Packets x Times,for Survival of the Fittest,
to have no Packet Loss on User Level.

**Comment by Krzmbrzl** [comment]
So regardless of the situation, the client should send all packets multiple times?
This seems like a fair amount of bandwidth overhead on the client and especially on the server side as the latter has to receive all hose packages and keep track which it has processed already. 

Not quite sure if this is a good idea :thinking:

**Comment by Kissaki** [comment]
The communication happens over two channels: The control channel uses TCP and the voice data channel UDP.

TCP makes sure transmission never loses information.

Voice data is time-critical, and once a critical time has passed delivering them late is of no use because that (buffer) time has passed.

Can you elaborate where you would want this? If the client notices packet loss on the UDP channel it should flood the network in hopes that if 30% gets lost pushing every packet twice will decrease it to 0.3 * 0.3 = 0.09?

That’s a lot of assumptions on the behavior of the networking. The percentages are not necessarily consistent with rate/data-width.

If the packet loss is because of network overload it could make the situation worse instead of better.

Do you experience regular packet loss? I feel like, at least where I am, this is not worth the effort at all. Not on the implementation side, nor performance side, nor the wasteful network usage.
