### ISSUE TITLE
Remove bandwidth/bitrate limit

### ISSUE THREAD

**Issue by vheuken** [mumble-voip/mumble#3895]
It's hard to find a definitive source, but it appears that the maximum bitrate you can set Opus to in Mumble is 128kbps. Opus supports up to 510kbps. Why does Mumble limit it? One use case for higher bitrates pointed out to me was streaming, where audio from Mumble would end up getting transcoded on the stream.

From the Murmur.ini wiki page in the bandwidth section: 
>Setting this over about 130000 doesn't really do anything.

https://wiki.mumble.info/wiki/Murmur.ini#bandwidth

From MumbleBoxes.com:
>The "bandwidth" setting on all of our mumble servers is 128kbits/s which is the maximum value that is able to be set on any Mumble server.

https://www.mumbleboxes.com/faqs/19-how-do-i-increase-the-voice-quality-on-my-mumble-server

**Comment by davidebeatrici** [comment]
The limit has been increased in #3753.

**Comment by TredwellGit** [comment]
The Mumble client user interface limits it, but you can actually use whatever bitrate and it will work. In Mumble.conf, you can set the `quality` option to values higher than the slider will go and as long as the `bandwidth` option in Murmur is set high enough it works. Both the wiki page and MumbleBoxes are just wrong.

However, considering how #3753 increased the user interface limit, I would like to see https://github.com/mumble-voip/mumble/blob/b54cf63549ed93ca2ce386ebecee6cb34c064cec/src/murmur/Meta.cpp#L49 and https://github.com/mumble-voip/mumble/blob/b54cf63549ed93ca2ce386ebecee6cb34c064cec/scripts/murmur.ini#L140 set to 220800 by default such as to permit using the maximum quality by default without requiring additional configuration.

**Comment by Krzmbrzl** [comment]
@davidebeatrici was there a specific reason to choose these values? Are there any negative effects of increasing them.
From the [wiki](https://wiki.mumble.info/wiki/Murmur.ini#bandwidth) it appears as if this is only to prevent users from exceeding your server's bandwidth. If this is the only reason, I'd agree with @TredwellGit as you can always set these to a lower value, if you indeed have bandwidth problems.

> set to 220800 by default such as to permit using the maximum quality by default 

Is this the maximum quality supported by Opus or how did you get to that exact number?

**Comment by TredwellGit** [comment]
I ended up looking at this more than I originally did.

220800 = 192000 + 28800
Where 192000 is the highest quality setting selectable in the user interface after #3753 and 28800 is the overhead with 10 ms audio per packet (the highest overhead selectable in the user interface).

However, this number was without position or TCP overhead. The correct maximum value selectable in the user interface is 240000 = 192000 + 9600 + 38400.

If you wanted to make the default bandwidth setting the highest that Opus (and Mumble) supports with 10 ms audio per packet, then it would be 558000 = 510000 + 9600 + 38400.

Opus can use down to 2.5 ms frame sizes and up to 255 audio channels, which I assume would have a larger overhead, but Mumble currently does not support that. See #2377 and #2829

So a good value for now would be either 240000 or 558000. Since it only uses that much bandwidth if the client wants to and because people have requested 510000 b/s support then maybe 558000 is the better value?

Also, I am curious as to why exactly the values used in #3753 were chosen.

**Comment by toby63** [comment]
Am I correct that this is only about setting of values (for now)?
Can we have a milestone for this then?

**Comment by Krzmbrzl** [comment]
> Am I correct that this is only about setting of values (for now)?

Afaik it is about lifting the limit, yes. However the protocol specification currently limits the maximum packet size to be 1020 bytes (+4 bytes overhead due to encryption). This had to be removed as well in order to remove unlimited bitrates (see #4260).

> Can we have a milestone for this then?

We don't use milestones anymore - see https://github.com/mumble-voip/mumble/issues/4000#issuecomment-629808853

**Comment by streaps** [comment]
I don't understand the problem. 192000 with 60 ms per packet would already create packets that are too big. So you send fewer frames per packet. For very high bandwidth you would need to use 10ms packets.

bandwidth=72000 is a bit conservative, but on the other hand you can achieve pretty good voice audio quality within this limit. Even more so with Opus 1.3. One could also argue that admins who want a higher limit can set it in murmur.ini. Setting the bandwidth too high allows excessive bandwidth usage without any useful improvement in audio quality. But it increases the traffic and on lower bandwidth connections this could lead to worse results. Several 500 kbps streams add up. If the kids are watching video streams and the boy friend zooms, do you really want to add 2 Mbit/s from Mumble?

I don't see much reason to change the default bandwidth. People who don't care reading the config file, would not hear the difference anyway.

**Comment by toby63** [comment]
@streaps 
> I don't understand the problem. 

The first problem is (if I understand correctly):
>> The correct maximum value selectable in the user interface is 240000 = 192000 + 9600 + 38400.

Some would like to set it higher,

The second problem is:
> bandwidth=72000

Actually I see three sub-problems:
1. (if I remember/observed correctly) The value is downscaled to around ~55000 by the client, so we have a further loss of quality.
2. Imo higher values (starting around 100000) sound remarkably better (but maybe I am wrong; I don't know much about the audio stuff).
3. The default value in the client is also around this value and so I have to instruct all my participants to set that higher. I guess it would be in the best interest to set it higher by default, so if the server allows to use it, it can be used "automatically".

**Comment by grravity** [comment]
Trying to read through this and am getting lost, do we have a definitive answer as to the maximum rate that Murmur and Mumble can be set to? Ignoring any limitations with the client interface, and going through mumble.conf, what are the highest we can set to that actually works _(by actually works I mean setting it to 192000 if it actually will just ignore it and only use 128000)_?

On a sidenote, is the interface planned to be updated to remove this restriction to be more accurately represented, as I don't understand why this would even be restricted or be a hard thing to fix?

**Comment by Krzmbrzl** [comment]
I think the numbers TredwellGit has provided in his post are valid. I haven't checked them yet nor did I look into the details of how hard it'd be to remove the limit yet though :shrug:

**Comment by toby63** [comment]
I might be wrong, but I saw two question that I haven't seen a real answer for:
1. Do such high values really benefit the audio quality (or other factors?) much?
For example it was mentioned in mumble itself before (code, wiki etc.) that values over `130000` would not do much.
2. The standard setting should be a reasonable value imo and not the highest possible one imo. Instead you can mention higher values in the description.
3. The topics raised by @streaps were not answered imo:
https://github.com/mumble-voip/mumble/issues/3895#issuecomment-644012953

**Comment by TredwellGit** [comment]
Mumble on master has support for multichannel audio, better support for OPUS_APPLICATION_AUDIO, and the ability to disable most audio processing which all together means better support for music where bitrate matters more than for VoIP.

This is the maximum allowed bandwidth not default bandwidth. The individual clients only use more bandwidth if configured to do so.

I have used clients with Opus at high bitrates without issue. See: https://github.com/mumble-voip/mumble/issues/4351#issuecomment-754335916

**Comment by toby63** [comment]
The point is that the standard values in a configuration files are understood as recommended default values by the users.
So you should not recommend such a high value.
As I said, you can mention that in the description (both in the file itself and in docs) instead.

Use a reasonable value as default value.

**Comment by TredwellGit** [comment]
That is why the client GUI configuration prevents setting it higher than 240000.

**Comment by toby63** [comment]
> That is why the client GUI configuration prevents setting it higher than 240000.

That is not really an argument imo.
1. We have a server side and a client side and they should be discussed seperately.
2. 240000 is still much higher than 72000.

Your higher setting will increase the bandwidth usage by a lot, and that should not be the recommended standard setting.

**Comment by TredwellGit** [comment]
The server and client are separate. Clients have to deliberately choose to use more bandwidth. The audio wizard still recommends the same defaults. The bandwidth is client egress not per client. 72000 is not good because even with 1.3.3 the audio wizard recommends defaults that use more than 72000 and on master new features require more bandwidth.

Understand that the way Mumble manages bandwidth is fundamentally flawed since it does not account and adjust for how much is available and actually used.

**Comment by toby63** [comment]
> The server and client are separate. Clients have to deliberately choose to use more bandwidth.

I know; still it's possible.

> The bandwidth is client egress not per client.

Can you clarify that, I don't really understand what you mean.
I was refering to the wiki which says that it's 72000 bits per client needed for the server, so 4 clients=288000.
But I have to admit that I don't know much about this audio stuff, thus I am asking questions.

> 72000 is not good because even with 1.3.3 the audio wizard recommends defaults that use more than 72000 and on master new features require more bandwidth.

72000 are just an example, if they should increase thats possible. But further explanation would be good, like:
1. How much is necessary (lowest reasonable amount for example)? 
2. What new features are those and more importantly are they enabled by default?

> Understand that the way Mumble manages bandwidth is fundamentally flawed since it does not account and adjust for how much is available and actually used.

Well that could be changed; still it is no argument for setting it very high, just because some people (like you, I assume :wink:) want it so high.

---

Bottomline is:
1. What is there against more explanation (in the description etc.)?
2. What are reasonable default values and why?

**Comment by TredwellGit** [comment]
The clients send data at a rate they choose. The server then retransmits this data to all clients listening. Multiple clients can send at once and at different rates. It is much more complicated than clients multiplied by bandwidth.

The important information being that this does not increase bandwidth usage by default and that if you have bandwidth issues then changing the setting will not help you because it is flawed.

The reasonable default is to effectively remove the limit by setting it to 558000. Feel free to write a better description of what the setting does, but it should not even be used since it does not manage bandwidth properly at any value.

To be clear I am talking about the server setting.

See https://github.com/mumble-voip/mumble/pull/3753 for the client setting.

**Comment by TredwellGit** [comment]
Please read https://github.com/mumble-voip/mumble/issues/2184.

**Comment by toby63** [comment]
@TredwellGit In all that I haven't seen any arguments:
1. Why should the setting be useless, even if it is flawed? You set a maximum and in combination with the user maximum you should be able to control maximum bandwidth usage.
2. In what way is it flawed? (Only thing I noticed so far, is that the client will set it below the limit, which should not be the way to go)
3. What is the reasonable default now? I am quite sure it is not your value.

Why can't you write the description? It obviously belongs to it.
I don't have enough knowledge to write it.

**Comment by TredwellGit** [comment]
It is flawed because it does not manage bandwidth by adjusting for actual utilization, packet loss, congestion, etc but instead just places a cap on the max a single client can egress which is not useful in real world situations. It allows for the server to egress very large bandwidth while at the same time limits clients to very small amounts even if doing so is not necessary. With the previous defaults a server can send 712.8 Mbps yet clients can only send 72 Kbps. Even if there is no reason to limit the client it does. Even if the server will use too much bandwidth it allows it.

Do you actually have bandwidth problems with Mumble? I would rather fix real issues than document broken settings.

**Comment by toby63** [comment]
@TredwellGit So I agree that there could be a better setting with dynamic automatic handling of the bandwidth situation.
Still I don't see why the setting is unnecessary and broken.
Broken is something that does not work as intended.
And the setting is still good, because it is also annoying if you have fluctuations in quality all the time (which a super-dynamic function would potentially cause), so a cap or a range setting is good imo.

> Do you actually have bandwidth problems with Mumble? I would rather fix real issues than document broken settings.

There are people in the world with bad internet, pal.
Also I am against wasting resources all the time, you sound like one of those web devs who say "well modern computers have so much cpu and ram, we can use as much as we want". This is bad behaviour.
That is not the way things should work, especially not by default.

@Krzmbrzl Could we get a comment on this from you or the team.

**Comment by Krzmbrzl** [comment]
I approved and merge the PR so I guess my take on this is clear. I don't see an issue with the change as it does not lead to increased network traffic unless explicitly set up in the clients. And if a server wants to be more restrictive, they are free to do so.

More docs for the setting is probably a good idea. Any PRs concerning that are welcome

**Comment by toby63** [comment]
You accept a PR that changes something, without any explanation.
I don't see why it's necessary to change and why it should be optional to provide explanation and description for it.

**Comment by TredwellGit** [comment]
Without the change servers would have to be reconfigured to use new client features. There is a difference between needless inefficiency and supporting (and not using by default) new requirements.

**Comment by Krzmbrzl** [comment]
Continuing this decision is rather pointless I think. There don't seem to be new arguments on either side and thus for now I would say, let's leave it alone. Please only comment on this issue again, if you have **new** arguments.
If the same arguments are brought upagain, I will lock this issue.

But as I said: If someone has a good idea as to how the description in the ini file can be improved, feel free to create a PR.
