### ISSUE TITLE
No new snapshot since March 2019

### ISSUE THREAD

**Issue by trudnorx** [mumble-voip/mumble#3899]
Time for a new snapshot?

https://dl.mumble.info/

BTW, when is 1.3.1 going to be released? Will it include the OPUS_APPLICATION_RESTRICTED_LOWDELAY mode?

**Comment by Kissaki** [comment]
1.4.0 was released in August.

**Comment by Kissaki** [comment]
Currently no plans for 1.3.1. The 1.3.1 milestone hast just one bug to be fixed.

Generally the patch releases are for bug and security fixes, not feature releases. Adding more features could introduce new issues reducing stability of the release.

The focus should be 1.4.0 instead. I feel like we already have too many big changes in the pipeline, but those are necessary (tech upgrades for future maintainability).

**Comment by Kissaki** [comment]
What do you want a new snapshot for?

**Comment by trudnorx** [comment]
I want to try some of the new changes, isn't the point of snapshots that the user can stay up to date with latest changes on Git without having to wait for stable release?

**Comment by Kissaki** [comment]
Yes it is. I am not sure about the state of changes, or if we want to release one in the current state though.

@davidebeatrici Your thoughts?

**Comment by davidebeatrici** [comment]
I would like to build the first 1.4 snapshot with the new build environment, so that we will have our dependencies up-to-date.

The CMake project is almost complete, for all platforms we support.

**Comment by trudnorx** [comment]
Would be cool to try the new low delay mode.

**Comment by davidebeatrici** [comment]
Indeed.

**Comment by Kissaki** [comment]
@davidebeatrici Any ETA? Or where one would be able to track progress to stay up to date on what is still open?

**Comment by davidebeatrici** [comment]
I didn't open a dedicated issue, but I can write future updates in this one.

Right now I'm working on gRPC support on Windows, aside from that only Ice is missing.

**Comment by Kissaki** [comment]
If our buildenv is able to release 1.4.0/master snapshots (with little effort) I think it would still be worthwhile to do so. As was pointed out master already contains some changes that are worth to be tested (or used). We don’t lose anything by doing so, and (from my limited view) I am not confident in the buildenv working in the (very) short term but only mid term - in a few weeks time rather than few days.

I think build env progress information would be better fit in a corresponding ticket on the build env. Although if it is a blocker to a snapshot release I guess updates on that are helpful here as well.

Either way this ticket should be renamed to either a feature request or a task. As we do plan to release one eventually I think it should be a task rather than a feature request.

**Comment by trudnorx** [comment]
I think it's time to release another snapshot

**Comment by Kissaki** [comment]
I asked @davidebeatrici a few weeks ago and he said our current build environment can not build master/snapshots.

We will have to finish #3996 and our new build environment for/including dependency management [mumble-releng-experimental/milestone/1](https://github.com/mumble-voip/mumble-releng-experimental/milestone/1) for this.

Then we will be able to release a snapshot, and do so. As such, I am closing this. (This ticket was and is formulated more as a question than a task.)
