### ISSUE TITLE
Make Log more User friendly to Read.

### ISSUE THREAD

**Issue by Stefan-comkmits** [mumble-voip/mumble#3908]
><W>2019-12-01 18:15:40.187 1 => CELT codec switch ffffffff80000010 0 (prefer ffffffff80000010) (Opus 1)

><W>2019-12-01 20:06:22.955 1 => CELT codec switch ffffffff8000000b 0 (prefer ffffffff8000000b) (Opus 1)

Is this Opus,or Celt?
Is there more as Celt 0.7/0.11/Opus as Version?

I use 1.3.0 on my PC,i think the First message mean Opus,and the Second mean Celt.
But i confused.

><W>2019-12-01 18:17:33.135 1 => Registration: SSL Handshake error: The certificate has expired

What Cert has Expired.

**Comment by Krzmbrzl** [comment]
These are messages logged to the console and not to the Mumble UI, aren't they? If so I'd say these are more or less Debug-messages.
Are there corresponding log entries in the Mumble UI?

**Comment by Stefan-comkmits** [comment]
>These are messages logged to the console

Yes,in the Console.

>Are there corresponding log entries in the Mumble UI?

No.

>If so I'd say these are more or less Debug-messages.

Of course,but i find god to know what the entries mean as And User too.

**Comment by Krzmbrzl** [comment]
Re-considering this issue I think these messages are only relevant for debugging purposes and for that you either have to know the code (in which case you'll also understand the messages) or you'll report your problem here on GitHub and copy&paste them here (in which case you don't have to understand them).

Therefore I think that it's not worth it to redesign debug messages to be friendly on the end-user that doesn't know the code.
