### ISSUE TITLE
The command setting superuser password returns exit code 1 even if successful.

### ISSUE THREAD

**Issue by nekatak** [mumble-voip/mumble#3911]
Trying to set the superuser password as described in the documentation (https://wiki.mumble.info/wiki/Running_Murmur#Setting_the_SuperUser_Password) seems to be returning exit code 1.

The output of the command is shown here:
```bash
root:~# murmurd -supw password
<W>2019-12-05 12:19:46.378 SSL: OpenSSL version is 'OpenSSL 1.1.1d  10 Sep 2019'
<W>2019-12-05 12:19:46.378 Initializing settings from /etc/mumble-server.ini (basepath /etc)
<W>2019-12-05 12:19:46.666 MetaParams: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<C>2019-12-05 12:19:46.666 Successfully switched to uid 117
<W>2019-12-05 12:19:46.698 ServerDB: Opened SQLite database /var/lib/mumble-server/mumble-server.sqlite
<W>2019-12-05 12:19:46.698 ServerDB: Using SQLite's default rollback journal.
<F>2019-12-05 12:19:46.730 Superuser password set on server 1
root:~# echo $?
1
```

This is happening on a Debian 10 installation with the package mumble-server.
```bash
root:~/# uname -a
Linux home 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux
```

The same exit code is returned from a command like:
```
echo -n "password" | murmurd -readsupw
```
Which makes password creation difficult to use it in a script.

**Comment by Kissaki** [comment]
How do you read out the superuser password?

The log says it set it for (virtual) server 1. Is that the one you are checking or possibly a different one?

**Comment by nekatak** [comment]
The password in this case is set correctly. I m checking it by logging into the server with the mumble client (debian package). But the status code should be 0 since it s successful.

**Comment by DanielMowitz** [comment]
I currently have the same issue as this breaks the entrypoint of the [docker image](https://github.com/sudoforge/docker-images/tree/master/murmur) I use.

**Comment by Krzmbrzl** [comment]
Yeah I can reproduce. I'll take a look at the cause of this right now. In theory it shouldn't be hard to track down the issue ^^

**Comment by Krzmbrzl** [comment]
Okay I found what the problem is: Inside mumur's main-function `qFatal` is being used for normal log-statements after which the program shall terminate.
The abuse of this function didn't have much effect until https://github.com/mumble-voip/mumble/commit/abdb5004bb92b28271673e33df9cc3e314f5711a introduced an exit code of 1 if a fatal log is encountered (which by itself is quite sensefull).

In this concrete example we are talking about this line in which it is logged for which VServer the password has been set:
https://github.com/mumble-voip/mumble/blob/b97baa1559425656adb3979d5b821631e52a26f9/src/murmur/main.cpp#L461
