### ISSUE TITLE
Case-sensitivity of AccessTokens

### ISSUE THREAD

**Issue by Krzmbrzl** [mumble-voip/mumble#3926]
https://github.com/mumble-voip/mumble/blob/61ee9ddf6d425d4da0bbe871280b6764d4409098/src/Group.cpp#L143-L144

From this code-fragment, I take it that Mumble's access tokens are treated in a case-insensitive way. Given the fact that these tokens are (more or less) the equivalent of a password, this makes me feel a bit uncomfortable:
1. I suspect most (new) users expect passwords to be treated case-sensitive (I actually don't know another application that does it otherwise)
2. This decreases the security of those passwords/tokens quite a bit as it reduces the amount of unique combinations of inputs (potential passwords). For simple channel-access this is not a big deal (I guess) but as https://github.com/mumble-voip/mumble/issues/3858#issuecomment-544180895 suggested that these AccessTokens might be used for SuperUser-registration, this becomes more of a concern.

Thus the question: Why was it chosen to be case-insensitive? And maybe more importantly: Should it stay like this?

**Comment by Krzmbrzl** [comment]
In any case, I think we should add some sort of global/static variable holding the flag for case-sensitivity of those tokens that is being used in the Mumble's code (instead of directly using the Qt-flag) so that this can be changed very easily in the future (can be done by changing the value of that one variable instead of having to search the code for all occurrences).

**Comment by Kissaki** [comment]
It was implemented this way in 9c5ecca3704ed66a98c4c7611888b01aab5caadd without a naming an explicit reason.

I guess it makes sense this way when passwords are passed in voice form rather than text form especially. Having to annotate encapsulation when dictating a password is cumbersome and error prone. And even without this reasoning, it would be a source for user errors.

That is not to say that case sensitivity could have a good use case as well, e.g. if it were used and passed in a more technical manner.

Security/Strength vs convenience is always a balance to consider and strike. End users mostly care for convenience. We support and advocate user certificates and ACL groups for secure authorization. Access tokens aka passwords are not as strong as those at all, and they probably should not be used for a permanent, strength-demanding use case. Whether the passwords are case sensitive or not is only a small difference. Users could still use short passwords over long ones.

**Comment by Krzmbrzl** [comment]
I don't think it is that hard to communicate a password case-sensitively via voice. And if I think that to be a problem, I can still simply make everything lowercase and be done with it.

Users choosing short passwords is of course always the bigger concern than case-sensitivity and certificates are obviously the more secure verification method.
However since we have passwords in place, we might as well make them as secure as possible. If a user chooses a 4 character password consisting of the 26 letters, there are 26^4 = 456,976 possible permutations when ignoring case and 52^4 = 7,311,616  permutations when taking case into account. There's a factor of 16 between them, which is quite a bit.

Therefore I'd still vote for case-sensitivity, though I see the reasoning against it as well...

**Comment by Krzmbrzl** [comment]
Since no one else participated in this discussion, I assume that this is nothing the majority of users want to be changed. And as such, I guess we'll leave it as it is.

Thus I created a PR to
> add some sort of global/static variable holding the flag for case-sensitivity of those tokens that is being used in the Mumble's code

which will close this issue, if merged.
