### ISSUE TITLE
Allow alternative configuration files for client

### ISSUE THREAD

**Issue by rafaelbonifaz** [mumble-voip/mumble#3953]
**Context** 

It would be nice to be able to start mumble with an alternative configuration file. That way an user could start Mumble without touching the the default configuration settings. In our case we plan to bundle Mumble in another application and start it with specific settings, without touching the system Mumble configuration.

**Describe the feature you have in mind**
It would be nice to start mumble with something like: 
```
mumble -f Mumble.conf
```
or
```
mumble -f Mumble.conf mumble://url
```

**Comment by davidebeatrici** [comment]
We should probably add an option to specify a different database file too.

**Comment by rafaelbonifaz** [comment]
Agree

**Comment by zBeeble42** [comment]
Copying in at least a tiny bit of content and reasoning from the ticket I opened ( #4343  ) ...  I'm a D&D DM.  I need to provide multiple streams into the room.  Multiple streams let different participants adjust the individual volumes of the streams (say mood music, ambient sounds, sound effects and my voice).  I achieve this now using the -m and -n switches, but this is massively suboptimal.  Each of the instances requires different settings --- which get overwritten depending on which client quits first ... and using both -m -n clients and regular clients involves an order to starting things.

All of this would be relatively simply fixed if you either added a -config switch or a -confdir switch (the latter could put both the config file and the database in a subdirectory).

**Comment by toby63** [comment]
@Krzmbrzl 
Maybe we could rename this, so it can be found easier?
like: `Allow alternative configuration files/ config flag` or something similar.

**Comment by Krzmbrzl** [comment]
I don't think the name you suggested would actually facilitate finding this issue... And I think the current title describes the issue pretty well, which is why I don't think it is necessary to change it :thinking:

**Comment by toby63** [comment]
> I don't think the name you suggested would actually facilitate finding this issue... And I think the current title describes the issue pretty well, which is why I don't think it is necessary to change it thinking

I just noticed that while I was searching for this (because of the duplicate), I couldn't find it immediately, so I needed to go through all feature requests to find it.

Maybe we could at least add some words like `Mumble`, `client`, `mumble.conf`?
Example: `Allow alternative configuration files for client`
Because besides the obvious reason for duplicates (which is lazyness), in this case it might be that people don't find this issue.

**Comment by Krzmbrzl** [comment]
That's usually what tags are for (and this issue already has the "client"-tag) - I'll change it to your suggestion anyways though :)

**Comment by Popkornium18** [comment]
I want to implement this. I came up with 2 different approaches and I would like to hear what you would prefer.

#### Config-Switch and DB-Switch

This would be the obvious approach. Add a `--config=...` option and a `--database=...` option. It is pretty flexible as you can specify whatever path you like and it will work. However it is also annoying since I can't imagine a situation where you would want only a different config but the same database. So you always have to specify both and remember their paths (which most people would probably alias)

#### One switch for both

The other approach (and the one I prefer) would be to let the user specify a configuration **name** like `--config=musicbot`. This would create a `musicbot.ini` configuration file and a `musicbot.sqlite` next to the regular config and database. This would be way more convenient as the user does not have to worry about config/DB paths and would only have to remember the config name. 
What I dislike about this approach is that it is rather unusual, as most other tools expect a _path_ to a file for the `--config` switch. Furthermore it doesn't allow to specify different paths as everything would be placed next to the regular files. But I think that's noi big deal since most people probably don't care about the path.

**Comment by davidebeatrici** [comment]
What about setting the database path in the configuration file?

**Comment by Popkornium18** [comment]
Also a viable Option. That's indeed cleaner as two seperate switches.

**Comment by zBeeble42** [comment]
While any of the proposed options would work in my situation, I lean towards the db being set in the config as the cleanest and most obvious solution.  It satisfies POLA (Path Of Least Astonishment).  If, indeed, there is reason to share a DB, you're simply providing the gun with which the user could choose to shoot themselves in the foot.

**Comment by Krzmbrzl** [comment]
I also like the config option in the ini.

**Comment by rkachach** [comment]
Thank you very much for this great feature. I'm interested in using this "configuration file" to configure the client input/output audio devices but I cannot find anywhere which format should this configuration file have. Is this documented somewhere?

**Comment by Popkornium18** [comment]
Just start the client with the configuration file parameter and set the options in the GUI. The changes will be saved to the config file that you specified.

**Comment by rkachach** [comment]
Ok, thank you very much, and congrats for this great feature. I'll try it. 

Anyway it would be good if the authors can provide some example of the configuration file so it can be used as starting point.

**Comment by Krzmbrzl** [comment]
The client configuration files are semi-binary and are not easily modified (and in fact not really meant to be modified manually)

**Comment by rkachach** [comment]
I see, I was able to generate a file and use it. Actually it has some binary entries on it ( in the form of @Bytearray) anyway as it is it basically fulfill my needs since I can launch mumble with two different configurations (switch between two different audio configuration: wired and bluetooth speaker). Thank you very much for this great feature and for the support 👍

**Comment by atrapero72** [comment]
Hi, 
I need to run multiple instances of mumble with different audio inputs and outputs.
what is the command line to create the new config file?
I've tried everything and I can't get it to save the new file.
I can't find the config file either
This is the line that I try but I can't get it to save the new file:
C:\Program Files\Mumble\client>mumble -c audio2


Thanks

**Comment by Krzmbrzl** [comment]
You'll have to use `-m` in addition to `-c`

**Comment by atrapero72** [comment]
I've created a bat file with the commands I need, but I can't get it to load different settings for the two mumbles.
This is how I do it:

start /b mumble.exe -m mumble://user:password@ip:64738/Channel1
start /b mumble.exe -m mumble://user:password@ip:64738/Channel2

Its work but If I put "-c anyname" after -m it doesn't work

**Comment by Krzmbrzl** [comment]
What doesn't work? Starting multiple Mumble instances?

**Comment by atrapero72** [comment]
Hi, Krmbrzl and thanks for your help
When I run the command :

start /b mumble.exe -m mumble://user:password@ip:64738/Channel1
start /b mumble.exe -m mumble://user:password@ip:64738/Channel2

It works and opens multiple instances.

When I run the command:

start /b mumble.exe -m -c "channel01" mumble://user:password@ip:64738/Channel1
start /b mumble.exe -m -c "channel02" mumble://user:password@ip:64738/Channel2

with -c no longer works

I don't quite understand how I have to put the -c variable to make it work

Thanks again

**Comment by atrapero72** [comment]
It works now.
I just had to create the ini file and put it in the mumble folder before running the command. My fault

Thank you so much

**Comment by Krzmbrzl** [comment]
I'm glad you figured it out :)
