### ISSUE TITLE
Spamming Mute Button overloads mute behaviour

### ISSUE THREAD

**Issue by theAkito** [mumble-voip/mumble#3968]
**Describe the bug**
When you spam the mute button really quickly, it stops muting/unmuting after a couple of seconds, when you are still spamming. You have to wait a couple of seconds after stopping to press the button and then it works again.

**Steps to Reproduce**
1. Spam your _Mute_ button.
2. Notice how you don't get muted/unmuted anymore.
3. Wait a couple of seconds.
4. _Mute_ button works again.

**Expected behavior**
Even when spamming the mute button, I expect the mute button to work.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
Windows 10
 - Version: [e.g. Mumble 1.3 or Murmur 1.3]
Mumble (1.3.0)

**Comment by davidebeatrici** [comment]
It's the rate limiter, implemented in Murmur 1.3.

See #3510.

**Comment by Krzmbrzl** [comment]
So basically the problem is that muting goes through the server as it has to notify other clients about your mute-change. And the server has the mentioned rate limiter preventing you from spamming messages to the server. Thus it stops working after some amount of messages in a certain time interval.

Do you have a special scenario in which you actually have to spam the mute button or is this just something you happened to notice?
