### ISSUE TITLE
Failed to create communication with overlay 

### ISSUE THREAD

**Issue by totalnooob** [mumble-voip/mumble#3970]
Hello on every startup of mumble 1.3 i get this error Failed to create communication with overlay at MumbleOverlayPipe QLocal ServerPrivate add listener Acces is denied 
Is it possible to disable this pop up?
Thanks

**Comment by Krzmbrzl** [comment]
Well this "pop-up" seems to be the symptom of a bug. Thus "disabling" it would require fixing the bug...

**Comment by Krzmbrzl** [comment]
The error seems to come from here
https://github.com/mumble-voip/mumble/blob/c2469ac29cc9761b8d90de958ab37573858db272/src/mumble/Overlay.cpp#L218-L219

@totalnooob what version of Mumble are you using and what OS? Did you encounter anything out of the ordinary besides that pop-up? Are you starting Mumble in any special way? 

@Kissaki or @davidebeatrici do you know what seems to be the problem here?

**Comment by totalnooob** [comment]
@Krzmbrzl Im running windows server 2016 everything works fine besides the popup this only appear on local users without admin rights

**Comment by Krzmbrzl** [comment]
Why are you running Mumble on Windows server? I mean I'd expect murmur to be run on servers and Mumble to run on clients only...

> this only appear on local users without admin rights

Ah so if you start Mumble with Admin rights, this error doesn't happen?
In that case I think the answer to the problem is that Mumble tries to create that pipe (a file) but doesn't have the permission to do so. That's what is causing the error. 

From what I have seen in the code that pipe file is being created in the home directory of the user. Do you have any special write access rules in place on your server?

**Comment by Krzmbrzl** [comment]
In any case, I think we should probably include the returned error message from `QLocalServer::errorString()` into the pop-up text in order to show more clearly what the error is...

**Comment by totalnooob** [comment]
im using windows server desktop experience with both murmur and client running with admin right it doesnt show the popup

**Comment by Krzmbrzl** [comment]
Yeah then it's a permission problem on your server that causes this problem.

The only thing that comes to my mind what you could try is giving the user that runs Mumble wrote access to the home-directory as well as Mumble's installation directory. The pipe file should be created in either of those, I think :thinking:

**Comment by totalnooob** [comment]
Hello added local user all permissions to folder but still the same popup

**Comment by Krzmbrzl** [comment]
You could try monitoring via FileAudit which file is attempted to be accessed: https://community.spiceworks.com/topic/2013112-is-it-possible-to-track-who-accessed-a-file-and-when

If that doesn't help you, I'm afraid I won't be able to help you any further as I'm not using Windows. I can only tell you that I'm 99% certain that this error is a permission problem that exists on your installation...

**Comment by totalnooob** [comment]
https://imgur.com/MytQLzt

**Comment by Krzmbrzl** [comment]
Find an entry that is about a file named `MumbleOverlayPipe` (potentially prefixed by a dot). It should have a "Denied" state.
This of course will only show up after you have started Mumble and got that pop-up. 

Once you found the entry, you can see the full path to that file and as what user the file was tried to he accessed. Based on that you/we might figure out how to set these permissions properly.

**Comment by totalnooob** [comment]
Nothing with that name

**Comment by Krzmbrzl** [comment]
But you did start Mumble and you did get that pop-up again?

Is there any file access logged that does **not** have status "Granted"? If so, which ones are these?

Could you please post a screenshot of the pop-up? I want to look at the exact error message...

**Comment by totalnooob** [comment]
Yes still getting the popup. One file showed in the app not sure what it is
![TeamViewer_2020-02-21_16-14-31](https://user-images.githubusercontent.com/31215293/75046458-65b6f100-54c5-11ea-9f90-eb77256fc788.png)

**Comment by Krzmbrzl** [comment]
Aha that error message might actually be caused by something more subtle than a simple file access error...
It I dictates that the error occurred somewhere in here: https://code.woboq.org/qt5/qtbase/src/network/socket/qlocalserver_win.cpp.html#_ZN19QLocalServerPrivate11addListenerEv

Looking at the linked source code and cross-referencing it with https://stackoverflow.com/questions/14313036/createnamedpipe-causes-error-access-denied I kind of have the feeling that Windows server does need some security descriptor that plain old desktop windows doesn't need. And as far as I can see, we don't set such a descriptor.

Thus this might be a bug in Mumble after all :thinking:

It might still be a problem with some access permissions on your specific server though. To be sure, we'd need someone willing to test this on another windows server. If he or she encounters the same problem, we'll know it's likely Mumble's fault... 

@davidebeatrici you don't happen to have access to a windows server you could test this on?

**Comment by Krzmbrzl** [comment]
From https://doc.qt.io/qt-5/qlocalserver.html#socketOptions-prop I take
> By default none of the flags are set, access permissions are the platform default.

This is the crucial part I think. I take it that on Linux and Windows desktop these defaults are enough for us but that Windows Server has more strict access options in place as the default and thus it fails.

The question is: Which access option should we go for? (https://doc.qt.io/qt-5/qlocalserver.html#SocketOption-enum)
I think we should use `QLocalServer::WorldAccessOption` as we don't want to restrict anything from talking to the Mumble overlay via that pipe (I guess?)

**Comment by Krzmbrzl** [comment]
Via IRC it has been reported that the issue did not occur on a Windows Server 2008.

**Comment by Krzmbrzl** [comment]
@totalnooob does anything seemingly related show up in the event log (https://www.dummies.com/computers/operating-systems/windows-10/how-to-use-event-viewer-in-windows-10/)?

**Comment by totalnooob** [comment]
nothing in event log it would be fine if we just disable it i wanted to make that mumble will automatically start on logon in background. We use it as language lab so students in class communicate in groups. On starting the murmur server students should automatically connect to the server withtout any student interaction with the software

**Comment by Krzmbrzl** [comment]
It appears as someone already thought about not creating the Overlay object if the overlay is disabled but noone seems to haev come around actually implementing it...
https://github.com/mumble-voip/mumble/blob/1ffbbc44d146bb974611fd93ebdfe606405b4d79/src/mumble/main.cpp#L437-L441

@totalnooob do you happen of being capable of compiling mumble on your server? If so we could test my suggested fix quite easily. If not I'll have to try to build an installer with the test-version for you... :thinking:

**Comment by totalnooob** [comment]
thanks for reply im not sure how to do it downloaded the visual studio and added the project from git but dont know how to compile it

**Comment by Krzmbrzl** [comment]
All good then we'll have to figure out a way to get you the installer. Would simply have been the easiest route if you happened to be familiar with compiling c++ projects on windows :)

**Comment by totalnooob** [comment]
@Krzmbrzl Will you have time to do it? When i tried to open the sln in the installer folder in vs community 2019 it shows that is unsupported project

**Comment by Krzmbrzl** [comment]
I have planned to look into it in the next couple of days. AFAIK we are building the installer on our CI servers anyways so the only issue will probably be getting it out of the server so we can get a hold of it...

**Comment by Krzmbrzl** [comment]
@totalnooob could you try downloading the WindowsInstaller from https://dev.azure.com/Mumble-VoIP/Mumble/_build/results?buildId=1276&view=artifacts&type=publishedArtifacts, install it on your server and check whether the problem still exists?

This is a snapshot of the current master branch (aka a Mumble 1.4 snapshot) + my proposed fix for your specific problem. Let's hope it does the job :)

**Comment by totalnooob** [comment]
@Krzmbrzl  Thanks works fine can i disable to check for new version
![mumble_2020-03-03_13-08-05](https://user-images.githubusercontent.com/31215293/75774327-0c19b680-5d50-11ea-96c7-092357b37bd5.png)

**Comment by Krzmbrzl** [comment]
Perfect :+1:

Yes this can be configured in the settings. That'd be Configure > Settings > Network > Mumble Services
I guess you want to disable `Check for application updates in startup` and should be good with that. You may also want to disable `Download plugin and overlay updates on startup` as well :)

**Comment by totalnooob** [comment]
Hm i got the option grayed out also i have question is it possible to change name of the software? Instead of mumble -- 1.4.0 318 to have custom name?
![mumble_2020-03-03_14-27-41](https://user-images.githubusercontent.com/31215293/75780172-2b6a1100-5d5b-11ea-8215-b43b96c16635.png)

**Comment by Krzmbrzl** [comment]
> Hm i got the option grayed out

Ah yeah apparently checking for updates is enforced for snapshot builds :man_shrugging: 
To me it makes sense that one would want people using snapshots to always update to the newest version, but I kind of disagree with forcing these updates onto them. If you explicitly set your settings to not be bothered with updates, I think snapshots should respect that as well. I'll open a PR for this, but I can't promise the other devs will agree :point_up: 
https://github.com/mumble-voip/mumble/blob/ec51a41cfe7a348d08c40468bc49aca0dbd3e9d8/src/mumble/NetworkConfig.cpp#L67-L70

>  i have question is it possible to change name of the software? Instead of mumble -- 1.4.0 318 to have custom name?

No - unless you compile it yourself.

**Comment by totalnooob** [comment]
Where can i find the source files to the version you sended can i edit it so i dont get the update notification?

**Comment by Krzmbrzl** [comment]
They're in #3982 and the patch allowing you disable the update notification is in #3984

**Comment by totalnooob** [comment]
@Krzmbrzl   when i try to compile it at this step 
To generate Makefiles for use with the build environment, run the following:

    c:\users\builder\mumble> qmake -recursive main.pro CONFIG+="release static tests warnings-as-errors no-elevation"

i get error 'qmake' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Krzmbrzl** [comment]
You're trying to build on Windows, right? I have no clue how to do that. You can join our IRC (via Matrix) and ask there. We do have people that managed to build on Windows but it is really cumbersome to set up. We just had someone who tried it for a few days and resided to build it on a Linux VM instead because it didn't work. That doesn't mean that it can't be done, but it is rather hard.

This will change though as soon as our new build environment is ready (we're switching to cmake). This should be the case sometime soon(ish).

IRC: https://riot.im/app/#/room/#mumble:matrix.org

**Comment by totalnooob** [comment]
https://wiki.mumble.info/wiki/BuildingLinux
With this guide i can build it to windows ?

**Comment by Krzmbrzl** [comment]
No - these are the instructions for Linux. You'd have to follow https://wiki.mumble.info/wiki/BuildingWindows
