### ISSUE TITLE
Voice is transmited to multiple channels

### ISSUE THREAD

**Issue by totalnooob** [mumble-voip/mumble#3992]
Hello,
im getting this bug when user can hear another user in different channel(group),  did anyone reported this issue? It only happens occasionally  its hard to reproduce it. Do you have any idea how to fix it? We are using it in school with 20 logged in local users. 

 - OS: Windows server 2016
 - Version: Mumble 1.3

**Comment by Krzmbrzl** [comment]
What version of murmur (the server) are you using? Also 1.3? Is it also running on the windows server?

Does this happen with only part of what is being said or

**Comment by totalnooob** [comment]
Yes the murmur is the same version and its running on the same server it happens that one user in different group can hear teacher whitch is admin account

**Comment by Krzmbrzl** [comment]
So a normal user hears everything the teacher (with the admin account) says even though the teacher is in another channel?

By admin account you mean an account that has full access to the server or do you mean the `SuperUser` account in particular.

Does the problem persist if the teacher uses an account without admin privileges?

Are you sure the teacher is not by accident using the whisper or shout functionality of Mumble? Are there shortcuts configured for either of the two that might get triggered by accident?

**Comment by Krzmbrzl** [comment]
Oh and is it always the same user who can hear the teacher unwanted or does it vary?

**Comment by Kissaki** [comment]
We have multiple features that would allow this to happen as an intended feature. Please make sure this is not one of them.

Linked channels allows an admin to link channels together and further configure who hears whom under what conditions with ACL rules. These linked channels are identifiable to the end user through styling; namely cursive captions (when inside of it).

The shouting feature allows you to bind push to talk keys to shout to [other] channels instead of simply talking in the default context (the channel).

The whispering feature allows you to whisper to individual users.

All these can be denied through the servers configuration. But from your description it seems very likely to me you are using one of them either accidentally, or someone else is using them on you without your realization.
