### ISSUE TITLE
Update OpenSSL binaries for 1.3.1

### ISSUE THREAD

**Issue by SC1040-TS2** [mumble-voip/mumble#4001]
**Context**
The current OpenSSL library implemented into Mumble (1.0.2k as of 1.2.19) has had an expired long-term support for a few months now. With this in mind, and given the latest OpenSSL version supports TLS 1.3 among other features, it is highly recommended to update to the newer binaries for security purposes for the 1.4.0 Mumble client release.

**Describe the feature you have in mind**
Update OpenSSL binary packages to 1.1.1e or a later current version of 1.1.1.

**Describe alternatives you've considered**
If not retention of the current unsupported library or moving to a different TLS library, there may not be any alternatives.

**Additional context**
https://www.openssl.org/blog/blog/2018/09/11/release111/ was the initial release announcement. I have yet to find the specific release notes for 1.1.1e at this time, but will edit it in later if possible.

**Comment by Krzmbrzl** [comment]
I assume you are referring to the OpenSSL that is built into the windows application? 'cause to my knowledge we use dynamic libraries on Linux and thus we don't have influence on what version is actually being used.

I assume that we'll update the libraries for the static build as soon as the new build system (cmake) has been integrated. 
/cc @davidebeatrici @ZeroAbility

**Comment by SC1040-TS2** [comment]
Yes, I am, @Krzmbrzl, for my use case is the Windows x64 build. However, a basic Linux end user whom does not use dynamic libraries may also be affected.

Based on prior version release notes found on the old wiki.mumble.info site, 1.2.16, 1.2.17, and 1.2.19 were the last times major releases of OpenSSL binaries were implemented, as evidenced here.

1.2.16(Relevant because some servers and clients are still on it.): https://wiki.mumble.info/wiki/1.2.16
1.2.17(The HopelessDemocracy.com server is still on it.): https://wiki.mumble.info/wiki/1.2.17
1.2.19(Most non-1.3.0 servers and clients still use this version.): https://wiki.mumble.info/wiki/1.2.19

**Comment by SC1040-TS2** [comment]
Also keep in mind that updating the static binary packages may help open the door to resolving https://github.com/mumble-voip/mumble/issues/3918 in the future.

**Comment by Krzmbrzl** [comment]
What has to be kept in mind though is that we can only use features of OpenSSL that are included in the version that ships with the oldest Ubuntu LTS. Right now this is Ubuntu 16.04 which ships with OpenSSL 1.0.2g (https://packages.ubuntu.com/xenial/openssl).

This doesn't mean that we can't include newer OpenSSL versions in the windows build but in terms of what features we can implement into Mumble, this is the restriction.

**Comment by toby63** [comment]
Also seems to be a problem in the static server builds:
```
SSL: OpenSSL version is 'OpenSSL 1.0.2k  26 Jan 2017'
[...]
Murmur 1.3.1 (1.3.1-rc1) running on X11: Debian GNU/Linux bullseye/sid: Booting servers
```

I don't know if thats possible, but could you at least include "OpenSSL 1.0.2u" into the static builds?
See Website:
> 20-Dec-2019 | OpenSSL 1.0.2u is now available, including security fixes

Also a note for downloaders of a static build would be nice.
Using EOL software depencies is considered a security issue by default.

**Comment by toby63** [comment]
@Krzmbrzl @mumble-voip @Kissaki @davidebeatrici 
You should at least switch to openssl v.1.0.2u (best bad option) and that should already be implemented in Release 1.3.1.
So I recommend a milestone change (1.3.1) and setting the priority (at least P1, maybe even P0-blocker).

For those arguing that it should wait till #3918 is solved, I disagree.
You are providing an openssl version from **2017(!)**, so you should at least switch all windows users and static server build users on linux to the newest available version, which is 1.0.2u (from December 2019) asap.

**Comment by davidebeatrici** [comment]
Yes, Mumble can already be compiled with OpenSSL 1.1, but doing that for 1.3.1 would require us to update Qt as well, dropping support for Windows XP.

1.4 will, of course, be released with up-to-date dependencies.

**Comment by toby63** [comment]
@davidebeatrici @mumble-voip @Kissaki @Krzmbrzl 
> Yes, Mumble can already be compiled with OpenSSL 1.1, but doing that for 1.3.1 would require us to update Qt as well, dropping support for Windows XP.

So you prefer delivering EOL (and by now extremly outdated) openssl software (which is crucial, because encryption is one of the most important parts), to support an OS that is EOL for **6(!) years**?
I very much hope you reconsider that.

* And am I understading correctly that mumble could just use openssl v.1.1.1 (on windows builds) right now?
* And why is the static server build for linux not using the newest openssl? 
(and don't give me "support for super old distros" as an explanation, they can use their super outdated packages if they want to)

**Comment by Kissaki** [comment]
None of what you want is trivial. We do what we reasonably can and what makes sense. We do not intend to support XP going forward. But we do value stability and not taking in unnecessary risks. The more we change the higher the risk something breaks. There’s good reasons for the split between minor and patch release being conceptually different.

EOL does not necessarily mean there are issues. Obviously it’s a pressing manner. But that does not mean it’s clearly the best choice to upgrade, or that it is simple or practical.

**Comment by davidebeatrici** [comment]
Also, we already dropped support for Windows XP in `master` (1.4).

Minor and patch releases should NEVER drop support for a platform, even if EOL.

Since OpenSSL is the most important component (in terms of security), we are going to build 1.3.1 with OpenSSL 1.0.2u: mumble-voip/mumble-releng#90.

**Comment by toby63** [comment]
@Kissaki:
> None of what you want is trivial.

I would like to hear a bit of detail.
Thus the question I asked above:
>> And am I understading correctly that mumble could just use openssl v.1.1.1 (on windows builds) right now?

Because #3053 indicates to me, that it is not such a big problem.
But maybe I'm wrong, a little detail would be useful to better understand the situation.
* Is a new API the problem? (and there is no compatibility?) 
Does not seem to be the case, because why can I then build mumble against OpenSSL 1.1.1f?
* Is Windows the problem?
Why then can't the static server build for linux be using openssl 1.1.1?
* And a change to OpenSSL 1.0.2u is not trivial?

> We do what we reasonably can and what makes sense.

I saw that in the completely outdated openssl version.

> But we do value stability and not taking in unnecessary risks.

Yeah very plausibel by using an openssl version from 2017 :facepalm: .

> EOL does not necessarily mean there are issues.

Once again I wonder if thats also your approach at work. I hope not.

@davidebeatrici 
> Minor and patch releases should NEVER drop support for a platform, even if EOL.

So thats important to keep, but not updating the "most important" part. Very logical.
I don't understand that, version numbers are mostly arbitrary, so what does it matter, if its 1.3.1 or 1.4 or 2.5?
If it matter so much, rename things. The question here is, what is more important?
My answer is clear.

>Since OpenSSL is the most important component (in terms of security), we are going to build 1.3.1 with OpenSSL 1.0.2u: mumble-voip/mumble-releng#90.

The best bad solution. 

I guess the other depedencies are also outdated beyond belief?
You really should change that. :pray:

**Comment by davidebeatrici** [comment]
> - Is a new API the problem? (and there is no compatibility?)
    Does not seem to be the case, because why can I then build mumble against OpenSSL 1.1.1f?

Right.

> - Is Windows the problem?
    Why then can't the static server build for linux be using openssl 1.1.1?

We would like to keep our dependencies synced across all platforms.

> - And a change to OpenSSL 1.0.2u is not trivial?

I'm pretty sure @Kissaki was referring to OpenSSL 1.1, which (as I said in my previous message), requires updating Qt.

And we're fortunate we didn't update to the latest LTS (5.12.5): https://bugreports.qt.io/browse/QTBUG-83450

> So thats important to keep, but not updating the "most important" part. Very logical.
I don't understand that, version numbers are mostly arbitrary, so what does it matter, if its 1.3.1 or 1.4 or 2.5?
If it matter so much, rename things. The question here is, what is more important?
My answer is clear.

> The best bad solution. 
>
> I guess the other depedencies are also outdated beyond belief?
You really should change that. :pray: 

@Kissaki can probably explain our versioning scheme clearly.

As for security: it's more important than keeping support for an EOL platform. However:

1. OpenSSL 1.0.2 is not EOL.
2. OpenSSL 1.1 brings TLS 1.3 to the table, but TLS 1.2 is not considered insecure yet.
3. Maintaining support for Windows XP doesn't automatically make the software insecure.

Our mistake was using outdated dependencies, which happened because 1.3.0 was supposed to be released in 2017 rather than 2019...

Please inform us whether there are other dependencies we should update for 1.3.1.

**Comment by streaps** [comment]
> * OpenSSL 1.0.2 is not EOL.

It is EOL:
https://www.openssl.org/blog/blog/2018/05/18/new-lts/
https://www.openssl.org/blog/blog/2019/11/07/3.0-update/
_Note that as previously announced OpenSSL 1.0.2 will be End Of Life at the end of this year [2019]. This means there will not be any further public updates or security fixes to the 1.0.2 branch from then. This gives another strong reason for existing 1.0.2 users to upgrade to 1.1.1 as soon as possible._

Releasing 1.3.0 with openssl 1.0.2 only a few month before 1.0.2's EOL was an oversight. I would consider it a bug, that should be fixed in 1.3.1.  

> * Maintaining support for Windows XP doesn't automatically make the software insecure.

What about another binary for legacy Windows (XP) and update the regular versions for Windows to openssl 1.1.1? Or build the 64-bit version with recent libs and the 32-bit with the older ones?

I do think that supporting older platform has some value, especially for an essential software that does work well on low-end devices. But Shipping an EOL openssl version to every Windows user is maybe too conservative?

**Comment by davidebeatrici** [comment]
> It is EOL:
https://www.openssl.org/blog/blog/2018/05/18/new-lts/
https://www.openssl.org/blog/blog/2019/11/07/3.0-update/
_Note that as previously announced OpenSSL 1.0.2 will be End Of Life at the end of this year [2019]. This means there will not be any further public updates or security fixes to the 1.0.2 branch from then. This gives another strong reason for existing 1.0.2 users to upgrade to 1.1.1 as soon as possible._

Sorry, I missed that.

Thank you for pointing it out.

> Releasing 1.3.0 with openssl 1.0.2 only a few month before 1.0.2's EOL was an oversight. I would consider it a bug, that should be fixed in 1.3.1.

Why do you think it's an oversight? OpenSSL 1.0.2 received the last security update in December.

Are there known vulnerabilities in 1.0.2u?

> What about another binary for legacy Windows (XP) and update the regular versions for Windows to openssl 1.1.1? Or build the 64-bit version with recent libs and the 32-bit with the older ones?
>
> I do think that supporting older platform has some value, especially for an essential software that does work well on low-end devices. But Shipping an EOL openssl version to every Windows user is maybe too conservative?

Right now we are using an older SDK and the `v141_xp` toolchain for the x86 build, in order to support Windows XP.

We could:

- Update OpenSSL and Qt to the latest version for the x64 build.
- Update OpenSSL and Qt to the latest version for the x64 and x86 builds and release a special build for XP.

However, it's something that requires quite a bit of time (e.g. updating our [patches](https://github.com/mumble-voip/mumble-releng/tree/master/buildenv/1.3.x/common/qt5/patches)), which can be potentially end up being wasted since we're working on a brand new build environment for 1.4.x: https://github.com/mumble-voip/mumble-releng-experimental

Honestly, I don't think it's worth  if there aren't known vulnerabilities in the latest OpenSSL 1.0.2 release.

We just want to move forward with 1.4.x at this point.

**Comment by toby63** [comment]
@davidebeatrici 
> Honestly, I don't think it's worth it if there aren't known vulnerabilities in the latest OpenSSL 1.0.2 release.

And who is going to check for vulnerabilities?
This is exactly the wrong approach, you don't use EOL-software because it is considered **insecure by default**!

> We just want to move forward with 1.4.x at this point.

The deciding question is, when will 1.4.0 be released?
And please don't start a discussion again about how much there is to do etc.
The point here is not for you to hurry to 1.4.0, the point here is, **you should fix the EOL software first, if 1.4.0 is still long away.**
And yes even a release of 1.4.0 in a few months (means more than 3 months at maximum) is to far away.

**Comment by bendem** [comment]
@toby63, please cut down on the bold and exclamation marks. Your communication is coming across as aggressive towards the team that's actually trying to fix things. Maintaining multi-platform software is hard, special cases are hard, and the team is already working on making it easier to update dependencies.

Unless you provide patches (and even if you provide patches), please don't act entitled toward a team that's already doing everything it can.

Pointing out solutions and outlining potential holdups is more productive than pointing out mistakes and attacking decisions. Everybody here is painfully aware that things are not ideal.

**Comment by toby63** [comment]
@bendem Even though it might look different, I only wanted to point out the most important points by using bold marks, because people read over things very fast.

**Comment by toby63** [comment]
@davidebeatrici 
Now that https://github.com/mumble-voip/mumble-releng/issues/90 is fixed, could you release a snapshot with newer openssl?

**Comment by davidebeatrici** [comment]
We were actually thinking about directly releasing 1.3.1, rather than 1.3.1 RC2.

**Comment by toby63** [comment]
@davidebeatrici 
Ok, 
I was just thinking about a development snapshot, that are listed on the bottom of the [Downloads page](https://www.mumble.info/downloads/).

**Comment by davidebeatrici** [comment]
The next snapshot will be based on 1.4.

**Comment by Krzmbrzl** [comment]
The update has been performed in the background (for our internal builders)

**Comment by tylerszabo** [comment]
@Krzmbrzl Did you update the builders for murmurd as well? In https://github.com/mumble-voip/mumble/releases/download/1.3.2/murmur-static_x86-1.3.2.tar.bz2 I'm still seeing the following:

`SSL: OpenSSL version is 'OpenSSL 1.0.2k  26 Jan 2017'`
...
`Murmur 1.3.1 (1.3.2) running on X11: Linux 4.19.0-10-cloud-amd64: Booting servers`

**Comment by Krzmbrzl** [comment]
No the environment for the static Linux server has not been updated.

The problem is that the only person who knew the internals of the static linux builder is no longer an active member of our team. Therefore updating it was impossible.

**Comment by tylerszabo** [comment]
In that case could this bug remain open as not all binaries are updated or the static build discontinued?

Shipping a build with outdated OpenSSL can cause downstream issues. I saw this in @PHLAK's Docker image; so there are downstream effects.

Also, do you have any context on the build options that produce the static build? Perhaps I could take a look and we could fix this with a PR.

**Comment by toby63** [comment]
> Also, do you have any context on the build options that produce the static build?

They use an ancient linux distro with an ancient software for building the static stuff (I forgot the details, but the software doesn't seem to exist any longer etc.).

The Team considers alternatives for that (for Linux there are multiple things like Flatpak, Appimage, Snap etc.), but right now it seems they want to stick with this.

Thx for pointing this out, I didn't check and believed they had solved this.
Missleading.

**Comment by Kissaki** [comment]
> In that case could this bug remain open as not all binaries are updated or the static build discontinued?

We should document it as a known issue/restriction. No need to keep it open if we can not or do not plan to fix it.

1.4 will have updated environments and stuff, including static server build. We are focusing on moving that forward.

**Comment by tylerszabo** [comment]
Noting the limitation in documentation sounds like a good solution - avoids lots of extra work; I was fiddling with the build indeed it's non-trivial.

The `murmur` packages in the Alpine and Fedora repositories and `mumble-server` packages in the default Debian and Ubuntu repositories are indeed using updated OpenSSL versions (it seems to be the shared lib, but I didn't verify beyond checking the reported version) so there are ample workarounds.

Thank you, both, for your quick response to a necro'd bug :)

**Comment by toby63** [comment]
> We should document it as a known issue/restriction.

You should simply take it down.

**Comment by Kissaki** [comment]
I would appreciate it if you would be less pissy, demanding, dismissing, disrespectful.

Did you run a security assessment? We have no indications of actual or even reported theoretical issues. Just because an upstream library fixes issues does not necessarily mean we use those things and that they apply to us.

Without an alternative removal is not an option.

We do what we reasonably can. So be concrete and practical, or fuck off.

**Comment by Kissaki** [comment]
This is our project, and our decision. You can voice disagreement, but your continued passive aggressive tone is very inappropriate and annoying.

**Comment by toby63** [comment]
https://security.archlinux.org/CVE-2020-1968

Your behaviour ist irresponsible.
You make people believe they use a secure and encrypted communication software.
But thats not the case, if you don't want to solve the situation, then at least be honest to people.

It's behaviour like yours that leads to the devastating IT security situation that we have now.

**Comment by toby63** [comment]
> Without an alternative removal is not an option.

There are lots of alternatives, for linux it is no problem at all to simply use packages or copy the contents of packages etc.
And even for windows (because I have the feeling it isn't fixed there either, is it?) users can now use linux versions easily over wsl.

**Comment by Krzmbrzl** [comment]
The libraries are updated for all targets but the static server binary. 
And not using packages is not an option since it's a **static** binary. All Linux packages are based on shared libraries though

**Comment by PHLAK** [comment]
The vulnerability linked isn't even practical to exploit.

From the linked reference:

> The attacker needs particular circumstances for the Raccoon attack to work. He needs to be close to the target server to perform high precision timing measurements. He needs the victim connection to use DH(E) and the server to reuse ephemeral keys. And finally, the attacker needs to observe the original connection. For a real attacker, this is a lot to ask for.

**Comment by minecraftchest1** [comment]
I am not much of a devloper, but I would still like to add my cents. Wouldn't sticking with old versions of a library make it harder to update if there are API changes in newer versions? Wouldn't it be better to slowly update the API calls, rather then having to change them all at once?

I have not worked with openssl so I do not no if this applies to the current situation.

**Comment by davidebeatrici** [comment]
There are indeed API changes between OpenSSL 1.0.2 and 1.1, however we already support the most recent version.

**Comment by LShirohana** [comment]
Reading this Github conversation was nauseating. The fact a team would not upgrade SSL to the most recent version because "muh windows XP support" has to be the dumbest excuse I've ever heard.

You should downgrade SSL so you can support Windows 95 while you're at it.

**Comment by TredwellGit** [comment]
https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/:
>On September 30 2021
>you’ll need to make sure
>if clients of your API are using OpenSSL, they must use version 1.1.0 or later. In OpenSSL 1.0.x, a quirk in certificate verification means that even clients that trust ISRG Root X1 will fail when presented with the Android-compatible certificate chain we are recommending by default.

@Krzmbrzl @davidebeatrici

**Comment by Krzmbrzl** [comment]
@TredwellGit thanks for letting us know. We will most likely not provide new builds for the 1.3.x series though. We are preparing to release 1.4.x that does not have this issue in the first place so that should cover it. And for those that can't wait until the stable release is performed, we already provide snapshot releases on our website :)
