### ISSUE TITLE
Murmur registration: No DNS records found

### ISSUE THREAD

**Issue by skobkin** [mumble-voip/mumble#4009]
**Describe the bug**

My server registration don't use hostname specified in the config. Some time after running I'm seeing this in the log:

```
murmur    | <W>2020-03-25 02:34:47.032 1 => <2:(-1)> New connection: 52.201.18.254:57238
murmur    | <W>2020-03-25 02:34:47.360 1 => <2:(-1)> Connection closed: The TLS/SSL connection has been closed [1]
murmur    | <W>2020-03-25 02:34:47.365 1 => Registration: No DNS records found: Registration updated
```

`murmur.ini` has this:

```
registerName="mumble.skobk.in - Дегенератуша Скобкина"
registerHostname=mumble.skobk.in
registerPassword=xxxx
registerUrl=https://skobk.in/mumble/
```

DNS is also properly configured:

```
% host mumble.skobk.in
mumble.skobk.in is an alias for mumble-msk1.skobk.in.
mumble-msk1.skobk.in has address 185.189.14.117
```

I even removed IPv6 record (didn't help).

**Additional context**

Murmur is running in the Docker container based on minimalistic image. The image is built based on Alpine with official static murmur build from Github releases.

[Docker image source](https://bitbucket.org/skobkin/docker-murmur-official-static-image/src/master/Dockerfile)
[Docker image build](https://hub.docker.com/repository/docker/skobkin/murmur-official-static)

**Comment by Krzmbrzl** [comment]
`New connection:`
https://github.com/mumble-voip/mumble/blob/310497a40054babeec7b39cfd9c1415b6cb9423d/src/murmur/Server.cpp#L1293

`Connection closed:`
https://github.com/mumble-voip/mumble/blob/310497a40054babeec7b39cfd9c1415b6cb9423d/src/murmur/Server.cpp#L1434

`err` being `1` represents `QAbstractSocket::RemoteHostClosedError` (https://doc.qt.io/qt-5/qabstractsocket.html#SocketError-enum)

`Registration:`
https://github.com/mumble-voip/mumble/blob/310497a40054babeec7b39cfd9c1415b6cb9423d/src/murmur/Register.cpp#L125

> My server registration don't use hostname specified in the config.

How did you come to that conclusion? From the IP that is listed in the `New connection` message? From a glance at the code that's the IP of a connecting client and not of the server...

**Comment by skobkin** [comment]
> How did you come to that conclusion? From the IP that is listed in the `New connection` message?

I came to that conclusion from public server list:

![2020_03_25__14_45_09](https://user-images.githubusercontent.com/967576/77533157-6ae1d400-6ea7-11ea-8afa-87004e26f081.png)

> From a glance at the code that's the IP of a connecting client and not of the server...

What? It's the `mumble.info` IP address. Why should I think that that's my server IP?

**Comment by Krzmbrzl** [comment]
> What? It's the mumble.info IP address. Why should I think that that's my server IP?

Oh lol - didn't notice that xD
Very weird to me though that this IP comes up in the log as a "new connection". In all cases I have seen so far, this message is only sent for joined clients...

> I expect that my server should be showed as a hostname and not as IP address in the server list.

Ahhhh. Okay now I get what is the problem :bulb:

**Comment by Krzmbrzl** [comment]
@davidebeatrici do you have a clue what could be the problem here?

**Comment by skobkin** [comment]
Some off-topic: My server were also registered twice because I was changing the name in the config.

Shouldn't name just be updated if `ip:port` and `password` are the same?

**Comment by Krzmbrzl** [comment]
Regarding your original problem:
It has been brought to my attention that apparently the `registerHostname` expects a so-called `A record` or `AAAA record` and what you have provided is a so-called `CNAME record`.
Now I don't claim that I really understand what these mean but from what I have been told the problem seems to be that you are using an alias here instead of `mumble-msk1.skobk.in` directly.
Thus you should try `registerHostname=mumble-msk1.skobk.in` and see if that works better :point_up: 

> Shouldn't name just be updated if ip:port and registerPassword are the same?

Uhm I guess? Don't know anything about the registration-backend though, so I can't say much about it ^^

**Comment by dabruh** [comment]
@Krzmbrzl Thanks for pointing this out. I was going nuts over the fact that my server wasn't registering with the proper hostname. I believe that CNAME support should be implemented.

My DNS configuration *was* something like this:
```
mumble.dabruh.domain is an alias (CNAME) for dabruh.domain.
dabruh.domain has address (A) 12.34.56.78
```

The reason for the configuration above was that I have a dynamic IP address, and my router is configured to update the DNS record(s) if a change is detected. I prefer creating CNAME records (aliases (something.dabruh.domain)) for my various services instead of pointing them to the IP as there's less administration required (I don't need to create a DNS updater for each).

Another reason for allowing CNAME records in registerHostname is if I'm hosting a Mumble server for a friend. I would probably like to have the DNS configured like this in such a case:
```
mumble.friend.domain is an alias (CNAME) for mumble582.dabruh.domain.
mumble582.dabruh.domain is an alias (CNAME) for dabruh.domain.
dabruh.domain has address (A) 12.34.56.78
```
The reason for the intermediate _mumble582.dabruh.domain_ is that it allows me as the hosting provider to migrate the Murmur server to another machine with a different IP without requiring him to update his DNS records - which can be tricky if he isn't tech savvy.

However, I understand that one might want to limit the allowed record depth, so that there isn't a huge chain of aliases that the public server indexer must go through before being able to validate that the address actually is resolvable. I think that at least 2 chained CNAME records should be allowed.

**Comment by dabruh** [comment]
> Shouldn't name just be updated if ip:port and registerPassword are the same?

I agree, I'd even go so far as to say that just the registerPassword should be enough in order to update a record - e.g. change name or hostname. A changed name shouldn't spawn a new record. I just had that happen to me.

**Comment by Krzmbrzl** [comment]
@dabruh  thanks for the input. I linked it in the dedicated issues.

Closing this in favor of #4078 and #4079

**Comment by reelsense** [comment]
This was very helpful information. I had been googling this once a year for a couple of years and never found the answer until now. The CNAME issue is a problem for me. I have many users that added my server to their favorites with an IP as the host and will never benefit from my automatic DNS failover server. It will probably be 5 years until all the users either upgrade their computer, reformat, or stop connecting until I can stop using that IP...
