### ISSUE TITLE
Could not verify host certificate.

### ISSUE THREAD

**Issue by kokorionk1** [mumble-voip/mumble#4025]
Hello!
First of all, I would like to thank the developer for this excellent product.
During the epidemic, I decided to create my server in the TOR.
I used Whonix at the same time. By setting up the server itself on one of 2 machines, on the workstation. (Whonix uses 2 virtual machines - Gateway and Workstation)
I made the standard server settings, however, when connected from a mobile device (the application was used Plumble), I get a certificate error.
I tried to create a certificate directly on the phone.
I tried to connect without a certificate.
Naturally, before connecting to the server from the phone, all traffic goes through the TOR.
Perhaps this is not a problem with the application, but with my little knowledge of certificates.

**Comment by Krzmbrzl** [comment]
I assume you got that error on you client?

One thing that I can think from the top off my head is that the server might use a self-signed certificate and thus it can't be verified. Most servers I encountered to this though and at least with the desktop app there the option to still trust the self-signed certificate.
Don't know how that is handled in Plumble though I thought I was connected to servers with self-signed certificates using Plumble before :thinking:

I don't know much about TOR though so maybe the issue lays somewhere in there. There was someone on our IRC that works with Mumble and Tor though. I'll try to reach out to them to visit this issue. Maybe they'll know more.

**Comment by kokorionk1** [comment]
Thank you for your reply!
You're right. In a desktop application, when the certificate is self-signed, you can trust it by clicking the "Yes" button.
In the Plumble application, with a certificate error, there is no way to accept it. If possible, I will test my server from other PCs. But initially the goal was to communicate using android. If you have any additional information, please write here.

**Comment by Krzmbrzl** [comment]
If it turns out that this is simply a missing feature in Plumble, then there's nothing we can do about it. We don't maintain the app.
Furthermore the app is no longer maintained, so if the feature doesn't exist, it will probably stay that way until someone finds the time and motivation to take up the work on it... :/

**Comment by rafaelbonifaz** [comment]
@kokorionk1, I think you can accept a self sign certificate in Plumble. I don't remember how, I haven't done for a while, but I posted this in 2018:
https://medium.com/@facceso.ca/comunicaciones-secretas-y-aut%C3%B3nomas-de-voz-ip-con-mumble-3b3d3bad06c5

Is in Spanish, but at the time I connected to a Mumble Onion from Plumble. I haven't use Plumble since, but I think you should be able to connect.

You might want to take a look to Wahay (https://wahay.org or https://github.com/digitalautonomy/wahay). We are building Tor + Mumble application, we have tested in most Linux, with Tails included. Soon we would publish installation options for each distro.

At the moment it does not work with Whonix, but it would be  nice app to have in Whonix.

**Comment by TredwellGit** [comment]
Just so you are aware, you can use free of cost [Let's Encrypt](https://letsencrypt.org/) certificates with Murmur instead of the default self-signed certificate.

**Comment by rafaelbonifaz** [comment]
> Just so you are aware, you can use free of cost [Let's Encrypt](https://letsencrypt.org/) certificates with Murmur instead of the default self-signed certificate.

You can not use Letsencrypt certificates with onion addresses.

**Comment by TredwellGit** [comment]
It was never stated if the connection was to an onion service or a regular service through an exit relay. Just trying to share some options.

**Comment by Krzmbrzl** [comment]
Given that there hasn't been any activity within the last week, I'll close this issue for now.

**Comment by rafaelbonifaz** [comment]
I would just like to say that @quite is creating a fork of Plumble and his making it friendly with Tor and Onion addresses:

https://gitlab.com/quite/mumla

**Comment by Oazis79** [comment]
Hi guys,
faced with such a problem, on one of the Internet operators, when connecting to the Mumble server in the mobile app, it gives an error — "could not verify host certificate". However, when connecting to the same server through another Internet operator, everything works fine.
Tell me please, what could be the problem?

**Comment by Krzmbrzl** [comment]
No idea. Note however, that we don't maintain the mobile app, so we can't really provide any help with that either. After all this appears to be a client-side issue :eyes:

**Comment by rafaelbonifaz** [comment]
> Hi guys, faced with such a problem, on one of the Internet operators, when connecting to the Mumble server in the mobile app, it gives an error — "could not verify host certificate". However, when connecting to the same server through another Internet operator, everything works fine. Tell me please, what could be the problem?

If you only have the problem with one ISP, then the issue might be on the ISP, and they might be trying to do a man in the middle attack:
https://en.wikipedia.org/wiki/Man-in-the-middle_attack
