### ISSUE TITLE
chat-entry "Drag here"-popover hides latest messages

### ISSUE THREAD

**Issue by rkoe** [mumble-voip/mumble#4094]
**Describe the bug**
When selecting the chat-entry to enter a text chat message, a "Drag here" popover occurs, which overlays the latest messages, so the latest messages cannot be seen.

**Steps to Reproduce**
1. Start Mumble and connect to a server.
2. Do some text chatting, so that the chat-window is filled to the bottom.
3. Go to the chat-entry field.
4. Now, a "Drag here" popover occurs, which hides the last message line.

**Expected behavior**
The last message must be completely viewable when typing a message.

**Screenshots**
The last message reads: "This message is only shown partially, since "Drag here" hides the last line." But it's partly hidden my Mumble.
![mumble-draghere-chatentry](https://user-images.githubusercontent.com/2507744/79975308-12e4c000-849b-11ea-80c3-2d142fdc27bc.png)

**Desktop (please complete the following information):**
 - OS: Linux (NixOS)
 - Version: Mumble 1.3.0

**Comment by Krzmbrzl** [comment]
I don't even have the "drag here" popup...

**Comment by Krzmbrzl** [comment]
Do you have your Layout set to "custom"?

**Comment by Krzmbrzl** [comment]
Okay I found it. This happens because you have set your layout to `Custom` and did not check `Lock Layout`.

The popup you're seeing is the point at which you can grab the widget and place it at a different place in the UI. I don't think that this is meant to be the default (the user being able to drag widgets around).

You can fix this by either selecting one of the pre-defined layouts or by checking said option to lock the layout. All of this can be done in the user interface settings.

**Comment by rkoe** [comment]
I haven't set the layout to "Custom" -- it's the default configuration!
So, I suggest to change the default configuration to "Classic".

I cannot fix this in any way (or configure anything) due to #4092.

**Comment by Krzmbrzl** [comment]
> So, I suggest to change the default configuration to "Classic".

This is already the default.
https://github.com/mumble-voip/mumble/blob/c84f0a5ebf337fa28ec37475537a584ad9dfaed3/src/mumble/Settings.cpp#L360

This is also true for the 1.3.x series (and probably a while longer)
https://github.com/mumble-voip/mumble/blob/dd9c261c521893f68bb75b1cd762aa7a6a873b56/src/mumble/Settings.cpp#L307
