### ISSUE TITLE
Implement Github Discussions 

### ISSUE THREAD

**Issue by toby63** [mumble-voip/mumble#4146]
**Context:**
Github, Issues, Feature Requests, Discussions

**Description:**
You might have already seen this new feature.
* [Github Blog post](https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/#discussions)
* [Example](https://github.com/githubevents/satellite2020/discussions)

I would like to see this implemented here, when it is available (currently Beta).

**Advantages:**
* Better discussion structure:
For example: The answers to one specific comment are directly placed under the comment (see [example comment](https://github.com/githubevents/satellite2020/discussions/11#discussioncomment-10528))
* Static: 
Even if marked as answered the threads will stay, so important information does not get lost in closed issues.
* Upvoting system: 
Can also be sorted, so one can see what has the most votes.
* Question/Answer-System:
Useful for support requests and general unspecific problems.
    * There is also an option to vote for the best answer
* Much better place for (user-written) FAQs, Guides etc.

I would probably shift most of the discussions/issues there (in the future).
Including:
* Feature Requests
* Implementation Discussions
* Support Requests
* General Discussions
* FAQs
* Guides
* Discussion about External Software
etc.

And I would use the Issues-Section only for:
* specific Bug reports
* specific Feature implementation tracking (aka short summaries of what was agreed on)

That would maybe also flatten the issue high tide.

**Comment by Krzmbrzl** [comment]
> That would maybe also flatten the issue high tide.

:heart: 

@davidebeatrici @Kissaki thoughts?
I also see a big potential in that. This might be a huge step towards an issue list that's properly usable :point_up:

**Comment by Kissaki** [comment]
I would like to see discussions activated. Not sure yet about feature requests and user created documentation like guides or FAQs, I have not thought about that yet.

Our forums are a pain to maintain. I’m the only team member responding there, we have manual approval due to spam, and there are continuous spam posts that have to be moderated with inefficient tools (account + post deletion is several actions in). Updating it is also a pita, which somehow I got stuck with. I would like to disable or drop our phpbb forums. There is value in the history, but otherwise it’s inefficient and frustrating and a time sink in maintenance and split in infrastructure.

**Comment by Krzmbrzl** [comment]
> I would like to disable or drop our phpbb forums. There is value in the history, but otherwise it’s inefficient and frustrating and a time sink in maintenance and split in infrastructure.

In that case I think moving everything here on GitHub and dropping the forums might be a good approach :+1:

**Comment by toby63** [comment]
Glad that you like the idea :smiley: .

FYI I have to add one potencial downside I noticed:
There don't seem to be categories. But maybe Github will add that.

> There is value in the history

You probably know/thought of that (but just in case):
Maybe you could create a static website from the content of the old forums...
It seems possible to export contents using php/or a php manager:
https://www.phpbb.com/community/viewtopic.php?p=13278598#p13278598
(I also use phpbb, so I once searched for that, but I never tried it)

**Comment by davidebeatrici** [comment]
Definitely.

It's more or less what we did with Wordpress (our old blog was based on it).

**Comment by Kissaki** [comment]
We discussed this yesterday in our team meeting. We have high hopes for GitHub discussions and want to implement it as soon as possible and ultimately replace/archive our separate forums.

We talked about the broader communication infrastructure and channels, what could and should be where, and what tools we can use. GitHub discussions seems to be a great fit between chat and issue tickets. We will see about how we will be able to separate enduser support, technical discussions, and potentially guides/content.

GitHub announced GitHub discussions with a beta for select open source projects. We contacted GitHub whether we could be one of them - in the hopes of implementing it earlier rather than waiting for it to be released publicly - with no ETA yet.

**Comment by Krzmbrzl** [comment]
As was stated already: We are very interested in this feature. We can't do anything until it is released though and therefore I am closing this issue.

**Comment by toby63** [comment]
Well I don't really understand why so many projects follow this "new" "close it all"-approach, even though things are not implemented yet, but still I guess in this case, it won't be forgotten, as the release of this feature will probably be advertised a lot.
