### ISSUE TITLE
Calling startTalking twice requires calling stopTalking twice to stop talking

### ISSUE THREAD

**Issue by wvffle** [mumble-voip/mumble#4154]
I guess I found an error in `startTalking` and `stopTalking` DBus calls implemented in https://github.com/mumble-voip/mumble/pull/3675

After some tests I could observe that calling `startTalking` twice requires calling `stopTalking` twice to stop talking in mumble client

I guess that `stopTalking` call should stop listening the voice input stream immediately no mater how many times `startTalking` has been called

Latest commit of a version that I have compiled is 54eb261ca37de0acb75a001e9fb7dbefb6123926 

The compile flags are:
```
  qmake-qt5 main.pro \
    CONFIG+="bundled-celt no-bundled-opus no-bundled-speex no-g15 no-xevie \
             no-server no-embed-qt-translations no-update no-jackaudio packaged" \
    DEFINES+="PLUGIN_PATH=/usr/lib/$_pkgname" \
    INCLUDEPATH+="/usr/include/speech-dispatcher"
  make release
```

**Comment by Krzmbrzl** [comment]
@wvffle could you post the exact DBus calls you have used please?

**Comment by Krzmbrzl** [comment]
Ah actually I think this behavior is intended after all. Imagine e.g. you have used DBus interface to map some custom keybinds to PTT (as shown in #3675). Then you press down both (leading to 2 calls to `startTalking`) and when you release only one of the keys (resulting in a single call to `stopTalking`)  you don't want the audio to stop, do you?

This is then basically the same behavior as for PTT key inside Mumble. If you have pressed multiple PTT keys, you have to release all of them in order to stop transmitting audio.
