### ISSUE TITLE
Add hotkey/toolbar icon to toggle RNNoise

### ISSUE THREAD

**Issue by trudnorx** [mumble-voip/mumble#4189]
I toggle it several times per day. It's better in some situations but worse in others.
For example: Good to filter out chewing sounds while I'm eating something.
But bad because it filters out whisper (very quiet human voice) and some other sounds.
So I do things like only turn it on while I'm eating.

**Comment by trudnorx** [comment]
Could add an option to toggle whether the user want a toolbar button under Settings > User interface > Look & Feel.

**Comment by sethbrown246** [comment]
Hey my name is Seth Brown and I am an undergraduate student looking to do my first issue contribution and was wondering if I could do this. Any tips/help would be greatly appreciated! Looking to submit a pull request within a few days.

**Comment by Krzmbrzl** [comment]
Welcome Seth and thanks for your interest in Mumble.
To get a general idea on how a shortcut can be added to Mumble, you could have a look at the changes made in [`62f087f` (#4636)](https://github.com/mumble-voip/mumble/pull/4636/commits/62f087fb3acf697c00245063ed297ee942217bfc). Note however, that this commit contains more changes than you will need, since toggle-shortcuts don't require special data handling (in contrast to  selecting and remembering a specific channel, which had to be created in the linked commit).

As a guide, you should probably orient yourself at the implementation for the shortcut for toggling the main window's visibility:
https://github.com/mumble-voip/mumble/blob/600ffb476a62901d374926cf8cab6875f4c93bbf/src/mumble/MainWindow.cpp#L284-L289
https://github.com/mumble-voip/mumble/blob/600ffb476a62901d374926cf8cab6875f4c93bbf/src/mumble/MainWindow.cpp#L3126-L3134
(Note that the shortcut and the linked function are automatically connected to each other thanks to the naming of the function (Qt takes care of that)).

The setting you are interested in setting is `Settings::noiseCancelMode` and after changing it, you probably want to call `AudioInput::selectNoiseCancel()`.
If you feel like it, you could also add a shortcut for toggling noise cancellation in general, instead of only toggling for RNNoise.

When committing, please follow [our commit guidelines](https://github.com/mumble-voip/mumble/blob/master/COMMIT_GUIDELINES.md).
Furthermore, you might be interested to read https://github.com/mumble-voip/mumble/blob/master/docs/dev/TheMumbleSourceCode.md

**Comment by Krzmbrzl** [comment]
I'm closing this issue in light of #6292
