### ISSUE TITLE
Re: Mumble rewrite, feature wishlist

### ISSUE THREAD

**Issue by felix91gr** [mumble-voip/mumble#4207]
From https://github.com/mumble-voip/mumble/issues/4195#issuecomment-633682172, https://github.com/mumble-voip/mumble/issues/4195#issuecomment-633684014 and https://github.com/mumble-voip/mumble/issues/4195#issuecomment-633685680, there seems to be a consensus that, now that the topic of a rewrite is on the table, there should be a thread to discuss / propose / assert what the community wishes the Mumble devs considered either adding or removing to / from the project.

#### Propose

If you want to propose something, do the following:

* Write one comment per idea.
* Start with a heading H3: `### My idea`, so that everyone can see it's a proposal and not a response to something else.

Also, try to leave space for others' ideas as well, so that everyone can make use of the thread :)
So, I'd suggest going for your 2 or 3 most wanted ideas.

You are allowed to iterate on your ideas upon receiving feedback! Try to annotate your edits at the bottom so that people can keep up to date :)

#### Vote

If you don't have anything left to propose, you can assert your opinion on an idea by voting on it. Use this as your reference:
* :+1: : Approval
* :eyes: : Mild Approval
* `<nothing>` : No opinion
* :confused: : Mild Disapproval
* :-1: : Disapproval

#### Give feedback

If you want clarification, or to improve someone else's idea, you should give them feedback! You can quote their text using `>` and tag them using `@`.

If you disagree with someone else's idea: remember that everyone's a person, so give them feedback with kindness :heart: 

---

@theAkito @timokoesters @fedetft you were interested in this, here's the thread ^^

**Comment by Krzmbrzl** [comment]
Be aware though that this is only for discussion and will be closed at some point. If there are feature requests for the feature you have in mind, make sure to link to it and also give that an upvote because these are the ones we'll actually process.
(Simply because there we have on issue per feature request. That's just a lot better to maintain than having one thread with dozens of them)

**Comment by streaps** [comment]
### Multichannel Audio Stream Ready / Ambisonics

It would be nice to support playback of surround / multichannel streams. In a first version the implementation doesn't have to be sophisticated, even a downmix to stereo would do it. The important thing is that the client will not choke on a multichannel stream and is able to play instead of discarding it completely or important parts of it.

I'm thinking especially of support for Ambisonics as it only needs 3 channels for horizontal 2D audio and already includes an omnidirectional mono signal in the first channel.

If and how this can be implemented with or without breaking compatibility is another question. The idea is to make it easier to add real full-featured surround / multichannel support in the future.

**Comment by streaps** [comment]
### Replace Murmur with Grumble

There is already a rewrite of the server part: Grumble. It claims to be 'pretty much feature complete, except for a few "minor" things.'

Instead of fighting with the gRPC implementation for Murmur that crashes the server, what about adding gRPC or some other remote interface to Grumble?

**Comment by Krzmbrzl** [comment]
Given that we won't do a rewrite, (see https://github.com/mumble-voip/mumble/issues/4195#issuecomment-640169462), I think we can close this issue.
