### ISSUE TITLE
Update checker broken

### ISSUE THREAD

**Issue by replydev** [mumble-voip/mumble#4270]
**Describe the bug**
I updated mumble to new 1.3.1 version, when i start the program it gives "New version available" message in chat, giving 1.3.0 as the new version released

**Steps to Reproduce**
1. Install new mumble version
2. Open it and see the bug

**Expected behavior**
No "new version available" message

**Screenshots**
![immagine](https://user-images.githubusercontent.com/43727434/84140478-fa803300-aa51-11ea-91b5-b20fc42571fd.png)

**Desktop:**
 - OS: Windows 10
 - Version: Mumble 1.3.1

**Comment by toby63** [comment]
Is this related to #4089 or a seperate bug?

**Comment by Krzmbrzl** [comment]
As this is an actual release (no snapshot/RC) it should be a different issue (in principle at least). However they are related: The backend that is currently used for the updater is pretty dumb (only does hash comparisons instead of looking at the actual version numbers in order to not suggest a downgrade)

**Comment by davidebeatrici** [comment]
The updater checker was not updated (...), it should be working correctly now.
