### ISSUE TITLE
RNNoise and EchoCanceler not working together nicely!?

### ISSUE THREAD

**Issue by netinetwalker** [mumble-voip/mumble#4302]
Today we have testet the new echocanceler from the master branch. I think the RNNoise is running before the echocanceler ... but the echocanceler need the unchanged signal to work properly.

Please run RNNoise after the echocanceler.

@Krzmbrzl ?

**Comment by Chris2000SP** [comment]
https://paste.xinu.at/m-KdZeD/

I have Compiled Mumble 1.4.0 master today and I get an echo when I leave RNNoice on. And when I have RNNoice on in Mumble 1.3.1 I get a peak in the echo analysis but it is probably a few milliseconds too late. I can remember that in Mumble 1.1.x the peak starts at the beginning, on the left of the diagram. Logically since the bass is quite loud in a male voice.
I think we need another tweak here.

**Comment by TerryGeng** [comment]
In the master branch, #4167 has been merged recently to provide better support for the echo cancellation. But the noise processing chain accompanying this change is in #4212 and is not merged yet. I think you can test that branch to see if this problem is fixed, and provide some feedback to facilitate the merging of that PR.

@Chris2000SP What do you mean the _peak_? Is that some FFT or you mean the echo cancellation is not matching the echo signal properly?
I have seen that you have also participated in #4167 and am not sure if you review the code. I'm still not sure the principle behind that PR (https://github.com/mumble-voip/mumble/pull/4167#issuecomment-631819112) and I'm not sure if it is related to this.

**Comment by Krzmbrzl** [comment]
As Terry said. Plus it'd be really important for folks to actually test #4212 as without it, we can't know whether it works or not and thus can't merge it...
