### ISSUE TITLE
Mumble not starting on Ubuntu 20.04 with Wayland

### ISSUE THREAD

**Issue by xile273** [mumble-voip/mumble#4308]
Mumble is not starting on Ubuntu 20.04 when using wayland.
When starting using the GUI nothing happens at all.
When started via the terminal the following error is given:

_This application failed to start because it could not find or load the Qt platform plugin "wayland-egl"
in ""._

_Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb._

_Reinstalling the application may fix this problem.
Aborted (core dumped)_

libwayland-egl1 is installed on my computer.

**Steps to Reproduce**
Simply start mumble.
Please note that I was only able to recreate this bug using the snap version of mumble.
Mumble obtained via apt starts as expected.
Also Mumble works as expected when using x11.

**Expected behavior**
Mumble starts and does not crash on startup.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 using wayland
 - Version: Mumble 1.3.0 Rev 1141 (Snap version)

**Comment by Krzmbrzl** [comment]
The snap package is not provided or maintained by us (afaik).

It appears as if this issue has already been reported to them for Ubuntu 19.10

And given that Mumble works when installing via apt, I assume that this is indeed something specific to the snap packaging and not to a bug in our code.
Therefore I'll close this issue here but I'll add a reference to the linked issue as well. Feel free to provide a follow-up post there as well :)
