### ISSUE TITLE
[Discussion] Found an Organisation for Mumble?

### ISSUE THREAD

**Issue by toby63** [mumble-voip/mumble#4313]
### Description:
@billfehring mentioned the idea to found an organisation for mumble.
(Original comment: https://github.com/mumble-voip/mumble/issues/4263#issuecomment-648060481)

**Advantages include:**
- `legal representation`: useful to gain benefits (including software etc.) for non-profit organisations and for dealing with companies, organisations, state etc.
- `legal responsibility`: the organisation would be responsible for the project, this could relieve each developer (still there is of course a personal responsibility especially for intentional unlawful acts)
- `clear and transparent structure`: builds trust in the community, helps organising processes
- `helps against "dictatorship"`, if one person involved suddenly wants to harm the project
- `potential for better "resource" collection`: The organisation could "collect" resources of many kinds:
    - money
    - hardware
    - software
- the organisation could also serve as a central supporter for other mumble related projects and could distribute resources

**Disadvantages:**
- costs some money: I would estimate around 100€ for the registration of the organisation  as a general value, depending on the circumstances it can get cheaper or more expensive; could be collected via crowdfunding
- needs a bit of work (see Details below)

## Details:
**Questions before founding:**
* what `form of organisation`? 
  I think a non-company form of organisation might be good (like a Foundation or a private non-profit organisation), also it might have a democratic decision process.
  The specific form depends on the country.
* in which `country` should the organisation be?
  There is for example no real european organisation besides the https://en.wikipedia.org/wiki/Societas_Europaea which is a form of stock company. So you would probably need to pick a specific country.
  Note: Still foreigners can be members in most cases.
* who should be a `member`?
  In "simple" private organisations there is mostly a democratic decision process and any member has one vote, so there is the question who should be a member and who not. 
  But maybe there are also alternative scenarios (including different levels of membership etc.).

**Necessary Things:**
* `Basic Agreement/Contract` (or similar) about the organisational structure etc.
* `Registration and Verification`: necessary in many countries to verify the identity of founding members; costs some money and might need the physical presence of people.
* `Meetings, Protocols, Votings`: for decision making and choice of representatives
* `Bodies` (such as Board of Directors (or something similar)): someone needs to head and represent the organisation
* `Finances and Financial reports`/Cash auditors: it is necessary in many countries to write financial reports, the person doing this, does not need to be an external professional, but someone has to do it.
  If the money transfer is mostly or purely based on banking, this should not be a problem at all, because everything is transparent in such a case.
* (Maybe necessary) Communication with state agencies about tax topics etc.

## My Evaluation and Oppinion:
I think it could be worth it.
Most additional work is only in the beginning (Agreements, Members, Registration).
Most regular work (such as Meetings etc.) is already part of the project.
So I think there are no real disadvantages, instead such a step could bring the project forward and attract more people.
:+1: 

**Additional context:**
Connected to #4263 #3593 and probably some others.

**Comment by Krzmbrzl** [comment]
We don't have enough man-power to maintain this project properly as it is, so I see any additional burden (in form of bureaucratic overhead) as a really huge disadvantage.

Furthermore right now all development is done in our free time. I won't let anyone dictate what it is that I have to be working on during that time. Thus as long as the devs are not paid I think an official council that votes on stuff is pretty pointless.

"Dictatorship" can't happen. If you don't like what someone is doing with the project, you can create and maintain your own fork and be done with it :shrug:

**Comment by toby63** [comment]
> We don't have enough man-power to maintain this project properly as it is, so I see any additional burden (in form of bureaucratic overhead) as a really huge disadvantage.

:thinking: As I said I don't think it is so much work, after it is setup (and some other people can help you with that).
Generally there are two regular tasks necessary:
1. Votings: only necessary according to the organisations basic contract; for example every two years positions need to be filled for specific bodies
2. Financial Reports: only necessary if you have income; done once a year by a specific person, can be a trusted person outside of developer circle; as I said very easy if everything is handled through banking

> Furthermore right now all development is done in our free time. I won't let anyone dictate what it is that I have to be working on during that time. Thus as long as the devs are not paid I think an official council that votes on stuff is pretty pointless.

I don't think this is how things work in other open-source software organisations.
Of course decisions are made and priorities are set, but I don't think anyone dictates the developers what to do (besides saying no to a feature being implemented).
Also the organisation's leader- or membership could be limited to developers, it is not necessary to give the community full membership, the basic goal are advantages mentioned above.

> "Dictatorship" can't happen. If you don't like what someone is doing with the project, you can create and maintain your own fork and be done with it shrug

That is not entirely correct imo, it was already mentioned, think about the website, this official repo etc.; someone has the "rights" to that and if that person decides to do something, he can simply do it.
An organisation would be more resilient against such scenarios.
But this is also not the main argument.

**Comment by Krzmbrzl** [comment]
Even if it is not much work, I don't really see a big benefit atm and thus I'm not a big fan of this idea.

The only advantage I can see right now is this BS Apple has going on... but there I also think that we shouldn't support it in either case, regardless of the price :shrug: 

That being said: As long as I am not forced to get myself involved with this whole organization thing, I also don't mind if Mumble was turned into one. Aka: I'm not directly opposed to the idea. I just don't think it's worth it.

**Comment by toby63** [comment]
> As long as I am not forced to get myself involved with this whole organization thing

No one is forced to anything, but someone needs to be a member, otherwise an organisation can't exist.

> The only advantage I can see right now is this BS Apple has going on

Well there might be many other cases for this licensing topic, also in a positive way, maybe you could get access to software, services etc. (often also stuff like better functionality, documentation etc. is hidden behind some hurdle (mostly money), with exceptions for non-profit orgs).
But it is of course an open question whether that is useful for you or not.

Also other advantages, like a more professional image of mumble, better communication with other instances, better financing, more developers etc. would be possible (but are of course not solely related to this).

So the overall main purpose would be better representation, everything else could work the same way as before.

**Comment by Krzmbrzl** [comment]
> more developers

I don't think that's connected to Mumble being an official organization. If anything lowering the entry-barrier to get into the code will help with that (alongside being active here on GitHub for PRs and issues) :shrug:

**Comment by ZeroAbility** [comment]
I would agree that the structure of the project could use more organization. I think that working on our documentation structure and the refactoring would go a long way to achieve that. I don't think turning the project into a structured hierarchy at this point would be beneficial. There are too many other aspects of the project that should take priority.

Since I have been here, we have been making decisions from the perspective of the product and its goals. I think if we introduce a political hierarchy then several perspectives will be lost and give way to majority decisions that do not benefit the project. You bring up avoiding a dictatorship, but poorly implemented or biased democratic processes can be just as destructive. Those are complications we don't really need right now.

This isn't to completely discount the idea entirely, just to say that this project isn't large enough for something as heavy handed as what you are describing. I think that statements like "some people might not like the official democratic decision making, but they can still fork the project etc." do more to turn people away from contributing which you have stated is a benefit of this process. It's not that I don't think we should have a discussion about structure or consider this as a goal in the future. We just need to focus on what we currently have and where we need to be from the perspective of the product first.

**Comment by toby63** [comment]
@ZeroAbility As I said above:
>> So the overall main purpose would be better representation, everything else could work the same way as before.

I probably should never have mentioned the structure and decision points.
Because like you said, thats what many people (sadly) hate, thats why they don't want democratic organisations.

Let me specify my idea a bit:
I imagine an organisation that simply serves as some kind of umbrella-organisation.
So it can represent the mumble project (and potencially other related projects) and gather resources of all kinds.
It would "own" the domain, servers, etc.

Everything else, including development, development decisions etc. could still work just like before.
And it will work just like before, because as you said, you are a volunteer project, so it will be done the way, people (involved or willing to participate) want it.
And thats what I meant with `some people might not like the official democratic decision making, but they can still fork the project etc.`.
It describes the "power" of the persons participating.
If we imagine the organisation deciding wrong things, people will say they will leave, thus it is likely a bad decision will not happen.

**Comment by ZeroAbility** [comment]
> I probably should never have mentioned the structure and decision points.
Because like you said, thats what many people (sadly) hate, thats why they don't want democratic organisations.

My point wasn't to discount an efficient and fair democratic process of decision making. I was mainly pointing out the perils of trying to implement that without careful thought and verbiage. I think a system like that would work if you had a significant number of high level contributors whose major purpose is governance. I don't believe the team is large enough to make that economical or practical. That doesn't mean it wouldn't be at some point.

> I imagine an organisation that simply serves as some kind of umbrella-organisation.
So it can represent the mumble project (and potencially other related projects) and gather resources of all kinds.
It would "own" the domain, servers, etc.

I think that is worth talking about further as it pertains to asset management. I know there have been some hurdles with getting some administrative things done (i.e. certificate renewal). It would be better to use role based administration for those purposes and have admin credential hand offs for people with access to the group administration that decide to leave the project. I'm not sure what kind of system would enable that but it's worth looking into.

**Comment by Krzmbrzl** [comment]
We discussed this in our last Team meeting and came to the conclusion that for now we think that founding an organization is more work than it'll actually do good.
This is due to the current overall project state.

This might be something we will reconsider at some point in the future, so thanks for bringing this up :point_up:
