### ISSUE TITLE
Admin muting or deafening another user toggles both

### ISSUE THREAD

**Issue by jaggzh** [mumble-voip/mumble#4320]
I was 99% sure I could just mute OR just deafen another user. But now, the context menu for either will always toggle both.  They can only be off or on.  If I just never noticed that this was happening, then this would end up being a feature request I guess.

Is there an option for this behavior so it [the linking of the options] can be controlled?

We use this as a baby monitor and it's important we be able to have the option, from an admin login, to enable or disable either of them.

Defaulting to them linked is good, but I think it should be a feature under control of the server or room admin, or.. anyone at all.

1. Right-click other user, as an admin
2. Click on Mute or Deafen
3. Both options are changed on my systems

**Expected behavior**
I should be able to toggle options separately, or enable the ability to unlink their toggling.

 - OS: Linux, W10
 - Version: At least >= 1.3, from 2019 to present I believe, although I *thought* I was able to do this earlier this year even.

**Comment by Krzmbrzl** [comment]
I just dug through the history of the server code. I stopped after digging 13 years in the past where deafening a user would already imply muting it. It seems as if this behavior might have been introduced by 6d6bcff7c7e76b175786bbf245917c1854ee0cf6 but it could very well be that the behavior existed before as well but is hidden in the refactor...

The relevant code part is 
https://github.com/mumble-voip/mumble/blob/2caae7960e3da0aac943c3eac82b55420c4a2721/src/murmur/Messages.cpp#L862-L866

and the same behavior applies if a user deafens itself:
https://github.com/mumble-voip/mumble/blob/2caae7960e3da0aac943c3eac82b55420c4a2721/src/murmur/Messages.cpp#L814-L819

> Is there an option for this behavior so it [the linking of the options] can be controlled?

No - it's hard-coded in the server's code (see above)

----

I actually think it's a bad idea to allow someone to deafen themselves without also muting them as otherwise they might spam noises to everyone else without the possibility to get notified to actually mute themselves.

Your scenario seems very specific to me and I don't think we should change the behavior to be suited to this specific scenario.

You have a few options though:
1. Use a Mumble 1.4.0 snapshot (you have to compile it yourself or you have to snatch one from one of the CI builds of any recent PR). In there you'll have access to ChannelListeners (see #4011) that allow you to listen to a channel without being able to speak in it (without using shouts that is). Note however that this feature is only available if the server you are connected to is also running at least Mumble 1.4.0
2. Use channel links + ACLs. You can link your normal channel with the baby's channel but set the ACLs of the latter so that only the baby's client is allowed to talk in that channel (just assign it a custom group and deny speak privileges to every one but explicitly grant it for the baby's group). Now you'll be able to hear the baby (due to channel links) but your voice is not sent to the baby's client as you don't have speak permission in its channel.

**Comment by Kuratius** [comment]
@jaggzh Does the problem even occur when just muting someone? If that's the case that part could probably be fixed.

**Comment by Krzmbrzl** [comment]
Ah yes that I didn't mention in my answer: Muting someone should **not** deafen them. If that'd be the case, that's a bug :point_up:

**Comment by jaggzh** [comment]
No, while I swear in my testing I found that was also linked, muting alone
does seem to be functioning correctly (can mute without deafening).

I built this one from git and would love to try channellisteners to see if
it works for our needs. (Does a client alone in a room still transmit audio
to the server?)

I'll find out how to build it. Thanks a bunch.

**Comment by Krzmbrzl** [comment]
> (Does a client alone in a room still transmit audio
to the server?)

Yes

> I'll find out how to build it. Thanks a bunch.

See https://wiki.mumble.info/wiki/BuildingLinux
(or https://wiki.mumble.info/wiki/BuildingWindows
or https://wiki.mumble.info/wiki/BuildingMacOSX)

**Comment by Krzmbrzl** [comment]
I assume that the problem did not occur when muting someone and given that there were no further voices for being able to deafen yourself without muting yourself, I'll close this discussion as "resolved". We'll keep it as it is

**Comment by midnightmagic** [comment]
For a mumble-ruby bot which has no capability or need to listen to voices, being able to voice/music/transcode into a channel while ignoring user chatter is a valid use case. (Control is via text message.) Request you re-open this: it looks like there are at least two of us who would find the functionality useful.

**Comment by Krzmbrzl** [comment]
I don't see how the functionality of the bot is related to it being muted or deafened. Could you elaborate on what exactly the bot does and why being in either of these states is useful?

**Comment by Hartmnt** [comment]
> For a mumble-ruby bot which has no capability or need to listen to voices, being able to voice/music/transcode into a channel while ignoring user chatter is a valid use case. (Control is via text message.) Request you re-open this: it looks like there are at least two of us who would find the functionality useful.

If this is just for preventing bandwidth being used to transmit to the bot, you can achieve a similar effect by: 1) placing the bot in its own channel 2) linking it with the channel your users are in 3) and disallowing everyone but the bot to speak in the bots channel

**Comment by edshot99** [comment]
> I don't see how the functionality of the bot is related to it being muted or deafened. Could you elaborate on what exactly the bot does and why being in either of these states is useful?

Music bots should not be muted to transmit audio, but should be deafened so that it does not receive audio and gives users more trust that the bot is not spying on them (kind of like Flavibot for Discord). This isn't possible anymore.

Putting the bot in it's own channel and doing channel linking is possible, but it makes sending commands more tedious by having to private message it.

As for keeping the hard code so that people can't deafen and mic spam, that's still possible by just turning off Windows volume for Mumble and then mic spamming so the hard code doesn't really do much there. Local mute or adding a client side normalizer would be better in that regard.
