### ISSUE TITLE
I cant connect to server

### ISSUE THREAD

**Issue by nhatmicls** [mumble-voip/mumble#4363]
I cant connect t server and it show me this message 
"[20:19:50] Server connection failed: The TLS/SSL connection has been closed."
When I ping to that server it still okay (time= 283ms, 0% loss)
Thanks
Nhat

**Comment by Krzmbrzl** [comment]
What server are you trying to connect to?
What version of Mumble are you using?
What version of Mumble is the server running?
Have you been able to connect to this server before?
Are you able to connect to any other server?

**Comment by nhatmicls** [comment]
I trying connect to this server: mumble.ncdot.co.uk.
I using the lastest one
I dont know about what is version of that server 
Yes I connect with other server is okay

**Comment by Krzmbrzl** [comment]
When I try to connect to that server my connection is refused due to missing password. However I don't see the error you are having.

My guess would be that this server might be misconfigured. As you can connect to other servers I'd say that the problem is probably not on the client's (your) side :thinking:
