### ISSUE TITLE
JPG images are broken on Windows x64 nigthtly build

### ISSUE THREAD

**Issue by promi** [mumble-voip/mumble#4393]
OS is Windows 10 x64, Build https://dev.azure.com/Mumble-VoIP/Mumble/_build/results?buildId=2267&view=results

Git commit is d2d5dc2cff854c864e4ec507ceb77a31963825da

JPG images are not shown, PNG images work fine.

**Comment by Krzmbrzl** [comment]
What server version are you using?
How do you send the images? I just tried it on Linux using the latest master version with a server hosted locally. When Drag&Dropping a JPG image to the chatbar and sending it that way, it is displayed on a second client running on the same machine just fine (it is also displayed properly in the sending client).

Is the JPG not shown on the receiving or the sending end? Or both?

Have you tried using different JPGs?

**Comment by hjf288** [comment]
Same on Windows 10 x64 - Using the image picker to insert an image on a channel using a JPG results in "Image format not recognized", manually inserting a <img> using base64 no longer works and jpg images set in existing channel descriptions are no longer displayed.

Older client works fine.

**Comment by davidebeatrici** [comment]
We probably have to explicitly import and link to the plugin, like we do for the SVG one:
https://github.com/mumble-voip/mumble/blob/06d0dbb5df700f991e0b70f95ec9577c89a8c63d/src/mumble/CMakeLists.txt#L336-L349

However, according to https://github.com/microsoft/vcpkg/issues/11727#issuecomment-638044293, with Qt 5.15 that is not required anymore.

The 64 bit build doesn't use the latest environment due to me forgetting to switch to it:
https://github.com/mumble-voip/mumble/blob/06d0dbb5df700f991e0b70f95ec9577c89a8c63d/.ci/azure-pipelines/main.yml#L8-L31

I'm going to create a pull request right now.

**Comment by davidebeatrici** [comment]
Could you test the build produced in #4404, please?

**Comment by hjf288** [comment]
> Could you test the build produced in #4404, please?

@davidebeatrici  Resolves the issue - JPGs are now visible and able to be used.

One slightly off topic note - it would be helpful if the Snapshot MSI builds are able to upgrade the installed version, it's a bit frustrating to have to remove the old version via Add/Remove programs in order to upgrade the snapshot.

**Comment by davidebeatrici** [comment]
> @davidebeatrici  Resolves the issue - JPGs are now visible and able to be used.

Thank you very much for testing it!

> One slightly off topic note - it would be helpful if the Snapshot MSI builds are able to upgrade the installed version, it's a bit frustrating to have to remove the old version via Add/Remove programs in order to upgrade the snapshot.

#4407
