### ISSUE TITLE
Win10 freezes and reboots every time the Mumble client connected to the server while QoS enabled

### ISSUE THREAD

**Issue by hmqgg** [mumble-voip/mumble#4405]
**Describe the bug**
Latest Win10 Insider build (Build 20185) freezes and restarts every time the Mumble client connected to the server.
There is no Event Viewer log for this freeze.
Under the `%appdata%\Mumble` folder, the last lines of `Console.txt` are

`ServerHandler: QOS2 loaded`
and
`ServerHandler: Failed to remove UDP from QoS`

After reboot, I tried to disable the QoS option, then connect to the server. It works and won't freeze and reboot. 

**Steps to Reproduce**
1. Upgrade OS to Win10 Insider Dev branch Build 20185.
2. Enable QoS option of Mumble client.
3. Connect to any mumble server.
4. OS freezes 1s and the PC reboots.

**Expected behavior**
Won't freeze and reboots the PC.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Insider Build 20185 Pro Workstation Edition
 - Version: Mumble 1.3.2

**Additional context**
[20185 changelog](https://blogs.windows.com/windowsexperience/2020/08/05/announcing-windows-10-insider-preview-build-20185/)

**Comment by ZeroAbility** [comment]
Could you please go into Windows 10 startup options and Disable Automatic reboot on error? The following article from hp may be of assistance if you are not familiar with the procedure:

https://support.hp.com/us-en/document/c03413399

We will need the stop error from the blue screen error to determine if that is a driver related issue or not. Please also keep in mind that insider builds may not be stable.

**Comment by Krzmbrzl** [comment]
The respective code parts to the encountered error messages are
https://github.com/mumble-voip/mumble/blob/06d0dbb5df700f991e0b70f95ec9577c89a8c63d/src/mumble/ServerHandler.cpp#L96
and
https://github.com/mumble-voip/mumble/blob/06d0dbb5df700f991e0b70f95ec9577c89a8c63d/src/mumble/ServerHandler.cpp#L428-L432

In order to find out what's going on, I think we have to include the returned error code in the error message. Ref: https://docs.microsoft.com/en-us/windows/win32/api/qos2/nf-qos2-qosremovesocketfromflow#return-value

**Comment by davidebeatrici** [comment]
@hmqgg #4408 adds extended error reporting for the `QOSRemoveSocketFromFlow()` failure. Could you test the build produced by CI, please?

**Comment by hmqgg** [comment]
@davidebeatrici 
I have disabled the auto-recovery for Windows, then connected to the mumble server with the QoS option enabled.
It just stopped at `ServerHandler: QOS2 loaded`, and no more logs in Console.txt

**Comment by Krzmbrzl** [comment]
@hmqgg but Mumble still crashed? Or hung up? Or did you actually connect to the server as normal?

**Comment by hmqgg** [comment]
> @hmqgg but Mumble still crashed? Or hung up? Or did you actually connect to the server as normal?

Still freezes the whole OS. It doesn't reboot automatically so I restarted manually.

**Comment by ZeroAbility** [comment]
That sounds like a driver error. Do you see any errors in the System or Application logs that give an indication which hardware device may have issues?

**Comment by hmqgg** [comment]
> That sounds like a driver error. Do you see any errors in the System or Application logs that give an indication which hardware device may have issues?

There are no event viewer logs related to the freeze though. But with the QoS option disabled, it works.

**Comment by Krzmbrzl** [comment]
My bet would still be on Windows having introduced a bug in the QOS part as it has been working before without any crashes or freezes. Thus I'd think that we use the API in a somewhat reasonable way :thinking:

**Comment by hmqgg** [comment]
Reinstalled my OS with drivers installed (clear install Win10 Insider Dev 20190), still reproducible.

**Comment by Krzmbrzl** [comment]
Yeah I was more thinking that the insider build may be buggy. It's a beta after all. And it appears to have been working on Win10 before :shrug:

**Comment by ZeroAbility** [comment]
> Reinstalled my OS with drivers installed (clear install Win10 Insider Dev 20190), still reproducible.

@hmqgg does this mean you are using the latest network drivers for your device from the manufacturer's website or the drivers installed from the Insider build?

**Comment by hmqgg** [comment]
Installed the manufacturer's driver from Realtek, the problem solved. It seems the network driver bundled with latest Win10 bugged.

**Comment by ZeroAbility** [comment]
> Installed the manufacturer's driver from Realtek, the problem solved. It seems the network driver bundled with latest Win10 bugged.

You may want to submit that through their feedback hub, as well. Sometimes you can go in Device Manager and do an Update Driver and it will install the latest. It depends on if they have the cab file in Windows Update. With custom PC builds I would typically disable the Hardware driver support feature in Windows Update because they tend to be out of date:

https://support.displaylink.com/knowledgebase/articles/543895-how-to-prevent-windows-checking-or-upgrading-from

Your screens may look different since you are on an Insider build. You can typically find these screens in the Control Panel -> System section by searching for Control Panel in the search bar.
