### ISSUE TITLE
CMake build no longer includes mumble-overlay executable

### ISSUE THREAD

**Issue by radioactiveman** [mumble-voip/mumble#4471]
**Describe the bug**
Mumble (<= 1.3.0) built with QMake contains two executables, `mumble` and `mumble-overlay`. Accordingly there are also two man files. This can also be confirmed by the package lists for Arch Linux or Debian (see additional context).
Mumble (latest Git version) built with CMake no longer includes the `mumble-overlay` file.

**Steps to Reproduce**
1. Fetch latest Mumble code from Git
2. Compile it with CMake on Linux

**Expected behavior**
Like with 1.3.0 there should be a `mumble` and `mumble-overlay` executable.

**Desktop**
 - OS: Arch Linux
 - Version: [mumble-git](https://aur.archlinux.org/packages/mumble-git/)

**Additional context**
https://www.archlinux.org/packages/community/x86_64/mumble/files/
https://packages.debian.org/buster/amd64/mumble/filelist

**Comment by ZeroAbility** [comment]
Can you pass `-Doverlay=ON` during the CMake configure step and let us know if that resolves it?

**Comment by radioactiveman** [comment]
Sure, but it does not change anything since the overlay is enabled by default, see [CMakeLists.txt#L49](https://github.com/mumble-voip/mumble/blob/master/CMakeLists.txt#L49).

**Comment by ZeroAbility** [comment]
This may be the source of the issue: https://github.com/mumble-voip/mumble/blob/0ba1eac51b5f4443e6fbb1bc3e157403903e9a01/overlay_gl/CMakeLists.txt#L12

**Comment by Krzmbrzl** [comment]
@ZeroAbility how so?

**Comment by ZeroAbility** [comment]
@davidebeatrici and I were discussing it. I didn't realize it was a script. This was my mistake.

> This may be the source of the issue:
> 
> https://github.com/mumble-voip/mumble/blob/0ba1eac51b5f4443e6fbb1bc3e157403903e9a01/overlay_gl/CMakeLists.txt#L12

**Comment by Krzmbrzl** [comment]
Btw. I do have a `libmumbleoverlay.x86_64.so.1.4.0` and a `libmumbleoverlay.x86.so.1.4.0` in my build directory. I am using KDE Neon (based on Ubuntu).

@radioactiveman could you please check your build directory and see if you have these as well?
Iirc we never had an actual overlay executable on Linux. That's why we had the overlay_wrapper script (or whatever it was called) :thinking:

**Comment by Krzmbrzl** [comment]
Ah I think I found it: There's a `mumble-overlay` script inside our `scripts/` directory.

@radioactiveman where did you expect this to be? I assume you want this to get installed via `make install`? I assume this should go into the user's `bin` directory (using something like `install(FILES mumble-overlay TYPE BIN)` in the respective CMakeLists.txt), right?

**Comment by radioactiveman** [comment]
@Krzmbrzl: Good catch, I didn't know `mumble-overlay` is actually a script. And yes, I would expect it to be installed by CMake to the bin directory. See also the file list of the Arch and Debian package in the original post.

But even if it gets installed, it will not work anymore. The script checks for a libmumble.so.1 file which are gone with CMake builds. My build directory contains instead `libmumbleoverlay.x86_64.so.1.4.0` and `libmumbleoverlay.x86.so.1.4.0` (plus two symlinks) but they are also not installed by `make install`.

**Comment by davidebeatrici** [comment]
The qmake project only built the library for the native architecture.
The reason why we decided to cross-compile the 32 bit library on `x86_64` (as we do on Windows) is because most games are `x86`.

However, we have to change the script to reflect that (it should use the correct library depending on the target's binary architecture).

Since we had to change the name anyway, we added `overlay` to it in order to make the purpose more clear.
