### ISSUE TITLE
Shortcut to listen to a channel

### ISSUE THREAD

**Issue by absfilho2** [mumble-voip/mumble#4486]
I believe that this implementation can be used for broadcast communication and also for games that want to hear a channel that is rolling a song for example.

Could you put a shortcut so you can start and end listening to a certain channel?
If you can have the implementation of a shortcut also to adjust the level of the channel. It will be perfect.

**Comment by timjwkim** [comment]
Is this an issue that I'd be able to pick up and work on?

**Comment by Krzmbrzl** [comment]
@timjwkim great to hear that! :) 

Yes this should be fairly easy to implement. To see how shortcuts can be added to Mumble, have a look at this recent PR: https://github.com/mumble-voip/mumble/pull/4562
You need a bit more but if you poke around in the respective code parts you should find all you need.

And furthermore you'll need to know how to add a new listener. For that, have a look at
https://github.com/mumble-voip/mumble/blob/13098748a9badf85f1faac65574570c3e9be3478/src/mumble/MainWindow.cpp#L2247
(in order to use this function, you'll have to have included `Global.h` in the source file you're editing - which usually is the case already anyways).

If you have further questions and/or need help, let me know :)

**Comment by timjwkim** [comment]
![Screen Shot 2020-11-08 at 10 51 53 PM](https://user-images.githubusercontent.com/44936218/98499413-735d0400-2217-11eb-9883-1c59193a77ec.png)

I forked a clone of the current Mumble repository. After running through the steps located in the build instructions for MacOS, I run into this compilation error. Is there something I am missing?

**Comment by Krzmbrzl** [comment]
I assume you are following the build instructions [located in this repo](https://github.com/mumble-voip/mumble/blob/master/docs/dev/build-instructions/README.md), right?

**Comment by timjwkim** [comment]
Yes, I am following the build instruction located in that repo. 
I decided to re-clone and re-build. One thing I ran into is: 

![Screen Shot 2020-11-09 at 10 18 50 AM](https://user-images.githubusercontent.com/44936218/98562584-3aa14700-2278-11eb-8df2-48a1373f2136.png)

which I resolved by the submodule `git submodule update --init --recursive` and re-running cmake.

I continue to run into the issue mentioned above which happens when "Linking CXX executable ../../Mumble.app/Contents/MacOS/Mumble"

**Comment by Krzmbrzl** [comment]
Okay that's interesting. From the error mwssage I assume that for some reason you habe installed a 32bit version of OpenSSL but are building a 64bit version of Mumble.

Could you verify that the OpenSSL version installed via homebrew is 64bit and that you are actually linking against this spwcific OpenSSL version and not any other onw thst might be installed on your system?

@TerryGeng do you have an idea what might be the problem. As you know my MacOS knowledge is very limited ^^

**Comment by timjwkim** [comment]
<img width="1126" alt="Screen Shot 2020-11-10 at 11 44 14 PM" src="https://user-images.githubusercontent.com/44936218/98769766-a4bc0800-23ae-11eb-8fe6-eb1706be142e.png">

It seems like I am using the 64bit version of OpenSSL. The only issue I can think of is that I am somehow linking against another version of OpenSSL. Is there a way I can confirm that I am using the 64bit version of OpenSSL when building and compiling?

**Comment by davidebeatrici** [comment]
It's possible that it's linking to Apple's SSL library.

I would try to pass `-DOPENSSL_ROOT_DIR=/usr/local/opt/openssl` to CMake.

**Comment by timjwkim** [comment]
That did the trick! 
Thank you so much :)

**Comment by timjwkim** [comment]
That did the trick! Thank you so much!

**Comment by davidebeatrici** [comment]
No problem!

We should probably add a note to https://github.com/mumble-voip/mumble/blob/master/docs/dev/build-instructions/build_macos.md.

**Comment by timjwkim** [comment]
Hi! Quick question: is there a public server accessible in Mumble in which I could use to test the changes that I make in my mumble build?

**Comment by davidebeatrici** [comment]
Hi! I generally start a local server to test changes, so that I can easily test server-side ones as well.

**Comment by timjwkim** [comment]
What is the general method of listening into channels? When I right-click on a specific channel it does not come up in the dropdown menu.

**Comment by kripton** [comment]
Which version of server and client are you using? Listening to channels is a feature that has not made it into any release

**Comment by Krzmbrzl** [comment]
As kripton said. As this is a feature that requires server-side support, it will only be shown in the context menu if the server's version is 1.4.0 or higher. Thus you'll probably have to use a locally hosted server that is running the current state of the master branch

**Comment by timjwkim** [comment]
I have been using the current state of the master branch (version "1.4.0"), but I have only been using the latest available server on the mumble site -- so that was my mistake. After switching to the server build available on the current state of the master branch, I got an error saying that I failed to set TOS for the UDP and TCP Sockets:
![Screen Shot 2020-12-12 at 10 56 12 PM](https://user-images.githubusercontent.com/44936218/102002726-74c59480-3ccd-11eb-835f-8b7c5adcf50f.png)

**Comment by Krzmbrzl** [comment]
I have never seen this error before. Maybe this is some security feature of macOS with regards to TCP sockets? :thinking: 

Details on what TOS is: https://en.wikipedia.org/wiki/Type_of_service
