### ISSUE TITLE
Linux Mumble - Launching Mumble causes all audio to stop 

### ISSUE THREAD

**Issue by HarrisonLeece** [mumble-voip/mumble#4515]
**Describe the bug**
If mumble is launched (Root or normal user) audio streams such as Youtube or an on disk mp3 will stop playing audio, and pause without the ability to resume playback.  Mumble audio does not play.  When Mumble is closed, music resumes playing normally, and any audio which should have played in mumble (such as TTS messages) will play simultaneously.  Oddly enough the input device seems to be working as intended...  I have already tried forcing TCP, as suggested but this does not fix the issue.

**Steps to Reproduce**
1. Open an audio stream
2. Open Mumble
3. Observe bug as described above

**Expected behavior**
I would expect audio channels to remain playing and for Mumble be able to playback.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Linux 20.04 LTS
 - Version: Mumble 1.3.0+dfsg-1build1
 - Source: ubuntu-focal-universe

**Additional context**
I am running my own mumble server on the same machine.

**Comment by davidebeatrici** [comment]
Which audio backend does the issue happen with?

**Comment by HarrisonLeece** [comment]
PulseAudio, thank you for any information you have.  I don't see anything
in the terminal...

**Comment by Krzmbrzl** [comment]
I a using Mumble on Linux as well but I have never experienced this issue :thinking: 

Have you tried using a different audio interface?

**Comment by cbs228** [comment]
![Mumble audio backend](https://user-images.githubusercontent.com/3526918/97520407-2d778480-1969-11eb-8878-d6e61214f1e4.png)

@HarrisonLeece, your bug report mentions trying to run mumble as the root user. This should not be done! PulseAudio runs one daemon per user and will only play audio from the current user.

The most frequent cause of this behavior on linux—at least for me—is using ALSA or (the ancient) OSS. Have you double-checked that both your Audio Input and Audio Output devices are set to `System: PulseAudio` as per the above screenshot?

With ALSA, only one program is typically allowed to use the sound hardware at a time. If programs suddenly stop being able to stream media, and streams won't play at all, it's frequently because some program grabbed the sound device with ALSA.

If you are running any programs which use ALSA sound output, you should set them to use the `pulse` ALSA device. This is a virtual ALSA device which passes through to PulseAudio. Any number of sound programs can use this, and thus play sound, at once. I think most web browsers use PulseAudio natively these days, so you shouldn't have to configure them for anything.

Have you made any changes to your pulseaudio configuration files?

You might try installing `pavucontrol` and running the "PulseAudio Volume Control" (`pavucontrol`) program while you test this. This program is very useful for seeing all of your audio streams and devices.
