### ISSUE TITLE
When "Listening" to a channel (#4011), text messages should also be delivered

### ISSUE THREAD

**Issue by kripton** [mumble-voip/mumble#4539]
**Context**
* User resides in **ChanA** and *listens* to **ChanB**
* Audio in **ChanB** is delivered to user thanks to the feature implemented in #4011 

**Describe the feature you have in mind**
* Text messages / chat that occurs in **ChanB** should also be delivered to user

I *plan* to work on this myself but of course if someone else is faster, that would be awesome. I do have the build system working for Linux and I do have some experience with Qt-based apps. However, the mumble source code and protocol are new to me.

**Comment by Krzmbrzl** [comment]
I'm not entirely sure that this is something that a user would/should expect when _listening_ to a channel :thinking: 

On the other hand there is probably not much that actually speaks against doing so in any case :shrug: 
And I do see some value in scenarios where e.g. someone references a link that (s)he has posted in chat that currently a listener won't be able to see.

> However, the mumble source code and protocol are new to me.

No problem. if you have any questions (which you probably will), just let me know. I'm happy to help :)

I think the implementation is actually rather straight forward: When receiving a text-message on the server, relay them to all listeners of a channel, that don't receive the message already (due to links, or simply due to being in that channel).

**Comment by kripton** [comment]
> I think the implementation is actually rather straight forward: When receiving a text-message on the server, relay them to all listeners of a channel, that don't receive the message already (due to links, or simply due to being in that channel).

Are you referring to *Channel Links* as documented here: https://wiki.mumble.info/wiki/ACL_and_Groups#Mumble_Access_Control_Vocabulary ? That feature was new to me, thanks for pointing it out :) However, I did a quick test and even with linked channels, the chat messages are not shared to all users in that link group (text messages are only given to the users in the channel they appear in, not to the users in other channels of the same link community). Do you think this should be done as well for consistency? Should that (and the case that I requested for the `Listeners` (I'd call them `Ears` because of the icon ;)) be discussed somewhere else than here as well?

**Comment by Krzmbrzl** [comment]
Yes I am referring to exactly that.

Okay then we only have an open feature requests for text-messages to be relayed from linked channels: #1719
I wasn't sure whether this is already implemented or not.

> Do you think this should be done as well for consistency?

Well if you want to, that'd be nice :+1:

> Should that (and the case that I requested for the Listeners (I'd call them Ears because of the icon ;)) be discussed somewhere else than here as well?

Here's fine (your PR works just as well).
Yeah I kinda switch between `Listeners` (due to the name of the action) and `Ears` :shrug:

**Comment by kripton** [comment]
Ops, I forgot to search for similar tickets. I'll implement the "text messages to linked channels" after PR #4540 is done.

**Comment by kripton** [comment]
Implemented by #4540. Thanks for merging so quickly!
