### ISSUE TITLE
Push to talk does not work in EVE Online in v1.4.0

### ISSUE THREAD

**Issue by strich** [mumble-voip/mumble#4595]
**Describe the bug**
Push to talk shortcuts don't work in EVE Online windowed mode in the latest snapshots.

**Steps to Reproduce**
1. Run EVE Online in windowed mode.
2. Use a push-to-talk shortcut (Tried F13, space, shift+ctrl). It does not activate.
3. Try the same shortcut with any other application focuses - It DOES activate.

**Expected behavior**
I the 1.3 stable version everything works as expected. In this latest snapshot it appears that Mumble is not able to capture key presses from EVE.

**Screenshots**
N/A.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: `1.4.0~2020-11-22~g0464d60~snapshot`

**Comment by elknif** [comment]
Confirming issue exists in release build: 1.4.230

Providing some more information.

I was experiencing similar behavior regarding PTT shortcut in a windowed game (Genshin Impact). I did not experience this issue in a full screen (Armello) and windowed full screen game (Guild Wars 2). To test this out, I switched Genshin Impact to full screen and restarted the game. The issue persisted. The likely difference is Genshin Impact requires some elevated permissions within Windows (UAC prompt). The other games and mumble do not. This ends up with the applications (Genshin Impact and Mumble) being at different permission levels within Windows and does not allow them to send information back and forth (key press events). If I recall correctly, Windows interprets the UAC prompted application to be a different user/session than non-UAC prompted applications. 

Genshin Impact has the same issue with Discord (PTT in Discord doesn't work with Genshin Impact due to the different levels). If EVE Online requires the escalated privileges within Windows, that would also result in the applications being at different permission levels.

OS: Windows 10 Pro x64
Mumble: 1.4.230

This issue didn't exist in 1.3.4. Not being familiar with the change log and inner workings, I could certainly understand if a commit for another issue to adhere to the Windows security model is the cause of this.

**Comment by Krzmbrzl** [comment]
We changed the API for shortcuts (raw input instead of direct input) so the change probably is due to that.

To me it seems like the issue is at Window's side though. If we don't receive a key event (which appears to be the case since I am not aware of any filtering that is performed on our side), there is not much we can do about it, it seems :thinking:


@elknif have you tried to verify your theory by running Mumble as administrator and then checking whether shortcuts work again?

**Comment by elknif** [comment]
Yes. Running Mumble as administrator does allow the shortcuts to work. I also tried using the shortcuts with applications not run as administrator and they work too. With the API change, it seems like to get the global shortcuts to work with everything, Mumble needs to be run as administrator on Windows.

**Comment by davidebeatrici** [comment]
Looks like we forgot to enable `elevation`:

https://github.com/mumble-voip/mumble/blob/5598fe82c7369c816ddac3cf51e1c5332351f71a/src/mumble_exe/CMakeLists.txt#L35-L37
