### ISSUE TITLE
Strings ending in ... are not translated though present in localization file

### ISSUE THREAD

**Issue by Ledarium** [mumble-voip/mumble#4654]
**Describe the bug**
Strings ending in `...` are not translated in Russian localization. I am not sure what is causing this, but these strings are definitely present in translation file: https://github.com/mumble-voip/mumble/blob/6625f9a877d0b107c05a32c0c4189843965a59a7/src/mumble/mumble_ru.ts#L5926

**Steps to Reproduce**
1. Set Russian localization
2. Go to Main menu

**Expected behavior**
Strings should be taken from Russian localization file.

**Screenshots**
![2020-12-25_15-37](https://user-images.githubusercontent.com/10389237/103135169-7f1d6080-46c7-11eb-9760-67fc612700aa.png)

**Desktop (please complete the following information):**
 - OS: Linux, Windows
 - Version: Mumble 1.3.3

**Comment by Ledarium** [comment]
I have tested German translation and it seems to be working fine there.

**Comment by Krzmbrzl** [comment]
Note that `Hide Mumble` is also not translated even though it does not contain any periods.

The issue however seems to be that these Strings are not translated in the 1.3.x series. The file you linked and checked is from current master (aka 1.4.0). It turns out the linked string was translated about 14 months ago whereas the last translation update for the 1.3.x series happened approx. 2 years ago.

To verify that the issue is indeed only that the String is not translated in 1.3.x, could you please check out the newly released [1.4.0 snapshot](https://www.mumble.info/blog/first-mumble-1.4.0-development-snapshot/) and report back whether that solves the issue?

**Comment by Ledarium** [comment]
Yes, in 1.4.0 snapshot strings are translated, thanks. This issue can be closed. Btw, any chance to include my translation updates (which were made today) into 1.4.0 or next release only?

**Comment by Krzmbrzl** [comment]
Perfect :+1: 

> Btw, any chance to include my translation updates (which were made today) into 1.4.0 or next release only?

1.4.0 has not yet been released yet. The snapshot release really only is a snapshot. That means that we don't have reached feature nor translation freeze for it yet.
So yes: Any translations that are currently made, will indeed be part of the actual 1.4.0 release (and also of the next snapshot).
