### ISSUE TITLE
Close quietly straight to system tray

### ISSUE THREAD

**Issue by buckwangs** [mumble-voip/mumble#4682]
Mumble is just one of those apps you don't want to open and close all the time. It's either open or it's closed. It's felt a "Close to tray" option may be a valuable ease-of-use addition to Mumble. At the moment, most software that hangs out in the tray will 9 times out of 10 silently close straight to it. With Mumble, you'll always get a prompt of "do you mean to quit or minimize?".

It doesn't have to be a default but an option of closing straight to the tray would be nice.

Thank you for considering this feature request <3

**Comment by Krzmbrzl** [comment]
The relevant code section is this:
https://github.com/mumble-voip/mumble/blob/ffb2b70b32558c4db0619ea22a7c6865fba58dc2/src/mumble/MainWindow.cpp#L474-L497

Imo it'd be best if we added an optional `Minimize instead of close` behavior that is used in case the user clicks the x button on the window instead of selecting `Quit` from Mumble's menu (in which case Mumble should really quit).
Thus if this potential new option is active, we would then always minimize Mumble instead of closing it, if the close event was triggered by pushing the x button on the Window.

If a user then wants the `Close to tray` functionality as is requested, they could simply turn on `Minimize to tray` in addition to `Minimize instead of close` and that should give the desired effect.

**Comment by buckwangs** [comment]
Sounds good. Yes, exit to tray, quit on quit. Unfortunately I do not know 1/100th the C++ I probably should. Hopefully this feature could one day be implemented. Thank you for your consideration :)

**Comment by Krzmbrzl** [comment]
> Unfortunately I do not know 1/100th the C++ I probably should. 

Hehe then this is a great opportunity for you to learn a bit more :P 
It should be relatively straight forward, so if you feel like it, definitely give it a try. I would also be willing to assist you in the process :point_up:

**Comment by buckwangs** [comment]
> I would also be willing to assist you in the process

That's an incredible offer of generosity and I honestly can't dare take you up on it. I'm sure if ever I touch the source code it'll be after a couple months of at least learning the basics of C++ and then moving on to the style, conduct and contribution, etc. 

Thank you, I'll remember the offer though, perhaps one day I will ask <3

**Comment by JKalliomaki** [comment]
I could try to get on this! Never contributed to open source before but I'm semi familiar with qt. I'll see what I can do

**Comment by Krzmbrzl** [comment]
@JKalliomaki that'd be great. If you need any further information, let me know. And if you want to, you can create a pull request early on so that I/we can directly start giving feedback and/or assistance :) 

In case you did not find it yet, the instructions on how to build the project are here: https://github.com/mumble-voip/mumble/tree/master/docs/dev/build-instructions

**Comment by JKalliomaki** [comment]
So as a beginner my first question would be that how do I create pull request? Am I right that I need to create my own branch for it? And then create PR from that?

**Comment by trymeouteh** [comment]
+1 for pressing the window close button to keep it running in the tray and not quit mumble
