### ISSUE TITLE
No notification for <1.4.0 clients that server has "Channel listening" enabled

### ISSUE THREAD

**Issue by Natenom** [mumble-voip/mumble#4687]
Tried with Mumble client 1.3.3 (Arch Linux) on a 1.4.0 (git master) Mumble server.

**Comment by Krzmbrzl** [comment]
From the code I don't see why this should not happen:
https://github.com/mumble-voip/mumble/blob/3a00d3770e305136e644595ce7f5c5a80411cfe4/src/murmur/Messages.cpp#L515-L537

The only things that I could imagine are
1. That your client for some reason does not authenticate itself (and thus this function is never called)
2. The client's version is set wrong
3. I messed up the version check

Of these possibilities I think option 3 is the most likely. It wouldn't be the first time I screwed up hexadecimal version IDs xD

@davidebeatrici could you perhaps have a look at the version ID as well in order to double-check it? :)

**Comment by Krzmbrzl** [comment]
Scratch that. I found the issue. I did not account for unrestricted ChannelListeners properly :point_up:
