### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by Survivalwar** [mumble-voip/mumble#4712]
**Describe the feature you have in mind**
1“Serverless, peer-to-peer architecture that uses[Distributed Hash Tables (DHT)](https://en.wikipedia.org/wiki/Distributed_hash_table)
2'use Blockchains

**Comment by Krzmbrzl** [comment]
This is simply not feasible for Mumble. It would require rewriting basically everything and therefore this does not make sense. If you want something like this, I think creating a new, separate project would be the way to go.

Something that _might_ be possible for Mumble would be to make use of #4049 in order to decrease dependence on an external server.

But as I said: Completely removing the server from the equation is just not feasible.
