### ISSUE TITLE
Whisper/Shout reversal option.

### ISSUE THREAD

**Issue by SpyB0rg** [mumble-voip/mumble#4747]
**Context**
Whispering to one channel rather than shouting to the whole room should be priority.

**Describe the feature you have in mind**
An option to reverse Whisper as default and Shout requires a key press to activate.

**Describe alternatives you've considered**
Not using mumble, because everybody else tells me that i am shouting to the whole room, not just the channel i'm in.

**Additional context**
I use mumble on a 2nd PC, the keyboard is not near me, i don't want to have to press a key to Whisper, if Whisper/Shout is reversed so that Whisper is the default voice and Shout requires a key press, would be much appreciated.

**Comment by Krzmbrzl** [comment]
I think you misunderstood how whispering and shouting work.

If you don't press a special key, you are talking normally. Thus everyone in the same channel and everyone in a channel that is linked to your current channel (if any) can hear you. In 1.4.0 in addition to that people listening to your channel or any channel linked to it can also hear you.

In order to whisper or shout you have to press a key that you have configured for this purpose.
For whispering you are selecting a user as a whisper target whereas for a shout you register a channel (tree) as a target. So which one you are using depends on what you have chosen when configuring the shortcut.
In 1.4.0 there is also the option to use the current selection in the UI as the whisper or shout target. In this case whether you are shouting or whispering it depends on what you have selected in the UI (channel or user) and can therefore also change with the selection.

Note however that in order to whisper _or_ shout, you always have to press a button. The default is to talk to all people in your channel.
Thus if you don't have a keyboard at hand (and did not configure a button on another device (mouse, joystick, ...)), you can't do either.

And if your request is really about whispering by default and requiring a key press for what currently is "normal speaking", then I will have to say that this won't happen. This would break the underlying concept of Mumble.

If you want to talk to an individual person, go ahead and create a (temporary) channel for the both of you, switch into that and then speak as usual.

**Comment by SpyB0rg** [comment]
I see, well I am new to mumble, and I use it for an online game, the group
of players I used it with have for example a channel with 4 other channels
within it.....when I talk normally (which I have been told is shouting) all
the players in the linked channels can hear me.....this is not what they
want, they want me to speak in the channel I am in.....there for, I HAVE to
use whisper.....and I do NOT want to press a button to talk......so there
is no way I can whisper using voice activation ?? That is basically what I
need.....not push to talk wether it's normal, shout or whisper.....just
voice activated ....normal, shout or whisper....basically......it's got
nothing to do with not having a keyboard or needing to press a key to talk
normally....voice activation work with normal speech (no key press
required) why can shout and whisper also not use voice activation.....I
don't want to press a key to whisper....I can only use whisper (as per
instructions from friends in channel) I want to use voice activation.....

Thank you.

**Comment by Krzmbrzl** [comment]
No this is not supported.

If your group doesn't want conversations to leak out of channels, they'll have to remove the links between these channels and/or update their server-side ACLs.

To me this sounds like a misconfigured server that needs to be fixed by the server admin.

**Comment by SpyB0rg** [comment]
Hi, thank you Robert. Much appreciated.
