### ISSUE TITLE
Place the per-user audio volume slider directly in the context menu

### ISSUE THREAD

**Issue by SeerLite** [mumble-voip/mumble#4748]
**Context**
When I'm too lazy to read the options or have to turn down the volume for someone quickly.

**Describe the feature you have in mind**
Move the volume slider from the "Local Volume Adjustment..." option to the context menu directly.

**Describe alternatives you've considered**
Add big colorful icons to the context menu options or move the less used ones to a sub-menu, to make it less cluttered with text and make the volume more obvious. **Edit:** Even just renaming it from "Local Volume Adjustment..." to just "Volume" is a really good improvement.

**Additional context**
Discord adds the volume slider directly to the context menu and it's a really smooth experience for when you have to reach it quickly.
![image](https://user-images.githubusercontent.com/21978144/107609826-cb444600-6c1e-11eb-882f-25bb0ab39506.png)

**Comment by Krzmbrzl** [comment]
### Implementation note

In order to do that, we'll have to use [QWidgetAction](https://doc.qt.io/qt-5/qwidgetaction.html) for adding the entry to the menu.

I guess the process would be to remove the `UserLocalVolumeDialog` and incorporate its functionality into a custom `QWidgetAction`.
And for consistency's sake, if this is done, then this should also be done to `ListenerLocalVolumeDialog`. It should be possible to create a base-class with the basic functionality and then subclass it for the user's and listener's volume adjustments.

**Comment by SC1040-TS2** [comment]
Having tested the existing process, it seems that the issue may be a case of user perception, given it is currently as simple as "find annoying user, right-click on annoying user, click on thing below Ignore Messages, turn slider in pop-up all the way down, close pop-up." At that point, most of the time overhead is in determining which user is the one whose volume just increased all of a sudden, to which Local Mute can be used as an immediate fix before using the Local Volume Adjustment slider to preference.

Adding it to the context menu removes some of the steps, but may clutter the existing menu a bit more and be in conflict with the existing UI design unless scaling down and shortening the slider dial to fit it in the context menu is manageable.
