### ISSUE TITLE
RPC commands take to long

### ISSUE THREAD

**Issue by terenc3** [mumble-voip/mumble#4751]
**Context**
When executing a rpc command like togglemute it taks more than a second to execute the command, which is way to long

**Describe the feature you have in mind**
Add a simple mumble-cli which can execute RPC commands

**Describe alternatives you've considered**
Using hotkeys

**Comment by Krzmbrzl** [comment]
Please have a look at https://github.com/mumble-voip/mumble-json-bridge

From my tests I have found that using the CLI from that, the reaction time is much better.

Note however that this will only work once #3743 has been merged (and it will also only work in 1.4.x not in 1.3.x since this won't be backported).
If you want to play around with that already, you can build Mumble from my PR and then build the JSON wrapper. Then install the corresponding plugin and enable it inside Mumble. And then you can go ahead and start playing with it :)

**Comment by terenc3** [comment]
@Krzmbrzl That looks promising but may i ask why you choose named pipes instead of unix socket/ip socket? Because the latter would allow to skip the cli and embed the calls directly into my application

**Comment by Krzmbrzl** [comment]
Mainly because it was the first thing that came into my mind. Also named pipes seemed to be somewhat similar on Windows and Unix so I thought that this would allow for an easy cross-platform implementation (turned out to be not that easy after all though).

If you want to interface with Mumble through your program directly, you should probably create a dedicated plugin for that. You can base that on https://github.com/mumble-voip/mumble-plugin-cpp in order to have a nice C++ wrapper for it.

Besides: You should be able to write to the named pipe directly from your program as well. No need for the CLI. You only have to know the path to the named pipe that you can copy over from the JSON Bridge's source code and that should be all that's necessary.
Note however that the CLI side does allow for more high-level functionality and it also can facilitate error handling.

**Comment by terenc3** [comment]
Thank you for your insight. I assume this issue can be closed, since you are working on the plugin topic and i will postpone my approach talking to mumble directly. Currently I'm bypass this issue by using hotkeys.
