### ISSUE TITLE
Mumble does not use icon on Plasma under Wayland.

### ISSUE THREAD

**Issue by baduhai** [mumble-voip/mumble#4851]
As the title implies, under Wayland, the icon does not get used. Here's what I looks like:

![image](https://user-images.githubusercontent.com/31864305/110759094-888d8200-824d-11eb-8e76-e50a13a7a537.png)

It seems as though notepadqq had the same [problem](https://github.com/notepadqq/notepadqq/issues/515) at one point. Specifically due to this:

> On X11 the applications exported the window icon as pixmap data. This is no longer possible on Wayland. Instead the compositor maps the window icon from the desktop file and the application announces the desktop file for a window. In Qt this is done by using the reverse domain name combined with the binary name. The domain name is set with KAboutData and defaults to “kde.org”. So for example in the case of kate the desktop file should be called “org.kde.kate.desktop”. So please fix the naming of your desktop files. If you want to test please be aware that this requires Qt 5.5 to work properly.

https://blog.martin-graesslin.com/blog/2015/07/porting-qt-applications-to-wayland/

The [fix](https://github.com/notepadqq/notepadqq/pull/661/commits/619ac281a969507602a874850b73d7a67cff1326) seems simple enough, will try to open a pull request when I have some time.

**Comment by Krzmbrzl** [comment]
The only problem I see with this is that ultimately we don't control the name of the desktop file (this is determined by whoever is packaging Mumble for that distro).
However given that we _are_ providing an official desktop file (https://github.com/mumble-voip/mumble/blob/master/scripts/org.mumble_voip.mumble.desktop) I think we should make it work with that one and then a packager has to fix it for themselves if they want to use a different one :point_up: 

In order to make this work though, we probably have to adapt
https://github.com/mumble-voip/mumble/blob/0e376a9fc6fe1247bfb29be6396592346b10e20c/src/mumble/main.cpp#L168-L170
as well (which by looking at this now seems like a good idea anyways)
