### ISSUE TITLE
Notification for speaking when muted

### ISSUE THREAD

**Issue by KorbinianOrt** [mumble-voip/mumble#4866]
**Context**
When I mute myself in mumble and forget to unmute myself I would like to get a notification, that my Microphone is still turned off.

**Describe the feature you have in mind**
A notification sound, for when I talk into a muted Microphone

**Additional context**
Other conference programs have this and it's really useful, in my opinion.

**Comment by Krzmbrzl** [comment]
Introducing this would require a rewrite of the audio system though as the system being muted is caught very early on, we can't simply detect the situation you are describing.

At least this is as far as I know. @davidebeatrici do you perhaps know more?

**Comment by toby63** [comment]
In case this would be implemented; it should probably be optional, because many of the people I know use the mute option with constant audio or voice detection, so they would get an unwanted warning each time.

I also think that the muted state icon should be obvious enough :thinking:, but I don't really remember how it looks in the overlay for example.

**Comment by Gunzinger** [comment]
I also think this would be a very useful feature to have, especially for people without multiple monitors or people not using the overlay.
I dont think it would require a rewrite as Krzmbrzl said as you can still watch the audio statistics while muted and the signals are all processed (speech probability, snr, etc. is still being calculated).

Speaking while being muted without noticing it is always a nuisance, it would be great if that could be avoided.

**Comment by Krzmbrzl** [comment]
@Gunzinger note that for users who don't want to (or can't) use the overlay, there is now the so-called TalkingUI in 1.4.0. You can find out more information about it here: https://www.mumble.info/blog/first-mumble-1.4.0-development-snapshot/#talkingui
Maybe this already helps in your situation :shrug:

**Comment by pkern** [comment]
It's about talking when Mumble is muted. There's no need to check the audio subsystem or detecting hardware mute, it's just about detecting a talking sound level while you're locally muted. A brief audio cue would be sufficient, sent periodically when talking is registered while mute is on. Yes, it should be an option. In other systems it's default on, I'm ambiguous about that.

I would say that TalkingUI does not solve this for fullscreen games. (One popular game - CSGO - banned overlays.)

**Comment by Krzmbrzl** [comment]
> I would say that TalkingUI does not solve this for fullscreen games. (One popular game - CSGO - banned overlays.)

Absolutely. That was never the goal of it (for games or other fullscreen applications there's the Overlay after all). I was just pointing out that for users that are not using the Overlay (because they are nor running a fullscreen application) the TalkingUI might be helpful here.

I am not saying that this replaces the feature of a notification as proposed here. I just wanted to point to a potential "workaround" for the time being :point_up: 

----

> I dont think it would require a rewrite as Krzmbrzl said as you can still watch the audio statistics while muted and the signals are all processed (speech probability, snr, etc. is still being calculated).

Thinking about this again I noticed that I confused being muted with being deafened. In the latter case the entire audio (output) system is suspended and therefore it's currently not easy to check whether there would be any output if the user was not deafened.
For muting one the other hand I am somewhat confident that we are indeed keeping the audio input system alive.
