### ISSUE TITLE
certificate issue?

### ISSUE THREAD

**Issue by yifan513** [mumble-voip/mumble#4871]
I exported a certificate generated from iphone (the ios version) and copy to my MAC, and tried to import to the MAC version, it can decrypt it correctly, but the Chinese characters in the name part is mess up, the English characters are good.
Any issue in which side?
I can attach the test certificate here if you need.
Thanks
David

**Comment by yifan513** [comment]
I checked the code, seems MAC side is using MBSTRING_ASC code for CN part of the certificate, but ios is using MBSTRING_UTF8 for that part.
Is this correct?

**Comment by Krzmbrzl** [comment]
@davidebeatrici do you know details about the cert?

**Comment by yifan513** [comment]
I attached a test file, the password is 123 and you need to remove the appended .txt.
The CN should be “mumble用户”

[111.pkcs12.txt](https://github.com/mumble-voip/mumble/files/6157587/111.pkcs12.txt)

**Comment by davidebeatrici** [comment]
That's indeed the issue: https://github.com/mumble-voip/mumble/blob/3beb90245cf00f72de217a2819dc7bd1d564f5f9/src/SelfSignedCertificate.cpp#L144-L149

@Krzmbrzl Simply replacing `MBSTRING_ASC` with `MBSTRING_UTF8` should work.

**Comment by yifan513** [comment]
Nice job.
Yes, if you can release a fixed version soon, I will wait for you. 
BTW, I use to report a user order issue 
https://github.com/mumble-voip/mumble/blob/master/src/User.cpp
QString::localeAwareCompare sort is not a fixed order in channel on different platform, if you release new version, can you also fixed that?)
Thank you so much.

**Comment by Krzmbrzl** [comment]
The fix is in #4872.
I wouldn't get my hopes up for a fast release of a new version of the 1.3.x series though. These are a PITA to create for us and this is nothing I would consider critical.

The fix will be part of the next 1.4.0 snapshot though, so you could consider downloading that from our website as soon as it gets released.

> BTW, I use to report a user order issue
https://github.com/mumble-voip/mumble/blob/master/src/User.cpp
QString::localeAwareCompare sort is not a fixed order in channel on different platform, if you release new version, can you also fixed that?)

Please report that as a different issue. That makes keeping track of this kind of stuff easier. :point_up:

**Comment by yifan513** [comment]
Good. Nice to know.
Will create a new issue for the other.
Thanks
David
