### ISSUE TITLE
Multiple entries in installed apps listing

### ISSUE THREAD

**Issue by ProjectPatatoe** [mumble-voip/mumble#4921]
**Describe the bug**
1.4.0 snapshots are creating multiple entries in installed apps list

**Steps to Reproduce**
Just install 1.4.0 versions as they come out.

**Expected behavior**
Updating old entry with new version instead of making a new one

**Screenshots**
Inside of Program Files...
![image](https://user-images.githubusercontent.com/27925441/114007846-8996dc80-9816-11eb-8ca6-d9194a0b9b6d.png)
Inside of Apps & Features...
![image](https://user-images.githubusercontent.com/27925441/114008271-ed210a00-9816-11eb-9e26-34a5aaf532ff.png)

You can ignore 1.3.3 being installed (thats more of an #4702 issue)

**Desktop (please complete the following information):**
 - OS: Win10 20H2
 - Version: 1.4 snapshots

**Comment by Krzmbrzl** [comment]
@ZeroAbility @davidebeatrici could you have a look at this, please?

The first snapshot not getting updated properly might be understandable since we introduced build numbers to our versioning only after that. At least since the second snapshot though I would have expected the upgrade to work by replacing the old version :thinking:

**Comment by ZeroAbility** [comment]
Based on the attached image, 1.4.0 is missing its trailing `0` in the version number. I don't know if that is a factor. Were there any other modifications made to the WixSharp files in  PR somewhere? This was definitely working. The Upgrade ID needs to be the same throughout each installer build and is found here:

https://github.com/mumble-voip/mumble/blob/f04d6635a9158a5dc42ccc814eb36e5272fdf4b3/installer/ClientInstaller.cs#L19

@ProjectPatatoe are you able to see the value listed here in the registry or the installer?

**Comment by ZeroAbility** [comment]
I downloaded the latest snapshot from the website (1.4.0.131) and the Upgrade ID matches. The behavior for the same version install and installer is correct. It asks to repair or uninstall. I would suggest removing all the 1.4.0 snapshot versions listed and don't install the oldest snapshot that you have. If I recall correctly, it was before we started applying the required 4th digit in the build number. I will see if I can confirm that with older snapshot versions after the initial snapshot release.

**Comment by ProjectPatatoe** [comment]
> 
> https://github.com/mumble-voip/mumble/blob/f04d6635a9158a5dc42ccc814eb36e5272fdf4b3/installer/ClientInstaller.cs#L19
> 
> @ProjectPatatoe are you able to see the value listed here in the registry or the installer?
@ZeroAbility 
A regedit search of `D269FC55-4F2C-4285-9AA9-4D034AF305C4` shows nothing. What do you mean by "in the installer"? The MSI properties does show `{91DCD639-31DD-4E67-8372-4373B8D82342}` as revision number but I don't think thats what you mean.

**Comment by ProjectPatatoe** [comment]
Searching for "mumble" instead through regedit, I found `Computer\HKEY_CLASSES_ROOT\Installer\Products\73D17CA5B3AC80F43ABFE0E0A554B2F1` that did list the current version's msi. PackageCode is `936DCD19DD1376E4382734378B8D3224`

**Comment by ZeroAbility** [comment]
> @ZeroAbility
> A regedit search of `D269FC55-4F2C-4285-9AA9-4D034AF305C4` shows nothing. What do you mean by "in the installer"? The MSI properties does show `{91DCD639-31DD-4E67-8372-4373B8D82342}` as revision number but I don't think thats what you mean.

You can use a utility like orca or SuperOrca to review items in the `msi` file database. There was another MS used to recommend called MSIAnalyzer. I believe this is the value that should be searched for:

https://docs.microsoft.com/en-us/windows/win32/msi/using-an-upgradecode

I'm wondering if this is a byproduct of having 1.3.x and 1.4.0 installed. Could you try installing the previous snapshot and the latest one after removing all installed versions?

**Comment by ProjectPatatoe** [comment]
So it would seem the package contains the info. I have uninstalled all versions (stable/snap) and still have the same problem
![image](https://user-images.githubusercontent.com/27925441/114949416-d9246c00-9e05-11eb-82a8-14ce7a0a2cb9.png)


msi analyzer

1.4.0 2021-04-03
  UpgradeCode                            | VersionMin | VersionMax | Language | Attributes | Remove | ActionProperty
  -------------------------------------- | ---------- | ---------- | -------- | ---------- | ------ | --------------
  {D269FC55-4F2C-4285-9AA9-4D034AF305C4} | 1.4.0.131  |            |          | 0          |        | NEWPRODUCTFOUND
  {D269FC55-4F2C-4285-9AA9-4D034AF305C4} | 0.0.0.0    | 1.4.0.131  |          | 256        |        | UPGRADEFOUND

1.4.0 2021-03-20

  UpgradeCode                            | VersionMin | VersionMax | Language | Attributes | Remove | ActionProperty
  -------------------------------------- | ---------- | ---------  | -------- | ---------- | ------ | --
  {D269FC55-4F2C-4285-9AA9-4D034AF305C4} | 1.4.0.122  |            |          | 0          |        | NEWPRODUCTFOUND
  {D269FC55-4F2C-4285-9AA9-4D034AF305C4} | 0.0.0.0    | 1.4.0.122  |          | 256        |        | UPGRADEFOUND


1.3.4.winx64
  UpgradeCode                            | VersionMin | VersionMax | Language | Attributes | Remove | ActionProperty
  -------------------------------------- | ---------- | ---------- | -------- | ---------- | ------ | --------------
  {E028BDFC-3FE2-4BEE-A33B-EB9C80611555} |            | 1.3.4      |          | 513        |        | WIX_UPGRADE_DETECTED
  {E028BDFC-3FE2-4BEE-A33B-EB9C80611555} | 1.3.4      |            |          | 2          |        | WIX_DOWNGRADE_DETECTED

**Comment by ZeroAbility** [comment]
This could potentially be an issue upstream:

https://github.com/oleg-shilo/wixsharp/issues/964

**Comment by Krzmbrzl** [comment]
This (from the linked issue) sounds worrying for us:
> Yes, while you can have 4-parts version, MSI only recognizes first 3-parts. It's an old dog that doesn't know new tricks :)

**Comment by ZeroAbility** [comment]
> This (from the linked issue) sounds worrying for us:
> 
> > Yes, while you can have 4-parts version, MSI only recognizes first 3-parts. It's an old dog that doesn't know new tricks :)

It was required in order to get the correct behavior for snapshots during testing. The versioning also seems to be correctly applied in MSI Analyzer, and is correctly reported in Windows 10. Alternatively, we could change our numbering scheme by dropping the 4th segment and using the increment behavior on the third segment. See this description:

https://docs.microsoft.com/en-us/windows/win32/msi/productversion

**Comment by Krzmbrzl** [comment]
Well there it explicitly states
> Note that Windows Installer uses only the first three fields of the product version. If you include a fourth field in your product version, the installer ignores the fourth field.

So to me this seems like the root cause for this issue: We only changed the fourth field as we use that for the build version (given that we are using SemVer).

Changing the third part of the version instead does not really seem feasible to me since that would break with our current versioning scheme where the third version part is the patch level and not the build number. Plus this would make it impossible to make the stable release version 1.4.0.

The only (viable) alternative I currently see would be to use odd-numbered minor versions for snapshot releases and even numbered ones for stable releases (or switched). That way we could still use the patch-level as usual. Thoughts?

**Comment by davidebeatrici** [comment]
It would be very confusing. The best solution would probably be to achieve the behavior our old installer had: upgrade even if the version is the same.

**Comment by ZeroAbility** [comment]
That may work if we modify the installer name on each snapshot build instead of the 4th segment of the version number. We need some way to tell what is installed in the Apps section of Windows. It's just very strange that despite what the document says, it was working as intended during manual testing.

**Comment by Krzmbrzl** [comment]
> That may work if we modify the installer name on each snapshot build instead of the 4th segment of the version number.

We could just add the build number to the installer name.

**Comment by ZeroAbility** [comment]
i.e. `snapshot-xxxxx`

**Comment by davidebeatrici** [comment]
What happens exactly when the installer name is different?

**Comment by ZeroAbility** [comment]
We actually have to change objects `Name` and `OutfileName` when initializing the new installer objects in `Client` and `Server`. This will change the installer name and the name of the entry in Apps. This will make it easier to identify which version of a snapshot is installed.

**Comment by davidebeatrici** [comment]
Still a problem, all versions are installed in the same directory.

**Comment by ProjectPatatoe** [comment]
still a problem in 191
![image](https://user-images.githubusercontent.com/27925441/118580413-afcc6800-b744-11eb-836e-5ead14aab4b5.png)

**Comment by Krzmbrzl** [comment]
@ZeroAbility did you have a chance to look into this further?

**Comment by Krzmbrzl** [comment]
@ZeroAbility ?

**Comment by ZeroAbility** [comment]
Apologies for the silence. We discussed this briefly in the meeting today. Windows Installers do not recognize the fourth segment of a product version. On top of that, the version of WixSharp we are using may be the older version that does not include a fix to a known Upgrade issue. We would need to look at that and apply needed changes. I don't think this is a showstopper for the 1.4 release since 1.3.x and older need to be manually uninstalled anyway.
