### ISSUE TITLE
Crash Upload Failed

### ISSUE THREAD

**Issue by Dastardly2000** [mumble-voip/mumble#4928]
![Crash_Uploading_Failure](https://user-images.githubusercontent.com/44360668/114371573-88e4aa00-9b78-11eb-932c-9e9a0481d8e1.PNG)

Starting Mumble, something crashed and then it failed to upload the crash dump with the attached error 203

**Comment by Krzmbrzl** [comment]
What version are you using? And on which OS (Windows I assume)?

**Comment by Krzmbrzl** [comment]
Quoting from Wikipedia an newtork error code of `203` seems to be
```
203 Non-Authoritative Information (since HTTP/1.1)
    The server is a transforming proxy (e.g. a Web accelerator) that received a 200 OK from its origin, but is returning a modified version of the origin's response.
```

@davidebeatrici given that we are using Fastly it seems plausible to me that Fastly has somehow modified the corresponding packet and is therefore returning `203`.

See also the description from [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/203):
```
The HTTP 203 Non-Authoritative Information response status indicates that the request was successful but the enclosed payload has been modified by a transforming proxy from that of the origin server's 200 (OK) response .

The 203 response is similar to the value 214, meaning Transformation Applied, of the Warning header code, which has the additional advantage of being applicable to responses with any status code.
```

I think we should probably consider all 2xx status codes as success (which is also the classification found on Wikipedia). @davidebeatrici what do you think?

**Comment by Kissaki** [comment]
Yes, all 2xx should probably be taken as success.

I’m not sure I get the specifics of that description in our context, because changing HTTP response body does not make sense to me, but modifying the headers does; so I assume payload means headers too here. And then we would want to accept that indeed.

**Comment by davidebeatrici** [comment]
I'm not sure why the error code is 203, but the issue was caused by me forgetting to change the script path in Apache's site configuration for `crash-report.mumble.info` after migrating all services to Exoscale.

Same for `update.mumble.info`, which caused Apache to transform itself into a benchmarking tool, using all cores of the CPU at 90%+. Here's the result:
```
-rw-r----- 1 root adm   6000742771 Apr 13 08:22 update.mumble.info_access.log
-rw-r--r-- 1 root root 12883264294 Apr 12 23:50 update.mumble.info_access.log.1
-rw-r----- 1 root adm   4610628403 Apr 13 08:03 update.mumble.info_error.log
-rw-r--r-- 1 root root 10038281590 Apr 12 23:50 update.mumble.info_error.log.1
```
```
-rw-r----- 1 root adm   5723M Apr 13 08:22 update.mumble.info_access.log
-rw-r--r-- 1 root root 12287M Apr 12 23:50 update.mumble.info_access.log.1
-rw-r----- 1 root adm   4398M Apr 13 08:03 update.mumble.info_error.log
-rw-r--r-- 1 root root  9574M Apr 12 23:50 update.mumble.info_error.log.1
```

**Comment by woodkoodaa** [comment]
Not sure if relevant to this issue, but my issue has crash uploading error 401. https://github.com/mumble-voip/mumble/issues/4932
