### ISSUE TITLE
Improve global shortcuts binding UX

### ISSUE THREAD

**Issue by Kissaki** [mumble-voip/mumble#5026]
Pressing the Add button to add a new shortcut should guide the user through setting it up.

At the moment it is multiple individual steps the user has to take that the user has to know about, and know about what to do.

The edit shortcut dialog should guide the user on how to use it. It should explain that multiple inputs can be combined, and that the user has to press Add and is then listening for input. This is completely unclear to the user right now. Nothing happens after pressing Add.

Preferably the setup would recognize key combinations without the need for users to individually bind keys that should be combined.

**Comment by trudnorx** [comment]
Yeah, users shouldn't have to click like 4 times per key to set up. Old setup was better, just 1 click required. Even with the raw input, that kind of UI could be kept. If a more complex UI is needed, it could be available as a menu option to "Customize" the hotkey.

**Comment by davidebeatrici** [comment]
The `Add` button actually remains pressed while listening for input, but unfortunately our theme doesn't show it. However, even without that cosmetic issue there's definitely space for improvement.

@trudnorx The reason why I decided to create the dialog in the first place is due to the old method not being versatile:

- All keys represented on a single line, as a result you cannot quickly distinguish separate devices.
- Inability to add/remove individual keys and/or devices, you had to register the entire shortcut again.
- Very little space for text, for which we originally implemented a workaround by writing the list into the tooltip.

**Comment by trudnorx** [comment]
Most users are fine with the older system and lose a lot with this change. Why not make it so by default it's like the old system but you can right click->customize a shortcut to show your dialog if you want to add multiple devices, etc.?

**Comment by davidebeatrici** [comment]
Why do you think they lose a lot of time?

**Comment by trudnorx** [comment]
Takes a lot more time to add multiple shortcuts compared to the old system.

**Comment by Hartmnt** [comment]
#5984 added "Listen for Input" and improved keyboard handling in this dialog. #6449 fixed the positioning.
I would say the usability has greatly improved.

If anyone has any more _specific_ requests for the edit shortcut dialog, please open a new issue for that.
