### ISSUE TITLE
1.4.0 Development snapshot not working on macOS < 10.15.0

### ISSUE THREAD

**Issue by heavygale** [mumble-voip/mumble#5039]
**Describe the bug**
Mumble windows doesn't come up after opening Mumble.app, the application closes immediately.

**Steps to Reproduce**
Try to start Mumble.app

**Expected behavior**
Mumble starts

**Screenshots**
Nothing visible, no window comes up.

**Desktop (please complete the following information):**
macOS 10.14.6.
Mumble 1.4 Development snapshots as of now.

Testet with both:
Client for macOS >= 10.13 (x64)
Client for macOS <= 10.12 (x64)

**Additional context**
Running the binary via command line reveals this error:

> Sorry, "Mumble" cannot be run on this version of macOS. Qt requires macOS 10.15.0 or later, you have macOS 10.14.6.

**Comment by davidebeatrici** [comment]
Thank you very much for reporting the issue!

We received a report a few days ago about the `NSAppearanceNameDarkAqua` symbol not being found on macOS < 10.14. For reference:

https://stackoverflow.com/questions/63513229/macos-app-crashes-on-10-13-with-symbol-not-found-nsappearancenamedarkaqua
https://github.com/qt/qtbase/blob/9db7cc79a26ced4997277b5c206ca15949133240/src/corelib/kernel/qcore_mac.mm#L357-L369

However, we were completely unaware about the minimum version being 10.15...

There's probably a dependency ignoring `CMAKE_OSX_DEPLOYMENT_TARGET`: https://github.com/mumble-voip/mumble/blob/8c99fe8119ce00fbcba55c69bde0a48383e7fa79/CMakeLists.txt#L39

Or the compiler itself is ignoring it because the value is too low.

**Comment by Krzmbrzl** [comment]
According to the [Qt docs](https://doc.qt.io/qt-5/macos.html#supported-versions) Qt is supposed to support macOS back to 10.13. Thus it's a bit odd that it claims that it requires 10.15 :thinking:

**Comment by Krzmbrzl** [comment]
@davidebeatrici maybe we have to explicitly set `VCPKG_MACOSX_DEPLOYMENT_TARGET` when building the macOS environment from vcpkg (https://github.com/microsoft/vcpkg/blob/62407516123a9aaf36710bce15368dd7ca9b168d/docs/users/triplets.md#vcpkg_osx_deployment_target)

**Comment by davidebeatrici** [comment]
Good catch, I'm pretty sure that's the solution.

I'm not sure whether `NSAppearanceNameDarkOrAqua` will be queried at runtime, but in our case it doesn't make any difference at the moment: #4420

**Comment by Krzmbrzl** [comment]
Will you rebuild the env then?

Also we should probably consider updating the referenced MacOS version in our cmake file to 10.13 instead of 10.9 as that's the minimum requirement for Qt5.

**Comment by davidebeatrici** [comment]
Yes, indeed.

**Comment by Krzmbrzl** [comment]
@davidebeatrici did you by any chance rebuild the env already? If not: do you still have that on your ToDo list? :)

**Comment by davidebeatrici** [comment]
Still have it on my list, I'm going to rebuild the environment for both Windows and macOS (to update all dependencies).

**Comment by Krzmbrzl** [comment]
This should bw fixed with the latest 1.4.0 RC already

**Comment by heavygale** [comment]
1.4.0 RC now works on my macOS 10.14.6 👍
