### ISSUE TITLE
Endless loop when canceling the Audio Wizard

### ISSUE THREAD

**Issue by vimpostor** [mumble-voip/mumble#5081]
**Steps to Reproduce**
1. Start Mumble for the first time
2. Click "Cancel" in the Audio Wizard
3. Endless loop

The endless loop that Mumble is caught in is in `Audio.cpp` line 299:
https://github.com/mumble-voip/mumble/blob/adf38593153a5ade60e89b4f92195006383ab201/src/mumble/Audio.cpp#L297-L301

I didn't have time yet to debug where these held pointers aren't released causing the deadlock.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Mumble 1.4.0 RC - adf385931

This doesn't seem to be tied to one audio backend only, I can reproduce it with both Pipewire and Pulseaudio.

**Comment by vimpostor** [comment]
The regression was introduced in ed2cf5c30.

Reverting the commit fixes the deadlock:
```diff
diff --git a/src/mumble/AudioWizard.cpp b/src/mumble/AudioWizard.cpp
index 0d466c079..c72045bf0 100644
--- a/src/mumble/AudioWizard.cpp
+++ b/src/mumble/AudioWizard.cpp
@@ -385,16 +385,15 @@ void AudioWizard::reject() {
 	Global::get().s = sOldSettings;
 
 	Global::get().s.lmLoopMode = Settings::None;
-
-	aosSource = nullptr;
+	restartAudio();
 
 	AudioOutputPtr ao = Global::get().ao;
 	if (ao) {
 		ao->wipe();
 	}
+	aosSource = nullptr;
 
 	Global::get().bPosTest = false;
-	restartAudio();
 	Global::get().bInAudioWizard = false;
 
 	QWizard::reject();
```

But simply removing the following section fixes the deadlock too:
```diff
diff --git a/src/mumble/AudioWizard.cpp b/src/mumble/AudioWizard.cpp
index 0d466c079..41ec30c86 100644
--- a/src/mumble/AudioWizard.cpp
+++ b/src/mumble/AudioWizard.cpp
@@ -386,13 +386,6 @@ void AudioWizard::reject() {
 
 	Global::get().s.lmLoopMode = Settings::None;
 
-	aosSource = nullptr;
-
-	AudioOutputPtr ao = Global::get().ao;
-	if (ao) {
-		ao->wipe();
-	}
-
 	Global::get().bPosTest = false;
 	restartAudio();
 	Global::get().bInAudioWizard = false;
```

I see that in the `accept()` method there is no such clean up code anyway so I am wondering why the code would be needed in `reject()`.

At a minimum the `aosSource = nullptr;` is unnecessary, as this is already done in `restartAudio()`.

**Comment by vimpostor** [comment]
The `ao->wipe()` section was introduced in 52b5939a80, but I cannot tell from the commit message whether it served a critical purpose.

**Comment by davidebeatrici** [comment]
The positional audio tester creates a looped sample, as such it keeps reproducing if the dialog is closed on that page and `AudioOutput::wipe()` is not called.

The code is not present in `accept()` because the function can only be called when reaching the last page of the wizard (at which point the sample doesn't exist anymore).

`AudioOutput`'s destructor actually calls `wipe()`:
https://github.com/mumble-voip/mumble/blob/0af1dfb36492f9d87e6c50e5a72bfff70f4e97f5/src/mumble/AudioOutput.cpp#L82-L91

https://github.com/mumble-voip/mumble/blob/0af1dfb36492f9d87e6c50e5a72bfff70f4e97f5/src/mumble/AudioOutput.cpp#L132-L135

https://github.com/mumble-voip/mumble/blob/0af1dfb36492f9d87e6c50e5a72bfff70f4e97f5/src/mumble/AudioOutput.cpp#L184-L198
