### ISSUE TITLE
SSL Version Mismatch

### ISSUE THREAD

**Issue by evokr** [mumble-voip/mumble#5110]
I've just created a recent server on minecraft and yeah it is called aternos.org and I tried connecting the server on mumble and it say "SSL Version Mismatch this server is using an older encryption standard, and is no
longer supported by modern versions of Mumble." I have no clue on how to fix this. I downloaded this on Win64 
and I tried talking to the creator of aternos that if their is a issue on their TLS/SSL version they said it's at 1.2

**Comment by Krzmbrzl** [comment]
> they said it's at 1.2

Yeah well that is indeed a super old version (like ~10 years old even though it has probably received bug fixes for longer - depends on what version exactly).

You'll have to install a recent Mumble server in order to be able to connect to it with a recent client as the old version is using insecure encryption schemes (or at least ones that are deemed insecure by more modern OpenSSL versions).

You can find newer versions here: https://www.mumble.info/downloads/

**Comment by evokr** [comment]
no I meant the minecraft server itself

**Comment by Krzmbrzl** [comment]
The Minecraft server is completely unrelated to this

**Comment by Krzmbrzl** [comment]
Did you even set up a Mumble _server_ or ar you trying to connect to your _Minecraft_ sever using a Mumble client?

**Comment by evokr** [comment]
no the minecraft itself kept crashing whenever I get in and the server will automatically close and say "ssl version mismatch"

**Comment by evokr** [comment]
I created a server using guildbit

**Comment by davidebeatrici** [comment]
You have to connect to the server provided by GuildBit in Mumble.

**Comment by Krzmbrzl** [comment]
> no the minecraft itself kept crashing whenever I get in and the server will automatically close and say "ssl version mismatch"

That does not answer my question. Please provide an answer to my question from above:
> Did you even set up a Mumble server or are you trying to connect to your Minecraft sever using a Mumble client?

The Mumble server is 100% unrelated to the Minecraft server so whatever you are experiencing with that one does not matter here at all. That is unless you are really trying to connect to your Minecraft server using Mumble in which case that will simply not work since a Minecraft server is not a Mumble server. These are two different things.

**Comment by evokr** [comment]
I didn't connect mumble to minecraft I connected my mumble thru a mumble hosting server but the server itself kept repeating "ssl version mismatch"

**Comment by Krzmbrzl** [comment]
Okay. So what is the version of the Mumble server you are using? And what client version are you using?

**Comment by evokr** [comment]
nvm I randomly fixed it by adding the mumbleLink mod in minecraft
