### ISSUE TITLE
Different datatypes for permissions in Mumble.proto

### ISSUE THREAD

**Issue by EPNW** [mumble-voip/mumble#5139]
While working with the `Mumble.proto` I noticed that the permission field of 

`PermissionQuery` in
https://github.com/mumble-voip/mumble/blob/31d0e8e7b4c7509cce1d128719c836a1a23acd4f/src/Mumble.proto#L469
and `PermissionDenied` in
https://github.com/mumble-voip/mumble/blob/31d0e8e7b4c7509cce1d128719c836a1a23acd4f/src/Mumble.proto#L303
are of the `uint32` datatype, while the permission field in `ServerSync`
https://github.com/mumble-voip/mumble/blob/31d0e8e7b4c7509cce1d128719c836a1a23acd4f/src/Mumble.proto#L110
is an `uint64`.

Is this on purpose or a bug?

**Comment by Krzmbrzl** [comment]
I would argue that this was not intentional but I don't think it qualifies as a real bug either since afaik we never exceed the uint32 range for the permissions.

I guess this is something that should have been fixed back when this was implemented but since it has been like this for a while now, we can't correct it without breaking the protocol :thinking:

**Comment by EPNW** [comment]
While I agree that it would break compability to change it, I would opt for putting a small note into the proto file itself, referencing this issue (as kind of documentation).

**Comment by Krzmbrzl** [comment]
Yes that sounds like a good idea :+1: 

Do you want to do it or shall I do it?

**Comment by EPNW** [comment]
I would leave that to you 😉

**Comment by Krzmbrzl** [comment]
-> #5144
