### ISSUE TITLE
Support - Is there any way to listen on multiple channels without joining them.

### ISSUE THREAD

**Issue by prashant-17-dev** [mumble-voip/mumble#5166]

**Comment by Krzmbrzl** [comment]
Yes this feature was introduced with version 1.4.0 - it's called "channel listeners".

You can download a snapshot release from our website. Note however that this feature will only work on servers running 1.4.0 as well.

If you are stuck with an earlier version, your only chance are channel links but these are not on an individual level.

**Comment by prashant-17-dev** [comment]
@Krzmbrzl I'm running a custom build of mumble-server (compiled by me). Facing the issue while running it. Not sure where to ask. -> MurmurIce: Initialization failed: ::Ice::VersionMismatchException

**Comment by Krzmbrzl** [comment]
See https://doc.zeroc.com/display/Ice35/Ice-VersionMismatchException for more info on that exception. 

It seems that the version of the ice library you are using is not the same, Mumble was compiled with. Did you perhaps compile on a different machine and then copy the binary or something like this?

If you need further assistance, please create a separate issue here so that we have one issue per topic :)
