### ISSUE TITLE
Is there any reason, that we have restricted VoiceTarget-ID(whisper targets) up-to 30 limit?

### ISSUE THREAD

**Issue by abwarlock** [mumble-voip/mumble#5180]
I'm referring to following 
[Mumble Proto Voice Target](https://github.com/mumble-voip/mumble/blob/master/src/Mumble.proto#L444)

As I was exploring mumble, I came across Whispering functionality. Looks interesting but as there is limit of 30 for setting VoiceTarget. 
I need to know that, limit is for number of session-id( aka Users) in voice-target or something else.

My use case:- I want to Talk with multiple players across the different channels.

**Comment by Krzmbrzl** [comment]
Yes: Audio packets have a single 8-bit header byte of which 3 bits are encoded for the type of the audio packet (Celt vs Opus) and only the remaining 5 bits are left for the actual voice target. That means there are only 2^5 = 32` distinct voice targets that can be addressed. And of these `0` is reserved for normal talking and `31` is reserved for server loopback mode. So that leaves targets 1-30 for regular voice targets.
https://github.com/mumble-voip/mumble/blob/ce90876bf02866ea08ab66c940f0c73ba66d531a/src/murmur/Server.cpp#L1108-L1109

Fun fact: The official Mumble client only ever uses distinct voice targets and recycles IDs (re-registers them with a new target) if more are needed.
https://github.com/mumble-voip/mumble/blob/ce90876bf02866ea08ab66c940f0c73ba66d531a/src/mumble/Messages.cpp#L145
https://github.com/mumble-voip/mumble/blob/ce90876bf02866ea08ab66c940f0c73ba66d531a/src/mumble/MainWindow.cpp#L2910-L2990

**Comment by abwarlock** [comment]
Thanks for update @Krzmbrzl. 
I have one more query, how many VoiceTarget can be register on there server by number of user at same time.

My use case:
Can '100+'  users register different whisper targets at same time.

**Comment by Krzmbrzl** [comment]
> Can '100+' users register different whisper targets at same time.

Yes, there is no limitation on that. Each user may register up to 30 distinct voice targets (provided the server has access to enough RAM to store all targets).

**Comment by abwarlock** [comment]
Thanks again @Krzmbrzl ,
Just curios when will be Murmur server 1.4.x will be available for Linus distribution. Came across **Listener Proxy**  feature looks interesting.

**Comment by davidebeatrici** [comment]
It's already available for linux distributions, you can compile it.

**Comment by Krzmbrzl** [comment]
And if you are referring to non-self-compiled versions, I can't tell. It depends on when the respective package managers decide to package it. On Arch it is already available whereas on Ubuntu I expect it to not be available before we have released 1.4.0 officially and then Ubuntu needs to release a new version with an updated repo.

We are also looking into generating packages like AppImages but that is currently not a priority, so I can't tell when that will happen

**Comment by Krzmbrzl** [comment]
I'm closing this issue as resolved. If you have further question, feel free to ask :)
