### ISSUE TITLE
1.4.0 snapshot 6 crashes because of opus.dll

### ISSUE THREAD

**Issue by ViBE-HU** [mumble-voip/mumble#5223]
**Describe the bug**
Referring to [this](https://github.com/mumble-voip/mumble/issues/4932#issuecomment-892769855) I opened this issue. So if I'm not wrong 1.3.4 stable version uses Opus codec already and that build runs without any issue. I directly changed from that to the new snapshot and this build instantly crash when I start Mumble.

**Steps to Reproduce**
1. Start Mumble

**Expected behavior**
It should run.

**Desktop (please complete the following information):**
 - OS: Windows 10 Build 19043 (19041.vb_release.191206-1406)
 - Version: Mumble 1.4.0.191

**Additional context**
The affected machine is a Lenovo ThinkPad R61. It is an upgraded oddware with a Penryn based [Intel Core 2 Duo T9300](https://www.cpu-world.com/CPUs/Core_2/Intel-Core%202%20Duo%20Mobile%20T9300%20FF80576GG0606M%20(BX80576T9300).html). While the motherboard is Meron based the only difference in specs is the SSE4.1 capability.

**Comment by Kissaki** [comment]
When the crash occurs the Mumble crash reporter opens and you submitted a crash report?

**Comment by Kissaki** [comment]
If you can provide a stacktrace here that could be helpful too as a starting point for anyone looking into this.

**Comment by Krzmbrzl** [comment]
Quoting from #4932:

The error log is
```
A hibát okozó alkalmazás neve: mumble.exe, verzió: 1.4.0.191, időbélyeg: 0x60a164a5
A hibát okozó modul neve: opus.dll, verzió: 0.0.0.0, időbélyeg: 0x60a16375
Kivételkód: 0xc000001d
Hiba pozíciója: 0x000000000001f350
A hibát okozó folyamat azonosítója: 0x17ec
A hibát okozó alkalmazás indításának időpontja: 0x01d789245c117909
A hibát okozó alkalmazás elérési útja: C:\Program Files\Mumble\client\mumble.exe
A hibát okozó modul elérési útja: C:\Program Files\Mumble\client\opus.dll
Jelentés azonosítója: ef84c957-293f-4e96-82b0-72ce94f17bb0
A hibát okozó csomag teljes neve: 
A hibát okozó csomag relatív alkalmazásazonosítója: 
```
which google-translates to
```
The name of the application that is causing the error: mumble.exe, version: 1.4.0.191, timestamp: 0x60a164a5
The name of the module causing the error: opus.dll, version: 0.0.0.0, timestamp: 0x60a16375
Exception code: 0xc000001d
Error position: 0x000000000001f350
The ID of the process that caused the error: 0x17ec
The time that started the application that is causing the error is 0x01d789245c117909
The path to the application that is causing the error is C: \ Program Files \ Mumble \ client \ mumble.exe
The path to the module that is causing the error is C: \ Program Files \ Mumble \ client \ opus.dll
Report ID: ef84c957-293f-4e96-82b0-72ce94f17bb0
Full name of the package causing the error:
Relative application ID of the package causing the error: 
```


Error code 0xc000001d seems to be "Illegal instruction" (see https://stackoverflow.com/questions/44231673/debugging-0xc000001d-exception-with-windbg) meaning that your CPU does not support some instruction that seems to be used inside the Opus library.

From [this post](https://stackoverflow.com/questions/47899971/c-getting-error-illegal-instruction-core-dumped-upon-bitwise-or-operatio) it seems that this is probably because on the machine we build our windows bianries there are some CPU instructions that are not available on your computer and therefore it fails.
I think in order to figure out how to proceed with this, we'll have to figure out what instruction is the issue exactly.
@Kissaki or @davidebeatrici does one of you have experience with figuring this out based on the given memory address? :thinking:

**Comment by ViBE-HU** [comment]
> When the crash occurs the Mumble crash reporter opens and you submitted a crash report?

yes it opens but @Krzmbrzl told that feature is dead. so i did not sent the report.

**Comment by Kissaki** [comment]
If it’s actually CPU instructions compiled with but not supported my first suspect would be the SSE/SSE2 extensions.

As you asked for it, my assumptions would be as follows:

if `Error position: 0x000000000001f350` indicates the memory or dll offset (which may be the same), then it should be discoverable while running, with a debugger, or maybe even from the dll itself.

A stacktrace may be very helpful though to get the function (maybe even the context may be useful) that contains the unsupported CPU instruction. Given that no stacktrace was posted above, the dump - which contains the stacktrace - would be very helpful to debug it - especially with the instruction pointer at the correct address already, which should simplify discovery.

What kind of CPU are you using @ViBE-HU ?

The easiest approach may be to check the CPU for supported CPU instruction sets and simply compile a test version for ViBE to try out without it. As I said before, if this is actually the issue, SSE2 seems very likely (which has been common for a long time, but may still be missing on still used older CPUs). Otherwise, we should be able to discover which instruction sets are supported and not supported here.

**Comment by ViBE-HU** [comment]
i mentioned in the additional info it is an [Intel Core 2 Duo T9300](https://www.cpu-world.com/CPUs/Core_2/Intel-Core%202%20Duo%20Mobile%20T9300%20FF80576GG0606M%20(BX80576T9300).html).

**Comment by davidebeatrici** [comment]
Reproduced on an [Arrandale](https://ark.intel.com/content/www/us/en/ark/products/codename/32724/products-formerly-arrandale.html) Intel Core i5.

Opus is probably attempting to use the AVX instruction set because it relies on what the machine it is compiled on supports.

**Comment by davidebeatrici** [comment]
@ViBE-HU The binary built from CI in #5229 should work.

**Comment by ViBE-HU** [comment]
cool. do i have to test?

**Comment by davidebeatrici** [comment]
That would be great, thanks!

**Comment by ViBE-HU** [comment]
where can i download the Windows x64 build?

**Comment by davidebeatrici** [comment]
https://dev.azure.com/Mumble-VoIP/Mumble/_build/results?buildId=5158&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by ViBE-HU** [comment]
it's working. thanks. but i had to start it for a few times. first it started with english without any error messages. then i changed the language and it won't started automatically. i tried to start it again but nothing happened. i checked the the task manager and looks like the application does not even stopped. it was stuck in the background and generated an event in the system log because of the mumble_app.dll [as i mentioned](https://github.com/mumble-voip/mumble/issues/4932#issuecomment-892667812) before. if i kill the process the application will starts normally with the selected language.

**Comment by Krzmbrzl** [comment]
I think what you are seeing now is #4932
