### ISSUE TITLE
Emit DBus signal when talking state changes

### ISSUE THREAD

**Issue by neumantm** [mumble-voip/mumble#5248]
**Context**
When using the mumble desktop client on a Linux system that has a DBus.

**Describe the feature you have in mind**
It would be great if the mumble desktop client would emit a DBus signal whenever the talking state changes
(so when I start or stop transmitting audio).
The new state (talking or not talking) should obviously be contained in the signal.

**Describe alternatives you've considered**
Currently I listen on the DBus, for when the mumble taskbar icon changes.
However, this is very flaky, is DesktopManager-specific and only works when the icon is visible.

Another way would be to replicate the mumble VAD and/or PTT behavior in another program.
Then I could configure mumble to use PTT on some special key I never use and control mumble using the `startTalking` and `stopTalking` DBus methods.
However, this would be a lot of additional work, especially if it should work with VAD.

**Additional context**
I'd like this feature to be able to visualize when I'm talking over mumble. 
("On-air" sign, etc.)
It could also be used to perform any other arbitrary action based on when the user starts or stops talking.

**Comment by Krzmbrzl** [comment]
I think this kind of feature should be implemented as a 3rdParty plugin instead of being implemented in Mumble itself. See https://github.com/mumble-voip/mumble/tree/master/docs/dev/plugins for a description of the new API (available since 1.4.0).

The reasons why I think this should be implemented externally is
1. Mumble is considering to completely remove the already existing DBus interface in favor of a plugin (see #4668)
2. This way in Mumble we only have to maintain the plugin API instead of also maintaining the different other APIs that currently exist in Mumble

@davidebeatrici @ZeroAbility  @Kissaki what are your thoughts on this?

**Comment by Kissaki** [comment]
I’m not too familiar with the technical things, but D-Bus has been queued for removal for a long time.
It was replaced with Ice a long time in the past.
I don’t think the primary reason for keeping it was backwards compatibility, but because some aspect still needed it anyway.
New triggers and stuff were added to Ice but not D-Bus, so I expect that to miss quiet a few things compared to Ice.
Usage has always been discouraged because of this nature - queued for removal; the outdated/deprecated API.

If the functionality remains, and people use it, I do not think adding one more event to our logic is a maintenance burden.
I’m fine with adding that.

Moving it to a plugin sounds good too in principle (especially considering separation of concerns).
But the same reasoning and questions apply.
Will we able to maintain it adequately? Can the community? Or would it be better to remove it entirely to nudge users to Ice, which is our primary and desired API (currently still)?

**Comment by Krzmbrzl** [comment]
@Kissaki I think you are mixing things up here. This about the client's DBus interface and not the server's

**Comment by Kissaki** [comment]
Yeah I did mix things up.

Does the client have dbus logic right now?

**Comment by Krzmbrzl** [comment]
Yes afaik there are very few ancient bindings that are available

**Comment by Kissaki** [comment]
I do think I thought of those as deprecated and scheduled for removal in the past.

**Comment by Krzmbrzl** [comment]
Yeah I thought the same. That's why I suggested that this could be handled by a plugin in the future so that we don't have to maintain these ancient bindings in the main code base.

**Comment by neumantm** [comment]
Ok, thank you. I will take a look at creating a plugin.

**Comment by Krzmbrzl** [comment]
@neumantm you can find the necessary docs for that at https://github.com/mumble-voip/mumble/tree/master/docs/dev/plugins

**Comment by Krzmbrzl** [comment]
Oh and just as a funny side-node: I think the two of us went to the same IT course back in school :D
