### ISSUE TITLE
channel_id is sometimes missing in UserState when joining the root channel

### ISSUE THREAD

**Issue by WGH-** [mumble-voip/mumble#5270]
**Describe the bug**
In `UserState` Protobuf messages sent by Murmur (which are sent when the user changes any info, joins a new channel, etc.) `channel_id` is not present in certain circumstances, making the protocol somewhat awkward to use.

To be precise, `channel_id` will be missing if it's the root channel (channel 0), and either the user whose state is being sent is already present in the root channel, or they've just connected. Sorry if that's not completely clear, the annotated log below illustrates the problem better.

The problem is that when `channel_id` is missing, it's somewhat awkward to figure out whether the user is in channel 0 (he's already there or he's just connected), or the `UserState` packet has been sent because of e.g. comment text change (and user's channels is actually unchanged).

**Steps to Reproduce**
I've prepared a bare-bones CLI Mumble client that logs Protobuf messages. Do it fast, because it doesn't sends pings :)

1. https://github.com/WGH-/mumble-channelid-bug-demo
2. `cargo build` (sorry, it's written in Rust)
3. `./target/debug/mumble-channelid-bug-demo 192.168.0.100:64738`
4. Connect with another client, try to join different channels, and observe `UserState` messages

```
# we have just connected, the other user is already in the root channel, "channel_id" is missing
UserState(session: 1 name: "WGH" user_id: 1 hash: "ec38e0ed4711e283e6d8ad34d4e47fb5b0dd6564")
# the other user moves to another channel
UserState(session: 1 actor: 1 channel_id: 1)
# the other user returns to the root channel, "channel_id" is present in this case
UserState(session: 1 actor: 1 channel_id: 0)
# the other user disconnects
UserRemove(session: 1)
# the other user connects back, "channel_id" is missing
UserState(session: 4 name: "WGH" user_id: 1 hash: "ec38e0ed4711e283e6d8ad34d4e47fb5b0dd6564")
# the other user moves to another channel
UserState(session: 4 actor: 4 channel_id: 1)
# the other user disconnects
UserRemove(session: 4)
# the other user connects back, "channel_id" is present
UserState(session: 6 name: "WGH" user_id: 1 channel_id: 1 hash: "ec38e0ed4711e283e6d8ad34d4e47fb5b0dd6564")
```

**Version:**
 - Version: Murmur 1.3.4

**Comment by Krzmbrzl** [comment]
I would argue that we can both agree on it making sense that the `channel_id` is not transmitted in cases where it didn't actually change (e.g. the user only changed their comment or something like this).

This leaves us with the situation in which a user freshly connects and ends up in the root channel. In that case this prevents the `channel_id` from being set explicitly:
https://github.com/mumble-voip/mumble/blob/296956c3e3e6100f05f6f2d1525fd592ef567a17/src/murmur/Messages.cpp#L419-L420

The commit that changed these lines is 13 years old now and does not mention any specific reason for this behavior. I assume the logic is as follows: If a client receives a `UserState` message for an user that is unknown to it (the user's session and/or ID are not yet known to the client), it is to place it in the root channel. If the message also contains a `channel_id` it is then to move that user from the root channel to the specified channel.

That being said though I think making the joining into the root channel more explicit is probably not a bad thing to do :thinking: 

In order to do that I think all that is needed is to remove the `if` from the code above and extend this code
https://github.com/mumble-voip/mumble/blob/296956c3e3e6100f05f6f2d1525fd592ef567a17/src/mumble/Messages.cpp#L387-L389
to only call `moveUser` if `channel` actually differs from `pDst->cChannel`.

Do you want to create a PR?

**Comment by Krzmbrzl** [comment]
@WGH- ☝️

**Comment by WGH-** [comment]
Yeah, I saw this. However, when I will finally have some free time to hack on Mumble, I'd rather invest it into more pressing issues, like 4883. Or investigate why lots of people around me always have trouble to setup Mumble.

**Comment by WGH-** [comment]
Fixing this issue might also break some obscure third-party clients that already work around this protocol quirk. I honestly don't know if it's worth it.

**Comment by Krzmbrzl** [comment]
Fixing this is so trivial that I simply did it now in #5324. Older clients should deal with this additionally information gracefully and if some obscure 3rdParty client breaks because of this, then they have a problem in their implementation anyway and should go fix it :shrug:
