### ISSUE TITLE
Plugin list showing duplicate entries in 1.4.0 rc1.

### ISSUE THREAD

**Issue by amackenzie** [mumble-voip/mumble#5271]
**Describe the bug**
When viewing the plugin list (Settings->Plugins), almost all plugins have at least a duplicate entry, sometimes more.

Unloading all plugins and pressing reload re-fills it with duplicates.

**Steps to Reproduce**
1. Go to the plugin section under Settings.

**Expected behavior**
A single entry for each plugin.

**Screenshots**
Duplicate plugins: https://i.imgur.com/H9qK95n.png

Plugin folder in mumble dir: https://i.imgur.com/EISF0en.png

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1.4.0 RC1 (Mumble (1.4.0\~2021-09-04\~g37ee677~snapshot)) (downloaded from https://www.mumble.info/downloads/#development-snapshots )

**Comment by davidebeatrici** [comment]
Do you perhaps have plugins in `%AppData\Mumble\Plugins`?

**Comment by amackenzie** [comment]
Just checked, that folder exists but is completely empty.

**Comment by davidebeatrici** [comment]
Okay, there's definitely a bug: all plugins have a duplicate entry.

If you're wondering why there are 4 entries for certain plugins, it's because they have separate x86 and x64 versions.

**Comment by amackenzie** [comment]
That makes sense, I just noticed that mousing over them has a "long name" tooltip that usually says x86/x64 for some relevant ones (FF14, for instance).

The duplicates don't sort consistently either (though I'm not sure if there's any rule for that). FF14's dupes go x86, 64, 86, 64, but WoW's go 86, 86, 64, 64.

**Comment by Krzmbrzl** [comment]
A few questions:
- Is the `Manual placement plugin` also listed twice?
- When you just hit reload a few times, does that create even more duplicates of the plugins or does it reproduce the initial problem (two entries for each plugin)?
- Are all plugins duplicated exactly twice (differentiating between x86 and x64 plugins)?

I am wondering whether there might be an issue with the plugins directory being added to the search path twice (on a case-insensitive filesystem as used by Windows).

Could you close Mumble, navigate to the plugins directory that you screenshotted and then move one of the DLLs out of that directory? Choose one whose name is obvious, e.g. `bf1.dll`. Then restart Mumble and check whether this has eliminated both entries for this plugin.
If it did, the duplicates are most likely caused by a duplicate in the searchpath. If it didn't, then it appears as if there are a duplicate set of plugins installed somewhere within the searchpath :thinking:

**Comment by amackenzie** [comment]
1. Manual placement only shows up once.
2. Mashing the reload button does not create more entries.
3. It looks like every individual plugin is listed exactly twice outside of Manual Placement.

Testing that process on bf1.dll removes both entries from the list when mumble is started without it, and both entries reappear when mumble is started after moving the dll back into the plugins folder.

**Comment by Krzmbrzl** [comment]
Okay then I am reasonably sure that we are dealing with a duplicate in the search path. I am thinking that currently `MUMBLE_PLUGIN_PATH` points to the same location as the hardcoded `./plugins/` directory. Mist likely the former is specified as an absolute path instead of a relative one though and thus a duplication can occur.

In that case the solution would be to convert all paths to absolute paths before adding them to the search pah set.
