### ISSUE TITLE
Mumble client dbus methods

### ISSUE THREAD

**Issue by icher** [mumble-voip/mumble#5287]
Hi. There's a chapter in documentation about dbus functionality in the Mumble **client**

https://wiki.mumble.info/wiki/DBus#DBus_in_the_Mumble_client

Can you please list all methods and how to use them?

**Comment by Krzmbrzl** [comment]
These are all available methods that _should_ be exposed via the DBus interface:
https://github.com/mumble-voip/mumble/blob/c453a8bded64914735c66e6f58cfdffb20999890/src/mumble/DBus.h#L23-L45

As to how they are used: I have no clue, since I have never used DBus before. But I assume with the examples on the wiki one should be able to figure this out.
