### ISSUE TITLE
Users should be sorted case-insensitively

### ISSUE THREAD

**Issue by promi** [mumble-voip/mumble#5293]
In Mumble 1.3 the user list in a channel used to be sorted case insensitive (User names starting with the same lower case and upper case letter were close together).

For example in 1.3:

- DrDoom
- drNo
- MrXYZ
- TimmyTrumpet
 
In current Git version:

- DrDoom
- MrXYZ
- TimmyTrumpet
- drNo

Notice how drNo is far away from DrDoom now.

If this was intentional: The new sorting breaks the old sorting (obviously), so users have to get used to a new order. I see no apparent advantage and consider this to be a bug.

Or is this an OS specific setting like LOCALE etc.?

OS is Linux (Gentoo Linux and Arch Linux both show the same ordering).
Commit is 756be79bee235f4a832317b7d1f2f6bfa5b8d300

**Comment by Krzmbrzl** [comment]
This was intentional: https://github.com/mumble-voip/mumble/pull/4875

The reason the sorting was chosen to be case-sensitive is that with Mumble it is possible to have multiple users whose names only differ in casing. In a case-insensitive comparison, this might introduce some level of arbitrariness in their order in channels (since all their names would compare equal)

**Comment by promi** [comment]
Why on earth would you have users that only differ by case? That is even more confusing to the other users. I would even disallow this in the database.

If it were not for certificates it would mean that the usernames in a username / password style login would have case sensitive usernames, have you ever seen this on any reasonable website?

Also as I already wrote it is not natural for humans to sort users in a case sensitive way. If there are two users named "paul" and "Peter" in the same channel no one in their right mind would expect  "paul" to be sorted after "Peter". It also changes the behavior from 1.3.

This is especially bad for visually impaired users who identify users by their location in the channel.

Is it possible to have a switch in the user interface settings to revert to the old behavior?

**Comment by promi** [comment]
Here is a great answer on the related subject of case sensitive filesystem:

https://www.quora.com/Should-file-systems-be-case-sensitive

> 
> Computers are tools for human beings. Humane computing adapts to the needs of human beings. It does not force human beings to adapt to what’s convenient for computers.
> 
> Case sensitivity is a human experience abomination.
> 
> No sane human being would expect “letter to mother.doc,” “letter to Mother.doc,” and “letter to mother.Doc” to be totally unrelated files with utterly unrelated contents. Yet that is exactly where case sensitivity takes us.
> 
> Computers are here for us. We are not here for them. The lash for any system architect who forgets that.
> 

It has 1.4 k upvotes.

**Comment by Krzmbrzl** [comment]
> Is it possible to have a switch in the user interface settings to revert to the old behavior?

No - this would only unnecessarily complicate things

> Why on earth would you have users that only differ by case?

Because users chose to name themselves like that? We don't have an influence on what users will pick as their username.

> I would even disallow this in the database.

That would be a possibility, if one really wanted that.

>  It also changes the behavior from 1.3.

So? This is not really an argument here, since the sorting of users is not an API and is thus not guaranteed to remain unchanged.

---

However, I think we could do the following: Perform an case-insensitive comparison and if the compared entities are not equal, use that. And only if the are equal in the case-insensitive comparison, will we perform a case-sensitive one. This should result in the behavior that you desire without introducing issues with names differing only in casing.

**Comment by promi** [comment]
> > Is it possible to have a switch in the user interface settings to revert to the old behavior?
> 
> No - this would only unnecessarily complicate things

OK.

> > It also changes the behavior from 1.3.
> 
> So? This is not really an argument here, since the sorting of users is not an API and is thus not guaranteed to remain unchanged.
>

I think that it is. I know at least to people who are impacted by such a drastic change in UI. One is sight impaired and the other has some mental difficulties and needs the user names and channel names to always be in the same location. This is an accessibility issue. You can't just make a change with such a big impact.

> However, I think we could do the following: Perform an case-insensitive comparison and if the compared entities are not equal, use that. And only if the are equal in the case-insensitive comparison, will we perform a case-sensitive one. This should result in the behavior that you desire without introducing issues with names differing only in casing.

That would be ideal, so the sorting is stable (= always has the same outcome) and the user names are again case-insenstive.

PS: I was a bit emotional about this change, sorry for that. The issue annoyed multiple people on our Mumble server.

**Comment by Krzmbrzl** [comment]
> I think that it is. I know at least two people who are impacted by such a drastic change in UI. One is sight impaired and the other has some mental difficulties and needs the user names and channel names to always be in the same location. This is an accessibility issue. You can't just make a change with such a big impact.

This argument is flawed. By that logic, the original bug should not have been fixed either, since the sorting very likely changed, due to it no longer being locale-aware. And one could even generalize this to any UI-change ever. And I think we can agree that such a premise is no good for the development of any project.

That being said, raising concerns about such changes is still important. Then we can discuss and see if we find a solution that works best for most cases and/or re-think the made changes based on the new arguments.

> That would be ideal, so the sorting is stable (= always has the same outcome) and the user names are again case-insenstive.

Alright, then let's do it that way :+1: 

> I was a bit emotional about this change, sorry for that. The issue annoyed multiple people on our Mumble server.

Yeah I noticed and was about to write something about it. Glad to see that you noticed it yourself though. And don't worry - we all have bad days every now and then :)
