### ISSUE TITLE
The priority speaker should either be saved/loaded or cleared when a user enters/leaves a channel

### ISSUE THREAD

**Issue by promi** [mumble-voip/mumble#5334]
As discussed in #5296 the current situation is not optimal. A user is assigned priority speaker and can take this state with her to another channel. This is usually not what is wanted at least on our server.

My suggestion is that it be saved on a per user per channel basis or that it be cleared when you leave a channel.

**Comment by Krzmbrzl** [comment]
I'll post this issue on our public matrix channel in order to get a few more folks to have a look at it.
If there are no good reasons, why it is necessary for the priority speaker property to be reassigned once a client rejoins the original channel in which they were given that right, then I would opt for the easy "remove priority speaker on channel leave" option.
