### ISSUE TITLE
publish registration server

### ISSUE THREAD

**Issue by qamodi** [mumble-voip/mumble#5335]
I cannot find the source code of the registration server anywhere publicly available.
It'd be great to publish it as free software, since the fact that Mumble is FLOSS is
the unique selling point.
There are a couple of possible use cases for hosting an own registration server.
The first one that comes to mind: If I were to use mumble in a corporation, having
an own mumble server for each department, I might want the mumble clients to
query an alternative registration server where the internal mumble servers are listed.

**Comment by Krzmbrzl** [comment]
Yeah the registration stuff is currently handled by a super ugly script on our server.

In order to use a custom registration server, the client and the server had to be modified anyway though. So the usecase you are describing isn't easily feasbible anyway :thinking:

At its core the list is only an XML list: https://publist.mumble.info/v1/list

Thus it should be quite easy to reimplement the functionality 👀

**Comment by davidebeatrici** [comment]
> Yeah the registration stuff is currently handled by a super ugly script on our server.

Not anymore, we've been using brand new scripts for a while now. As the author, I have no problems making them public.

**Comment by Krzmbrzl** [comment]
Ah okay then. Nice!

In that case I'd suggest creating a dedicated repository for these scripts :point_up:

**Comment by Krzmbrzl** [comment]
The scripts are now available at https://github.com/mumble-voip/backend-services
