### ISSUE TITLE
CertificateWizard: create trusted certificate link points to dead URL

### ISSUE THREAD

**Issue by hacst** [mumble-voip/mumble#5362]
### Description

Our certificate wizard links to a no longer existing documentation on how to create your certificate. Have to see whether we still have recent info to put there and whether we should restore/move/remove it.

### Steps to reproduce

1. In the certificate wizard click the link that explains how to create your own certificate
2. It opens to https://mumble.info/certificate.php which no longer exists

### Mumble version

1.3.4

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment]
I guess this page here seems to contain some information on the topic: https://wiki.mumble.info/wiki/Mumble_Certificates

**Comment by rgarrettrun** [comment]
Hello, I am a student looking to contribute to my first open source project for software engineering class. Would I be able to take this problem, and would you mind helping to walk me through what needs to be done?

**Comment by Krzmbrzl** [comment]
@rgarrettrun sure - great to see you are willing to help out :+1: 

As a general introduction to the Mumble source code, I recommend reading https://github.com/mumble-voip/mumble/blob/master/docs/dev/TheMumbleSourceCode.md (though for this particular issue it seems like that's not that important)

The link in question is set inside the `Cert.ui` file:
https://github.com/mumble-voip/mumble/blob/0e204e1d61fddc1934ce499975cae291450abfe3/src/mumble/Cert.ui#L33
(it'll probably be easiest if you edit this file via Qt designer).

The change itself should be rather trivial, but this issue is mostly about what to change the link to. I think the best approach would probably be to write a new documentation page detailing how one can obtain a strong/trusted certificate on our website and then linking to that.
Essentially that page would simply describe how one can obtain a proper SSL certificate and import it into Mumble. See also the links I posted here before.

So as you can see, this issue is mostly a documentation effort. If you are still willing to pick it up, the first step would be to create a PR with the mentioned documentation at https://github.com/mumble-voip/mumble-www (inside e.g. https://github.com/mumble-voip/mumble-www/tree/master/hugo/content/documentation/user)
