### ISSUE TITLE
UI is hard to use on small screens like Pinephone

### ISSUE THREAD

**Issue by mikebdp2** [mumble-voip/mumble#5412]
### Description

Currently it's really hard to use Mumble on small screens. I have to constantly rotate Pinephone between portrait and landscape modes to see more stuff, but even in this way - many of UI buttons/info can't be accessed!

Meanwhile, the android clients Mumla & Plumble are quite usable on Android phone of my friend. It could be possible to borrow their optimized-for-mobile UI, hopefully without losing any advanced settings, and offer to switch to it on the first startup _(and also to choose it later in settings)_ :

- [Mumla source code](https://gitlab.com/quite/mumla)
- [Plumble source code (archived)](https://github.com/acomminos/Plumble)

### Steps to reproduce

1. Install Mumble on Pinephone, i.e. on Alpine-based PostmarketOS:
`sudo apk add mumble` - package built using this [APKBUILD recipe](https://gitlab.alpinelinux.org/alpine/aports/-/tree/master/community/mumble)
Alternatively, install Mumble to a virtual machine with a low screen resolution like 800x600.
2. Open Mumble, try to use it and feel the pain :stuck_out_tongue: 

### Mumble version

1.3.4

### Mumble component

Client

### OS

Linux

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment]
As a desktop application, I'm don't think it is worth it to invest the time to adapt the UI to phone-sized screens. I would argue that in like 99% of the cases, whenever a user is using a phone-sized screen, it'll be running Android or iOS anyway and as such will have to use the respective native app.
Burdening the main desktop client with supporting this scenario as well just seems too much work for too little gain :thinking:

**Comment by davidebeatrici** [comment]
The issue mentioned by the user is something that can be annoying on desktop as well though, the settings dialog for example has a ridiculous minimum size enforcement.

**Comment by Krzmbrzl** [comment]
For the settings dialog, I agree, but ad I ubdertsood it, the main request here is to adapt the main UI and I don't think that that has size issues on desktop

**Comment by mikebdp2** [comment]
@davidebeatrici and @Krzmbrzl : it's strange that the users of the proprietary OS like Android/iOS are having a much more usable Mumble than the opensource-loving users of Pinephone: who couldn't run the proprietary crap like Whatsapp. Mumble could become a great fit for opensource VoIP void on the Pinephone - and get into a golden list of Pinephone apps. Maybe someone would suggest running a Mumble apk inside some Android emulator - but that's a really inefficient solution for the opensource software which could be - and has been originally created - to run natively.

If you feel that main UI could suffer in detail/usability on the ordinary desktop from the adaptation, please at least provide the alternative "mobile UI" which could be enabled by the user: there's already such a UI at [Mumla](https://gitlab.com/quite/mumla), could be copied from there

**Comment by Krzmbrzl** [comment]
it's not strange at all. Without having researched this, I would be confident in saying that the amount of Pinephone users is diminishingly low compared to either the Android or iOS users. That being said, the comparison is really lacking anyway, since the Android app has never been developed by the core Mumble team. That's a completely separate implementation that is in no way related to the main project (other than using the Mumble protocol specification). The iOS app on the other hand has been an "official" implementation by one of the core Mumble developers. Note however that it was developed due to personal need and if you look at the app now, it's in a miserable state, since it is completely unmaintained and outdated (said developer is no longer active). Thus, I'd doubt that any iOS user would currently testify that they are having a great experience.

That all is to say that "official" Mumble client is not and has never been aimed at being used on mobile devices in any way shape or form. All Mumble clients that have aimed at being mobile clients have always been rewritten from scratch, so far.

And providing a completely separate "mobile UI" is not feasible either, since for a mobile UI, certain concepts just have to be implemented in a radically different way, because of the different nature of the hardware and input methods. Thus, it would pose a significant maintenance burden on us, if we had to invent every UI change twice. And for the required burden, the amount of potential users is just not big enough.

If you want, you are of course more than welcome to fork this repo and adapt the UI to mobile and maintain that separately. Alternatively you could also walk the route of writing a minimal Mumble client aimed at mobile-sized devices. But the main Mumble desktop client will not be adapted to that. Not unless someone presents us with a good plan on how the UI is to be structured such that it will serve both needs (desktop & mobile) without requiring to maintain two separate UIs and without looking and/or feeling out of place on either platform.

**Comment by Krzmbrzl** [comment]
That is to say: If you have a good idea for how such a unification could look like, please share it. I just can't really come up with a good mockup

**Comment by fortysixandtwo** [comment]
@Krzmbrzl 

So I have been running Mumble a bit on a Librem 5 on Debian/Mobian and wanted to share some screenshots, as well as 
two videos so you can see how it currently looks like and what I think could be done to address the one shortcoming (which is the preferences window).

First of all: A ~45 minute meeting in Mumble while outside using cabled headphones (and moderating the call):

The stacked layout works really well on mobile!

![meeting](https://github.com/mumble-voip/mumble/assets/5196864/6fd8b248-2213-444b-9828-e09db5d67f51)


The preferences window (and trying to use the scale-to-fit for Mumble):
https://fortysixandtwo.eu/upload/mumble1.webm

When rotating the phone it becomes much easier:
https://fortysixandtwo.eu/upload/mumble3.webm

Originally reported at [Purism Gitlab](https://source.puri.sm/Librem5/OS-issues/-/issues/326)


Scale-to-fit could be fixed by increasing the minimum requested window size.
I will dig in to the sources (but any pointers welcome as I'm not familiar with the codebase and Qt) and can try hacking on this.

I  initially configured my Mumble using a NexDock360 because I didn't realize there were scrollbars (and that I could run it in landscape instead of portrait which already helps a lot).

**Comment by fortysixandtwo** [comment]
Scale-to-fit is performed by the (wayland) compositor [phoc](https://gitlab.gnome.org/World/Phosh/phoc/) and in the [purism issue](https://source.puri.sm/Librem5/OS-issues/-/issues/326) Sebastian said the following:

> From the video (mumble1.webm) it appears that the mechanism works fine. phoc tries to resize the window to fit the screen and if it ends up being oversized, it scales it down. In this case, Mumble doesn't end up with oversized window at all, it internally cuts the content instead, so phoc can't do anything as from its perspective the window fits.
Mumble would need to set a minimum size for the preferences window for it to get scaled.

**Comment by Maryjane-ai** [comment]
I think this issue title by mentioning specifically phones is not properly framed. Phones like the pinephone, Librem 5, One Plus 6, are basically GNU/Linux computers, with all the user space components that we are used to in a GNU/Linux operating system, with a small form touch screen as the main input, and that are _also_ capable of doing phone calls and SMS. 

Focusing specific cases for phones, brings up the Android versions of mumble into the topic.

I would frame this issue as something like: providing better mumble support for small form screens. 

I would argue that having better support for smaller forms helps not only with Pinephone, Librem 5, OP6, but also with other use cases like:  notebooks with small screens, tablets that run GNU/Linux like the pine64 tablet, laptop users that use tilling window managers. 

And I would be happy if mumble fitted better in smaller displays. And I would use it on my Librem 5

PS: I use the expression GNU/Linux to distinguish from Android.
