### ISSUE TITLE
Informations on the link-plugin

### ISSUE THREAD

**Issue by bmorel** [mumble-voip/mumble#5413]
### The issue

Hi. I have questions about how to integrate mumble into a FOSS game.
I have already found this page: https://www.mumble.info/documentation/developer/positional-audio/link-plugin/ and understand the big lines. The questions I have, and which could be answered by said page are:

1. if plugin is integrated, does the user still need to install mumble client?
2. can games provide a way to configure mumble, or does the user must go with mumble's client GUI (I'm not saying it's a bad one mind you, just asking!) 
3. should informations about players be sent by the game server, or by the game client?
4. can the plugin connect to a specific server (out of control of player, if you see what I mean)?
5. can the player connect to another server at the same time (clans, other chats, etc etc)?
6. the game I'm thinking to integrate mumble to is based on daemon-engine (https://github.com/DaemonEngine) which uses a system of VM to be able to run mods distributed by server. This means I may have to go through custom network API (I do not know yet). Is it possible to use the link-plugin in such situations?

### Mumble version

1.4.0

### Mumble component

I don't know

### OS

Other

PS: sorry, I noticed the "forum" entry only after posting this...

**Comment by Krzmbrzl** [comment]
1. Yes - the plugin essentially only serves as a proxy that relays information about the player's position to Mumble
2. With the new plugin system, a plugin is able to read and write certain settings without the user having to access the UI (Mumble needs to be running though). At this point only small portion of settings is currently exposed, bur we can easily extend that to your needs. Mind you though that this won't work via the link plugin but instead requires a dedicated plugin implementation.
3. The information should be sent by whatever is running on the same machine as Mumble (it has to access shared memory after all), which most likely ends up being the client
4. Not yet - but if needed, adding this functionality should be relatively easy. But again: That would require a dedicated plugin rather than using the link plugin
5. Unfortunately that is currently not possible. The only workaround is to start two separate Mumble instances (which has its own problems)
6. Using the link plugin requires to (eventually) write data to a region of shared memory. As long as you get that done, you can use it. Without knowing details about your system though, it's hard to tell

**Comment by Krzmbrzl** [comment]
Btw, in case you aren't aware of it, here are the docs for the new plugin system (starting from Mumble 1.4): https://github.com/mumble-voip/mumble/tree/master/docs/dev/plugins

This is what I mean, when I say that a dedicated plugin is necessary

**Comment by bmorel** [comment]
So, I assume link-plugin support was ceased between 1.3 and 1.4? (and I was not aware for that new doc, only fishing info for now, possibly going to poque the thing on a dumb project today as a PoC today, not sure)

**Comment by Krzmbrzl** [comment]
No no - the link plugin is still a thing at it will continue to work as usual. The new plugin framework is 100% compatible with all old plugins - it only drastically extends the possibilities for new ones :)

**Comment by bmorel** [comment]
Nice. I'll get a read at this. Maybe there will be answers to the questions I asked on opening, too :)
