### ISSUE TITLE
AUTHORS file hasn't gotten updated with new release

### ISSUE THREAD

**Issue by MoKe12g** [mumble-voip/mumble#5449]
### Description

I contributed for a in this release merged  pull-request #4531 and haven't gotten into the AUTHORS file.

I looked into [scripts/generate-AUTHORS.py](https://github.com/mumble-voip/mumble/blob/5574cc8e2462349ae953a9d0a4ed2dbe7dfeeba9/scripts/generate-AUTHORS.py#L116) and on line 116 it seems like the script is generating the AUTHORS file out of an old branch (origin/1.2.x) which isn't even accessible anymore.

This very much seems selfish of me asking, but it would be great if contributors would get something back.

### Steps to reproduce

Download the Mumble v1.4.230 sources https://github.com/mumble-voip/mumble/archive/refs/tags/v1.4.230.tar.gz and check the AUTHORS file

### Mumble version

v1.4.230

### Mumble component

Both

### OS

Linux

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment]
The AUTHORS file is not used anymore - we just haven't gotten around to deleting the file yet. Not even I am contained in it and I have been by far the most active developer here since two years or so ^^

All contributors are refernced in GitHubs metric (see the "Insights" tab), which provides a much better overview anyway :)
