### ISSUE TITLE
Flag bot connections, so user count does not get inflated by them

### ISSUE THREAD

**Issue by mweinelt** [mumble-voip/mumble#5461]
### Context

We currently have 5 bots on our mumble server. One is botamusique, four are telephone dial-in connections. That means our server always shows at least 5/100 users in the connection pane, while no actual people are connected.

### Description

Allowing bots to flag their connection as such would allow the server to advertise the actual number of people connected, which is more helpful to users joining.

### Mumble component

Both

### OS-specific?

No

### Additional information

Other options that we've considered:
- Having an ACL that prevents users in it from being counted
- Living with the offset :cry:

**Comment by m-lin1** [comment]
Did the above code solve the issue? I'm looking to be a first time contributor to an open source project, and I thought this might be a good first issue for me to solve if no one has done it yet.

**Comment by Krzmbrzl** [comment]
@m-lin1 no it has not been taken yet. You are very welcome to work on this :+1: 

Do you already have an idea on how this could be implemented or do you want some additional input from my side? And/or do you have any other questions with regards to Mumble & its code base?

**Comment by juanrodl** [comment]
Hey @Krzmbrzl, I'm looking to contribute to my first open-source project and I think this looks like a great opportunity. I'd be interested to look into this issue and help you with it if possible.

**Comment by Krzmbrzl** [comment]
@juanrodl it seems like @m-lin1 volunteered for this task first (that's the first time we have a collision in terms of people wanting to fix something xD)

We still have a bunch of [other issues](https://github.com/mumble-voip/mumble/labels/good%20first%20issue) that would be suitable for a first-time contribution. I could recommend e.g.
- https://github.com/mumble-voip/mumble/issues/4591
- https://github.com/mumble-voip/mumble/issues/4128
- https://github.com/mumble-voip/mumble/issues/4735

**Comment by juanrodl** [comment]
Thanks @Krzmbrzl, I'll look into these issues and hopefully I can help you with some of them 👍

**Comment by Krzmbrzl** [comment]
@juanrodl just let me know which issue you settle on and I will gove you details there :)

**Comment by m-lin1** [comment]
@Krzmbrzl additional input would be awesome, I just found this repository recently so I’m not too familiar with it yet. Also, do you have any suggestions on what to look at/where to start so that I can familiarize myself with the code here?

**Comment by Krzmbrzl** [comment]
> do you have any suggestions on what to look at/where to start so that I can familiarize myself with the code here?

Yes: https://github.com/mumble-voip/mumble/blob/master/docs/dev/TheMumbleSourceCode.md

----

In terms of implementing this feature I would imagine this to work something like this:
- Extend the `Authenticate` message with a new boolean that tells the server that the just connected user is a bot (Maybe using an enum here is better because in the future that would allow us to generalize to multiple kinds of "special" connections - but then again that might be overkill)
- Every time the server sees a connection with this special flag, it performs the authentication process as usual but in addition to that will increment a separate counter that keeps track of how many bots are currently connected
- Now when queried for the user count on the server (happens in ping messages - handled inside `src/murmur/Server.cpp`), the server calculates the amount of currently connected clients `qhUsers.size()`) and subtracts the amount of currently connected bot users from that to yield the real user count. That is then what is written to the respective field in the ping
- Additionally the `ServerUser` class will have to be extended by a boolean member flag that indicates whether this client is actually a bot. If it is, we have to decrease the bot count once that client disconnects from our server

**Comment by m-lin1** [comment]
@Krzmbrzl Thank you so much for the help and suggestions! I'll try to do my best with this during my free time.

**Comment by Krzmbrzl** [comment]
You're welcome :)
And no hurry - after all this is supposed to be fun and not stressful. Maybe you want to create a draft PR somewhat early on, so we can start discussing your changes right from the beginning.

**Comment by m-lin1** [comment]
Does anyone know if there is a special way that bots are identified in the code currently? I tried looking for something like that but I couldn't find anything. My thinking right now is to flag the bots in the ServerHandler.cpp file in the serverConnectionConnected function, but it seems like I'll need something else to indicate that the bot flag should be set for a user in the Mumble.proto Authenticate message. If someone knows if my logic is wrong or if there is a variable that only bots have, let me know.

Additionally, I'm currently having trouble being able to download the libraries because of something with my cmake, so it'll take me some time to figure that out. If someone wants to give this a try as well, I wouldn't be opposed to it.

**Comment by Krzmbrzl** [comment]
Atm Mumble does not know anything about bots. For it these are just regular users.

In order to implement this issue here though, no client-side changes are required. This is a purely server-side feature, so there should be no need to edit the ServerHabndler class.

Did you run `git submodule update --init`? Or are you having trouble with setting up the vcpkg environment?

**Comment by m-lin1** [comment]
Hmm, I see. I’ll try to look through things again sometime soon. 

I’m having troubles with downloading and installing the libraries in vcpkg, it vaguely says smth about a cmake error or smth about how there was an error executing smth? I’m not entirely sure but it pops up when I’m trying to install the qt libraries and also grpc if I remembered correctly. 

I haven’t ran the git submodule update —init, I think I missed some documentation on the build instructions, so I’ll probably try and look over those again as well and see if anything helps. Things have been getting busy on my side, so definitely not gonna be able to get this finished by the weekend like I wanted. Probably going to take a lot more time, but I’ll still try to solve this!

**Comment by Krzmbrzl** [comment]
If you are having issues with building a vcpkg env yourself, you can also download a pre-built one from https://dl.mumble.info/build/vcpkg/

**Comment by m-lin1** [comment]
It’s been a while, but I’m still busy and I haven’t been able to work on this at all if I’m being honest. So I wanted to say that I’ll be dropping this since I’m not sure when exactly I’ll have the time/energy to work on it. I’m really sorry for the late notice, but if anyone else wants to pick this up, feel free to.

**Comment by martinv98** [comment]
Hey @Krzmbrzl , I'm a university student and we have this class in this semester where the main goal of the class is to contribute code to an open source project. I find Mumble to be really interesting project and would like to contribute. From what I see no one worked on this issue for quite some time and it seems like something I would like to try to solve if it's possible. If yes then please assign me this issue, if no then are there any other open issues that you would recommend to a first time contributor as me ? and maybe if you're willing to then run me through it a bit as well. Thank you

**Comment by Krzmbrzl** [comment]
> and maybe if you're willing to then run me through it a bit as well

I think as far as this issue is concerned, my comment [here](https://github.com/mumble-voip/mumble/issues/5461#issuecomment-1019549078) still applies and covers the basics that should get you started. If you have more specific questions, please let me know.
