### ISSUE TITLE
[1.4.230] [Windows 10] Too much padding in option menus

### ISSUE THREAD

**Issue by theAkito** [mumble-voip/mumble#5462]
### Description

The text padding in the option menus is too large. The text is positioned way to far on the right side.

I assume, this has been updated intentionally and I can imagine the reasons for doing that. However, at some point it looks very exaggerated. It's fine to have a little padding but having half the menu being just empty (wasted) space is a bit too much. It looks even more unbalanced, as the padding on the right side is too little, compared to the left side.

### Steps to reproduce

1. Install 1.4.230.
2. Open the Mumble client.
3. Check out the options.

### Mumble version

1.4.230

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

### Additional information

Windows Version 10.0.19042 Build 19042

### Screenshots

![2022-01-18 15_40_47-](https://user-images.githubusercontent.com/26848976/149959570-8b7109dd-acd2-4988-8595-f2c64469152e.png)

![2022-01-19 17_47_29-](https://user-images.githubusercontent.com/26848976/150176300-0f6db746-dc91-4107-8f2c-5b50fb787c0d.png)

**Comment by Krzmbrzl** [comment]
We did not make any changes to that nor am I aware of a place where we set the padding for these option menus. In fact, I think it's barely possible to set these, even if we wanted to :thinking: 
This seems like a Qt bug to me...

What was the last version that you were using that showed this issue? Did you by any chance try any of the 1.4 snapshot releases?

**Comment by theAkito** [comment]
@Krzmbrzl 

According to my installation log, I installed Mumble `1.3.4` (64-bit) on 2021/02/17 and used it since then. Today, I got a notification inside that client to update to `1.4.230`. So, I did.

Then, I immediately noticed the difference.

So, to answer your question, the current version is the one where this issue is present. I did not use any Snapshot releases or anything like that (at least not consciously -- if the Mumble client does not recommend Snapshot releases, I did not install any), because the stable version, which is usually recommended inside the client, is all I need.

The only reason I would get out of my way to update to a Snapshot or nightly build is if a client-side chat log would be implemented.


>This seems like a Qt bug to me...

Sounds reasonable to me. However, I don't know much about Qt, so I cannot give qualified input about that.

**Comment by Krzmbrzl** [comment]
Alright - I'll have to check the release on my Windows VM to see if I can reproduce the issue

**Comment by StrangePeanut** [comment]
Also seeing this on Windows 10. I'd assumed there were supposed to be icons that were not present for some reason. No such issues on 1.3.4

**Comment by Krzmbrzl** [comment]
Could you click on the `Talking UI` option? That should show a checkbox next to the text - I wonder if that icon will fill up all the available space. If it does, then the change is most likely due to Qt reserving space for that (apparently overly large) checkbox icon for the new options entry `Talking UI`.

If that theory is correct, then only the options menu should suffer from this issue. Is that the case?

**Comment by theAkito** [comment]
@Krzmbrzl 
![2022-01-19 17_47_29-](https://user-images.githubusercontent.com/26848976/150176300-0f6db746-dc91-4107-8f2c-5b50fb787c0d.png)

**Comment by StrangePeanut** [comment]
@Krzmbrzl Unfortunately Server and Self also have the additional padding

**Comment by Krzmbrzl** [comment]
Now that you mention it, I see that this additional padding is also present on my Linux build. I never noticed that before :thinking: :eyes:

**Comment by Snowknight26** [comment]
This seems to also cause text overlap issues, such as in the context menu when right clicking on Mumble's system tray icon on Windows.

![image](https://user-images.githubusercontent.com/5608270/170812426-65febea4-14c6-4db2-92d7-e8cc86e776da.png)

**Comment by Hartmnt** [comment]
I have done some research on this and found the following:

1) This is not a Windows bug. The problem exists on all platforms.
1) All Menus except "Channel", "Developer" and "Help" are affected.
1) The issue exists in Mumble versions 1.5, 1.4.230, 1.3.4 and I even found this screenshot online of version 1.3.0 (probably snapshot): [link to screenshot](https://support.mayfirst.org/attachment/wiki/mumble-desktop/mumble-turn-off-text-to-speech.png)
1) The issues only exists when using the "Mumble (dark/lite)" theme. Confirm it yourself: If you switch to "None" or "Classic" the issue is not present.
1) I used GammaRay to inspect the theme drawing and the issue seems to come from the checkable menu items. ("Channel", "Developer" and "Help" do not have checkable menu items, however "Server" also seems to have none (?) and is still broken, which makes my theory questionable?)

My current theory: This is a theme bug.

**Comment by Hartmnt** [comment]
Update:
After diving into a deep, deep rabbit hole, this seems to be a Qt bug after all. The key insights are:
1) The UI is generated differently, depending on if it was loaded by CSS style-sheet or qt-class (hence the "none" theme seems to work as expected)
1) The behavior of CSS ``padding`` in ``qMenu``s [was changed](https://bugreports.qt.io/browse/QTBUG-78238?focusedCommentId=488799&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-488799) in Qt. Previously, the padding counted from the beginning of the menu item. This was changed to start after any icon or check-mark.
1) All menu bar menus have at least one item with either check-mark or an icon, except "Channel", "Developer" and "Help".
1) All menu items have ``iconVisibleInMenu = false`` which is confusing. I understand it for items which have both a check-mark and an icon, but why is e.g. the ``serverConnect`` icon not displayed?

This leads to the following conclusions:
a) Since the behavior change the padding for menu items with check-mark OR icon has effectively doubled. The padding needs to be halved.
b) Menus without check-mark or icon need to increase the padding (in code. I do not think this is possible in CSS) or include an invisible icon as a workaround.
c) Maybe enable icons for some options in the menus
