### ISSUE TITLE
Forward secrecy information missing

### ISSUE THREAD

**Issue by zappepappe** [mumble-voip/mumble#5469]
### Description

In Server information, TCP (Control) tab it says "No information about forward secrecy available." even though the TLS version is TLS 1.3. As I understand it forward secrecy is mandated in TLS 1.3.

### Steps to reproduce

Connect to a server that supports TLS 1.3 and look in Server information.

### Mumble version

1.4.230

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment]
Okay as it turns out, we are using a hard-coded list of known ciphers and if that list doesn't contain an entry for the used cipher, the "Forward secrecy information is missing" statement is printed.

The list is https://github.com/mumble-voip/mumble/blob/master/src/SSLCipherInfoTable.h and its last update has been in 2017. So no wonder, it is out of date.
