### ISSUE TITLE
Suppress hotkey checkbox missing from shortcuts

### ISSUE THREAD

**Issue by XNtricity** [mumble-voip/mumble#5472]
### Description

Mumble 1.3.4 x64 provides the ability to suppress any shortcut. After updating to 1.4.230 x64, the "suppress hotkey" checkbox is missing from the shortcuts in the shortcut list.

### Steps to reproduce

1. Open the settings menu
2. Navigate to the "Shortcuts" tab
3. For any given function, a checkbox/toggle was available to the far right to suppress the input outside of Mumble
4. This toggle is no longer available
5. Shortcut keys or buttons now interact with the OS, applications, etc.

### Mumble version

1.4.230

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

### Additional information

The ability to suppress the PTT (or any) shortcut is one of the primary reasons I use Mumble over something like Discord: not being able to suppress the PTT hotkey causes numerous problems when trying to talk and navigate applications at the same time.

### Screenshots

![mumble_suppress_hotkey_missing](https://user-images.githubusercontent.com/70313059/150076153-3e92032f-68c9-48d7-a28a-9c02a898d0b2.jpg)

**Comment by XNtricity** [comment]
I want to add that I tried to do my research; combing through previous release notes and issues, searching for terms such as "shortcut", "suppress", etc. but could not find any information on this feature missing in the latest release of Mumble. A bug report seemed like the next logical step.

**Comment by Krzmbrzl** [comment]
See also: https://github.com/mumble-voip/mumble/issues/5099

We transitioned from the direct input to the raw input API because the former was causing multiple issues. The latter however doesn't provide support for suppression, so this feature has been dropped.

**Comment by XNtricity** [comment]
To me, the ability to suppress a hotkey (however it was achieved under the hood) was an essential feature of Mumble. Is there a plan to re-implement this feature in some other manner? If not, this is a serious regression in part of what made Mumble eminently more usable than other voice chat software.

**Comment by Krzmbrzl** [comment]
> Is there a plan to re-implement this feature in some other manner?

No

> If not, this is a serious regression in part of what made Mumble eminently more usable than other voice chat software.

:shrug: 

We can't change the Windows API and besides: The ability to suppress shortcuts was (more or less) the cuplrit of why direct input was such a huge mess (affecting e.g. mouse polling rates)

**Comment by davidebeatrici** [comment]
I understand the disappointment, but unfortunately we have no control over this.

Ideally the operating system should provide a way to make combinations only work for certain applications.

The problem is relevant to macOS too, since we have to intercept the event and then decide whether to pass it on or not depending on the suppression setting:

https://github.com/mumble-voip/mumble/blob/0e204e1d61fddc1934ce499975cae291450abfe3/src/mumble/GlobalShortcut_macx.mm#L21-L124

We cannot do the same with raw input on Windows, as Microsoft's [documentation](https://docs.microsoft.com/en-us/windows/win32/inputdev/wm-input) does not mention that the message can be intercepted:

> If an application processes this message, it should return zero.

https://github.com/mumble-voip/mumble/blob/0e204e1d61fddc1934ce499975cae291450abfe3/src/mumble/MumbleApplication.cpp#L58-L80

**Comment by ionstorm66** [comment]
Is it not possible to use RegisterHotKey for the shortcut that are suppressed? Global hotkeys processed before keyboard input processing.

**Comment by DesktopMasters** [comment]
> Is it not possible to use RegisterHotKey for the shortcut that are suppressed? Global hotkeys processed before keyboard input processing.

Is that not what AutoHotKey is doing?  Why can Mumble not do this?  I am confused.
Also, hotkeys are now broken if you run mutliple versions of Mumble on Windows with "-m".

**Comment by Krzmbrzl** [comment]
@davidebeatrici could you provide the details?

@DesktopMasters please open a separate issue about the broken shortcuts when running multiple Mumble instances

**Comment by DesktopMasters** [comment]
With a great deal of trouble I was able to work through this.
1. Install Microsoft Powertoys
2. Enable Keyboard Manager in PowerToys
3. Map your key to "CTRL (Right)-Shift (Right)-ATTN" so for me it is the tilda/apostrophe key "`".
![Example 1](https://user-images.githubusercontent.com/58863524/152247155-a244fe01-f034-446c-8f14-9edab0e5b071.png)
4. So I had problems using the FULL mapping.  So in Mumble I mapped only to the Right CTRL and Shift by pressing them.  DO NOT map to the remapped key.  Mumble for some reason cannot tell the difference between these "extra" keys.  And so when I used my hot key to switch desktops it would key up.  By mapping only to CTRL-Shift on the right side when I press the hotkey even though it is doing all 3 keys.  Mumble detects the 2 operator keys and keys up perfectly.
![Example 2](https://user-images.githubusercontent.com/58863524/152247478-39a1de0c-30fe-4e21-a718-c262f96068f1.png)

It would be much better if we did not have to work around this... but since we do...  (:

**Comment by JennyLeeP** [comment]
Not gonna lie, this is really troublesome.
I appreciate the effort being put in here.

I realize this issue is already closed.
Do hope you find a way to make suppress work again.

Installing more software as a workaround might be ok for some.
Thank you for your efforts.

**Comment by DesktopMasters** [comment]
@JennyLeeP The "Microsoft PowerToys" is not totally considered "more software" as it is, in a way, an extension of windows.  But I agree.  It would be nice if they could sort out how to make this work natively like other softwares have.

**Comment by davidebeatrici** [comment]
> Is it not possible to use RegisterHotKey for the shortcut that are suppressed? Global hotkeys processed before keyboard input processing.

[`RegisterHotKey()`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-registerhotkey) is extremely limited, it doesn't even differentiate between left/right CTRL/ALT.

**Comment by prog4food** [comment]
@XNtricity 
Look at my [MumHotDi...](https://github.com/prog4food/MumHotDi) it suppresses(and remap) the hotkey operation while the Mumble client is running.
Just run it with the code of the necessary key after Mumble or use it to start Mumble
`MumHotDi.exe <ahk_key-from_hook> [ahk_key-to_hook] [pre_run_exe_full_path]`

**Example to bind PTT only to RightCTRL:**
`MumHotDi.exe RCtrl F13`
*After starting MumHotDi, you must reconfigure the hotkey in the client by pressing RightCTRL, the client should show a different key code (in this case F13 = K100)*
