### ISSUE TITLE
generate_cmake_options_docs.py does not cope with OS dependent options

### ISSUE THREAD

**Issue by klemensn** [mumble-voip/mumble#5488]
### Description

`xinput2` is documented as default-on, yet it is only enabled on Linux.
Doing the same for another OS and running the script readds the same documentation twice.

Either way, there is at least one bug in this script which errorneously flags such pull requests as broken due to the failed "PR (Docs)" check.

### Steps to reproduce

1. apply #5487 
2. run `scripts/generate_cmake_options_docs.py`

### Mumble component

Both

### OS

OpenBSD

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment]
In order to be able to do as you suggest, the script would have to actually parse the entire cmake file hierarchy to know which option is present when. That's definitely out of scope.

Therefore what it does is simply looking at the line in which any given option is defined and the default value used in the docs is the literal expression used in that exact line.

I'll close this as _out of scope_. If you (or someone else reading this) has a good idea how we could remedy the situation in an easy way, please let me know though.
