### ISSUE TITLE
Mumble Crash on Raspberry Pi

### ISSUE THREAD

**Issue by Stefan1121** [mumble-voip/mumble#5496]
### Description

Hello,
my Mumble-Client exit after a few days. It should run 24/7.
I can't find a logfile for the Client only for the server.

Can someone help me with this problem?
I dont get any error message on my Raspberry Pi.

best regards
Stefan

### Steps to reproduce

I dont get any error messages

### Mumble version

1.3.4

### Mumble component

Client

### OS

Raspberry Pi

### Reproducible?

No

**Comment by Krzmbrzl** [comment]
The client prints its log directly to the console, so you'd have to start it from a terminal and pipe its output to some file.

That being said: There is essentially nothing we can do with the information provided. It could essentially be anything or nothing :eyes: 

Since the client does not store a permanent log that could be obtained after a crash, I'll close this issue as "not enough information to act upon". If you re-encounter the issue and have a bit more information about the circumstances, either comment here again or open a new issue.

As a sidenode: Why do you have a _client_ running 24/7?
