### ISSUE TITLE
`magnet:` URI is not supported in 1.4.230

### ISSUE THREAD

**Issue by ancarda** [mumble-voip/mumble#5535]
### Description

Support for clickable `magnet:` URI was added in https://github.com/mumble-voip/mumble/commit/05bc95e6edd58880d3b39f9c29a033dcd1c7671e (Jun 2021), however as of 1.4.230 (Jan, 2022), this doesn't seem to work.

### Steps to reproduce

1. Join a Mumble server using the latest stable client build (1.4.230).
2. Paste a `magnet:` URI, such as magnet:?xt=urn:btih:f1fcdc1462d36530f526c1d9402eec9100b7ba18&dn=ubuntu-21.10-desktop-amd64.iso&tr=https%3A%2F%2Ftorrent.ubuntu.com%2Fannounce&tr=https%3A%2F%2Fipv6.torrent.ubuntu.com%2Fannounce (Ubuntu 21.10)
3. Observe the link is not clickable.

### Mumble version

1.4.230

### Mumble component

Client

### OS

_Not Applicable_

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment]
Yeah that commit was not backported. That's because at that point 1.4 was already feature-frozen (as announced [here](https://www.mumble.info/blog/1.4.0-development-snapshot-6/)) and thud we were only backporting bug fixes.

If you want this feature, you'll have to wait for 1.5 to he released (or build 1.5 yourself in the meantime)
