### ISSUE TITLE
Protocol violation.

### ISSUE THREAD

**Issue by ravicant** [mumble-voip/mumble#5570]
### Description

Whenever I am connecting my mumble client (Latest) to my uMurmur server I am facing an error: - **_Protocol violation. Server sent remove for occupied channel._**
But If I use Old version like 1.3.0 mumble client I don't get that error.
Server Details : - https://img.ravicant.in/u/l1lBRzgBxH9kdtXK7iXwlEh9Nb8Y4Ojq.png

### Steps to reproduce

1. Use Latest Mumble Client and connect to uMurmur server
2. You will get the error

### Mumble version

1.4.0

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment]
Is your server publicly accessible? Or if it not, would it be possible to give me access to it (only that I can connect with my own Mumble client and have a look at the sent protocol messages)?

**Comment by Krzmbrzl** [comment]
That's alright. You can mail it to me. May mail address is available at
https://github.com/mumble-voip/mumble/blob/ef79268165a66ca17fa18141c527a1b66f892184/.mailmap#L122
(either works)

**Comment by Krzmbrzl** [comment]
Okay so I checked the sent messages and in there you can see the following excerpt from right before the protocol violation message:
```
UserState:
session: 173
name: "xxx"
channel_id: 1099
suppress: false
UserState:
session: 178
name: "xxx"
channel_id: 1103
suppress: false
listening_channel_add: 935
listening_channel_add: 940
listening_channel_add: 942
listening_channel_add: 976
listening_channel_add: 982
listening_channel_add: 996
listening_channel_add: 998
listening_channel_add: 1053
listening_channel_add: 1073
listening_channel_add: 1092
listening_channel_add: 1098
UserState:
session: 179
name: "Krzmbrzl"
channel_id: 0
suppress: false
ServerSync:
session: 179
max_bandwidth: 76000
welcome_text: "Welcome to uMurmur!"
ServerConfig:
allow_html: true
message_length: 512
image_message_length: 0
ChannelRemove:
channel_id: 1099
```

See how the first `UserState` message specifies a user with session ID 173 (and a name that I have removed) to sit in a channel with ID 1099. This is the exact channel that is removed in the `ChannelRemove` message sent at the bottom. Therefore we do indeed attempt to remove a channel that is non-empty. Therefore, there really is a protocol violation. The issue however is with uMurmur as that is the one that's sending these messages.

Additionally, the received messages are a bit flaky anyway, since I get a few warnings about invalid channel IDs referenced in the messages sent from the server. There seems to be a problem on uMurmur's side.

I suggest you open an issue for uMurmur instead.

As to why this would work with a 1.3.x client, I have no clue. But from the messages I am seeing, the current client's behavior is in fact correct.

**Comment by ravicant** [comment]
is there any other way bcz uMurmur is dismantled

**Comment by Krzmbrzl** [comment]
Well you could just go for the main Mumble server instead.

Why did you prefer using uMurmur anyway?
