### ISSUE TITLE
UI icon size is too small on 4K screen.

### ISSUE THREAD

**Issue by tianxuanliu** [mumble-voip/mumble#5632]
### Description

Hello everyone,

I find the UI icons on the right-hand side are too small on a 4K resolution screen. 
Is there a way to fix it by changing skin?

Thanks.

### Steps to reproduce

1. Start up the problem.
2. Open your eyes.

### Mumble version

All

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

### Screenshots

![Screenshot 2022-04-22 071708](https://user-images.githubusercontent.com/67667637/164713083-3a0613e7-ed28-4a0c-8883-46e898f9dc85.jpg)

**Comment by Krzmbrzl** [comment]
> Is there a way to fix it by changing skin?

I don't think so, no :thinking:

**Comment by davidebeatrici** [comment]
I've personally seen Qt applications not being rendered correctly with a 4K screen and 150% scaling.

In my case I had to set the `QT_AUTO_SCREEN_SCALE_FACTOR` environment variable to `1` on Windows 10 and `0` on 11.

However, I would first try `QT_ENABLE_HIGHDPI_SCALING` and `QT_SCALE_FACTOR_ROUNDING_POLICY`, introduced in Qt 5.14. From https://doc.qt.io/qt-5/highdpi.html#high-dpi-support-in-qt:

> The QT_ENABLE_HIGHDPI_SCALING environment variable, introduced in Qt 5.14, enables automatic scaling based on the pixel density of the monitor. Replaces QT_AUTO_SCREEN_SCALE_FACTOR.

> The QT_SCALE_FACTOR_ROUNDING_POLICY environment variable and [QGuiApplication::highDpiScaleFactorRoundingPolicy](https://doc.qt.io/qt-5/qguiapplication.html#highDpiScaleFactorRoundingPolicy) API, introduced in Qt 5.14, makes it possible to control if and how the device pixel ratio should be rounded to the nearest integer. This is relevant for configurations like Windows at 150% scale. Possible values are **Round**, **Ceil**, **Floor**, **RoundPreferFloor**, **PassThrough**. See the [Qt::HighDpiScaleFactorRoundingPolicy](https://doc.qt.io/qt-5/qt.html#HighDpiScaleFactorRoundingPolicy-enum) enum documentation for a full description of the options.

**Comment by Hartmnt** [comment]
This bug (duplicates: #3773 #3412) is not an upstream problem. The status icons sizes are hard-coded in [``UserView.cpp``](https://github.com/mumble-voip/mumble/blob/master/src/mumble/UserView.cpp#L21) and drawn using ``QIcon::paint`` in ``UserDelegate::paint``. Neither the Qt layout engine nor the font-size (as it is in TalkingUI) are influencing the size of the icons. This has been this way since the inline status icons were introduced in b39f73befca.

To fix this, Mumble could simply infer the size from the font size as it is done in TalkingUI.
