### ISSUE TITLE
Is there any way to create a public server with password?

### ISSUE THREAD

**Issue by jobber2955** [mumble-voip/mumble#5670]
### The issue

In mumble's public server list, I can see some of those servers which when connecting to it, it will give me a error that says ```Rejected: Wrong certificate or password for existing user```

My question is that: How did this error generated? Is it a password issue or a certificate issue?

It's strange that if I set a not null password, the server should not be published via Bonjour protocal. So if it's a password issue, how does those server achieve this(Published server with password)?

I just want a server that can be easy to find(Simply click some GUI element and search then join, Many of my friends even don't know what is Ip or Domain or Port), meanwhile no random noisy maker could join in(No, I'm not being hatred. Just I'm Chinese and My server's country id is CN, so many unknown people will join in saying lot's of dirty words. For those who only want a low-latency voip server, I'm very welcome).
I also noticed that, Maybe I can use the ```Username Pattern``` to kind of achieve the "AUTH" function, will give it a try  

### Mumble version

latest

### Mumble component

Server

### OS

Linux

**Comment by Krzmbrzl** [comment]
So you want to configure your server with a password?
This should be your option: https://wiki.mumble.info/wiki/Murmur.ini#serverpassword

An even easier approach would be to create your server without a password and then setup the ACLs that any channel but the root channel, requires the user to be registered in order to enter it. Then users can join, you can register them once and from then on they can use one of the restricted channels that is not accessible to the general public.
Additionally, you could revoke the Speak privilege in the Root channel to prevent folks from making any noise in there.

**Comment by jobber2955** [comment]
@Krzmbrzl Thanks for replying, I know how to set a password, but the problem is, If I set a password to the server, then the server won't publish itself via bonjour(make it PUBLIC, can be searched or listed in Public Server List), the log says
```
2022-05-09 22:09:44.680 1 => Registration needs nonempty 'registername', 'registerpassword' and 'registerurl', must have an empty 'password' and allowed pings.
```
I will give ACL a try, thanks !

**Comment by Krzmbrzl** [comment]
Ah okay, I see. Yeah in that case, the ACL solution is probably what you are looking for :)
