### ISSUE TITLE
Doesn't run on XP

### ISSUE THREAD

**Issue by Montclair** [mumble-voip/mumble#5740]
### Description

Not sure if this started with v1.4 (couldn't find system requirements listed anywhere) but 1.4.230.0 does not run on XP SP3.  I get the message "mumble.exe is not a valid Win32 application."

If Mumble 1.4+ doesn't support XP anymore, maybe make a system requirements section on the site (or make it easier to find as I couldn't).

### Steps to reproduce

1. Install Mumble 1.4.230.0
2. Attempt to run.

### Mumble version

1.4.230.0

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

**Comment by ZeroAbility** [comment]
We previously had stated in our documentation that Windows 7 is the lowest supported version for 1.4.x. Microsoft does not support XP anymore, so it makes sense that we do not, either. Windows 7 is supported until Qt stops supporting it since Microsoft has an extended support plan for some commercial customers. Since a lot of this is common knowledge, that is probably why the need for us explicitly stating it was probably redundant. Basically, if you are using XP off internet, you will want to use 1.3.

**Comment by Montclair** [comment]
Just a suggestion to make a "System Requirements" section on the main site.  As I said, I couldn't find this info.  Thanks for the response.

**Comment by Krzmbrzl** [comment]
The requirement is stated in this repo's README but I guess it could be a bit more prominent...
