### ISSUE TITLE
Mumble Formatting Issue

### ISSUE THREAD

**Issue by Cutethulhu** [mumble-voip/mumble#5817]
### Description

Since the update to 1.4.274, the Mumble client's text area's font size has shrunk, on top of changing the size of the various icons that show up next to a user while in a server. The change in size has effected the ability to click links in the text area, making it so that you can't click a link if it's on the same line as the person's name, only if it extends past the line. Further more, image embedding via Send Message is still messed up with the formatting in that it'll shoot the scroll bar all the way up if the next image being embedded is too large.

### Steps to reproduce

1. Update Mumble to 1.4.274
2. Connect to server
3. Look at channel text area/channel user list
4. Send message with link or embedded image

### Mumble version

1.4.274

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

### Screenshots

![mumble_WtsA7qlKN1](https://user-images.githubusercontent.com/74110006/185816043-18ebaeef-baf7-474c-b116-0f6b92a6de59.png)

**Comment by Hartmnt** [comment]
Hi,

> on top of changing the size of the various icons that show up next to a user while in a server

Could you please open the "Talking UI" (Configure -> Talking UI) and observe, if the icons there are sized correctly?

**Comment by Cutethulhu** [comment]
Nothing shows up in the little box when I open the "Talking UI" thing.

**Comment by Cutethulhu** [comment]
Didn't mean to close that, sorry.

**Comment by Cutethulhu** [comment]
Okay, so what about the inability to click links and the embedded images issues?

**Comment by Hartmnt** [comment]
> Okay, so what about the inability to click links and the embedded images issues?

The link clicking issue is tracked in #5818 (MR #5820). I think that will also affect the embedded images, but since this fix is done by another developer, I am not sure. Remember, these kind of issue trackers are best used by creating separate issues for separate problems.

**Comment by LeRaldo** [comment]
![Clipboard03](https://user-images.githubusercontent.com/3815475/185991547-61698795-c6dc-43f0-90f0-079d43e83b13.png)

**Comment by Cutethulhu** [comment]
![mumble_fGESYDif3V](https://user-images.githubusercontent.com/74110006/186293251-35a8061b-ab62-4320-8c62-d544fe2fb1db.png)
This is what I'm talking about for the embedded image issue, the GIANT space between the image and the person if the image is wide. As for the link down below, there's no ability to click it, as you can see there's no underline to it, meaning that the chat doesn't see it as a link.

**Comment by Krzmbrzl** [comment]
The image issue is tracked is a separate issue. Don't mix different issues in a single ticket.

**Comment by Cutethulhu** [comment]
> 

I mean. it's still part of the formatting issue I've been on about, but okay. How about the problem with the links?

**Comment by Hartmnt** [comment]
> I mean. it's still part of the formatting issue I've been on about, but okay. How about the problem with the links?

First, thank you very much for bringing these problems you encounter with Mumble to our attention. The GitHub issue tracker - and for that matter pretty much every other ticket system in the world - works by encapsulating single software related problems into single "objects" or "issues".
This is done for multiple reasons: Different problems, even if they appear related or are encountered in the same release, are usually not really connected. Additionally, developers will try organize and coordinate their work by focusing on, or assigning single issues.
Combining multiple problems into a single issue is therefore usually a bad idea, even if the intent is honorable.

In this instance the problems you describe in this issue are valid, have to be taken care of, and are quite severe. But, on the other hand, mostly independent of each other. So it would have been probably best to separate them by creating multiple different issues here in GitHub. Usually, you would probably have already been requested to do this by a maintainer, but due to the freshness of the release and the resulting, you were not.

This issue (with the id #5817) is currently used to **only** track the icon scaling issue, which I am personally involved in. **Even though** you also list other problems in your original post. The link clicking problem is, as I have already stated, tracked by #5818 (which may or may not also relate to the embedded image problem).

If you have any more information that would help fixing problems, post them in the appropriate GitHub issue, if applicable. 
If you encounter a problem that seems to be not tracked by any Issues currently open in the GitHub tracker, please create a new one.

**Comment by Stefan-comkmits** [comment]
-The GitHub issue tracker - and for that matter pretty much every other ticket system in the world - works by encapsulating single software related problems into single "objects" or "issues".

Sure,but in a World,where Problems not come in Public Versions.
This is the Reason,why is Bad Work,do Overdie Version to Version,to Version.

So,the new Relase brings Nothing Relevant,
but day for day the Trolls in the World,comes with Make Update".

And fpr this reason,
the User of every Software in the World,have the Right,for good and Series Updates.

-This issue (with the id https://github.com/mumble-voip/mumble/issues/5817) is currently used to only track the icon scaling issue

The Only Issue is,that is Publicity a Broken Version to the World.

The World is not in Ownership,of a Elite.
And the World neeed Tools like Mumbel,the Times we have shown this.

A Discord Server Like Hauptbahnhof had Tousends of Users,

--The GitHub issue tracker - and for that matter pretty much every other ticket system in the world

Make a Beta Tree,who ist Indebendent from the Main Line.
Than where this not a Problem.

Sorry,but its Sad!!!!

**Comment by Krzmbrzl** [comment]
@Stefan-comkmits I am only telling you this once: Your tone and attitude here is completely out of place. You are using a software free of charge that is developed by us in our free time and then you come here and make demands and talk about being entitled to certain things. 

No, you are not entitled to anything! If you find issues, we are happy to receive constructive reports about them, but we don't have to listen to your whining and blaming.

If you stick to your attitude and tone, I will simply ban you from posting here again. As it stands, your posts do not add any value to the process of improving the application. Instead, the only thing that they achieve is killing the motivation of volunteers to work on this app. This is destructive in the long run, which is why I will take the aforementioned measures, if necessary.
