### ISSUE TITLE
First lines of messages are uninteractable

### ISSUE THREAD

**Issue by mataha** [mumble-voip/mumble#5818]
### Description

It's impossible to interact with the first line (as in the UI) of any message typed in the chat.

### Steps to reproduce

1. Open Mumble, join any server, join any channel.
2. Type a message (preferably with a link) that doesn't exceed one line in your UI.
3. Observe how you're utterly unable to click the link or even select anything in that line.

### Mumble version

1.4.274

### Mumble component

Client

### OS

Windows 10.0.19044.1889

### Reproducible?

Yes

### Additional information

Literally how?

### Screenshots

![image](https://user-images.githubusercontent.com/7210216/185820060-ee046ece-aa91-4af5-8b31-41c57a46ef2b.png)

![hQiJvawkgG](https://user-images.githubusercontent.com/7210216/185819727-5aa091b7-a0d3-4a14-bb02-05de88457aa5.png)

Note that the screenshot includes an additional bug (link percent expansion) as well, though that's not relevant here.

**Comment by And4713** [comment]
This issue is also happening on Windows 7. I have not tested it on Linux yet. In addition, the lack of interaction extends to the right click context menu:
![image](https://user-images.githubusercontent.com/60132557/186055283-803e934f-e856-4f88-b3f7-874188efccb9.png)
Copying the entire line does work. Copying any individual part does not. I have not tested it on Linux.

**Comment by MikkoMajuri** [comment]
I can also confirm this behaviour. If the chat is scaled narrower and the links turn into 2-3 lined, the first line is uninteractable, but the rest of the lines work.
