### ISSUE TITLE
Can't find Slovakia as a country

### ISSUE THREAD

**Issue by BRNSystems** [mumble-voip/mumble#5831]
### Description

In the serverlist, I can see Czechia, Slovenia, but not Slovakia.
Is it present in the code?
I want to ask, if Slovakia was left out from the serverlist or it was never added there.
If the latter is true, then please add it there.
Thanks.

### Steps to reproduce

Look at the locations in the mumble client

### Mumble version

227d7fcee38d7bfdeac2aa9621f5b525ccdf3836

### Mumble component

Client

### OS

Linux

### Reproducible?

Yes

**Comment by BRNSystems** [comment]
OK, never mind, I saw it now

**Comment by BRUTme** [comment]
Ahoj, predpokladam ze si slovak aj ze si sa regol u nas na fore.

I will continue in english for everybody, as I assume the countries are added only when there is at least one server from this country, so before 1.3, there were SLovakia too because our BRUT.me server vas visible, but beginning with 1.4, our server is not visible and as there is no other slovak server, u can not see SLovakia as a country, I am trying to figure the invisibility of our server in the topic below this
