### ISSUE TITLE
1.4.287 servers wrongfully appear as 1.4.255 after updating

### ISSUE THREAD

**Issue by StrangePeanut** [mumble-voip/mumble#5887]
### Description

1.4.287 servers report version 1.4.255 after updating. If this is the intended behaviour, https://github.com/mumble-voip/mumble/pull/5868 seems to complicate things if anything.

### Steps to reproduce

1. View the version reported by a 1.4.287 server

### Mumble version

1.4.287

### Mumble component

Server

### OS

Linux

### Reproducible?

Yes

**Comment by Hartmnt** [comment]
Does this happen when you hover over servers in the server browser, or when you open the "server information" when already connected to a server.

If it is only the former, that is intended behavior. (But will be fixed in 1.5)

**Comment by StrangePeanut** [comment]
@Hartmnt Yep, just the former. Sorry, I should have been more specific.

**Comment by Hartmnt** [comment]
> @Hartmnt Yep, just the former. Sorry, I should have been more specific.

Ok this is, for the time being, intentional. The 1.4.x branch expects a legacy ping format for the server browser and changing that would have taken some serious additional considerations. (We had our brains working quite hard for two weeks to fix this whole situation in the first place and decided that the additional effort was not worth it)

**Comment by StrangePeanut** [comment]
@Hartmnt fair enough, I noticed the version go from 1.5.18 to 1.4.255 neither of which being correct. The correct version is displayed in the server info dialogue as expected. Thanks for clarifying!
