### ISSUE TITLE
Denial of service. User count above limit.

### ISSUE THREAD

**Issue by fuck-shithub** [mumble-voip/mumble#5900]
### Description

Today I saw a mumble server with a continuously increasing user count. The count even went above its limit, 125/100, until it dropped again. When I got the chance to join, there were only about 6 real users on the server, while in my server list the user count kept increasing and going above the server's limit of 100.
I suppose it's some kind of denial of service exploit.

Is there an option to allow registered users to join even if the user count exceeds the server limit?
Is there a way to mitigate this DoS attack in some other way?
Can a new protocol feature be added to make such attacks harder, like client challenges?

The server seemed to be running murmur 1.3.0, so maybe it is already fixed in 1.4.0? I'm not sure. It might be worth investigating as there are trolls DoSing servers which is pretty annoying.

### Steps to reproduce

I don't know how the denial of service exploit works. I'm guessing the server reserves a slot for connections that haven't even fully joined the server yet. Probably handshaking and then dropping, but I don't know enough of Mumble protocol to have good insight.

### Mumble version

1.3.0

### Mumble component

Server

### OS

Linux

### Reproducible?

Haven't tried

**Comment by Krzmbrzl** [comment]
I believe what you are experiencing is https://github.com/mumble-voip/mumble/issues/4277, which has already been fixed in more recent server versions (in the 1.4 series).

Essentially, older servers report any TCP connection made to the host as a "user", even though these are not actually Mumble users. Thus, they are obviously also not participating in the user-count limitation.

Until this has been reproduced with a server version of 1.4.230 or more recent, I'll close this as a duplicate of #4277.
