### ISSUE TITLE
Users with Access Token Set Always Login to Root Channel

### ISSUE THREAD

**Issue by ethaldeman** [mumble-voip/mumble#5907]
### Description

Users with Access Tokens set always login to root channel regardless of what channel they were in when they disconnected. 

### Steps to reproduce

1. Connect to a mumble server running 1.4.287 using a client of any version. 
2. Enter any non-root channel.
3. Disconnect
4. Reconnect and confirm you log back into that channel.
5. Add an Access Token of any value.
6. Disconnect.
7. Reconnect, you will now be in the root channel and always reconnect there.

### Mumble version

1.4.287

### Mumble component

Server

### OS

Linux

### Reproducible?

Yes

### Additional information

The server I tested on is running the 1.4.287 docker build.

**Comment by ethaldeman** [comment]
Using the official Docker repo, I built a Docker image from master. However upon testing on that server, I still have the problem when connecting with a 1.4.287 Windows client and Mumla, an Android client based on 1.2.5. This appears to conflict with what Hartmnt reported above. I will admit i am new to Docker, but the server is reporting a protocol of 1.5.403, so i believe I built the image correctly.

**Comment by Hartmnt** [comment]
@ethaldeman Mhh I tried again with a 1.5 client on a 1.5 server and could not reproduce it there. Are you sure you registered the clients on the new server before trying the steps above? IIRC only registered clients have their channel saved. Also, do you have ``rememberchanduration`` set to anything other than ``0``? In my test just now I had the weird problem that the sqlite DB was using UTC while my system was not resulting in ``rememberchanduration`` not working as expected.

**Comment by ethaldeman** [comment]
@Hartmnt I am sure the two user accounts are registered. I started my docker container with MUMBLE_CUSTOM_CONFIG_FILE set to an ini file, therefore I am not using environment variables to set mumble-server settings. The ini file has `rememberchannel=true` and `rememberchannelduration=0` . Other settings within the ini file are present in the mumble server, so I know the ini file is being loaded. 

Maybe unrelated, but the Ubuntu 20.04 installation the mumbler-server is running on has the system time set to local. I achieved this by running `timedatectl set-local-rtc 1 --adjust-system-clock`. The mumble-server.sqlite used by the mumble-server has also been in existence and run under mumble-server versions from 1.2.X and upward. 

Is there a mumble 1.5 Window per-complied client I could download and test with? Development builds on the website appear to be 1.4.

**Comment by ethaldeman** [comment]
I managed to build the Linux client on my Ubuntu computer from master. I confirmed the client is reporting a version of 1.5.0. I connected to my mumble server, a docker image from master, and confirmed that when a token is set, it is still not saving the last channel I was connected too. @Hartmnt it seems running a 1.5 client and 1.5 server does not fix the issue. 

However when connecting with an access toke, the terminal that launches the client contains the below warnings that are not present when connecting without an access token. 

`<W>2022-10-31 17:36:10.810 Server attempted state change on nonexistent channel
<W>2022-10-31 17:36:10.810 Server attempted state change on nonexistent channel
<W>2022-10-31 17:36:10.810 Server attempted state change on nonexistent channel
<W>2022-10-31 17:36:10.810 Server attempted state change on nonexistent channel
<W>2022-10-31 17:36:10.810 Server attempted state change on nonexistent channel
<W>2022-10-31 17:36:10.810 Server attempted state change on nonexistent channel
<W>2022-10-31 17:36:10.810 Server attempted state change on nonexistent channel
`

**Comment by Krzmbrzl** [comment]
That seems to indicate that the server has not yet broadcasted all channels or that it read some invalid channel IDs from the database

**Comment by ethaldeman** [comment]
Based on all the above, I decided to try generating a new sqlite file for the server. I allowed my mumble server, 1.5.420, a docker image from master, to generate a new sqlite file. Then I made some channels to test, added an access token to my client, 1.5 from master, entered a channel and then disconnected. Upon reconnecting, the server remembered the channel I was in. I tested this multiple times to confirm it worked. 

Then I used the same server and client, but loaded my old sqlite file. The bug occurred and it would not remember my last channel. 

Therefore it seems the 1.4.287 server update broken backwards compatibility with server sqlite files made in earlier versions. My sqlite database dates back to 1.2, maybe earlier. With this in mind, I understand if it is not worth investigating and fixing the backwards compatibility. However any advice on how to fix my sqlite file? I would prefer not having to rebuild all my channels and permissions.

**Comment by Hartmnt** [comment]
> Based on all the above, I decided to try generating a new sqlite file for the server. I allowed my mumble server, 1.5.420, a docker image from master, to generate a new sqlite file. Then I made some channels to test, added an access token to my client, 1.5 from master, entered a channel and then disconnected. Upon reconnecting, the server remembered the channel I was in. I tested this multiple times to confirm it worked.
> 
> Then I used the same server and client, but loaded my old sqlite file. The bug occurred and it would not remember my last channel.
> 
> Therefore it seems the 1.4.287 server update broken backwards compatibility with server sqlite files made in earlier versions. My sqlite database dates back to 1.2, maybe earlier. With this in mind, I understand if it is not worth investigating and fixing the backwards compatibility. However any advice on how to fix my sqlite file? I would prefer not having to rebuild all my channels and permissions.

The 1.4 server which also triggered the error for me has the following special characters in some channel names
``()-=_`` and space. Maybe this is the reason.

**Comment by Krzmbrzl** [comment]
Backwards compatibility (especially for the DB) is quite important to us, so if we can we will definitely want to fix that.

What version before 1.4.287 did you use where the issue did not occur?
And when running the server at that version with your old database, does the used client version matter?

In your first post you seem to suggest that this is reproducible with any arbitrary channel on your server. Does every channel name contain any special characters or do you also have some that only use ASCII characters in their names? If so, could you confirm that the issue persists in those channels as well?

Finally: How big is your SQLite file? If it is not unreasonably large and you are okay with that, you could send it to me, so I can reproduce the issue. That would greatly facilitate debugging. Note however, that you might want to make a copy first and delete some tables containing user information.

**Comment by ethaldeman** [comment]
Before 1.4.287, the server ran 1.3.4 on Redhat 8.  On 1.3.4 I never observed this problem regardless of client used.  Specifically clients 1.2.4, 1.3.4, and 1.4.287 were used. I switched OS to Ubuntu 22.04 so I could run docker and upgrade to 1.4.287. Upon upgrading to the 1.4.287 docker image the problem started.

The problem is reproducible with any arbitrary channel on the server. Whether the channel required an access token or its name had special characters didn't matter, no channel location was saved upon reconnecting. 

All of my channel names contain just letters and spaces. The root channel contained letters, spaces, and an apostrophe. I removed all the spaces and apostrophe, retested on client 1.5.0 and docker image 1.5.420, and the problem still occurs. I also tested on server v1.4.230 via docker compiled image and client 1.5.0, and the bug still occurred. I tried to compile server 1.3.4 via docker for testing, but it failed to compile.

I sent the sqlite file via e-mail to your e-mail address within the git logs.

**Comment by ethaldeman** [comment]
Using the built-in mumble-server 1.3.4 for Ubuntu 22.04, I confirmed neither my mumble sqlite database with spaces and commas nor with just letters experience the bug. I tested this with 1.3.4 and 1.5.0 clients.

Therefore it seems the bug is based on the server version and was introduced between 1.3.4 and 1.4.230 and is not caused by special characters in channel names.

**Comment by Hartmnt** [comment]
Ok I have narrowed the problem down:

* A fresh 1.5.0 server does not have the issue out of the box
* My 1.4.0 production server does have this issue
* I copied the database from my 1.4.0 to a test 1.5.0 server and the issue appeared there, too. This means the problem is indeed  in the database as previously assumed
* I then shut the 1.5.0 test server down, blindly deleted all ACL rows in the table and left everything else as it was - restarted the server and the issue is gone.

=> Some specific ACL rules are causing this issue. I have a suspicion that it might be some "traverse" or "enter" ACLs on the root channel, but I am investigating further.

**Comment by Hartmnt** [comment]
Minimal issue reproducing instructions:

1) Enabled rememberchannel, if not already enabled in server.ini
1) Start a Mumble server with supw (1.5.0 master should work, but there are probably most versions affected)
1) Login as SuperUser into the fresh server
1) Create a sub-channel of Root (I called it A)
1) Deny ``Enter`` or ``Traverse`` or both for ``@all`` in A
1) Allow the previously denied permission(s) for ``@auth`` in A
1) Login as non-SuperUser (SuperUser is immune to this bug)
1) Register self
1) Observe that the channel is remembered, if no Access Token is present. And observe that the Client reconnects to Root, if a Access Token is present.

**Comment by Hartmnt** [comment]
Alright so I found the cause of this issue. In 1.5 RC you can even observe the issue visually by looking at the lock icons for channels with ACL specified as above. Here is how it boils down:

* The client connects to the server. The ``msgAuthenticate`` in ``murmur/Messages.cpp`` method parses the content of the user connection msg and sets everything up.
* Somewhere within this method the channel remember feature is computed and applied to the client.
* The server has a cache system for permissions aka ACLs, probably implemented to reduce the number of expensive computations and database lookups.
* To invalidate the cache aka "force the server to recalculate all ACLs for a client" the server has a ``clearACLCache(User*)`` method. Note that the recreation/recomputation of ACLs happens on the next permission check and not instantly.
* The rememberchannel thingy checks the ACL for ``Enter``/``Traverse`` as I already experimentally concluded

Now here is the issue:  
When the permissions are checked and Enter/Traverse is somehow denied for the client, but then later allowed for ``@auth``, which our client is, we observe the following in [Group.cpp](https://github.com/mumble-voip/mumble/blob/master/src/Group.cpp#L155):
```
else if (groupSpecification == QLatin1String("auth"))
		matches = (user.iId >= 0);
```
Hold on... ``user.iId`` is the DB id of our user (if registered) and this value is set at exactly one spot in the ``msgAuthenticate`` handler exactly [here](https://github.com/mumble-voip/mumble/blob/master/src/murmur/Messages.cpp#L213)...
Also, if and only if the client connects with access tokens set, the ACL cache is cleared at the very top of [``msgAuthenticate``](https://github.com/mumble-voip/mumble/blob/master/src/murmur/Messages.cpp#L176) such that the ``@auth`` permissions are unset.

Now remember, the ACLs are cached... and sadly there is no cache invalidation after the id is set, making ACLs for ``@auth`` unavailable until later (where the cache is cleared again for other reasons) and definitively not available for rememberchannel.
The lock-icons suffer for the exact same reason as they are set also in the ``msgAuthenticate`` handler.

Removing the access tokens while connected to the server fixes the lock-icons because the ``msgAuthenticate`` is sent again by the client, but this time the server already knows the DB id.

---
The fix is simple: We need to clear the ACL cache after setting the user db id, because as it turns out: this is invalidating the ACLs

**Comment by Hartmnt** [comment]
@ethaldeman If you have the time and want to, you can try to compile my branch, or cherry pick my change into your 1.5 branch to test the fix. Seems to work for me.

**Comment by ethaldeman** [comment]
I just compiled from the commit in your PR, and it has fixed the problem for me. :)
