### ISSUE TITLE
Mumble Server Tray Icon on Linux

### ISSUE THREAD

**Issue by trymeouteh** [mumble-voip/mumble#5913]
### Context

Add a tray icon to mumble server (murmur) when the server is running.

### Description

The mumble server (murmur) on Windows has a tray icon for when the server is running and if you are running multiple servers, it does show a tray icon for each server.

Please add a tray icon for the mumble server (murmur) on Linux to allow users to easily shutdown the server by right clicking on the tray icon. This will be useful if you run multiple servers.

### Mumble component

Server

### OS-specific?

Yes

### Additional information

Would be great to also have the server name listed in the tray icon also
https://github.com/mumble-voip/mumble/issues/5914

**Comment by Krzmbrzl** [comment]
_If_ this is implemented, it should be disabled by default and should be explicitly requested via e.g. a CLI flag.
Otherwise, I don't think it'd suit the expected behavior for servers on Linux.

Furthermore, I'm not sure whether it is a good idea to bring any UI component into the server as that requires all sorts of additional dependencies (Qt wise) that we don't really need. Plus, I don't know whether these dependencies might create issues when running the server on a non-UI host (e.g. on an actual server).

The fact that the Windows version has a tray icon (and some other UI components) is mostly due to Windows not having a usable command line and also due to it not having a non-UI server. 

@davidebeatrici what is your take on this?

**Comment by Krzmbrzl** [comment]
> some sort of RPC client as a separate binary.

Yeah, I was thinking about something like this as well. Some kind of "server manager" that lists currently running servers and allows you to  configure them.
