### ISSUE TITLE
Link is not created since v1.4

### ISSUE THREAD

**Issue by sliekens** [mumble-voip/mumble#5919]
### Description

The latest client software doesn't create the MumbleLink memory-mapped file on Windows 11 (22H2).

### Steps to reproduce

You can use Sysinternals Process Explorer to see open handles to memory-mapped files. You can see that the section is mapped when you use v1.3.4, but not when you use the latest release.

### Mumble version

1.4.287

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

### Screenshots

Open handles in **v1.3.4**

![image](https://user-images.githubusercontent.com/1583241/194711627-8a797019-f53b-41fa-84c2-85fd172c6ab3.png)

Open handles in **v1.4.287**

![image](https://user-images.githubusercontent.com/1583241/194711743-61b782e2-7833-4484-9497-44432fc977b6.png)

**Comment by Krzmbrzl** [comment]
Do you actually have the `Link` plugin enabled? Since 1.4 plugins are disabled by default and you'll have to explicitly enable those that you want to use.

**Comment by sliekens** [comment]
This checkbox? Doesn't seem to make a difference whether I enable it or not.
![image](https://user-images.githubusercontent.com/1583241/194722314-f25eac00-9ba3-4fc9-8d14-8b0cc79a0bc6.png)

**Comment by ppfeufer** [comment]
Sope, this one I geuss

![image](https://user-images.githubusercontent.com/2989985/194722479-6de0ed4f-b7fe-467c-a9f8-f2f3a6463790.png)

**Comment by sliekens** [comment]
Aha, that worked. It's a bit unfortunate that it's opt-in now. I couldn't find this and I'm a technical person,

**Comment by Krzmbrzl** [comment]
It being opt-in is due to plugins now being much more generic in their potential scope of action and thus you just don't want all installed plugins to be enabled by default. 

And in terms of finding how to enable a plugin: You search for the specific plugin and check the `Enabled` checkbox - not sure if that should he considered hard to find :shrug:
I do see that such a behavioral change might be suprising to users accustomed to things "just working on their own", but I don't think this can be helped 👀
