### ISSUE TITLE
if $XDG_RUNTIME_DIR is unset, D-Bus calls don't work

### ISSUE THREAD

**Issue by carlocastoldi** [mumble-voip/mumble#5962]
### Description

Mumble does not respond to certain D-Bus calls if `$XDG_RUNTIME_DIR` is unset, such as: `startTalking()`, `stopTalking()`, `setSelfDeaf()`, `setSelfMuted()`. It works with properties and some other calls: `mute`, `deaf`, `isSelfMuted()`, `isSelfDeaf()`.

### Steps to reproduce

1. open terminal
2. `unset XDG_RUNTIME_DIR`
3. `mumble`
4. open a DBus inspector and call `net.sourceforge.mumble.mumble /isSelfDeaf()`. Alternatively run in a new terminal `mumble rpc starttalking`

### Mumble version

1.4.287

### Mumble component

Client

### OS

Linux

### Reproducible?

Yes

**Comment by carlocastoldi** [comment]
> Is this also fixed by https://github.com/mumble-voip/mumble/pull/5961? thinking

unfortunately, no :\

**Comment by Krzmbrzl** [comment]
Okay. Then I am pretty sure that this is a Qt limitation. We let Qt manage the DBus interface and therefore the requirement for XDG_RUNTIME_DIR is most likely theirs.

And according to https://askubuntu.com/questions/872792/what-is-xdg-runtime-dir this environment variable is supposed to be set in any case upon login and if it is not, that seems like a broader issue to me.

So to sum it up, I would close this as an upstream bug until proven otherwise.
