### ISSUE TITLE
XDG_CONFIG_HOME is not respected

### ISSUE THREAD

**Issue by eukara** [mumble-voip/mumble#6029]
### Description

Currently the Mumble client hard-codes the location of the Mumble config directory to be located at ~/.config/mumble when it should read the XDG_CONFIG_HOME environment instead.

https://github.com/mumble-voip/mumble/blob/f73db9da7ac81eda2c6eeacad6c97d97481a5e65/src/mumble/Database.cpp#L50

### Steps to reproduce

1. Changing XDG_CONFIG_HOME and move ~/.config to set location.
2. Launch Mumble client.
3. Mumble will give an alert about the database file being missing.

### Mumble version

1.4.0

### Mumble component

Client

### OS

Linux

### Reproducible?

Yes

**Comment by eukara** [comment]
Thank you, I left a comment on the PR commit in question with some feedback.

**Comment by Krzmbrzl** [comment]
No need to comment here - I get notifications for anything that happens in the PR anyway

**Comment by Hartmnt** [comment]
Ok, so I investigated this issue again. Mumble (at least the most recent versions) are respecting ``XDG_CONFIG_HOME`` for the ``mumble-settings.json`` config file and ``XDG_DATA_HOME`` for the Mumble SQLite DB, which is apparently not considered configuration, but rather data.

The respective code parts are:

SQLite DB: https://github.com/mumble-voip/mumble/blob/a32229f88c9b6cbf8f33a2baa3e4373b27d54d80/src/mumble/Global.cpp#L142

Config files: https://github.com/mumble-voip/mumble/blob/a32229f88c9b6cbf8f33a2baa3e4373b27d54d80/src/mumble/Settings.cpp#L1312-L1314

The code OP posted originally is part of the fallback chain for legacy locations. These are prioritized in order from top to bottom and if a database is found at those locations, that will be used instead.

The reason why OP ran into an issue is probably because they did not migrate ``XDG_DATA_PATH`` when they moved their home directory.

The only issue remaining here is that some of the ``QStandardPaths`` that we use as part of the fallback chain are deprecated in Qt5 and removed in Qt6 which has to be addressed at some point

**Comment by Hartmnt** [comment]
See #6459
