### ISSUE TITLE
Registering with password

### ISSUE THREAD

**Issue by roughnecks** [mumble-voip/mumble#6141]
### The issue

Can I register a user with a password instead of certificate? That would make it easier for a user on iOS to connect with the same credentials as PC.

Alternatively, how to use the same certificate between a PC client and an iOS client?

### Mumble version

Sep 13, 2017 Version 1.3.1

### Mumble component

Client

### OS

Other

### Additional information

Talking about the official Mumble release for iPhone, since I didn't find any other client.

**Comment by Krzmbrzl** [comment]
Yes, you should be able to use Ice for this:
https://github.com/mumble-voip/mumble/blob/82bcd1eb3d53aa9bfc1f6ff539961b0c29336266/src/murmur/MumbleServer.ice#L722-L726

Note however that password authentication is considered deprecated. Since I have no clue about the iOS app though, I also can't tell you how one could reuse the certificate there :thinking:

**Comment by roughnecks** [comment]
We'll create a different account if that's the case, no problem.
If you think no one lese here can help, feel free to close the ticket.
