### ISSUE TITLE
Unauthenticated users cannot create channels, including with access for that permission

### ISSUE THREAD

**Issue by crossliner** [mumble-voip/mumble#6320]
### Description

This seems to be not documented, i haven't found any proper mention that it's supposed to.
To be more precise, the client is aware he has the access for that permission, but the server accepts but doesn't add the channel, the case is fine for authenticated users

### Steps to reproduce

1. create a channel
2. allow someone / group to make a channel (temp or perm) in the channel's ACL

### Mumble version

1.4.287

### Mumble component

Server

### OS

Windows

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment]
Hm? Could you maybe illustrate a bit more what it is exactly that you are referring to? I'm not sure I quite understand the described scenario 👀

**Comment by crossliner** [comment]
> Hm? Could you maybe illustrate a bit more what it is exactly that you are referring to? I'm not sure I quite understand the described scenario 👀

The client tries to create a channel, server allows it but doesn't actually create the channel, only does that when the client is authenticated

**Comment by crossliner** [comment]
What's the reason to only allow authenticated users to change [channel state](https://github.com/mumble-voip/mumble/blob/c4b5858d141f76cce553be2f74dfc4291989fc9b/src/murmur/Messages.cpp#L1237)?

**Comment by Hartmnt** [comment]
@crossliner When you say "authenticated" do you mean "registered" or "fully connected to the server"? Because the code snippet you linked talks about the latter.

As far as I know, you can not specify ACLs for unregistered users individually or as a non-default group (they have no database entry, and can therefore not be assigned to a group).

What you can do is specify an "Access Token Group" using ``#<access token>`` (without <>) in the group field of the ACL. That would allow to assign ACLs to unregistered users which have the correct access token in their list.

Anyway, I tried to reproduce your issue but I can not. Can you please tell us what channel combination and ACLs are needed to trigger this bug (ideally starting from a fresh database)?

If you have been working with access tokens to trigger this bug, this might be a duplicate of #6334 or #6044
