### ISSUE TITLE
Plugin interface: Add fucntion to API that uses mumbles internal SSL capability to read a webserver ressource

### ISSUE THREAD

**Issue by hbeni** [mumble-voip/mumble#6365]
### Context

Plugin API

### Description

Please add a  `mumble_getHTTPURL()` plugin API function to query the internet.

If in my plugin `mumble_hasUpdate()` function I could just call some `mumble_getHTTPURL("https://example.org")` function to utilize the already linked ssl engine of mumble, this would be beneficial in several places:
- My `mumble_hasUpdate()` could be much more simple.
- The plugin itself won't have a openssl dependency, helping with 
  - building for multiple targets
  - maintaining openssl compatibility
  - the byte-bloat of a statically linked openSSL for my windows build

The requested `mumble_hasUpdate()` Plugin-API function should just try to lookup the web ressource (using TLS when the protocol part has a `https://` prefix) and return either the HTTP error code or the contents of the page.

### Mumble component

Client

### OS-specific?

No

### Additional information

Basicly `mumble_hasUpdate()` probably just needs to leverage or expose the already existing mumble-code that gets called to actually fetch the updated plugin from the web, which is already part of the plugin updater process.

Probably here? 
https://github.com/mumble-voip/mumble/blob/23f76509048664ea919586f77f0c8b6ce272a1f4/src/mumble/PluginUpdater.cpp#L80-L90

**Comment by Krzmbrzl** [comment]
I'm wondering whether this has any security-implications. If there is some sort of bug in the webpage fetching, then a malicious website could end up causing havoc in Mumble itself. Then again, the same could already happen with the update URL :thinking:

**Comment by hbeni** [comment]
Yes, it can happen with the update URL too.
And also, to consider: The update fetcher already runs inside mumble process context, as well as any plugin stuff (like my own http fetch code).

The URL should be properly sanitized by the api function, of course.
And also strict tests are prudent when fetching the content, like what to do if the requested URL is slow to respond (or hangs forever), or the webserver returns endless data. There should be limits to this, but maybe it would be good to have a possibility for the plugin code to also adjust those limits if needed.
(Said that, that is also already true for all other http stuff mumble does. But going trough a common, well tested function (which it is already probably) is better than every plugin developer reinventing the wheel here)

**Comment by Krzmbrzl** [comment]
The issue here is that the fetching would be asynchronous as that's the way Qt does web requests. That means that we would either have to implement an explicit waiting for the fetched resource (I'm not even sure how to do that properly) or make the fetching API asynchronous (with a callback function that provides the result). However, the latter would likely defeat the main use-case, which is to provide an easy to use way to fetch web resources.

Furthermore, fetching stuff from the internet does imply that some sanity checking has to be done. However, I don't think that Mumble can implement this in a one-size-fits-all way as it doesn't know any specifics about what a given plugin is trying to achieve and whether the expected payload is in the KB or GB regime.
You proposed adding limits and making those adjustable but that adds complexity.

So all in all I am not entirely convinced about such an API function. Additionally, this would be an API function that has nothing to do with Mumble itself, which I would consider to be rather weird (also, it would probably open the door for requests to more general purpose API functions) as this is not a general programming API.

Therefore, I will close this request with the note that if someone opens a PR that implements this functionality in a sound way, I might reconsider (instead of a PR a comment illustrating the implementation plan would also be fine).

**Comment by hbeni** [comment]
> The issue here is that the fetching would be asynchronous as that's the way Qt does web requests

That complicates tings, yes. But a callback sounds sane in my opinion.


> Furthermore, fetching stuff from the internet does imply that some sanity checking has to be done. 

Yes, absolutely. However, that is to remain in the realm of the plugin i guess, like currently. The only check enforceable currently mumble-side (as in "behind the url fetch api)" could be SSL cert validity and maximum size of payload; both parameters that could be set from the plugin when calling the API.
More checks, against the actual fetched content can only be done by the plugin itself (like currently already).

> Additionally, this would be an API function that has nothing to do with Mumble itself

Not directly, yes. But it would avoid every plugin needing its own openssl and http binding to libs providing that. That really can get complicated and avoids binary package size. For windows support for my plugin for example, I need to statically link openssl.

> Therefore, I will close this request with the note that if someone opens a PR that implements this functionality in a sound way, I might reconsider (instead of a PR a comment illustrating the implementation plan would also be fine).

:( 
I think, exposing the mumble call using a callback scheme could work. If you don't mind - can we try to work more on that route for now, and see if bear fruit?

In my case, mumble asks my plugin via the `has_update()` call if there is an update. Thats where I would anted to use a call to mumbles ssl api to fetch my github releases web page (line 487, which delegates the fetch to its own function, `fgcom_getLatestReleaseFrom_Github_Web()`, which in turn, calls another `httplib` to actually do the call).
https://github.com/hbeni/fgcom-mumble/blob/2088e866fc6e5fc5af44437a634d562eccc59929/client/mumble-plugin/lib/updater.cpp#L468
I think, mumble does this in an own thread, or other non-blocking way regarding the mumble main thread, and so, probably the `has_update()` function call can safely be made plugin-side to wait for the callback to deliver the actual http content?

**Comment by hbeni** [comment]
> instead of a PR a comment illustrating the implementation plan would also be fine

M plan for that would be like this (barring any QT knowledge; and following function names and types just as rough idea):

- Mumble API provides a new `mumble_http_result fetch_https(std:string url, int maxlen)` function.
  - It is meant to be blocking.
  - The return value should be indicating success/failure, holding the http error code (if any) and (if success) the actual content (empty std:string in case of errors).
- Internally
  - it hands the url over to the asyncronous QT function, blocks and waits for the callback to finish.
  - the callback can prepare the aforementioned result structure depending on QTs result.

**Comment by Krzmbrzl** [comment]
I'm wondering whether refining the way the `hasUpdate` function might be sufficient for the vast majority of use cases. E.g. instead of the current way, have a plugin function that provides information about where to fetch information about whether or not a new plugin version is available. 

My thinking being that we could introduce a standard end point API for this that e.g. yields the latest version and a download link for that version. With this information, Mumble should be able to autonomously handle the update checking and fetching 👀

**Comment by hbeni** [comment]
That would be another option, however - you cannot know what each project release and versioning structure is, so i would strongly advice to let this reside in the hands of the plugin for that reason.
When following the Idea of "common API", what API should that be? The simplest case would be "look at github" like I currently do, however that locks people to github as code provider and release platform. And my other option since recently is a custom API where I just return strings from my own server, but that forces projects to self-host some means providing that. Or optionally both - but that sends mumble down the rabbit hole to implement and support "supported update provider APIs".

If you look again closely, the most common denominator of all that is "look somewhere on the web", and that would be awesome if the plugin could do without the need to implement ssl/http stuff on its own, because its such a bloat, especially given mumble itself already has dependencies for that.

And for security reasons (I guess, that is your main concern) we open no more holes than are already present that way - code from the plugin already runs in mumbles context. And exchanged info is just an URL (which can be sanitized using regex mumble sided) and the payload (which you basicly just need to hand over to the plugin, so no responsibility of mumble itself for checking). The thing that could happen when downloading stuff from the net is, that it exceeds some buffer (ie. we should do timeout and payload length checks inside the mumble context, but sanity of the payload should be the responsibility of the plugin).

Mabe we should talk more about your concerns, what scenarios are you afraid of exactly, making you want a stricter API?

**Comment by Krzmbrzl** [comment]
We are already forcing plugins to use semantic versioning so I would simply extend this to the updater as well.
And in special cases, the old functions (e.g. the current ones) will remain available so that the plugin can do whatever it wants (at the cost of having to do the fetching itself).

> but that sends mumble down the rabbit hole to implement and support "supported update provider APIs".

I think there are a couple of options that cover the vast majority of use cases and those can be implemented by Mumble without too much fuss (at least that's my hope).
And for everything special, the plugin can always go back to doing things itself. 

> Mabe we should talk more about your concerns, what scenarios are you afraid of exactly, making you want a stricter API?

My main concern here is that "looking something up on the web" has nothing to do with Mumble and therefore it feels wrong to me to be present in the Mumble API.
Everything else (e.g. the hassle of handling asynchronous fetching) comes on top of this but is mostly secondary.

**Comment by hbeni** [comment]
> I think there are a couple of options that cover the vast majority of use cases

What options are you thinking about exactly?
Is looking at the github release page one of those?
I ask, because in my instance the mumble plugin is just one piece of the plugin, and so the version number on the github release page is sometimes increasing even if the plugin is untouched.
And how should the download-url be provided in that case?

> My main concern here is that "looking something up on the web" has nothing to do with Mumble and therefore it feels wrong to me to be present in the Mumble API.

A valid concern. But such a function would come handy also for plugin developers, because it could for example also be used to handle custom REST-APIs of a plugin very easily (just came to my mind).
So the potential usecase is not only limited to updating...
But I see your point - however, updating/checking a plugin is nearly in every case done trough the web, and having such a generic function would make plugin developers life much more easy, helping to spread mumble and the overall plugin idea.

**Comment by Krzmbrzl** [comment]
> What options are you thinking about exactly?

Initially I was thinking about
- self hosted server with a standardized API for querying the latest version and where to download it
- GitHub releases
- (GitLab releases)

more could be added as needed.

> I ask, because in my instance the mumble plugin is just one piece of the plugin, and so the version number on the github release page is sometimes increasing even if the plugin is untouched.
And how should the download-url be provided in that case?

I would argue that re-downloading the same plugin again doesn't hurt. Also, I was thinking of simply iterating all files (ending in `.mumble_plugin`) attached with a release and then asking the plugin about whether this is the one to download and we could make it so that if none of the files get accepted, the update is cancelled.

> But such a function would come handy also for plugin developers

True. The thing is, I'm sure there are lots of other functionalities that would be handy. To be fair though, most other functionalities can likely be covered by a recent-enough C++ standard library or something similar... :thinking: 

@davidebeatrici @Hartmnt what are your thoughts on including functionality into the Mumble API that have nothing to do with Mumble? Am I overly pedantic in wanting to restrict that API to strictly Mumble-related functionality?
