### ISSUE TITLE
Export metrics

### ISSUE THREAD

**Issue by timhae** [mumble-voip/mumble#6529]
### Context

Maintaining a server

### Description

I would like to collect metrics of my running instance with Prometheus. Teamspeak exposes [these](https://github.com/hikhvar/ts3exporter#examples) metrics. I looked into the ice RPC interface but there is nothing like that exposed (or I could not find it). Directly exposing metrics with Prometheus CPP would also be an option. Please let me know what you think.

### Mumble component

Server

### OS-specific?

No

**Comment by Krzmbrzl** [comment]
What metrics are you looking for specifically?

**Comment by timhae** [comment]
basically everything in the ts3 exporter, so per channel for the channel metrics and everything else per virtual server:
```
ts3_channel_clients_online
ts3_channel_max_clients
ts3_serverinfo_bytes_send_total
ts3_serverinfo_channels_online
ts3_serverinfo_client_connections
ts3_serverinfo_clients_online
ts3_serverinfo_control_bytes_received_total
ts3_serverinfo_control_bytes_sent_total
ts3_serverinfo_file_transfer_bytes_received_total
ts3_serverinfo_file_transfer_bytes_sent_total
ts3_serverinfo_speech_bytes_received_total
ts3_serverinfo_speech_bytes_sent_total
```
and also `virtualserver_total_packetloss_total`

**Comment by Krzmbrzl** [comment]
And for what purpose?

**Comment by timhae** [comment]
To observe the health and state of my instance

**Comment by Krzmbrzl** [comment]
Could you be more specific? Many of the listed metrics seem useless to me so I am wondering what exactly you want to do with them.

**Comment by timhae** [comment]
So for example I would like to see how many people are connected to a virtual server and each channel within that server. Then the bytes transmitted per type would give me an indication if something unusual is going on and packet loss indicates the quality of the service for the users

**Comment by Krzmbrzl** [comment]
You can use the Ice interface to query the channels and users on the server which implicitly gives you information about the users per channel.

The amount of bytes per message type is not available but I think using that for monitoring goes more into the Vodoo direction than actually being useful. 

And packet loss is very dependent on the individual client, so I'm not sure what a packet loss metric would even describe. Maybe the average packet loss?
But what would this tell you? It could simply be a single client with a bad connection that drives this number up.

I don't know what I would consider valuable metrics as I have never needed anything in this direction. That's why I was asking about what exactly you are planning to do with the requested metrics. 
I'm not sure though that there exist reliable metrics that tell you how well every client is enjoying the use of your server 🤔

**Comment by Krzmbrzl** [comment]
With the information provided I don't think this would be a valuable feature to have in Mumble. If someone has additional arguments for certain metrics, I will reconsider this issue.

**Comment by vitoyucepi** [comment]
Hi @Krzmbrzl,
The integrated Prometheus exporter is a good idea because it allows administrators to collect metrics without writing their interaction level with ICE or GRPC. In some cases, the mumble server wasn't even built with ice support.

As for the metrics. In addition to the standard metrics, such as
- `process_cpu_seconds_total` - Total user and system CPU time spent in seconds.
  Of type counter.
- `process_resident_memory_bytes` - Resident memory size in bytes.
  Of type gauge.
- `process_start_time_seconds` - Start time of the process since unix epoch in seconds.
  Of type gauge.
- `process_virtual_memory_bytes` - Virtual memory size in bytes.
  Of type gauge.
- `process_max_fds` - Maximum number of open file descriptors.
  Of type gauge.
- `process_open_fds` - Number of open file descriptors.
  Of type gauge.

I'd like to see
- `mumble_build_info` - A metric with a constant '1' value labeled by version, revision, branch...
  Of type gauge.
- `mumble_sent_bytes_total` - Bytes sent by the server.
  Of type counter.
- `mumble_received_bytes_total` - Bytes received by the server.
  Of type counter.
- `mumble_speech_bytes_sent_total` - Bytes of speech data sent by the server.
  Of type counter.
- `mumble_speech_bytes_received_total` - Bytes of speech data received by the server.
  Of type counter.
- `mumble_connections_total` - Number of connection attempts to the server.
  Of type counter.
- `mumble_connection_errors_total` - Number of failed connections to the server.
  Of type counter.
- `mumble_active_users` - Number of users currently connected to the server.
  Of type gauge.
- `mumble_channels` - Number of channels on server.
  Of type gauge.
  Maybe split by `type=permanent` and `type=temporary`.

**Comment by Krzmbrzl** [comment]
> In some cases, the mumble server wasn't even built with ice support.

Imo that's not a good argument. The server admin can change that if they need it.

Some of the requested metrics are available already and for the others I still see no use.

**Comment by timhae** [comment]
would you oppose a PR or are you not interested in implementing someting yourself?

**Comment by vitoyucepi** [comment]
> would you oppose a PR or are you not interested in implementing someting yourself?

I don't think that I would be able to do that.

**Comment by timhae** [comment]
Sorry, I meant @Krzmbrzl . if I prepare a PR with Prometheus CPP metric export do you think that has a chance of being merged or not?

**Comment by Krzmbrzl** [comment]
I would not oppose a PR. Quite on the contrary, actually. The only thing is that I would not want for this PR to be very disruptive in terms of which and how many parts of the code need to be adapted in order to get this to work. If this can be done with relatively small-ish overhead, I would be happy to merge such a PR.

**Comment by Hartmnt** [comment]
> If this can be done with relatively small-ish overhead

@timhae 
I could be wrong because it has been a while, but does Prometheus not require metrics via HTTP? If so, one would require to include or implement a minimal HTTP server, right?

**Comment by timhae** [comment]
Thanks for the feedback, I would try to use [this](https://github.com/jupp0r/prometheus-cpp) library since I am familiar with it. And yes, that includes an http server. Don't expect anything soon but I have it on my list :)
