### ISSUE TITLE
Links do not hyperlink if pasted to fast

### ISSUE THREAD

**Issue by ionstorm66** [mumble-voip/mumble#6568]
### Description

If you paste and send a link to fast it wont get turned into a hyperlink. I have a macro on my mouse to do "ctrl + v" then "enter" and noticed after the 1.5.634 update I could no longer send hyperlinks, but everyone else could. Further tested revealed that if you paste and send a link to fast it wont link. I added a delay to my macro to fix the issue, but no other software has the same issue.

### Steps to reproduce

Copy a link to your clipboard, then hit ctrl+v and enter in rapid succession.

### Mumble version

1.5.634

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

**Comment by Hartmnt** [comment]
I can reproduce this. That will be fun to track down :smiling_face_with_tear:

**Comment by Hartmnt** [comment]
Ok, that was easier to find than expected. The commit that introduced this bug is e658c4a0e094d2a and looking at it I think I know what is going on. The "send plaintext" shortcut is processed in an event. I assume that if you manage to do ctrl+v + enter in the same Qt event tick, it will still think that you are holding ctrl when pressing enter.
