### ISSUE TITLE
Multichannel-Recording gets out-of-sync over time

### ISSUE THREAD

**Issue by ghost** [mumble-voip/mumble#964]
I have a 2h multichannel-recording with two people in Mumble, where one resulting file is 3 seconds shorter than the other. In the beginning everything is ok, but after 30 minutes there were some UDP transmission problems caused by one user doing heavy uploads on his side. Right after the transmission error, the channels were heavily out-of-sync.

By looking at the source, I found some code generating silent samples when there are missing samples - but only when the silence period is larger than 100ms. Do you think that our silence period was shorter? BTW, I used WAV for recording.

Our settings are shown on the screenshots found here:

http://www.sowennet.de/mumble

Thanks!

_This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/964/ ._

**Comment by rtrind** [comment]
I'd like to get this reopened. I am the "technical guy" for a small podcast in Brazil and since we discovered mumble it was a pleasure using the record feature to skip using Skype audio and individual local recordings.

But we are having serious desync issues all the time. We were using a 1.3.0 snapshot version on a local server at my house. After 20 minutes of recording, the audio tracks start to drift and they continue to drift until the end of the tracks. 

We all use continuous mode all the time because there is always a popping sound on the beginning of each voice capture (not always, but frequent enough we notice it, we will open another ticket for this after the recording issue is solved). Some users were having audio aggressive delays during the recordings (because of the low quality brazilian internet, reaching 4000 latency), so we put the murmur server on the Amazon EC2, Sao Paulo (very low latency, 15~20ms). This solved most of the delays while talking with 4~6 clients in continuous mode.

Even so, the recording does not reflect the audio we hear while live, the tracks are still drifting. One user was recording on wav format and me on flac. Both representations have the drift.

Right now the murmur server is using version 1.3.0~540~gedd5509 on a Ubuntu 14.04.2 LTS, hosted on Amazon EC2. The live session goes perfect, without any problems (except for some specific problems with some users), but the recording always suffers. We believe most of the clients are up to date, but we never checked one by one.

I don't know what you guys need us to deliver for this analysis to be performed. Feel free to ask anything and I will help as best as I can.

**Comment by hacst** [comment]
The important part for recording is the client. What client version is the recording party running? It needs to be a 1.3.0 snapshot.

**Comment by rtrind** [comment]
It makes sense. The recorders are myself the the podcast editor, and both always update to the latest snapshot when prompted by the software, so we are using the latest one.

**Comment by hacst** [comment]
I guess the issue isn't resolved for all cases after all then :( As it seems to be an edge case I opened #1617 to track this separately.
