### ISSUE TITLE
Inverted samples in WAV recording when clipping

### ISSUE THREAD

**Issue by mumble-voip** [mumble-voip/mumble#971]
I'm not sure whether this is related to Mumble or libsndfile, but when I record into a WAV file I get really heavy noise when samples are clipped. Instead of just being clipped to value 1.0 or -1.0 they somehow change sign and "jump" to the other side. To demonstrate this, I have attached a screenshot from Audacity where on the top I did a direct audio recording using Audacity and on the bottom you see the recorded WAV from Mumble of the same voice.

So, on the top this is how I would expect the waveform to look like and on the bottom you see the inverted samples. This makes the clipping noise much worse than it should be. Instead of sounding just a bit distorted, you get a very loud click noise.

I have tried and switched line 198 in VoiceRecorder.cpp from

sfinfo.format = SF_FORMAT_WAV | SF_FORMAT_PCM_24;

to

sfinfo.format = SF_FORMAT_WAV | SF_FORMAT_FLOAT;

and the inverted samples are gone. But this is probably just a work-around.

Any clue?

_This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/971/ ._

*The following attachments were added on the original item:
- https://sourceforge.net/p/mumble/bugs/971/attachment/mumble_wav_bug.png*

**Comment by flyser** [comment]
I am experiencing this issue in flac or wav multi-track recordings with version 1.3.0 f8b63cd53c3a481ab90fb840ad1c68f40493b2c1
Please reopen

**Comment by hacst** [comment]
@flyser Hi. Can you provide a recording with the issue? Also which platform and architecture architecture are you running on? I can't reproduce the issue with the current snapshot (was pretty easy before). If it's just clipping that would be expected behavior. This issue produced wraparound with a very audible crackle.

**Comment by flyser** [comment]
I analyzed the problem a bit further and found very weird behaviour.
Take a look at the following screenshot: http://i.imgur.com/y7uJey8.png
The first track is the flac file generated by mumble, the second track is the same flac file transcoded to .wav with ffmpeg and the third track is an ogg file generated by a different mumble instance.

I would be happy to provide a sample file, but it seems I can't cut out the example portion without creating the artifacts you see on track two. 
I am wondering why audacity is able to decode it properly, but neither sox, flac-utils nor ffmpeg are ...

**Comment by flyser** [comment]
Here is another screenshot showing inversed clipping in mumble: http://i.imgur.com/Pg8faIW.png
The first track is the flac file generated by mumble and the second track is the a recording done by sox via pulseaudio simultaniously

**Comment by hacst** [comment]
Ah dammit. I just review my patch (8e22f9a2110907df0cf49dc1a838da3e6043bbb5) and it looks like I was working under the invalid assumption that SF_FORMAT_* subtypes were flags and not an enumeration. That screwed up the comparison  No idea why I didn't catch that in testing.

@flyser If you can compile from our master please check if 1c00533b091b683cfa25b218da69afcb0360284c resolves the issue. Thanks a lot for reporting this.

**Comment by flyser** [comment]
Thanks for the fast response, I will test this as soon as I can.
What about the inverted clipping that occured in the ogg file as well?

**Comment by hacst** [comment]
Not sure what's up with that. From my understanding vorbis only does floating point encoding and shouldn't be constrained to [-1.0, 1.0] either. Are you sure that spike is an inversion and not just a pop + clipping introduced in another way?

That being said: If it does turn out to be an inversion I'd be interested to find out where in our processing pipeline that is coming from...

**Comment by flyser** [comment]
The inverted clipping you see in http://i.imgur.com/Pg8faIW.png is also present in the ogg file and not present in the sox recording, so yes I am pretty sure

**Comment by flyser** [comment]
I suspect the inverted clipping occurs before the opus encoding step, as surrounding samples seem to contain encoding artifacts. Maybe the compressor is causing these?

**Comment by hacst** [comment]
Sounds reasonable. The output path from decoder into the recorder should all be float. In the input we still have a PCM16 conversion due to the Speex filter stage.

**Comment by flyser** [comment]
Is there anything I can do to help debug this issue? I am happy to test patches or provide debugging output if it helps. This bug is a means a lot of extra work for me and would love to see it fixed.

**Comment by notthetup** [comment]
:+1: Didn't realise this was a Mumble issue. Have been trying to fix stuff with level for almost 1.5yrs.

I'm gonna try to build of 1c00533 on saturday. Will report if it fixed the issues.

**Comment by notthetup** [comment]
Wow, compiling Mumble on my OSX is complicated. Are the development snapshots off the master branch?? So would Mumble-Universal-1.3.0~547~g657f9e8 which was built on 15-Mar-2015 01:40 have picked up 1c00533?

**Comment by hacst** [comment]
@notthetup Yes. Snapshots are created from the master on github. g657f9e8 means the snapshot was created from git revision 657f9e8 which contains 1c00533b091b683cfa25b218da69afcb0360284c .

**Comment by mkrautz** [comment]
Note that the "-Universal" builds for OS X are legacy builds. They built with Qt in Carbon mode as opposed to Cocoa. They only exist to allow people to use Mumble on OS X 10.4-10.6 machines, as well as PowerPC Macs.

**Comment by notthetup** [comment]
OK. Got it. I'll try this fix and let you know in a couple of days!

**Comment by flyser** [comment]
1c00533 does not fix this completely. I am not sure how to explain this ... somehow the the waveform is always clipped to the positive (i.e. the upper maximum in audacity) value even if they should be clipped to the lowest value. Does that make sense to you?

**Comment by notthetup** [comment]
@flyser I think a waveform image would explain this the best.

**Comment by notthetup** [comment]
Also, it seems all builds in the snapshot repository from 1c00533 forward are Universal. What's the process of creating snapshots?

P.S. I'm failing horribly at building mumble on OSX. After working around some QT SSL version issues now there is a linker issue.

**Comment by hacst** [comment]
@notthetup I think @mkrautz is currently working on some issue with the normal OSX builds that prevent new snapshots for them from being created.

**Comment by notthetup** [comment]
Yup. I talked to @mkrautz on IRC. I'm stuck at the same place as him.

**Comment by mkrautz** [comment]
@notthetup It's fixed now.

**Comment by notthetup** [comment]
:+1:

**Comment by notthetup** [comment]
So I was using a g657f9e8 build for my podcast recording yesterday, and I can confirm that the inversion issue is fixed. 

Here is a screenshot of a bit where the audio clipped because it was too loud.

![screenshot 2015-03-22 17 43 47](https://cloud.githubusercontent.com/assets/553140/6768815/05bbbbf2-d0bb-11e4-8573-3616e5d1af48.jpg)

**Comment by flyser** [comment]
This is what happens to some really bad clipping in my recording: http://i58.tinypic.com/t71pgw.jpg
The first track is the original mumble file, the second track shows how the clipping *should* look like.

**Comment by flyser** [comment]
Note that https://github.com/mumble-voip/mumble/pull/1651 fixes some inverted clipping that was shown in this issue. inverted clipping in FLAC (and possibly WAV) recording as shown in my last comment is still present though

**Comment by thernztrom** [comment]
Any progress on this issue? @hacst 
Havent tested the new versions since 1.2.4, but looking at this its at the same state in 1.2.10?

Some clipping exmaples from when we recorded audio in 1.2.4 (.wav):
https://youtu.be/2i35f6XBvCg?t=15s
https://youtu.be/2i35f6XBvCg?t=1m

**Comment by hacst** [comment]
@thernztrom As flyser says 1.2.10 does not have the later patches. We changed numbering schemes http://blog.mumble.info/version-numbering-change/ which makes the version numbers mentioned in this issue a bit confusing. TL;DR: Since 1.2.4 the 1.2.X branch only receives essential fixes for security and breaking issues. Pretty much all the new features as well as most bugfixes are currently only available in our 1.3 snapshots.

W.r.t to whether it is completely fixed by now: I don't know. Looking at flysers last reports it doesn't look like it. I think I had some IRL distractions and simply forgot about following up with this one again...

@flyser Steps to reproduce is simply recording something in say WAV and ensuring clipping occurs? That's on a Linux box with Pulseaudio?

**Comment by flyser** [comment]
It should be reproducable in any recording that takes several minutes. It might me easier if you allow mumble to amplify your microphone a lot (I don't remember what this setting was called; the automatic amplification thingy) and when you don't talk constantly, but do a lot of pauses, so the automatic amplification has time to raise the volume while you don't talk.

But even without these preconditions, it should be easy to reproduce.

To find the clipping in the recording, I opened the file in audacity, doubled the track and applied a 20kHz high-pass filter to the second one. When you zoom near the peaks of the filtered track, the result should be similar to the screenshots I posted.

I also use Linux and pulseaudio, but I doubt it makes any difference, since .au recording is fine.

**Comment by flyser** [comment]
Did you manage to reproduce it?

**Comment by hacst** [comment]
Unfortunately not yet. I'm having a real hard time to even get it to clip in the first place and the occurances I've had were all clean. I'll have to inject clipping audio into the input stage I guess...

**Comment by mkrautz** [comment]
We believe the commit 23fa9b3979c244f1bcdbc80972a88ef7144f8f4a might have something to do with this.

Could you guys please test this? It is in the latest snapshot, 1.3.0~883~g2a31708~snapshot.

Thanks.

**Comment by flyser** [comment]
I didn't do much recording lately, but I will try to test this in the coming weeks.

**Comment by flyser** [comment]
I just did a one hour recording with 2 participants (me using a git build of today on linux and the other one using the most recent snapshot on windows). Both tracks did not exhibit any inverted clipping when recording to floating-point .au, but did invert-clip about 15 times during this hour when recording to .flac.

**Comment by ZeroAbility** [comment]
Has this been addressed in 1.4?

**Comment by Krzmbrzl** [comment]
I know the audio processing itself (the one responsible for playing things through the speakers) does clipping (seemingly) properly (explicitly).
I believe recording bypasses this processing though :thinking:

**Comment by flyser** [comment]
> Has this been addressed in 1.4?

Yes, it was fixed in some 1.3 Version
